<table>
    <tr>
        <td>
            <p>
                <b><?php echo __('Hello,'); ?></b>
            </p>
            <p>
                <?php echo __("A request to reset your password has been made to log in to your administration panel."); ?>
            </p>
            <p>
                <?php echo __('Here is your new password:'); ?> <b><?php echo $this->getPassword() ?></b>
            </p>
        </td>
    </tr>
</table>
