<sb-section title="section_title">
    <form ng-submit="save();">
        <div class="col-md-6" 
             ng-show="!is_edit">
            <div class="form-group">
                <label for="country_code"><?php echo __("Select a language"); ?></label>
                <select id="country_code" 
                        class="form-control"
                        ng-model="translation.country_code"
                        ng-options="k as v for (k, v) in countries"
                        ng-change="changeCountry();">
                    <option value=""></option>
                </select>
            </div>
        </div>

        <div class="col-md-12"
             ng-show="translation.country_code || is_edit">

            <div class="form-group">
                <label for="files_list"><?php echo __("Search/Filter translations"); ?></label>
                <input type="text"
                       class="form-control"
                       placeholder="<?php echo __("Sentence, words, etc... (3 characters required, multi-terms supported)") ?>"
                       ng-model="filter.search" />

                <div ng-show="filter.search.length > 2 && results.length > 0"
                     class="results">
                    <table class="table table-striped"
                           style="margin-bottom: 0;">
                        <thead>
                            <tr>
                                <th style="width: 25%;"><b><?php echo __("File"); ?></b></th>
                                <th style="width: 65%;"><b><?php echo __("Text"); ?></b></th>
                                <th style="width: 10%;"></th>
                            </tr>
                        </thead>
                    </table>
                    <div style="max-height: 200px; overflow-x: hidden; overflow-y: scroll;">
                        <table class="table table-striped"
                               style="margin-bottom: 0;">
                            <tbody>
                                <tr ng-if="filter.search.length > 2"
                                    ng-repeat="item in search_context | multiWordsFilter:filter.search as results">
                                    <td style="width: 25%;">{{ item.title }}</td>
                                    <td style="width: 65%; white-space: normal;">
                                        <span style="color: #000000;">{{ item.key }}</span>
                                        <br />
                                        <i>{{ item.value }}</i>
                                    </td>
                                    <td class="text-right"
                                        style="width: 10%; white-space: normal;">
                                        <a class="btn btn-sm btn-primary"
                                           ng-click="openFile(item.file)"><?php echo __("OPEN") ?></a>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div ng-show="filter.search.length > 2 && results.length == 0">
                    <h3><?php echo __("No match.") ?></h3>
                </div>
            </div>

            <div class="form-group">
                <label for="files_list"><?php echo __("Select a file"); ?></label>
                <select id="files_list"
                        class="form-control"
                        ng-model="translation.file"
                        ng-options="k as v for (k, v) in translation_files"
                        ng-change="selectFile();">
                    <option value=""></option>
                </select>
            </div>
        </div>

        <div class="col-md-12" ng-show="translation.file && can_translate">
            <div class="form-group" style="margin-top: 24px;">
                <a class="btn btn-primary left pull-right"
                   style="margin-right: 15px;"
                   ng-show="!yandexTranslation.showProgress"
                   ng-click="translateAll();">
                    <?php echo __("Translate all"); ?>
                </a>
                <a class="btn btn-primary left pull-right"
                   style="margin-right: 15px;"
                   ng-show="!yandexTranslation.showProgress"
                   ng-click="translateMissing();">
                    <?php echo __("Translate missing entries"); ?>
                </a>
                <a class="btn btn-primary left pull-right"
                   style="margin-right: 15px;"
                   ng-show="yandexTranslation.showProgress">
                    <i class="fa fa-spinner fa-spin"></i>
                    <?php echo __("Translation in progress ... "); ?>
                    {{ yandexTranslation.progress + '%' }}
                </a>
                <div class="clear"></div>
            </div>
        </div>

        <div class="col-md-12" ng-show="translation.file && !can_translate">
            <div class="form-group" style="margin-top: 24px;">
                <div><?php echo __("<b>Warning:</b> translation API is experimental for the current language and may fail.") ?></div>
                <a class="btn btn-primary left pull-right"
                   style="margin-right: 15px;"
                   ng-click="translateAll();"><?php echo __("Translate all"); ?></a>
                <a class="btn btn-primary left pull-right"
                   style="margin-right: 15px;"
                   ng-click="translateMissing();"><?php echo __("Translate missing entries"); ?></a>
            </div>
        </div>

        <div class="col-md-12" ng-show="translation.file">
            <div class="form-group" >
                <label for="file_datas"><?php echo __("Text translation"); ?></label>
                <h4 class="a-center bold" ng-if="info[translation.file]"><i class="fa fa-warning"></i> {{ info[translation.file] }}</h4>
                <table class="table" id="file_datas">
                    <col width="50%" />
                    <col width="50%" />
                    <thead>
                        <tr>
                            <th class="text-center"><?php echo __("Default text"); ?></th>
                            <th class="text-center"><?php echo __("Your translation"); ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="slide-left" ng-repeat="key in notSorted(translation.collection)" ng-init="file_data = translation.collection[key]">
                            <td class="valign-middle wrap">{{ key }}</td>
                            <td class="valign-middle text-center">
                                <input type="text" ng-model="translation.collection[key]" class="form-control" placeholder="{{ file_data }}" value="{{ file_data }}" ng-class="currentClass[key]" ng-change="updateClass(key)" />
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="col-md-12">
            <div class="form-group">
                <button type="submit" class="btn btn-primary right" ng-disabled="!translation.file"><?php echo __("Save"); ?></button>
                <sb-loader is_visible="form_loader_is_visible" type="'inner_content'" size="'small'" animation="'no'" class="form_loader"></sb-loader>
                <div class="clear"></div>
            </div>
        </div>
    </form>

    <div class="clear"></div>

</sb-section>

<style type="text/css">
    .btn-sm {
        padding: 1px 5px !important;
        font-size: 11px !important;
        line-height: 1.4 !important;
        font-weight: bold;
        border: 0 !important;

    }

    a.btn-sm,
    a.btn-sm:hover {
        text-decoration: none !important;
    }

    .tos-optin {
        font-weight: bold;
        font-style: italic;
        font-size: 11px;
        line-height: 16px;
    }

    .tos-optin span {
        font-weight: bold;
    }
</style>