<table>
    <tr style="margin:auto; padding: 0 15px; color:#888888; font-size: 17px; line-height: 150%; width:600px">
        <td>
            <p align="justify"
               style="color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 13px;">
                <?php echo __('Your access token is') . ': ' . $this->getGdprToken() ; ?>
                <br />
                <br />
                <?php echo __('You can follow the URL below to access your data report'); ?>:
                <br />
                <br />
                <a href="<?php echo $this->getData('url') ?>"><?php echo $this->getData('url') ?></a>
            </p>
        </td>
    </tr>
</table>