<div class="notification text-center slide-down" ng-show="show_notif">
    <a class="btn btn-primary" href="<?php echo $this->getUrl("backoffice/notif_list"); ?>">{{ unread_messages }}</a>
</div>

    <canvas id="line" class="chart chart-bar"
    	chart-data="graphData"
		chart-labels="graphLabels"
		chart-options="graphOptions"
		chart-series="graphSeries"
		chart-dataset-override="graphDatasetOverride"
	</canvas> 
