<?php
$application = $this->getApplication();

$layout_model = new Application_Model_Layout_Homepage();
$layout = $layout_model->find($application->getLayoutId());

$layout_options = Siberian_Feature::getLayoutOptionsCallbacks($layout->getCode());
$layout_form = false;
if(isset($layout_options["form"]) && class_exists($layout_options["form"])) {
    $layout_form = new $layout_options["form"]($layout);

    $layout_options = $application->getLayoutOptions();
    if(!empty($layout_options) && $values = Siberian_Json::decode($layout_options)) {
        $layout_form->populate(array_merge($application->getData(), $values));
    }
}

$layout_form_options = new Siberian_Form_Options($layout);
$layout_form_options->populate($application->getData());

// Count elements (excluding hidden fields)
$countOptions = array_filter($layout_form_options->getElements(), function ($element) {
    return get_class($element) !== 'Siberian_Form_Element_Hidden';
});

$template_design = $application->getDesign();
$overview_new = $template_design->getOverviewNew();

# App design
$design_id = $application->getDesignId();
//For Facebook import
$app_id     = Core_Model_Lib_Facebook::getAppId();
$app_secret = Core_Model_Lib_Facebook::getSecretKey();
$app_linked_fb_page = $application->getFacebookLinkedPage();

$splashVersion = (integer) $application->getSplashVersion();

?>
<div class="page-content-wrapper">
    <div id="template_content"
         class="content">
        <h3 class="title-editor border-red text-center">
            <?php echo __("Your design"); ?>
        </h3>
        <div id="templates"
             class="subcontent content-color container-fluid">
            <div class="row">
                <div id="sb-tour-change-template-section"
                     class="col-sm-4 col-xs-6 sb-tour">
                    <?php if ($this->_canAccess("application_create")) : ?>
                        <div id="show_templates"
                             class="pointer">
                            <p>
                                <?php if (empty($design_id)): ?>
                                    <img id="design_overview"
                                         class="overview-old"
                                         src="/images/templates/blank/overview.png"
                                         width="100%"
                                         height="100%"/>
                                <?php elseif (!empty($overview_new)): ?>
                                    <img id="design_overview"
                                         src="<?php echo $application->getDesign()->getOverview("overview_new"); ?>"
                                         width="100% "
                                         height="100%" />
                                <?php else: ?>
                                    <img id="design_overview"
                                         class="overview-old"
                                         src="<?php echo $application->getDesign()->getOverview(); ?>"
                                         width="100% "
                                         height="100%" />
                                <?php endif; ?>
                            </p>
                            <button id="sb-tour-change-template"
                                    type="button"
                                    class="show_templates btn-grey btn btn-full-width sb-tour">
                                <?php echo __("Change your template"); ?>
                            </button>
                            </div>
                    <?php endif; ?>
                </div>
                <div id="sb-tour-change-layout-section"
                     class="col-sm-4 col-xs-6 sb-tour">
                    <div id="show_layouts"
                         class="pointer">
                        <div id="layout_overview">
                            <p>
                            <img id="layout_overview"
                                 src="<?php echo $this->getImage($layout->getPreview()); ?>"
                                 width="100% "
                                 height="100%" />
                            </p>
                        </div>
                        <button id="sb-tour-change-layout"
                                type="button"
                                class="show_layouts btn-grey btn btn-full-width sb-tour">
                            <?php echo __("Change your layout"); ?>
                        </button>
                    </div>
                </div>
                <div id="layouts"
                     class="col-sm-4 col-xs-12 sb-tour">

                    <?php if (!$layout_form_options->isEmpty()): ?>
                    <div id="default-options"
                         class="content-options content-white-bkg">
                        <h4><?php echo p__("application", "Homepage options") ?></h4>
                        <?php echo $layout_form_options; ?>
                        <div style="clear: both;"></div>
                    </div>

                    <hr class="general spacer" />
                    <?php endif; ?>

                    <?php if ($layout_form !== false): ?>
                    <div id="custom-options"
                         class="content-options content-white-bkg">
                        <h4><?php echo p__("application", "Layout options") ?></h4>
                        <?php if($layout_form->getPresets()): ?>
                            <p class="preset-title"><?php echo p__("application", "Preset") ?></p>
                            <div class="preset-sets"
                                 data-form="<?php echo $layout_form->getId(); ?>">
                                <table style="text-align: center;" class="sb-mini-carousel" data-items="3">
                                    <tr>
                                        <td class="prev-arrow">
                                            <i class="fa fa-chevron-left"></i>
                                        </td>
                                        <td class="sb-carousel-items">
                                            <div class="sb-carousel-inline">
                                                <?php foreach($layout_form->getPresets() as $preset): ?>
                                                <?php
                                                $values = "";
                                                foreach($preset["values"] as $key => $value) {
                                                    $values .= " data-$key=\"$value\"";
                                                }
                                                ?>
                                                <a class="sb-carousel-item preset-link"
                                                   style="display: none;"
                                                   href="javascript:void(0)" <?php echo $values; ?>>
                                                    <img src="<?php echo $preset["preview"] ?>" />
                                                </a>
                                                <?php endforeach; ?>
                                            </div>
                                        </td>
                                        <td class="next-arrow">
                                            <i class="fa fa-chevron-right"></i>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        <?php endif; ?>
                        <?php echo $layout_form; ?>
                    </div>
                    <?php endif; ?>

                    <?php if (($layout_form === false) && $layout_form_options->isEmpty()): ?>
                    <div class="content-options content-white-bkg">
                        <p class="preset-title text-center"><?php echo p__("application", "This layout has no option.") ?></p>
                    </div>
                    <?php endif; ?>
                </div>
            </div>

            <!-- Homepage Carousel -->
            <?php if(($application->getLayoutVisibility() == Application_Model_Layout_Homepage::VISIBILITY_HOMEPAGE) &&
                $application->getHomepageSliderIsVisible() && $layout->getUseHomepageSlider()): ?>
            <div id="sb-tour-slider-section"
                 class="row content-in sb-tour">
                <div class="col-sm-12 col-xs-12 col-md-12">
                    <div class="content-options content-white-bkg">
                        <div id="homepage_slider">
                            <div id="homepage_slider_options">
                                <?php
                                    $size = $application->getHomepageSliderSize();
                                    if(empty($size)) {
                                        $application->setHomepageSliderSize(33)->save();
                                        $application->setData("homepage_slider_size", 33)->save();
                                    }

                                    $form_slider = new Application_Form_HomepageSlider();
                                    $form_slider->populate($application->getData());
                                    echo $form_slider;
                                ?>
                                <div class="slider_images">
                                    <div id="uploaded_slider_images"
                                         class="listing">
                                        <div>
                                            <ul id="slider_images"
                                                class="images_list">
                                                <?php foreach($application->getSliderImages() as $slider_image): ?>
                                                    <li id="slider_image_<?php echo $slider_image->getImageId(); ?>"
                                                        class="slider_image sortable">
                                                        <span class="details">
                                                            <img width="195"
                                                                 src="<?php echo $slider_image->getLink(); ?>" />
                                                        </span>
                                                        <div class="actions"
                                                             style="display:none">
                                                            <a class="move_page pull-left btn btn-grey"
                                                               href="javascript:void(0)">
                                                                <i class="fa fa-sort"></i>
                                                            </a>
                                                            <a class="delete_page delete_slider_image pull-right btn btn-grey"
                                                               onclick="deleteSliderImage(event, this);"
                                                               href="<?php echo str_replace('$', '/', $this->getUrl('application/customization_design_style/deletesliderimage') . '$image_id$'); ?>">
                                                                <i class="fa fa-times"></i>
                                                            </a>
                                                            <input type="hidden"
                                                                   class="image_id"
                                                                   value="<?php echo $slider_image->getImageId(); ?>" />
                                                        </div>
                                                    </li>
                                                <?php endforeach; ?>
                                            </ul>
                                        </div>
                                        <a id="carousel_prev">
                                            <i class="fa fa-angle-left"></i>
                                        </a>
                                        <a id="carousel_next">
                                            <i class="fa fa-angle-right"></i>
                                        </a>
                                    </div>
                                </div>
                                <div class="slider_images_uploader_action text-right">
                                    <button type="button"
                                            class="upload_images btn color-red"
                                            rel="<?php echo $this->getPosition(); ?>">
                                        <?php echo __('Add pictures'); ?>
                                    </button>
                                    <input style="display:none"
                                           enctype="multipart/form-data"
                                           rel="slider_images"
                                           class="fileupload"
                                           type="file"
                                           name="files[]"
                                           data-url="<?php echo $this->getUrl('template/crop/upload'); ?>" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?php endif; ?>
            <!-- /Homepage Carousel -->

        </div>
    </div>

    <?php if ($splashVersion == 2): ?>
    <div id="homepage_content"
         class="content sb-tour">
        <h3 class="title-editor border-red text-center">
            <?php echo __('Unified homepage'); ?>
        </h3>
        <div id="homepage" class="subcontent content-color container-fluid">
            <div class="icon_color">
                <input type="hidden"
                       id="homepage_image_name"
                       name="homepage_image"
                       value="" />
                <input type="hidden"
                       id="homepage_image_has_changed"
                       name="homepage_image_has_changed"
                       value="0" />
            </div>
            <?php echo $this->createPartialHtml(
                    'homepage_create',
                    'admin_view_default',
                    'application/customization/design/style/homepage-unified.phtml'); ?>
        </div>
    </div>
    <?php else: ?>
        <div id="homepage_content"
             class="content sb-tour">
            <h3 class="title-editor border-red text-center">
                <?php echo __('Homepage'); ?>
            </h3>
            <div id="homepage" class="subcontent content-color container-fluid">
                <div class="icon_color">
                    <input type="hidden"
                           id="homepage_image_name"
                           name="homepage_image"
                           value="" />
                    <input type="hidden"
                           id="homepage_image_has_changed"
                           name="homepage_image_has_changed"
                           value="0" />
                </div>
                <?php echo $this->createPartialHtml(
                    'homepage_create',
                    'admin_view_default',
                    'application/customization/design/style/homepage.phtml'); ?>
            </div>
        </div>
    <?php endif; ?>

    <div id="countries_container" class="content">
        <h3 class="title-editor border-red text-center">
            <?php echo __('Choose your country'); ?>
        </h3>
        <div id="countries" class="subcontent content-color sb-tour">
            <div class="col-md-12">
                <p><?php echo __("This option enables you to set the currency used in your app"); ?></p>
                <div class="row">
                    <div class="col-md-5">
                        <label for="select_locale"><?php echo __('Choose a country'); ?> : </label>
                        <select id="select_locale"
                                name="locale"
                                class="styled-select color-red sb-tour">
                            <?php foreach(Core_Model_Language::getCountriesList() as $country) : ?>
                                <option value="<?php echo $country->getCode() ?>"<?php if($application->getLocale() == $country->getCode()) : ?> selected="selected"<?php endif; ?>><?php echo $country->getName().' ('.$country->getSymbol().')' ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="font_content"
         class="content sb-tour">
        <h3 class="title-editor border-red text-center">
            <?php echo __('Choose your font family'); ?>
        </h3>
        <div id="fonts"
             class="subcontent content-color">
            <?php
                $fontFamilies = Core_Model_Lib_Fonts::getFonts();
                $fontGroupFamilies = Core_Model_Lib_Fonts::getFonts(true);
                $current = $application->getFontFamily();
            ?>
            <?php foreach($fontGroupFamilies as $groupName => $families) : ?>
                <div class="col-md-12 clear">
                    <h4 class="font-group"><?php echo __($groupName) ?></h4>
                </div>
                <?php foreach ($families as $fontFamily => $options): ?>
                <div class="col-md-6">
                    <label for="<?php echo slugify($fontFamily) ?>"
                           class="font-label <?php if ($current === $fontFamily): ?>checked<?php endif; ?>">
                        <input id="<?php echo slugify($fontFamily) ?>"
                               type="radio"
                               name="font_family"
                               value="<?php echo $fontFamily ?>"
                               <?php if ($current === $fontFamily): ?>checked="checked" <?php endif; ?>
                               class="color-red font-family" />
                        <span class="font-name"><?php echo str_replace("+", " ", $fontFamily); ?></span>
                        <span class="font-example"
                           style="font-family: '<?php echo str_replace("+", " ", $fontFamily); ?>' !important;">
                            Lorem Ipsum DOLOR SIT AMET
                            <?php if ($options["cyrillic"] === true): ?>
                            <span class="cyrillic"> + <?php echo __("CYRILLIC") ?></span>
                            <?php endif; ?>
                        </span>
                    </label>
                </div>
                <?php endforeach; ?>
            <?php endforeach; ?>


        </div>

        <div class="subcontent content-color">

            <div class="col-md-12"
                 style="margin-top: 15px;">
                <div class="alert alert-info">
                    <?php echo __("You can also use another Google Font not listed up there") ?>,
                    <b class="text-danger"><?php echo __("please respect the font name case!") ?></b>
                </div>
            </div>

            <div class="col-md-12">
                <div class="custom-box <?php if (!in_array($current, $fontFamilies) && !empty($current)): ?>checked<?php endif; ?>">
                    <div class="col-md-3">
                        <label for="custom_<?php echo slugify($current) ?>"
                               class="custom-box-label form-group">
                            <?php echo __("Custom font") ?>
                        </label>
                    </div>
                    <div class="col-md-7">
                        <input id="custom_<?php echo slugify($current) ?>"
                               type="text"
                               name="font_family_custom"
                               value="<?php echo !in_array($current, $fontFamilies) ? $current : "" ?>"
                               class="col-md-7 input-flat" />
                    </div>
                    <div class="col-md-2 text-right">
                        <button class="btn color-red save-custom-font"><?php echo __("Save") ?></button>
                    </div>

                    <div style="clear: both;"></div>
                </div>
            </div>
        </div>
    </div>
</div>

<style type="text/css">
    @import url('https://fonts.googleapis.com/css?family=<?php echo join("|", $fontFamilies + [$current]) ?>&subset=latin,greek,cyrillic');

    .font-group {
        border: 1px solid rgba(0,0,0,0.1);
        text-align: center;
        background-color: #f0f0f0;
        font-style: italic;
        padding: 10px;
        letter-spacing: 2px;
    }

    .font-label {
        background-color: #f0f0f0;
        padding: 6px 12px 0 8px;
        border: 1px solid rgba(0,0,0,0.1);
        border-radius: 2px;
        width: 100%;
    }

    .custom-box-label {
        margin: 0;
        line-height: 34px;
        font-weight: bold;
    }

    .custom-box {
        background-color: #f0f0f0;
        padding: 6px;
        border: 1px solid rgba(0,0,0,0.1);
        border-radius: 2px;
        width: 100%;
    }

    .custom-box.checked {
        border-color: #ff3a2e;
    }

    .font-example-custom {

    }

    .font-label.checked,
    .font-label:hover {
        border-color: #ff3a2e;
        cursor: pointer;
    }

    .font-label input {
        transform: translateY(13px);
    }

    .font-name {
        display: inline-block;
        transform: translate(5px, 1px);
        font-weight: bold;
        letter-spacing: 1px;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
        margin: 0;
        padding: 0;
        width: calc(100% - 40px);
    }

    .font-example {
        display: inline-block;
        width: 100%;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
        margin-bottom: 6px;
        margin-left: 29px;
    }
</style>

<script type="text/javascript">
    var carousel = null;
    var modal_preview;
    var modal_layouts;
    var modal_fb_import;
    $(document).ready(function(){

        bindForms("#default-options", "color-red", function () {
            setTimeout(function() {
                location.reload();
            }, 200);
        });
        bindForms("#custom-options", "color-red", function () {
            setTimeout(function() {
                iframe.reload();
            }, 200);
        });
        bindForms("#homepage_slider_options");

        $("#homepage_slider_options").on("change", function() {
            setTimeout(function() {
                iframe.reload();
            }, 2000);
        });

        $("table.sb-mini-carousel").sbcarousel({
            min_size: 48
        });

        let fontFamilySelectors = $(".font-family");

        fontFamilySelectors.off("click");
        fontFamilySelectors.on("click", function () {
            let el = $(this);
            let value = el.val();

            $(".font-label").removeClass("checked");
            $(".custom-box-label").removeClass("checked");
            $("input[name='font_family_custom']").val("");
            el.parent().addClass("checked");

            formget('<?php echo $this->getUrl('application/customization_design_style/save-font?font='); ?>' + value,
                {},
                function (data) {
                    feature_form_success(data.message);

                    // Reload only on success and when done!
                    setTimeout(function () {
                        iframe.reload();
                    }, 1000)
                },
                function (data) {
                    feature_form_error(JSON.parse(data.responseText).message);
                },
                false);
        });

        let saveCustomFont = $(".save-custom-font");

        saveCustomFont.off("click");
        saveCustomFont.on("click", function () {
            let el = $("input[name='font_family_custom']");
            let value = el.val();

            $(".font-label").removeClass("checked");
            $(".font-family").removeAttr("checked");
            $(".custom-box").addClass("checked");

            formget('<?php echo $this->getUrl('application/customization_design_style/save-font?font='); ?>' + value,
                {},
                function (data) {
                    feature_form_success(data.message);

                    // Reload only on success and when done!
                    setTimeout(function () {
                        iframe.reload();
                    }, 1000)
                },
                function (data) {
                    feature_form_error(JSON.parse(data.responseText).message);

                    $(".custom-box").removeClass("checked");
                    el.val("");
                },
                false);
        });

        $('#select_locale').change(function() {
            var countries_loader = $('#'+this.id+'_loader');
            countries_loader.show();
            reload(this.parentNode, '<?php echo $this->getUrl('application/customization_design_style/savelocale'); ?>', false, function(datas) {
                if(datas.success) {
                    iframe.reload();
                }
                countries_loader.fadeOut();
            }, function() {
                countries_loader.fadeOut();
            });
        });

        modal_preview = new Modal({
            id: 'preview',
            url: '<?php echo $this->getUrl('template/design/list'); ?>',
            is_retain: false,
            width: 1050,
            height: 'auto'
        });

        var showTemplatesButton = $("#show_templates");

        showTemplatesButton.click(function() {
            modal_preview.show();
        });

        modal_layouts = new Modal({
            id: 'modal_layouts',
            url: '<?php echo $this->getUrl('application/customization_design_style/layouts'); ?>',
            is_retain: false,
            width: 1050,
            height: 'auto'
        });

        $('#show_layouts').click(function() {
            modal_layouts.show();
        });

        <?php if ($app_id AND $app_secret): ?>
            modal_fb_import = new Modal({
                id: 'modal_fb_import',
                url: '<?php echo $this->getUrl('importer/facebook/getmodaltemplate'); ?>',
                is_retain: true,
                width: 800,
                height: 'auto'
            });
        <?php endif;?>

        <?php if (empty($design_id) && $application->getPages(0)->count() <= 0): # Show template modal until one is selected or there is no features. ?>
            modal_preview.show();
        <?php endif ?>

        if ($("#slider_images").length) {
            initCarousel();
        }

        $(".sb-check-container label.control.control--checkbox").addClass("col-md-6");
    });

    /** Homepage Image Slider **/
    var currentHeight = function(intialHeight) {
        var current_scale = $("#homepage_slider_size").val();
        var target_height = intialHeight * current_scale;
        return Math.ceil(parseFloat(target_height));
    };

    var sliderImages = $("#slider_images");
    var initCarousel = function() {
        // Images slider carousel
        createCarouselSortable();
        sliderImages.sbCarousel({item_width: 195, items_per_page: 3, next_button: $("#carousel_next"), prev_button: $("#carousel_prev")});
        carousel = sliderImages.data('carousel');
        carousel.update();
        sliderImages.on({
            mouseenter: function () {
                $(this).children('div.actions').fadeIn();
            },
            mouseleave: function () {
                var a = $(this).children('span.details');
                if (!$(this).hasClass('selected')) {
                    $(this).children('div.actions').stop().fadeOut();
                }
            }
        }, '.slider_image');
    };

    var previousSize = $("#homepage_slider_size").val();

    $("#homepage_slider_size").on("change", function() {
        var image_counts = $(".slider_image.sortable").length;

        if(image_counts != 0) {
            var confirm_client = confirm("<?php echo __js('If you decide to change the slider size, all images will be dropped. Are you sure ?');?>");
            if (confirm_client) {
                $(".delete_page.delete_slider_image").each(function (idx, elm) {
                    $(elm).click();
                });

                previousSize = $(this).val();
            } else {
                $(this).val(previousSize);

                return;
            }
        }

        if(image_counts > 0) {
            iframe.reload();
        }
    });

    $("#homepage_slider_options .upload_images").click(function() {
        $('.fileupload[rel="slider_images"]').trigger('click');
    });

    var slider_images_uploader = new Uploader();
    $('.fileupload[rel="slider_images"]').fileupload({
        dataType: 'json',
        add: function(e, data) {
            data.formData = {
                minwidth: '100',
                minheight: '200',
                maxwidth: '3000',
                maxheight: '3000'
            };
            data.submit();
            slider_images_uploader.showProgressbar();
        },
        progressall: function(e, data) {
            slider_images_uploader.moveProgressbar(data);
        },
        done: function(e, data) {
            if (data.result.error) {
                slider_images_uploader.showError(data.result.message);
            } else {
                slider_images_uploader.hide();

                var params = new Array();
                params["url"] = '<?php echo $this->getUrl('template/crop/crop'); ?>';
                params["file"] = data.result.files;
                params["uploader"] = 'slider_images_uploader';
                params["output_w"] = 1080;
                params["output_h"] = 1920*$("#homepage_slider_size").val()/100;
                params["output_url"] = '<?php echo str_replace('/', '$', $this->getUrl('application/customization_design_style/savesliderimages')) ?>';

                slider_images_uploader.crop(params);
                slider_images_uploader.callback = function(file) {
                    sliderImages.append(
                        '<li id="slider_image_' + file.id + '" class="slider_image sortable" data-pos="' + file.id + '">\n\
                            <span class="details">\n\
                                <img width="195" src="' + file.url + '">\n\
                            </span>\n\
                            <div class="actions" style="display: none;">\n\
                                <a class="move_page pull-left btn btn-grey" href="javascript:void(0)"><i class="fa fa-sort"></i></a>\n\
                                <a class="delete_page delete_slider_image pull-right btn btn-grey" onclick="deleteSliderImage(event, this);" href="<?php echo str_replace('$', '/', $this->getUrl('application/customization_design_style/deletesliderimage') . '$image_id$'); ?>">\n\
                                    <i class="fa fa-times"></i>\n\
                                </a>\n\
                                <input type="hidden" class="image_id" value="' + file.id + '">\n\
                            </div>\n\
                        </li>'
                    );

                    carousel.update();
                    iframe.reload();
                };
            }
        }
    });

    var deleteSliderImage = function(e, element) {
        e.preventDefault();

        var id = $(element).parent().find(".image_id").val();
        reload(this, element.href + id, true, function(response) {
            if(response.reload) {
                $(element).parent().parent().remove();
                carousel.update();
                iframe.reload();
            }
        });
    };

    var createCarouselSortable = function() {
        sliderImages.sortable({
            items: '> li.sortable:visible',
            cursor: "ew-resize",
            handle: '.move_page',
            placeholder: "page_placeholder",
            axis: 'x',
            tolerance: 'pointer',
            start: function () {
                var prev_button_position = carousel.getPrevButtonPosition();
                var next_button_position = carousel.getNextButtonPosition();

                $(document).mousemove(function (e) {

                    if (e.pageX > next_button_position.x1 && e.pageX < next_button_position.x2 && e.pageY > next_button_position.y1 && e.pageY < next_button_position.y2) {
                        carousel.startInterval('next');
                    } else {
                        carousel.stopInterval('next');
                    }
                    if (e.pageX > prev_button_position.x1 && e.pageX < prev_button_position.x2 && e.pageY > prev_button_position.y1 && e.pageY < prev_button_position.y2) {
                        carousel.startInterval('prev');
                    } else {
                        carousel.stopInterval('prev');
                    }
                });

            },
            stop: function () {
                $(document).unbind('mousemove');
            },
            update: function (e, ui) {
                var order = sliderImages.sortable('serialize');
                sliderImages.sortable("refresh");

                var order_url = "<?php echo $this->getUrl('application/customization_design_style/setsliderimagepositions'); ?>?" + order;
                reload(sliderImages, order_url, true, function () {
                    iframe.reload();
                });
            }
        });
    };

</script>
<style>
    .slider_size {
        width: 100%;
        display: block;
    }
    .slider_size > label {
        width:100%;
    }
    /** IMAGE SLIDER CAROUSEL **/
    #homepage_slider .slider_images {
        left: 0;
        position: relative;
        padding: 15px 0 0 0;
    }
    #homepage_slider .slider_images_uploader_action {
        margin-top: 10px;
    }
    #uploaded_slider_images {
        overflow: hidden;
        width: 100%;
        height: 100%;
        margin-left: 0;
        min-height: 120px;
        background-color: #E9E9E9;
        padding: 15px 0;
    }
    #uploaded_slider_images > div {
        margin: auto;
        overflow: hidden;
    }
    #uploaded_slider_images.listing ul {
        height: 100%;
        -webkit-transition: all 0.4s ease 0s;
        -moz-transition: all 0.4s ease 0s;
        -ms-transition: all 0.4s ease 0s;
        -o-transition: all 0.4s ease 0s;
        transition: all 0.4s ease 0s;
        list-style: none;
        padding: 0;
    }
    #uploaded_slider_images.listing ul li {
        float: left;
        width: 185px;
        height: 100%;
        padding: 0;
        transition: none;
        position: relative;
        margin: 0 5px;
    }
    #uploaded_slider_images.listing ul li:hover {
        background-color: #ffffff;
    }

    #uploaded_slider_images.listing ul li span.details {
        display: block;
        height: 100%;
        text-align: center;
    }
    #uploaded_slider_images.listing ul li span.details img {
        width: 100%;
        height: 100%;
        border-radius: 2px;
    }
    #uploaded_slider_images.listing ul li.slider_image div.actions {
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        z-index: 2;
    }
    #uploaded_slider_images.listing ul li.slider_image div.actions .move_page {
        cursor: ew-resize;
        left: 5px;
        top: 5px;
        padding: 6px 8px 4px;
        border-bottom-right-radius: 3px;
        border-top-left-radius: 2px;
        color: inherit;
    }
    #uploaded_slider_images.listing ul li.slider_image div.actions .delete_page {
        right: 5px;
        top: 5px;
        padding: 3px 10px 5px;
        border-bottom-left-radius: 3px;
        border-top-right-radius: 2px;
        color: inherit;
    }
    #uploaded_slider_images #carousel_prev {
        left: 15px;
    }
    #uploaded_slider_images #carousel_next {
        right: 15px;
    }
    #uploaded_slider_images #carousel_prev, #uploaded_slider_images #carousel_next {
        position: absolute;
        top: 50px;
        width: 16px;
        height: 92px;
        padding: 0;
        cursor: pointer;
        z-index: 2;
        font-size: 25px;
    }


    .opacity_container { width: 100%; }
    .opacity_container input[type=range] { float: left; width: 90%; }
    .opacity_container span { float: right; font-size: 11px; margin-top: -1px }
    /** /IMAGE SLIDER CAROUSEL **/

    .preset-title {
        margin-bottom: 1px;
        font-weight: bold;
    }

    .preset-sets {
        border-radius: 2px;
        background-color: #F4F4F4;
        float: left;
        padding: 4px;
        margin-bottom: 20px;
        width: 100%;
    }

    form.sb-form:not(.form-horizontal) .control--checkbox {
        margin: 0;
        padding: 0;
        display: inline-block;
        margin-top: 5px;
    }

    form.sb-form:not(.form-horizontal) .sb-form-checkbox {
        width: 20px;
    }

    form.sb-form:not(.form-horizontal) .form-group-checkbox {
        margin-bottom: 0px;
        margin-top: 10px;
    }

    form.sb-form:not(.form-horizontal) .sb-save-info-button {
        margin-top: 10px;
    }

    .prev-arrow, .next-arrow {
        width: 30px;
        min-width: 30px;
        max-width: 30px;
        font-size: 24px;
    }

    .preset-sets .col-md-4 {
        padding-left: 5px;
        padding-right: 5px;
    }

    .slider_images .fa-sort {
        cursor: ew-resize;
        transform: rotate(90deg);
    }

    form label {
        max-width: 90%;
    }

    select.form-control.no-dk {
        padding-left: 8px;
    }

    .styled-select {
        height: 28px;
        font-size: 14px;
        line-height: 2em;
    }

    .xb-slider {
        margin-bottom: 24px;
    }

    .sb-check-container label {
        width: 50%;
    }

    hr.general {
        border: 1px dashed;
        color: #E9E9EB;
        background-color: transparent;
    }

    .slider_images .fa-angle-right, .slider_images .fa-angle-left {
        font-size: 2em;
    }

</style>