<sb-section title="'<?php echo __title("List of your users"); ?>'" button="button">
    <br />
    <div class="form-group">
        <label for="filter"><?php echo __("Search"); ?></label>
        <input type="text"
               id="filter"
               class="form-control"
               ng-model="urlParams.filter"
               placeholder="<?php echo __("Search"); ?>" />
    </div>
    <br />
    <table class="table">
        <col width="5%" />
        <col width="14%" />
        <col width="14%" />
        <col width="14%" />
        <col width="14%" />
        <col width="14%" />
        <col width="25%" />
        <thead>
            <tr>
                <th class="pointer"
                    ng-class="{'pointer-up': urlParams.order == 'admin_id' && urlParams.by, 'pointer-down': urlParams.order == 'admin_id' && !urlParams.by}"
                    ng-click="urlParams.order = 'admin_id'; urlParams.by = !urlParams.by"><?php echo __("Id"); ?></th>
                <th class="pointer"
                    ng-class="{'pointer-up': urlParams.order == 'email' && urlParams.by, 'pointer-down': urlParams.order == 'email' && !urlParams.by}"
                    ng-click="urlParams.order = 'email'; urlParams.by = !urlParams.by"><?php echo __("Email"); ?></th>
                <th class="pointer"
                    ng-class="{'pointer-up': urlParams.order == 'firstname' && urlParams.by, 'pointer-down': urlParams.order == 'firstname' && !urlParams.by}"
                    ng-click="urlParams.order = 'firstname'; urlParams.by = !urlParams.by"><?php echo __("Name"); ?></th>
                <th><?php echo __("Phone"); ?></th>
                <th class="pointer"
                    ng-class="{'pointer-up': urlParams.order == 'company' && urlParams.by, 'pointer-down': urlParams.order == 'company' && !urlParams.by}"
                    ng-click="urlParams.order = 'company'; urlParams.by = !urlParams.by"><?php echo __("Company"); ?></th>
                <th class="pointer"
                    ng-class="{'pointer-up': urlParams.order == 'created_at' && urlParams.by, 'pointer-down': urlParams.order == 'created_at' && !urlParams.by}"
                    ng-click="urlParams.order = 'created_at'; urlParams.by = !urlParams.by"><?php echo __("Created At"); ?></th>
                <th class="text-right"><?php echo __("Actions"); ?></th>
            </tr>
        </thead>
        <tbody>
            <tr ng-repeat="admin in admins">
                <td>{{ admin.id }}</td>
                <td style="overflow: visible;">
                    {{ admin.email }}
                    <br />
                    <span class="tos-optin">
                        <b><?php echo __('Accepted Terms of Service') ?></b>&nbsp;&nbsp;
                        <span class="text-danger"
                              ng-if="admin.accept_tos !== '1'"><?php echo __('NO') ?></span>
                        <span class="text-success"
                              ng-if="admin.accept_tos === '1'"><?php echo __('YES') ?></span>&nbsp;&nbsp;&bull;&nbsp;&nbsp;
                        <b><?php echo __('Opt-in e-mails') ?></b>&nbsp;&nbsp;
                        <span class="text-danger"
                              ng-if="admin.optin_email !== '1'"><?php echo __('NO') ?></span>
                        <span class="text-success"
                              ng-if="admin.optin_email === '1'"><?php echo __('YES') ?></span>
                        <span ng-if="admin.website">&nbsp;&nbsp;&bull;&nbsp;&nbsp;<b><?php echo __('Website') ?></b>&nbsp;&nbsp;<a href="{{ ::admin.website }}" target="_blank">{{ ::admin.website }}</a></span>
                        <span>&nbsp;&nbsp;&bull;&nbsp;&nbsp;<b><?php echo __('Role') ?></b>&nbsp;&nbsp;{{ admin.label }}</span>
                    </span>
                </td>
                <td>{{ admin.name }}</td>
                <td>{{ admin.phone }}</td>
                <td>{{ admin.company }}</td>
                <td>{{ admin.created_at }}</td>
                <td class="text-right"
                    style="white-space: normal;">
                    <a href="<?php echo $this->getUrl("admin/backoffice_edit"); ?>/admin_id/{{ admin.id }}"
                       class="btn btn-sm btn-primary"><?php echo __('EDIT') ?></a>
                    <a href="<?php echo $this->getUrl("admin/backoffice_list/loginas"); ?>/key/{{ admin.key }}/admin_id/{{ admin.id }}"
                       target="_blank"
                       class="btn btn-sm btn-info"><?php echo __('IMPERSONATE') ?></a>
                    <a href="javascript:void(0);"
                       ng-click="deleteAdmin(admin)"
                       class="btn btn-sm btn-danger"><?php echo __('DELETE') ?></a>
                </td>
            </tr>
            <tr ng-show="!admins.length">
                <td colspan="7"
                    class="a-center"><?php echo __("You don't have any users yet"); ?></td>
            </tr>
        </tbody>
    </table>
    <br />
    <bgf-pagination
        collection="admins"
        page="page"
        per-page="perPage"
        link-group-size="2"
        client-limit="clientLimit"
        transform-response="parseCollection"
        template-url="/backoffice/paginate/template"
        url="'/admin/backoffice_list/findall'"
        url-params="urlParams">
    </bgf-pagination>

    <div class="clear"></div>

    <style type="text/css">
        .btn-sm {
            padding: 1px 5px !important;
            font-size: 11px !important;
            line-height: 1.4 !important;
            font-weight: bold;
            border: 0 !important;

        }

        a.btn-sm,
        a.btn-sm:hover {
            text-decoration: none !important;
        }

        .tos-optin {
            font-style: italic;
            font-size: 13px;
            line-height: 16px;
            display: inline-block;
            padding-top: 6px;
        }
    </style>
</sb-section>
