<sb-section title="'<?php echo __title("List of your users"); ?>'" button="button">
    <br />
    <div class="form-group">
        <label for="filter"><?php echo __("Search"); ?></label>
        <input type="text" id="filter" class="form-control" ng-model="urlParams.filter" placeholder="<?php echo __("Search"); ?>" />
    </div>
    <br />
    <table class="table">
        <col width="5%" />
        <col width="20%" />
        <col width="20%" />
        <col width="20%" />
        <col width="10%" />
        <col width="25%" />
        <thead>
            <tr>
                <th class="pointer"
                    ng-class="{'pointer-up': urlParams.order == 'admin_id' && urlParams.by, 'pointer-down': urlParams.order == 'admin_id' && !urlParams.by}"
                    ng-click="urlParams.order = 'admin_id'; urlParams.by = !urlParams.by"><?php echo __("Id"); ?></th>
                <th class="pointer"
                    ng-class="{'pointer-up': urlParams.order == 'email' && urlParams.by, 'pointer-down': urlParams.order == 'email' && !urlParams.by}"
                    ng-click="urlParams.order = 'email'; urlParams.by = !urlParams.by"><?php echo __("Email"); ?></th>
                <th class="pointer"
                    ng-class="{'pointer-up': urlParams.order == 'firstname' && urlParams.by, 'pointer-down': urlParams.order == 'firstname' && !urlParams.by}"
                    ng-click="urlParams.order = 'firstname'; urlParams.by = !urlParams.by"><?php echo __("Name"); ?></th>
                <th class="pointer"
                    ng-class="{'pointer-up': urlParams.order == 'company' && urlParams.by, 'pointer-down': urlParams.order == 'company' && !urlParams.by}"
                    ng-click="urlParams.order = 'company'; urlParams.by = !urlParams.by"><?php echo __("Company"); ?></th>
                <th class="pointer"
                    ng-class="{'pointer-up': urlParams.order == 'created_at' && urlParams.by, 'pointer-down': urlParams.order == 'created_at' && !urlParams.by}"
                    ng-click="urlParams.order = 'created_at'; urlParams.by = !urlParams.by"><?php echo __("Created At"); ?></th>
                <th><?php echo __("Actions"); ?></th>
            </tr>
        </thead>
        <tbody >
            <tr ng-repeat="admin in admins">
                <td>{{ admin.id }}</td>
                <td>{{ admin.email }}</td>
                <td>{{ admin.name }}</td>
                <td>{{ admin.company }}</td>
                <td>{{ admin.created_at }}</td>
                <td class="text-right"
                    style="white-space: normal;">
                    <a href="<?php echo $this->getUrl("admin/backoffice_edit"); ?>/admin_id/{{ admin.id }}"
                       class="btn btn-sm btn-primary"><?php echo __('EDIT') ?></a>
                    <a href="<?php echo $this->getUrl("admin/backoffice_list/loginas"); ?>/key/{{ admin.key }}/admin_id/{{ admin.id }}"
                       target="_blank"
                       class="btn btn-sm btn-info"><?php echo __('IMPERSONATE') ?></a>
                    <a href="javascript:void(0);"
                       ng-click="deleteAdmin(admin)"
                       class="btn btn-sm btn-danger"><?php echo __('DELETE') ?></a>
                </td>
            </tr>
            <tr ng-show="!admins.length">
                <td colspan="5" class="a-center"><?php echo __("You don't have any users yet"); ?></td>
            </tr>
        </tbody>
    </table>
    <br />
    <bgf-pagination
        collection="admins"
        page="page"
        per-page="perPage"
        link-group-size="2"
        client-limit="clientLimit"
        template-url="<?php echo $this->getUrl("/backoffice/paginate/template") ?>"
        url="'<?php echo $this->getUrl("/admin/backoffice_list/findall") ?>'"
        url-params="urlParams">
    </bgf-pagination>

    <div class="clear"></div>

    <style type="text/css">
        .btn-sm {
            padding: 1px 5px !important;
            font-size: 11px !important;
            line-height: 1.4 !important;
            font-weight: bold;
            border: 0 !important;

        }

        a.btn-sm,
        a.btn-sm:hover {
            text-decoration: none !important;
        }
    </style>
</sb-section>