<?php $section = $this->getSection();
$section_id = $section->getId();
$sectionModel = new Form_Model_Field();
$fields = $sectionModel->findBySectionId($section_id); ?>

<div id="section_<?php echo $section_id;?>" class="inner_content container-fluid subcontent content-white-bkg">
    <div class="details form-horizontal">
        <div id="section_details_<?php echo $section_id;?>" class="name">
            <div class="form-group">
                <div class="col-md-11">
                    <input type="text" id="main_section_name_<?php echo $section_id; ?>" class="main_section_name input-flat" name="name" rel="<?php echo $section_id; ?>" value="<?php echo $section->getName(); ?>" />
                </div>
                <div class="col-md-1 text-center">
                    <a href="javascript:section.remove('<?php echo $section_id; ?>');" class="delete_section btn color-blue">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            <input type="hidden" name="section_id" value="<?php echo $section_id; ?>" />
            <input type="hidden" name="option_value_id" value="<?php echo $this->getOptionValue()->getId(); ?>" />
        </div>
        <div class="actions">
        </div>
    </div>

    <div class="fields">
        <ul id="section_fields_<?php echo $section_id ?>" class="fields_list list-group">
            <?php if(count($fields) > 0) : ?>
            <?php foreach($fields as $field) : ?>
            <?php echo $this->getLayout()
                    ->addPartial('product_'.$field->getId(), 'admin_view_default', 'form/application/edit/section/field.phtml')
                    ->setField($field)
                    ->setOptionValue($this->getOptionValue())
                    ->toHtml()
                ;
            ?>
            <?php endforeach; ?>
            <?php endif; ?>
        </ul>
        <div>
            <a id="add_field_section_<?php echo $section_id ?>" class="add_field link btn color-blue" section_id="<?php echo $section_id; ?>" href="#" class="name"> <?php echo $this->_('Add a field'); ?></a>
        </div>
    </div>
    
</div>
<script type="text/javascript">
    $(document).ready(function(){
       if($('#form_email_config').is(':visible') == false) {
           $('#form_email_config').show();
           $('#form_email').attr('rel', '<?php echo $section_id?>');
       }
    });
</script>