<div class="has_header" sb-background-image>

    <sb-header title-back="'<?php echo $this->_("Back") ?>'" title="'<?php echo $this->_("Privacy Policy"); ?>'" message="message" right-button="header_right_button"></sb-header>

    <sb-loader is-loading="is_loading" size="'48'" block="'background'"></sb-loader>

    <div id="sections_privacy_policy" class="scrollable_content">
        <div class="padding for_ads_banner">
            <h1>Privacy Policy of the <?php echo $this->getApplication()->getName(); ?> application</h1>
            <span>This Application collects some Personal Data from its Users.</span><br />


            <h2>Data Controller and Owner</h2><br />
            <h2>Types of Data collected</h2>
            <p>Among the types of Personal Data that this Application collects, by itself or through third parties, there are: Geographic position, Cookie and Usage Data.
            Other Personal Data collected may be described in other sections of this privacy policy or by dedicated explanation text contextually with the Data collection.
            The Personal Data may be freely provided by the User, or collected automatically when using this Application.
            Any use of Cookies - or of other tracking tools - by this Application or by the owners of third party services used by this Application, unless stated otherwise, serves to identify Users and remember their preferences, for the sole purpose of providing the service required by the User.
            Failure to provide certain Personal Data may make it impossible for this Application to provide its services.
            The User assumes responsibility for the Personal Data of third parties published or shared through this Application and declares to have the right to communicate or broadcast them, thus relieving the Data Controller of all responsibility.</p>


            <h2>Mode and place of processing the Data</h2>
            <h3>Methods of processing</h3>
            <p>The Data Controller processes the Data of Users in a proper manner and shall take appropriate security measures to prevent unauthorized access, disclosure, modification, or unauthorized destruction of the Data.
            The Data processing is carried out using computers and/or IT enabled tools, following organizational procedures and modes strictly related to the purposes indicated. In addition to the Data Controller, in some cases, the Data may be accessible to certain types of persons in charge, involved with the operation of the site (administration, sales, marketing, legal, system administration) or external parties (such as third party technical service providers, mail carriers, hosting providers, IT companies, communications agencies) appointed, if necessary, as Data Processors by the Owner. The updated list of these parties may be requested from the Data Controller at any time.</p>
            <h3>Place</h3>
            <p>The Data is processed at the Data Controller's operating offices and in any other places where the parties involved with the processing are located. For further information, please contact the Data Controller.</p>
            <h3>Retention time</h3>
            <p>The Data is kept for the time necessary to provide the service requested by the User, or stated by the purposes outlined in this document, and the User can always request that the Data Controller suspend or remove the data.</p>
            <h2>The use of the collected Data</h2>
            <p>The Data concerning the User is collected to allow the Application to provide its services, as well as for the following purposes: Access to third party services' accounts, Location-based interactions, Content commenting and Interaction with external social networks and platforms.
            The Personal Data used for each purpose is outlined in the specific sections of this document.</p>
            <h2>Facebook permissions asked by this Application</h2>
            <p>This Application may ask some Facebook permissions allowing it to perform actions with the User's Facebook account and to retrieve information, including Personal Data, from it.
            For more information about the following permissions, refer to the Facebook permissions documentation and to the Facebook privacy policy.
            The permissions asked are the following:</p>
            <h3>Basic information</h3>
            <p>By default, this includes certain User’s Data such as id, name, picture, gender, and their locale. Certain connections of the User, such as the Friends, are also available. If the user has made more of their data public, more information will be available.</p>
            <h3>Checkins</h3>
            <p>Provides read access to the authorized user's check-ins</p>
            <h3>Email</h3>
            <p>Provides access to the user's primary email address</p>
            <h3>Likes<h3>
            <p>Provides access to the list of all of the pages the user has liked.</p>
            <h3>Photos</h3>
            <p>Provides access to the photos the user has uploaded, and photos the user has been tagged in.</p>
            <h3>Publish App Activity<h3>
            <p>Allows the app to publish to the Open Graph using Built-in Actions, Achievements, Scores, or Custom Actions. The app can also publish other activity which is detailed in the Facebook's Publishing Permissions document.</p>

            <h2>Detailed information on the processing of Personal Data</h2>
            <p>Personal Data is collected for the following purposes and using the following services:</p>
            <h3>Access to third party services' accounts</h3>

            <p>These services allow this Application to access Data from your account on a third party service and perform actions with it.
            These services are not activated automatically, but require explicit authorization by the User.<br />
            <strong>Access to the Facebook account (This Application)</strong><br />
            This service allows this Application to connect with the User's account on the Facebook social network, provided by Facebook Inc.
            Permissions asked: Checkins, Email, Likes, Photos and Publish App Activity.
            Place of processing : USA – Privacy Policy</p>


            <h3>Content commenting</h3>

            <p>Content commenting services allow Users to make and publish their comments on the contents of this Application.
            Depending on the settings chosen by the Owner, Users may also leave anonymous comments. If there is an email address among the Personal Data provided by the User, it may be used to send notifications of comments on the same content. Users are responsible for the content of their own comments.
            If a content commenting service provided by third parties is installed, it may still collect web traffic data for the pages where the comment service is installed, even when users do not use the content commenting service.<br />
            <strong>Facebook Comments (Facebook)</strong><br />
            Facebook Comments is a content commenting service provided by Facebook Inc. enabling the User to leave comments and share them on the Facebook platform.
            Personal Data collected: Cookie and Usage Data.
            Place of processing : USA – Privacy Policy</p>


            <h3>Interaction with external social networks and platforms</h3>

            <p>These services allow interaction with social networks or other external platforms directly from the pages of this Application.
            The interaction and information obtained by this Application are always subject to the User’s privacy settings for each social network.
            If a service enabling interaction with social networks is installed it may still collect traffic data for the pages where the service is installed, even when Users do not use it.<br />
            <strong>Facebook Like button and social widgets (Facebook)</strong><br />
            The Facebook Like button and social widgets are services allowing interaction with the Facebook social network provided by Facebook Inc.
            Personal Data collected: Cookie and Usage Data.
            Place of processing : USA – Privacy Policy</p>


            <h3>Location-based interactions</h3>

            <p><strong>Geolocation (This Application)</strong> <br />
            This Application may collect, use, and share User location Data in order to provide location-based services.
            Most browsers and devices provide tools to opt out from this feature by default. If explicit authorization has been provided, the User’s location data may be tracked by this Application.
            Personal Data collected: Geographic position.</p>


            <h2>Additional information about Data collection and processing</h2>
            <h3>Legal Action</h3>
            <p>The User's Personal Data may be used for legal purposes by the Data Controller, in Court or in the stages leading to possible legal action arising from improper use of this Application or the related services.<br />
            The User is aware of the fact that the Data Controller may be required to reveal personal data upon request of public authorities.</p>
            <h3>Additional information about User's Personal Data</h3>
            <p>In addition to the information contained in this privacy policy, this Application may provide the User with additional and contextual information concerning particular services or the collection and processing of Personal Data upon request.</p>
            <h3>System Logs and Maintenance</h3>
            <p>For operation and maintenance purposes, this Application and any third party services may collect files that record interaction with this Application (System Logs) or use for this purpose other Personal Data (such as IP Address).</p>
            <h3>Information not contained in this policy</h3>
            <p>More details concerning the collection or processing of Personal Data may be requested from the Data Controller at any time. Please see the contact information at the beginning of this document.</p>
            <h3>The rights of Users</h3>
            <p>Users have the right, at any time, to know whether their Personal Data has been stored and can consult the Data Controller to learn about their contents and origin, to verify their accuracy or to ask for them to be supplemented, cancelled, updated or corrected, or for their transformation into anonymous format or to block any data held in violation of the law, as well as to oppose their treatment for any and all legitimate reasons. Requests should be sent to the Data Controller at the contact information set out above.<br />
            This Application does not support “Do Not Track” requests.<br />
            To determine whether any of the third party services it uses honor the “Do Not Track” requests, please read their privacy policies.</p>
            <h3>Changes to this privacy policy</h3>
            <p>The Data Controller reserves the right to make changes to this privacy policy at any time by giving notice to its Users on this page. It is strongly recommended to check this page often, referring to the date of the last modification listed at the bottom. If a User objects to any of the changes to the Policy, the User must cease using this Application and can request that the Data Controller erase the Personal Data. Unless stated otherwise, the then-current privacy policy applies to all Personal Data the Data Controller has about Users.</p>

            <h2>Definitions and legal references</h2>

            <h3>Personal Data (or Data)</h3>
            <p>Any information regarding a natural person, a legal person, an institution or an association, which is, or can be, identified, even indirectly, by reference to any other information, including a personal identification number.</p>
            <h3>Usage Data</h3>
            <p>Information collected automatically from this Application (or third party services employed in this Application ), which can include: the IP addresses or domain names of the computers utilized by the Users who use this Application, the URI addresses (Uniform Resource Identifier), the time of the request, the method utilized to submit the request to the server, the size of the file received in response, the numerical code indicating the status of the server's answer (successful outcome, error, etc.), the country of origin, the features of the browser and the operating system utilized by the User, the various time details per visit (e.g., the time spent on each page within the Application) and the details about the path followed within the Application with special reference to the sequence of pages visited, and other parameters about the device operating system and/or the User's IT environment.</p>
            <h3>User</h3>
            <p>The individual using this Application, which must coincide with or be authorized by the Data Subject, to whom the Personal Data refer.</p>
            <h3>Data Subject</h3>
            <p>The legal or natural person to whom the Personal Data refers to.</p>
            <h3>Data Processor (or Data Supervisor)</h3>
            <p>The natural person, legal person, public administration or any other body, association or organization authorized by the Data Controller to process the Personal Data in compliance with this privacy policy.</p>
            <h3>Data Controller (or Owner)</h3>
            <p>The natural person, legal person, public administration or any other body, association or organization with the right, also jointly with another Data Controller, to make decisions regarding the purposes, and the methods of processing of Personal Data and the means used, including the security measures concerning the operation and use of this Application. The Data Controller, unless otherwise specified, is the Owner of this Application.</p>
            <h3>This Application</h3>
            <p>The hardware or software tool by which the Personal Data of the User is collected.</p>
            <h3>Cookie</h3>
            <p>Small piece of data stored in the User's device.</p>
            <h3>Legal information</h3>
            <p>Notice to European Users: this privacy statement has been prepared in fulfillment of the obligations under Art. 10 of EC Directive n. 95/46/EC, and under the provisions of Directive 2002/58/EC, as revised by Directive 2009/136/EC, on the subject of Cookies.
            This privacy policy relates solely to this Application.</p>
            <p>Latest update: June 11, 2014.</p>
                    <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </div>
    <div class="clear"></div>
</div>