<?php
    $application = $this->getApplication();

    $form = new Application_Form_Advanced();
    $form->populate($application->getData());
?>
<div class="application_settings application">
    <div class="application_header app_name">
        <?php echo $this->getPartialHtml('customization_header'); ?>
    </div>
    <div class="application_content inner_content">
        <div class="title">
            <i class="left icon-info"></i>
            <h2 class="left inner_content f-rounded"><?php echo __('Settings'); ?></h2>
            <div class="clear"></div>
            <hr />
        </div>
        <div class="area">
            <h3 class="title">
                <span class="left area"><?php echo __("Advanced Application Options"); ?></span>
                <hr />
                <div class="clear"></div>
            </h3>
            <div id="advanced" class="area_content">
                <?php echo $form; ?>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    bindForms("#advanced");
</script>
