<div>
    <ul class="list-group">
        <li class="animated step1 list-group-item"><i id="step1_ok" class="icon-ok blue5 animated" style="opacity:0;"></i> Welcome</li>
        <li class="animated step2 list-group-item"><i id="step2_ok" class="icon-ok blue5 animated" style="opacity:0;"></i> Agreement</li>
        <li class="animated step3 list-group-item"><i id="step3_ok" class="icon-ok blue5 animated" style="opacity:0;"></i> Database</li>
        <li class="animated step4 list-group-item"><i id="step4_ok" class="icon-ok blue5 animated" style="opacity:0;"></i> Installation</li>
        <li class="animated step5 list-group-item"><i id="step5_ok" class="icon-ok blue5 animated" style="opacity:0;"></i> Admin</li>
        <li class="animated step6 list-group-item"><i id="step6_ok" class="icon-ok blue5 animated" style="opacity:0;"></i> Application</li>
        <li class="animated step7 list-group-item"><i id="step7_ok" class="icon-ok blue5 animated" style="opacity:0;"></i> Done!</li>
    </ul>
</div>
