<?php
$has_previewer = Installer_Model_Installer::hasModule("previewer");
$previewer = null;
if ($has_previewer && method_exists(new Previewer_Model_Previewer(), "getInstance")) {
    $previewer = Previewer_Model_Previewer::getInstance();
}
?>
<div id="iphone">
    <?php if($has_previewer && $previewer && $previewer->getShowModalButton()==1 && $this->_canAccess("previewer")): ?>
        <button id="previewer"
                class="btn btn-grey btn-previewer"><?php echo __('Preview on your phone'); ?></button>
    <?php endif; ?>
    <div class="iphone_content">

        <iframe id="mobile_overview"
                sandbox="allow-same-origin allow-scripts allow-forms allow-modals"></iframe>
        <div id="mask-overview"
             class="mask">
            <button id="hide_mask"
                    class="reverse btn color-blue"
                    style="display:none;">
                <i class="fa fa-times"></i>
            </button>
            <div class="loader"></div>
        </div>
    </div>
</div>

<script type="text/javascript">
$(document).ready(function() {
    $("#mobile_overview").attr("src", "<?php echo $this->getApplication()->getUrl("/", [], Core_Model_Language::getCurrentLanguage(), true); ?>?overview=1");
    iframe.iframeIsLoaded = function() {
        iframe.content.find("body").removeClass("platform-browser").addClass("platform-ios");
        $("#mask-overview").hide();

        $("#mobile_overview")
        .contents()
        .find("ion-side-menu-content")
        .css({borderRadius: "20px", border: "1px solid #d4d4d4", boxShadow: "none"});

        setTimeout(function() {
            if((typeof iframe != "undefined")
                && (typeof iframe.f != "undefined")
                && (typeof iframe.f.setPath == "function")
                && (typeof window.overviewEvents != "undefined")
                && (window.overviewEvents.length > 0)) {

                iframe.contentWindow.setPath(window.overviewEvents[0]);
                window.overviewEvents = [];
            }
        }, 1000);

    };

});
</script>