<?php
$has_previewer = Installer_Model_Installer::hasModule("previewer");
$previewer = null;
if($has_previewer && method_exists(new Previewer_Model_Previewer(), "getInstance")) {
    $previewer = Previewer_Model_Previewer::getInstance();
}
?>
<?php if($has_previewer && $previewer && $previewer->getShowModalButton()==1 && $this->_canAccess("previewer")): ?>
    <button id="previewer"
            class="btn color-blue"
            style="position: absolute;right: 302px;top: -150px;"><?php echo __('Preview on your phone'); ?></button>
<?php endif; ?>
<div id="iphone">
    <div class="iphone_content">
        <?php $hide_status_bar = $this->getApplication()->getIosStatusBarIsHidden() ? ' hide' : ''; ?>
        <p id="iphone_header"
           class="status_bar iphone_header toolbar_overview a-center<?php echo $hide_status_bar; ?>"><?php echo date('H:m'); ?></p>
        <p id="iphone6_header"
           class="status_bar iphone6_header toolbar_overview a-center<?php echo $hide_status_bar; ?>"
           style="display:none;"><?php echo date('H:m'); ?></p>
        <p id="android_header"
           class="android_header toolbar_overview a-right"
           style="display:none"><?php echo date('H:m'); ?></p>

        <iframe id="mobile_overview"
                sandbox="allow-same-origin allow-scripts allow-forms allow-modals"
                width="324"
                height="579"
                style="overflow: hidden; background-color: lightgrey;"></iframe>
        <div id="mask-overview"
             class="mask">
            <button id="hide_mask"
                    class="reverse btn color-blue"
                    style="display:none;">
                <i class="fa fa-times"></i>
            </button>
            <div class="loader"></div>
        </div>
    </div>
    <div class="btn-group-vertical">
        <button type="button"
                class="overview_size mobile-advice"
                rel="mini"></button>
        <button type="button"
                class="overview_size mobile-advice"
                rel="iphone5"></button>
        <button type="button"
                class="overview_size mobile-advice"
                rel="iphone6"></button>
        <button class="overview_size mobile-advice"
                rel="android"><i class="fa fa-android"></i></button>
        <button class="overview_size mobile-advice"
                rel="html5"><i class="fa fa-html5"></i></button>
    </div>
</div>

<script type="text/javascript">
    let overview = [];
    overview['iphone5'] = {
        background: '<?php echo $this->getImage('customization/overview/iphone5.svg'); ?>',
        width: 324,
        height: 579,
        container_width: 381,
        container_height: 805,
        marginTop: 112,
        marginLeft: 31,
        toolbar: ''
    };
    overview['iphone6'] = {
        background: '<?php echo $this->getImage('customization/overview/iphone6.svg'); ?>',
        width: 414,
        height: 736,
        container_width: 455,
        container_height: 971,
        marginTop: 102,
        marginLeft: 25,
        toolbar: ''
    };
    overview['android'] = {
        background: '<?php echo $this->getImage('customization/overview/android.svg'); ?>',
        width: 367,
        height: 603,
        container_width: 400,
        container_height: 785,
        marginTop: 84,
        marginLeft: 17,
        toolbar: ''
    };
    overview['html5'] = {
        background: '<?php echo $this->getImage('customization/overview/html5.svg'); ?>',
        width: 352,
        height: 675,
        container_width: 400,
        container_height: 730,
        marginTop: 20,
        marginLeft: 22,
        toolbar: ''
    };
    overview['mini'] = {
        background: '<?php echo $this->getImage('customization/overview/responsive_overview/iphone5.svg'); ?>',
        width: 324,
        height: 578,
        container_width: 381,
        container_height: 805,
        marginTop: 58,
        marginLeft: 32,
        toolbar: ''
    };
    let buttonOverviewSize = $('button.overview_size');
    let iPhone = $('#iphone');

    let setSize = function (rel) {
        let sizes = overview[rel];
        if (sizes && !$(this).hasClass('active')) {

            let button = $('.overview_size[rel="' + rel + '"]');

            localStorage.setItem('overview_last_choice', rel);

            $('#mobile_overview').attr('width', sizes.width)
            .attr('height', sizes.height)
            ;

            $('.toolbar_overview').hide();
            if (sizes.toolbar) {
                $('#'+sizes.toolbar).show();
            }

            iPhone.css('background-image', 'url('+sizes.background+')');
            iPhone.css({
                width: sizes.container_width,
                height: sizes.container_height
            });

            $('.iphone_content').css({
                'margin-top' : sizes.marginTop,
                'margin-left': sizes.marginLeft
            });

            /** Resize mask */
            $("#mask-overview").css({
                'top' : sizes.marginTop,
                'left': sizes.marginLeft,
                'width': sizes.width,
                'height': sizes.height
            });

            if(button.attr("rel").indexOf("iphone") >= 0) {
                iframe.content.find("body").removeClass("platform-browser").addClass("platform-ios")
            } else {
                iframe.content.find("body").removeClass("platform-ios").addClass("platform-android")
            }

            $('.overview_size').removeClass('active no-background');
            button.addClass('active no-background');
        }
    };

    buttonOverviewSize.off("click");
    buttonOverviewSize.on("click", function() {
        let rel = $(this).attr('rel');
        setSize(rel);
    });

    $(document).ready(function() {
        $("#mobile_overview").attr("src", "<?php echo $this->getApplication()->getUrl("/", array(), Core_Model_Language::getCurrentLanguage(), true); ?>?overview=1");
        iframe.iframeIsLoaded = function() {
            iframe.content.find("body").removeClass("platform-browser").addClass("platform-ios");
            $("#mask-overview").hide();

            setTimeout(function() {
                if((typeof iframe != "undefined")
                    && (typeof iframe.f != "undefined")
                    && (typeof iframe.f.setPath == "function")
                    && (typeof window.overviewEvents != "undefined")
                    && (window.overviewEvents.length > 0)) {

                    iframe.contentWindow.setPath(window.overviewEvents[0]);
                    window.overviewEvents = [];
                }
            }, 1000);

        };

        let lastChoice = localStorage.getItem('overview_last_choice');
        if (lastChoice) {
            setSize(lastChoice);
        }
    });

</script>

<style type="text/css">
    #mask-overview {
        left: 30px;
        top: 113px;
        width: 324px;
        height: 578px;
    }
    @media (max-width: 1440px) and (min-width: 768px) {
        #mask-overview {
            left: 32px;
            top: 58px;
        }
    }
</style>