<?php
$application = $this->getApplication();
$headerRgba = $application->getBlock("header")->getBackgroundColorRGBA();

?>
<div id="iphone">
    <div class="iphone_content">

        <img class="homepage-preview"
             style="width: 100%; height: 100%;"
             src="/app/sae/design/desktop/flat/images/customization/overview/homescreen.png" />

        <div id="phone-bar">
            <span class="pull-left"
                  style="font-weight: 500;"><?php echo date("G:i") ?></span>
            <span class="pull-right">
                <i class="fa fa-signal"></i>
                <i class="fa fa-wifi"></i>
                <i class="fa fa-battery-full"></i>
            </span>
        </div>

        <div id="overview_icon"
             class="overview mobile_view right touch_icon">
            <div class="icon">
                <img src="<?php echo $application->getIcon(); ?>"
                     id="preview_icon"
                     width="62"
                     height="62" />
            </div>
            <p id="app_name"
               class="no-margin"><?php echo $application->getShortName(); ?></p>
        </div>
    </div>

    <script type="text/javascript">
        $(document).ready(function() {
            var phoneBar = $("#phone-bar");
            phoneBar.show();

            $("#overview").affix({
                offset: {
                    top: 60,
                    bottom: 20
                }
            });
        });
    </script>

    <style type="text/css">
        .homepage-preview {
            width: 100%;
            height: 100%;
            overflow: hidden;
            background-color: #e9e9eb;
            padding: 10px;
            border-radius: 30px;
            border: 1px solid #c5c5c5;
            box-shadow: 1px 1px 1px #d4d4d4;
        }

        div#phone-bar {
            top: calc(-1 * 87vh + 15px);
            color: white !important;
        }

        #overview_icon {
            position: absolute;
            top: 27.5vh;
            left: 4.6vh;
        }

        #overview_icon img {
            width: 7.1vh;
            height: 7vh;
            border-radius: 1.5vh;
        }

        #overview_icon #app_name {
            text-align: center;
            font-size: 1.4vh;
            font-weight: 400;
            color: #cecece;
            margin-top: 4px;
            letter-spacing: 1px;
            overflow: hidden;
            text-overflow: clip;
            width: 7.1vh;
            height: 1.4vh;
            line-height: 1.5vh;
        }

    </style>
</div>

