<?php

use Siberian\Json;
use Siberian\Provider;
use Siberian\Version;

$backofficeThemeView = __get('display_backoffice_theme');

$displayTheme = false;
if (empty($backofficeThemeView)) {
    $displayTheme = true;
}

$systemError = false;

$allow_url_fopen = (integer)ini_get('allow_url_fopen');
if ($allow_url_fopen !== 1) {
    $systemError = true;
}
$max_execution_time = ini_get('max_execution_time');
if ($max_execution_time < 300) {
    $systemError = true;
}
$memory_limit = ini_get('memory_limit');
$mlNumeric = (int)preg_replace("/[^0-9]/", '', $memory_limit);
if ($mlNumeric < 512) {
    $systemError = true;
}

$post_max_size = ini_get('post_max_size');
$pmsNumeric = (int)preg_replace("/[^0-9]/", '', $post_max_size);
if ($pmsNumeric < 100) {
    $systemError = true;
}

$upload_max_filesize = ini_get('upload_max_filesize');
$umfNnumeric = (int)preg_replace("/[^0-9]/", '', $upload_max_filesize);
if ($umfNnumeric < 100) {
    $systemError = true;
}

$exec = function_exists('exec');
if (!$exec) {
    $systemError = true;
}

$pathError = false;

$pathVarTmp = path('/var/tmp');
$varTmp = is_writable($pathVarTmp);
if (!$varTmp) {
    $pathError = true;
}

$pathVarLog = path('/var/log');
$varLog = is_writable($pathVarLog);
if (!$varLog) {
    $pathError = true;
}

$pathVarCache = path('/var/cache');
$varCache = is_writable($pathVarCache);
if (!$varCache) {
    $pathError = true;
}

// Unstable notice
$updates = Provider::getUpdates();
$isUnstable = false;
$statusText = '';
if (array_key_exists(Version::VERSION, $updates)) {
    $current = $updates[Version::VERSION];
    $isUnstable = ('unstable' === strtolower($current['status']));
    $statusText = $current['statusText'];
}

?>
<div class="row">
    <div class="col-md-8 col-md-offset-2 col-sm-12">
        <span ng-if="!sslLoading">
            <p class="alert"
               ng-class="{
                 'alert-info': sslWarning.remainInDays > 5,
                 'alert-danger': sslWarning.remainInDays <= 5
               }"
               ng-show="sslWarning && sslWarning.showWarning"
               ng-bind-html="sslWarning.message"></p>
            <p class="alert alert-info"
               ng-show="!sslWarning">
                <?php echo __('HTTPS is not available on your server.') ?></p>
        </span>

        <?php
        $mobilcartFlag = __get('mobilcart_warning');
        ?>
        <?php if ($mobilcartFlag === 'show'): ?>
            <div class="alert alert-warning">
                <?php echo __('You have Mmobilcart installed, this module is known to cause a lot of side-effects and it is recommended to remove it'); ?>
                <br/>
                <?php echo __('Please note it affects: emails, templates & pages behavior in editor, backoffice & applications.') ?>
                <br/>
            </div>
        <?php endif; ?>

        <?php if ($isUnstable && !isDev()): ?>
            <div class="alert alert-danger">
                <?php echo p__('backoffice', 'You are currenctly running a version of Siberian marked as unstable for production, please follow the instructions'); ?>
                :
                <a href="/installer/backoffice_module"
                   style="letter-spacing: 2px;"><?php echo $statusText ?></a>
                <br/>
                <?php echo p__('backoffice', 'You can review the release notes and their statuses'); ?>:
                <a style="letter-spacing: 2px;"
                   href="https://updates02.siberiancms.com/release-notes/all/index.php"
                   target="_blank"><?php echo p__('backoffice', 'Release notes'); ?></a>
            </div>
        <?php endif; ?>

    </div>

    <?php if ($displayTheme): ?>
        <div class="col-md-8 col-md-offset-2 col-sm-12">
            <div class="alert alert-info">
                <?php echo __('New backoffice themes are available, check them out <a href="/system/backoffice_config_design">here</a>.') ?>
            </div>
        </div>
    <?php endif; ?>

    <?php if (isDev() || $systemError || $pathError): ?>
        <div class="col-xs-12 col-md-12">
            <sb-section title="'<?php echo __title("System diagnostic"); ?>'"
                        klass="'critical'"
                        button="button">

                <?php if ($systemError || $pathError): ?>
                    <div class="alert alert-danger">
                        <?php echo p__('backoffice', 'Incorrect settings have been detected on your server, below are all the recommended settings, the ones in red are incorrect and can lead to issue while running the editor & applications.') ?>
                    </div>
                <?php endif; ?>

                <table class="table table dashboard no-wrap">
                    <col width="32px"/>
                    <col width="150px"/>
                    <col width="55%"/>
                    <tbody>
                    <tr>
                        <td rowspan="6">
                            <?php if ($systemError): ?>
                                <img src="/app/sae/design/desktop/backoffice/images/service/offline-16.png"/>
                            <?php else: ?>
                                <img src="/app/sae/design/desktop/backoffice/images/service/running-16.png"/>
                            <?php endif; ?>
                        </td>
                        <td rowspan="6">
                            <?php echo __('PHP Settings') ?>
                        </td>
                        <td>allow_url_fopen</td>
                        <td>
                            <?php if ($allow_url_fopen == 1): ?>
                                <span class="service-green"> <?php echo $allow_url_fopen ?></span>
                            <?php else: ?>
                                <span class="service-red"> <?php echo $allow_url_fopen ?></span>
                            <?php endif; ?>
                        </td>
                        <td class="text-right">
                            <?php echo p__('backoffice', 'Must be %s / %s', 'On', '1') ?>
                        </td>
                    </tr>
                    <tr>
                        <td>max_execution_time</td>
                        <td>
                            <?php if ($max_execution_time >= 300): ?>
                                <span class="service-green"> <?php echo $max_execution_time ?></span>
                            <?php else: ?>
                                <span class="service-red"> <?php echo $max_execution_time ?></span>
                            <?php endif; ?>
                        </td>
                        <td class="text-right">
                            <?php echo p__('backoffice', 'Must be at least %s', 300) ?>
                        </td>
                    </tr>
                    <tr>
                        <td>memory_limit</td>
                        <td>
                            <?php if ($mlNumeric >= 512): ?>
                                <span class="service-green"> <?php echo $memory_limit ?></span>
                            <?php else: ?>
                                <span class="service-red"> <?php echo $memory_limit ?></span>
                            <?php endif; ?>
                        </td>
                        <td class="text-right">
                            <?php echo p__('backoffice', 'Must be at least %s', '512M') ?>
                        </td>
                    </tr>
                    <tr>
                        <td>post_max_size</td>
                        <td>
                            <?php if ($pmsNumeric >= 100): ?>
                                <span class="service-green"> <?php echo $post_max_size ?></span>
                            <?php else: ?>
                                <span class="service-red"> <?php echo $post_max_size ?></span>
                            <?php endif; ?>
                        </td>
                        <td class="text-right">
                            <?php echo p__('backoffice', 'Must be at least %s', '100M') ?>
                        </td>
                    </tr>
                    <tr>
                        <td>upload_max_filesize</td>
                        <td>
                            <?php if ($umfNnumeric >= 100): ?>
                                <span class="service-green"> <?php echo $upload_max_filesize ?></span>
                            <?php else: ?>
                                <span class="service-red"> <?php echo $upload_max_filesize ?></span>
                            <?php endif; ?>
                        </td>
                        <td class="text-right">
                            <?php echo p__('backoffice', 'Must be at least %s', '100M') ?>
                        </td>
                    </tr>
                    <tr>
                        <td>exec()</td>
                        <td>
                            <?php if ($exec): ?>
                                <span class="service-green"> <?php echo p__('backoffice', 'Enabled') ?></span>
                            <?php else: ?>
                                <span class="service-red"> <?php echo p__('backoffice', 'Disabled') ?></span>
                            <?php endif; ?>
                        </td>
                        <td class="text-right">
                            <?php echo p__('backoffice', 'Must be enabled') ?>
                        </td>
                    </tr>
                    <tr>
                        <td rowspan="6">
                            <?php if ($pathError): ?>
                                <img src="/app/sae/design/desktop/backoffice/images/service/offline-16.png"/>
                            <?php else: ?>
                                <img src="/app/sae/design/desktop/backoffice/images/service/running-16.png"/>
                            <?php endif; ?>
                        </td>
                        <td rowspan="6">
                            <?php echo __('System') ?>
                        </td>
                        <td><?php echo $pathVarTmp ?></td>
                        <td>
                            <?php if ($varTmp): ?>
                                <span class="service-green"> <?php echo p__('backoffice', 'Writeable') ?></span>
                            <?php else: ?>
                                <span class="service-red"> <?php echo p__('backoffice', 'Unable to write') ?></span>
                            <?php endif; ?>
                        </td>
                        <td class="text-right">
                            <?php echo p__('backoffice', 'Must be writeable') ?>
                        </td>
                    </tr>
                    <tr>
                        <td><?php echo $pathVarLog ?></td>
                        <td>
                            <?php if ($varLog): ?>
                                <span class="service-green"> <?php echo p__('backoffice', 'Writeable') ?></span>
                            <?php else: ?>
                                <span class="service-red"> <?php echo p__('backoffice', 'Unable to write') ?></span>
                            <?php endif; ?>
                        </td>
                        <td class="text-right">
                            <?php echo p__('backoffice', 'Must be writeable') ?>
                        </td>
                    </tr>
                    <tr>
                        <td><?php echo $pathVarCache ?></td>
                        <td>
                            <?php if ($varCache): ?>
                                <span class="service-green"> <?php echo p__('backoffice', 'Writeable') ?></span>
                            <?php else: ?>
                                <span class="service-red"> <?php echo p__('backoffice', 'Unable to write') ?></span>
                            <?php endif; ?>
                        </td>
                        <td class="text-right">
                            <?php echo p__('backoffice', 'Must be writeable') ?>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </sb-section>
        </div>

        <div class="clearfix"></div>
    <?php endif; ?>


    <div class="col-xs-12 col-md-6">
        <sb-section title="'<?php echo __title("New messages"); ?>'"
                    button="button">
            <div ng-if="messagesIsLoading"
                 class="async-loader">
                <i class="fa fa-circle-o-notch fa-spin fa-2x fa-fw"></i>
            </div>
            <table ng-if="!messagesIsLoading"
                   class="table table dashboard no-wrap small-padding">
                <col width="50%"/>
                <col width="40%"/>
                <col width="10%"/>
                <tbody>
                <tr ng-repeat="message in new_messages"
                    ng-if="new_messages.length">
                    <td>
                        <i ng-if="message.source == 'cron' || message.priority"
                           class="fa fa-exclamation"></i>
                        {{ message.title }}
                    </td>
                    <td class="text-right">{{ message.created_at }}</td>
                    <td class="text-right">
                        <a href="<?php echo $this->getUrl("backoffice/notif_message") ?>/message_id/{{ message.id }}"
                           class="btn btn-xs btn-primary"
                           target="_blank"><?php echo __("Read") ?></a>
                    </td>
                </tr>
                <tr ng-if="!new_messages.length">
                    <td colspan="3"><?php echo __("You have no new messages.") ?></td>
                </tr>
                </tbody>
            </table>
        </sb-section>

        <br/>

        <sb-section title="'<?php echo __title("Services", "'"); ?>'"
                    button="button">
            <div ng-if="isLoading"
                 class="async-loader">
                <i class="fa fa-circle-o-notch fa-spin fa-2x fa-fw"></i>
            </div>
            <table ng-if="!isLoading"
                   class="table table dashboard no-wrap">
                <col width="32px"/>
                <col width="180px"/>
                <tbody>
                <tr>
                    <td>
                        <img ng-if="services.cron"
                             src="/app/sae/design/desktop/backoffice/images/service/running-16.png"/>
                        <img ng-if="!services.cron"
                             src="/app/sae/design/desktop/backoffice/images/service/offline-16.png"/>
                    </td>
                    <td>
                        <?php echo __("Cron scheduler") ?>
                    </td>
                    <td>
                        <table ng-show="services.cron"
                               class="sub-table">
                            <tbody>
                            <tr>
                                <td colspan="3">
                                    <button class="btn btn-xs btn-primary"
                                            ng-click="clear('locks', '<?php echo addcslashes(__("You are about to clean all the cron lock files !\nAre you sure ?"), "'"); ?>');"><?php echo __("Remove locks") ?></button>
                                </td>
                            </tr>
                            <tr ng-show="services.cron_error.full"
                                ng-class="{ 'no-border-bottom': !cron_error_show }">
                                <td><i class="fa fa-exclamation-triangle"></i><?php echo __("Last cron error") ?>
                                    :[<strong>{{ services.cron_error.date }}</strong>] <span
                                            class="service-red"> {{ services.cron_error.short }}</span>
                                </td>
                                <td></td>
                                <td class="text-right">
                                    <button class="btn btn-xs btn-primary"
                                            ng-hide="cron_error_show"
                                            ng-click="cron_error_show = !cron_error_show;"><?php echo __("Show more") ?></button>
                                    <button class="btn btn-xs btn-primary"
                                            ng-hide="!cron_error_show"
                                            ng-click="cron_error_show = !cron_error_show;"><?php echo __("Hide") ?></button>
                                    <button class="btn btn-xs btn-primary"
                                            ng-hide="!services.cron_error.full"
                                            ng-click="clear('cron_error');"><?php echo __("Clear") ?></button>
                                </td>
                            </tr>
                            <tr ng-show="services.cron_error.date">
                                <td></td>
                                <td></td>
                            </tr>
                            <tr ng-hide="!cron_error_show">
                                <td colspan="3"
                                    style="white-space: initial;"
                                    ng-bind-html="services.cron_error.full"></td>
                            </tr>
                            </tbody>
                        </table>
                        <?php if (Cron_Model_Cron::is_active()): ?>
                            <span ng-show="!services.cron">
                                <?php echo __("Not running") ?> <a class="btn btn-xs btn-primary"
                                                                   ng-click="showCronModal();"><?php echo __("How to install the cron scheduler ?") ?></a>
                            </span>
                        <?php else: ?>
                            <span>
                                <?php echo __("Disabled") ?>, <a
                                        href="<?php echo $this->getUrl("backoffice/advanced_cron") ?>"><?php echo __("see Settings > Advanced > Configuration > Cron to edit options.") ?></a>
                            </span>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <td>
                        <img ng-if="extensions.php_sqlite3 || extensions.bin_sqlite3"
                             src="/app/sae/design/desktop/backoffice/images/service/running-16.png"/>
                        <img ng-if="!extensions.php_sqlite3 && !extensions.bin_sqlite3"
                             src="/app/sae/design/desktop/backoffice/images/service/offline-16.png"/>
                    </td>
                    <td>
                        <?php echo __("Required extensions") ?>
                    </td>
                    <td class="extensions">
                            <span class="group"
                                  style="margin-left: 0;">
                            <?php $phpVersion = phpversion(); ?>
                                <?php echo __("PHP version") ?>:&nbsp;
                                <span class="service-green"><b><?php echo explode("-", $phpVersion)[0] ?></b></span>&nbsp;&nbsp;
                            </span>

                        <span class="group" ng-show="extensions.php_sqlite3">
                                <?php echo __("PHP SQLite3:") ?>
                            <span ng-show="extensions.php_sqlite3"><span class="service-green"><i
                                            class="fa fa-check"></i></span></span>
                                    <span ng-show="!extensions.php_sqlite3"><span
                                                class="service-red"><?php echo __("Not found") ?></span></span>
                                </span>
                        <span ng-show="!extensions.php_sqlite3">
                                    <?php echo __("Bin SQLite3:") ?>
                            <span ng-show="extensions.bin_sqlite3"><span class="service-green"><i
                                            class="fa fa-check"></i></span></span>
                                        <span ng-show="!extensions.bin_sqlite3"><span
                                                    class="service-red"><?php echo __("Not found") ?></span></span>
                            </span>
                    </td>
                </tr>
                <tr>
                    <td>
                        <img src="/app/sae/design/desktop/backoffice/images/service/info-16.png"/>
                    </td>
                    <td>
                        <?php echo __("Optional binaries") ?>
                    </td>
                    <td class="extensions">
                            <span class="group"
                                  style="margin-left: 0;">
                                <?php echo __("OptiPNG:") ?>
                                <span ng-show="libraries.optipng">
                                    <span class="service-green"><i class="fa fa-check"></i></span>
                                </span>
                                <span ng-show="!libraries.optipng">
                                    <span class="service-blue"><?php echo __("Not found") ?></span>,
                                </span>
                            </span>

                        <span class="group">
                                <?php echo __("JpegOptim:") ?>
                            <span ng-show="libraries.jpegoptim">
                                    <span class="service-green"><i class="fa fa-check"></i></span>
                                </span>
                                <span ng-show="!libraries.jpegoptim">
                                    <span class="service-blue"><?php echo __("Not found") ?></span>,
                                </span>
                            </span>

                        <span class="group">
                                <?php echo __("PNGQuant:") ?>
                            <span ng-show="libraries.pngquant">
                                    <span class="service-green"><i class="fa fa-check"></i></span>
                                </span>
                                <span ng-show="!libraries.pngquant">
                                    <span class="service-blue"><?php echo __("Not found") ?></span>,
                                </span>
                            </span>

                        <span class="group">
                                <?php echo __("ClamAV:") ?>
                            <span ng-show="libraries.clamav">
                                    <span class="service-green"><i class="fa fa-check"></i></span>
                                </span>
                                <span ng-show="!libraries.clamav">
                                    <span class="service-blue"><?php echo __("Not found") ?></span>
                                </span>
                            </span>
                    </td>
                </tr>
                <tr ng-show="system_diagnostic.length !== 0">
                    <td>
                        <img src="/app/sae/design/desktop/backoffice/images/service/info-16.png"/>
                    </td>
                    <td>
                        <?php echo __("System Diagnostic") ?>
                    </td>
                    <td class="extensions">
                            <span ng-repeat="diagnostic in system_diagnostic">
                                {{ diagnostic.label }}:
                                <span ng-class="{
                                    'service-red': !diagnostic.valid,
                                    'service-green': diagnostic.valid }">{{ diagnostic.message }}</span>
                                <br/>
                            </span>
                    </td>
                </tr>
                <tr ng-show="external_services.length !== 0">
                    <td>
                        <img src="/app/sae/design/desktop/backoffice/images/service/info-16.png"/>
                    </td>
                    <td>
                        <?php echo __("External extensions") ?>
                    </td>

                    <td ng-if="servicesIsLoading">
                        <div class="async-loader">
                            <i class="fa fa-circle-o-notch fa-spin fa-fw"></i> <?php echo __("Loading, please wait ...") ?>
                        </div>
                    </td>
                    <td ng-if="!servicesIsLoading">
                            <span ng-repeat="(name, values) in external_services">
                                {{ name }}:
                                <span ng-show="values.status"><span
                                            class="service-green"> {{ values.text }}</span> </span>
                                <span ng-show="!values.status"><span
                                            class="service-red"> {{ values.text }}</span> </span>
                            </span>
                    </td>
                </tr>
                <tr>
                    <td>
                        <img src="/app/sae/design/desktop/backoffice/images/service/info-16.png"/>
                    </td>
                    <td>
                        <?php echo __("Web space") ?>
                    </td>
                    <td>
                        <table class="sub-table">
                            <tr class="no-border-bottom">
                                <td colspan="3">
                                    <div class="alert alert-info" style="padding: 4px; margin: 0;">
                                        <i class="fa fa-database"></i><?php echo __("Disk usage & Cache:") ?>
                                        <?php echo __('values are refreshed once a day only!') ?>
                                    </div>
                                </td>
                            </tr>
                            <tr ng-class="{ 'no-border-bottom': !show_more_size }">
                                <td>
                                    <?php echo __("Total usage:") ?>
                                </td>
                                <td colspan="2">
                                    {{ server_usage.total }}
                                </td>
                            </tr>
                            <tr>
                                <td class="indent"><?php echo __("Log (var/log, log files)") ?></td>
                                <td>{{ server_usage.log_size }}</td>
                                <td class="text-right">
                                    <button class="btn btn-xs btn-primary"
                                            ng-click="clear('log', '<?php echo addcslashes(__("You are about to clean all your log files !\nAre you sure ?"), "'"); ?>');"><?php echo __("Clear") ?></button>
                                </td>
                            </tr>
                            <tr>
                                <td class="indent"><?php echo __("Cache (var/cache, system cache)") ?></td>
                                <td>{{ server_usage.cache_size }}</td>
                                <td class="text-right">
                                    <button class="btn btn-xs btn-primary"
                                            ng-click="clear('cache');"><?php echo __("Clear") ?></button>
                                </td>
                            </tr>
                            <tr>
                                <td class="indent"><?php echo __("Cache (var/cache_images, images cache)") ?></td>
                                <td>{{ server_usage.cache_images_size }}</td>
                                <td class="text-right">
                                    <button class="btn btn-xs btn-primary"
                                            ng-click="clear('cache_images');"><?php echo __("Clear") ?></button>
                                </td>
                            </tr>
                            <tr>
                                <td class="indent"><?php echo __("Temp (var/tmp, application sources)") ?></td>
                                <td>{{ server_usage.tmp_size }}</td>
                                <td class="text-right">
                                    <button class="btn btn-xs btn-primary"
                                            ng-click="clear('tmp', '<?php echo addcslashes(__("You are about to wipe all your temporary files, this includes the generated sources builds !\nAre you sure ?"), "'"); ?>');"><?php echo __("Clear") ?></button>
                                </td>
                            </tr>
                            <tr>
                                <td class="indent"><?php echo __("Applications/Previewer manifest for automatic updates.") ?></td>
                                <td>-</td>
                                <td class="text-right">
                                    <button class="btn btn-xs btn-primary"
                                            ng-click="clear('app_manifest', '<?php echo addcslashes(__("Are you sure ?"), "'"); ?>');"><?php echo __("Rebuild") ?></button>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
        </sb-section>

        <br/>
    </div>

    <div class="clearfix visible-xs visible-sm"></div>

    <div class="col-md-12 col-lg-6">
        <sb-section title="'<?php echo __title("Statistics"); ?>'"
                    button="button">
            <div ng-show="graphIsLoading"
                 class="async-loader">
                <i class="fa fa-circle-o-notch fa-spin fa-2x fa-fw"></i>
            </div>
            <canvas ng-show="!graphIsLoading"
                    id="line"
                    class="chart chart-bar"
                    height="420"
                    width="1040"
                    chart-data="graphData"
                    chart-labels="graphLabels"
                    chart-options="graphOptions"
                    chart-series="graphSeries"
                    chart-dataset-override="graphDatasetOverride"
            </canvas>
        </sb-section>
    </div>
</div>


<div id="cron-help"
     ng-hide="!show_cron_modal">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title"><?php echo __("Cron scheduler help") ?></h4>
        </div>
        <div class="modal-body">
            <?php
            $base_path = Core_Model_Directory::getBasePathTo("");
            $guessed_php = "/usr/bin/php";
            if (file_exists("/opt/plesk/php/5.6/bin/php")) {
                $guessed_php = "/opt/plesk/php/5.6/bin/php";
            }
            ?>

            <span>
                <?php echo __("Check if this cron command is installed under the web user & if you have set a timezone in Settings > General"); ?><br/><br/>
                <pre>* * * * * <?php echo $guessed_php ?> -d memory_limit=512M -f <?php echo $base_path; ?>cron.php >> <?php echo $base_path; ?>var/log/cron.log 2>&1</pre>
                <br/>
                <?php echo __("Otherwise install it manually, from your panel, or directly from your ssh access."); ?>
                <br/>
                <?php echo __("The PHP executable guessed path <b>'%s'</b> may be incorrect, please double check for it.", $guessed_php); ?>
                <br/><br/>
                <b>
                    <?php echo __("Note: we recommand to install under the web user to maintain file & folders permissions, but if this is not possible at all you can install it under the root user."); ?>
                </b>
            </span>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default"
                    ng-click="show_cron_modal = !show_cron_modal;"><?php echo __("Close"); ?></button>
        </div>
    </div>
</div>

<style type="text/css">
    a.btn-xs,
    a.btn-xs:hover {
        text-decoration: none !important;
    }

    div.async-loader {
        width: 100%;
        text-align: center;
        padding: 15px 0;
    }
</style>
