<table>
    <tr style="margin:auto; padding: 0 15px; color:#888888; font-size: 17px; line-height: 150%; width:600px">
        <td>
            <p style="font-family: Verdana; font-weight: bold; color: #404040;font-size:18px; line-height:150%;"><?php echo $this->getApplicationName(); ?></p>
            <hr style="border:0; height: 3px; background-color: #e0e0e0; width: 600px;" />
            <p style="font-family: Verdana; color: #404040;font-size:18px; line-height:150%;"><?php echo __("The requested APK/Source generation failed !"); ?></p>
        </td>
    </tr>
</table>