<div class="has_header" sb-background-image value-id="value_id" ng-class="{background_image: style_background_image}" ng-style="style_background_image">

    <div class="mcommerce cart">
        <div id="mcommerce_purchase_success_content" class="relative" rel="mcommerce_purchase_confirm">
            <div class="scroll" class="relative">
                <div class="padding">
                    <p><?php echo $this->_('We thank you for your order. A confirmation email has been sent'); ?></p>
                </div>
            </div>
        </div>
    </div>
</div>