<?php
$level1 = $this->getCurrentMenu();
$level2 = $this->getCurrentSubmenu();

$publication_type = System_Model_Config::getValueFor("system_publication_access_type");
$publish_type = $this->getAdmin()->getPublicationAccessType() ?
    $this->getAdmin()->getPublicationAccessType() : $publication_type;

$has_previewer = Installer_Model_Installer::hasModule("previewer");
$previewer = null;
if ($has_previewer && method_exists("Previewer_Model_Previewer", "getInstance")) {
    $previewer = Previewer_Model_Previewer::getInstance();
}

/**
 * @var Application_Model_Application $application
 */
$application = $this->getApplication();

$expiredSubscriptions = (new Subscription_Model_Subscription_Application())
    ->findAll([
        'is_subscription_deleted = ?' => 1,
        'app_id = ?' => $application->getId(),
    ],
    [
        'updated_at DESC',
    ]);

?>
    <div class="menu_steps">
        <ul>
            <?php if ($this->_canAccess("editor_design")) : ?>
                <div id="step_1"
                     class="step_menu_feature first<?php if ($level1 == 'design') : ?> f-bold active<?php endif; ?> color-red-hover step-background sb-tour">
                    <a href="<?php echo $this->getUrl('application/customization_design_style/edit'); ?>">
                        <li data-image="335"
                            data-style="editor_menu"
                            data-color="background_color<?php if ($level1 == 'design') : ?>_on_active<?php endif; ?>">
                            <?php echo __('Design'); ?>
                        </li>
                    </a>
                    <i class="fa fa-angle-right"></i>
                </div>
            <?php endif; ?>

            <?php if ($this->_canAccess("editor_colors")) : ?>
                <div id="step_2"
                     class="step_menu_feature <?php if ($level1 == 'colors') : ?>f-bold active<?php endif; ?> color-yellow-hover step-background sb-tour">
                    <a href="<?php echo $this->getUrl('application/customization_design_colors/edit'); ?>">
                        <li data-image="337"
                            data-style="editor_menu"
                            data-color="background_color<?php if ($level1 == 'colors') : ?>_on_active<?php endif; ?>">
                            <?php echo __('Colors'); ?>
                        </li>
                    </a>
                    <i class="fa fa-angle-right"></i>
                </div>
            <?php endif; ?>

            <?php if ($this->_canAccess("editor_features")) : ?>
                <div id="step_3"
                     class="step_menu_feature <?php if ($level1 == 'features') : ?>f-bold active<?php endif; ?> color-blue-hover step-background sb-tour">
                    <a href="<?php echo $this->getUrl('application/customization_features/list'); ?>">
                        <li data-image="337"
                            data-style="editor_menu"
                            data-color="background_color<?php if ($level1 == 'features') : ?>_on_active<?php endif; ?>">
                            <?php echo __('Features'); ?>
                        </li>
                    </a>
                    <i class="fa fa-angle-right"></i>
                </div>
            <?php endif; ?>

            <?php if ($this->_canAccess("editor_application")) : ?>
                <div id="step_4"
                     class="step_menu_feature <?php if ($level1 == 'publication_app') : ?>f-bold active <?php endif; ?>wl_panel color-purple-hover step-background sb-tour">
                    <a href="<?php echo $this->getUrl('application/customization_publication_app'); ?>">
                        <li>
                            <?php echo __('Application'); ?>
                        </li>
                    </a>
                    <i class="fa fa-angle-right"></i>
                </div>
            <?php endif; ?>

            <?php if ($this->_canAccess("editor_publication")) : ?>
                <div id="step_5"
                     class="step_menu_feature <?php if ($level1 == 'publication_infos') : ?>f-bold active <?php endif; ?>wl_panel color-green-hover step-background sb-tour">
                    <a href="<?php echo $this->getUrl('application/customization_publication_infos'); ?>">
                        <li>
                            <?php echo __('Publication'); ?>
                        </li>
                    </a>
                </div>
            <?php endif; ?>

        </ul>
    </div>

<?php if ($this->_canAccess('editor_publication') &&
    $level1 == 'publication_infos' &&
    $application->canBePublished()) : ?>

    <div class="container-fluid">
        <div id="sb-tour-section-general-source"
             class="content sb-tour">
            <h3 class="title-editor border-green text-center">
                <?php echo __('Subscription'); ?>
            </h3>
            <div class="form-horizontal container-fluid subcontent content-color">
                <?php if (!$application->subscriptionIsActive()): ?>
                    <div class="form-group">
                        <div class="col-md-12">
                            <div id="sb-tour-ready-publish"
                                 class="container-fluid subcontent sb-tour text-center">
                                <a class="btn color-red"
                                   href="<?php echo $this->getUrl('application/customization/check'); ?>"
                                   onclick="reload(this, this.href, true); return false;"><?php echo __('Ready ? Publish my app!'); ?></a>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>

                <?php if ($application->subscriptionIsActive()): ?>

                    <?php
                        $subscriptionApp = $application->getSubscription();
                        $subscription = $subscriptionApp->getSubscription();
                    ?>


                    <div class="form-group">
                        <div class="col-md-12">
                            <table class="table table-striped">
                                <tbody>
                                    <tr>
                                        <th style="width: 33%;"><?php echo __('Name') ?></th>
                                        <td><?php echo $subscription->getName() ?></td>
                                    </tr>
                                    <tr>
                                        <th><?php echo __('Description') ?></th>
                                        <td><?php echo $subscription->getDescription() ?></td>
                                    </tr>
                                    <?php if (!$subscriptionApp->isChild()): ?>
                                    <tr>
                                        <th><?php echo __('Setup fee') ?></th>
                                        <td><?php echo $subscription->getFormattedSetupFee() ?></td>
                                    </tr>
                                    <?php endif; ?>
                                    <?php if ($subscription->getPaymentFrequency() && !$subscriptionApp->isChild()): ?>
                                        <tr>
                                            <th><?php echo __($subscription->getPaymentFrequency() . ' fee') ?></th>
                                            <td><?php echo $subscription->getFormattedRegularPayment() ?></td>
                                        </tr>
                                    <?php endif; ?>
                                    <tr>
                                        <th><?php echo __('Subscription date') ?></th>
                                        <td><?php echo datetime_to_format($subscriptionApp->getCreatedAt(), Zend_Date::DATETIME_MEDIUM) ?></td>
                                    </tr>
                                    <?php if (!$subscriptionApp->isChild()): ?>
                                    <tr>
                                        <th><?php echo __('Payment method') ?></th>
                                        <td>
                                            <?php if ($subscriptionApp->getPaymentMethod() === ''): ?>
                                                <span style="text-transform: uppercase; font-weight: bold;"><?php echo __('Free plan') ?></span>
                                            <?php else: ?>
                                            <span style="text-transform: uppercase; font-weight: bold;"><?php echo $subscriptionApp->getPaymentMethod() ?></span>
                                            <?php endif; ?>
                                        </td>
                                    </tr>
                                    <?php else: ?>
                                    <tr>
                                        <th><?php echo __('Payment method') ?></th>
                                        <td>
                                            <span style="text-transform: uppercase;">
                                               <?php echo __('Linked to Subscription') ?> <b>#<?php echo $subscriptionApp->getParentId() ?></b>
                                            </span>
                                        </td>
                                    </tr>
                                    <?php endif; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            <div class="container-fluid subcontent text-right">
                                <a class="btn color-red cancel-subscription"
                                   href="javascript:void(0);">
                                    <?php echo __('Cancel current Subscription'); ?>
                                </a>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
            </div>

            <?php if ($expiredSubscriptions->count() > 0) : ?>
            <div class="form-horizontal container-fluid subcontent content-color">
                <div class="form-group">
                    <div class="col-md-12">
                        <h4 class="subtitle"><?php echo __('Previous and/or Expired subscriptions') ?></h4>
                    </div>
                    <div class="col-md-12">
                        <table class="table table-striped"
                               style="width: 100%;">
                            <thead>
                                <tr>
                                    <th><?php echo __('ID') ?></th>
                                    <th><?php echo __('Name') ?></th>
                                    <th><?php echo __('Description') ?></th>
                                    <th><?php echo __('Setup fee') ?></th>
                                    <th><?php echo __('Regular fee') ?></th>
                                    <th><?php echo __('Expired on') ?></th>
                                    <th><?php echo __('Payment method') ?></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($expiredSubscriptions as $expiredSubscription):
                                    $subscription = $subscriptionApp->getSubscription(); ?>
                                <tr>
                                    <td>#<?php echo $subscription->getId() ?></td>
                                    <td><?php echo $subscription->getName() ?></td>
                                    <td><?php echo $subscription->getDescription() ?></td>
                                    <td>
                                        <?php if (!$expiredSubscription->isChild()): ?>
                                            <?php echo $subscription->getFormattedSetupFee(); ?>
                                        <?php endif; ?>
                                    </td>
                                    <td>
                                        <?php if ($subscription->getPaymentFrequency() && !$expiredSubscription->isChild()): ?>
                                            <?php echo $subscription->getFormattedRegularPayment() ?>
                                        <?php endif; ?>
                                    </td>
                                    <td><?php echo datetime_to_format($expiredSubscription->getExpireAt(), Zend_Date::DATE_SHORT) ?></td>
                                    <td>
                                        <?php if (!$expiredSubscription->isChild()): ?>
                                        <span style="text-transform: uppercase; font-weight: bold;"><?php echo $expiredSubscription->getPaymentMethod() ?></span>
                                        <?php else: ?>
                                        <span style="text-transform: uppercase;">
                                           <?php echo __('Linked to Subscription') ?> <b>#<?php echo $expiredSubscription->getParentId() ?></b>
                                        </span>
                                        <?php endif; ?>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>

<script type="text/javascript">
    var cancelUrl = '<?php echo $this->getUrl('subscription/application/cancel'); ?>';

    $(document).ready(function () {
        $('.cancel-subscription').off('click');
        $('.cancel-subscription').on('click', function () {
            swal({
                html: true,
                title: '<?php echo __js("Cancel Subscription", "'") ?>',
                type: 'prompt',
                text: '<?php echo __js("You are about to cancel your Subscription, if this is a paid plan the subscription will be cancelled at the end of the recurring period, otherwise the subscription will be immediately cancelled and the application locked.", "'") ?>',
                showCancelButton: true,
                closeOnConfirm: false,
                closeOnCancel: true,
                confirmButtonColor: '#ff3a2e',
                confirmButtonText: '<?php echo __js("Yes, Cancel my subscription", "'") ?>',
                cancelButtonText: '<?php echo __js("No, go back!", "'") ?>',
                buttons: {
                    confirm: {
                        value: ''
                    }
                }
            }, function (value) {
                if (value === false) {
                    return;
                }

                formget(
                    'subscription/application/cancel',
                    {
                        'message': value
                    },
                    function () {
                        // Success!
                        location.reload();
                    },
                    function () {
                        // Error!
                        location.reload();
                    });

                swal.close();
                return true;
            });
        });
    });
</script>
