<?php
$level1 = $this->getCurrentMenu();
$level2 = $this->getCurrentSubmenu();

$publication_type = __get('system_publication_access_type');
$publish_type = $this->getAdmin()->getPublicationAccessType() ?
    $this->getAdmin()->getPublicationAccessType() : $publication_type;

$has_previewer = Installer_Model_Installer::hasModule("previewer");
$previewer = null;
if ($has_previewer && method_exists("Previewer_Model_Previewer", "getInstance")) {
    $previewer = Previewer_Model_Previewer::getInstance();
}

/**
 * @var Application_Model_Application $application
 */
$application = $this->getApplication();

if (Siberian_Version::is('PE')) {
    $expiredSubscriptions = (new Subscription_Model_Subscription_Application())
        ->findAll([
            'is_subscription_deleted = ?' => 1,
            'is_active = ?' => 0,
            'app_id = ?' => $application->getId(),
        ],
            [
                'subscription_app_id DESC',
            ]);
}

// Check application currency!
$warningCurrency = false;
if (empty($application->getCurrency())) {
    $warningCurrency = true;
}

$warningLocale = false;
if (empty($application->getLocale())) {
    $warningLocale = true;
}

$hasFeatures = $application->getOptions()->count() >= 1;


?>
<div class="menu_steps">
    <ul>
        <?php if ($this->_canAccess("editor_design")) : ?>
            <div id="step_1"
                 class="step_menu_feature first<?php if ($level1 == 'design') : ?> f-bold active<?php endif; ?> color-red-hover step-background sb-tour">
                <a href="<?php echo $this->getUrl('application/customization_design_style/edit'); ?>">
                    <li data-image="335"
                        data-style="editor_menu"
                        data-color="background_color<?php if ($level1 == 'design') : ?>_on_active<?php endif; ?>">
                        <?php echo __('Design'); ?>
                    </li>
                </a>
                <i class="fa fa-angle-right"></i>
            </div>
        <?php endif; ?>

        <?php if ($this->_canAccess("editor_colors")) : ?>
            <div id="step_2"
                 class="step_menu_feature <?php if ($level1 == 'colors') : ?>f-bold active<?php endif; ?> color-yellow-hover step-background sb-tour">
                <a href="<?php echo $this->getUrl('application/customization_design_colors/edit'); ?>">
                    <li data-image="337"
                        data-style="editor_menu"
                        data-color="background_color<?php if ($level1 == 'colors') : ?>_on_active<?php endif; ?>">
                        <?php echo __('Colors'); ?>
                    </li>
                </a>
                <i class="fa fa-angle-right"></i>
            </div>
        <?php endif; ?>

        <?php if ($this->_canAccess("editor_features")) : ?>
            <div id="step_3"
                 class="step_menu_feature <?php if ($level1 == 'features') : ?>f-bold active<?php endif; ?> color-blue-hover step-background sb-tour">
                <a href="<?php echo $this->getUrl('application/customization_features/list'); ?>">
                    <li data-image="337"
                        data-style="editor_menu"
                        data-color="background_color<?php if ($level1 == 'features') : ?>_on_active<?php endif; ?>">
                        <?php echo __('Features'); ?>
                    </li>
                </a>
                <i class="fa fa-angle-right"></i>
            </div>
        <?php endif; ?>

        <?php if ($this->_canAccess("editor_application")) : ?>
            <div id="step_4"
                 class="step_menu_feature <?php if ($level1 == 'publication_app') : ?>f-bold active <?php endif; ?>wl_panel color-purple-hover step-background sb-tour">
                <a href="<?php echo $this->getUrl('application/customization_publication_app'); ?>">
                    <li>
                        <?php echo __('Application'); ?>
                    </li>
                </a>
                <i class="fa fa-angle-right"></i>
            </div>
        <?php endif; ?>

        <?php if ($this->_canAccess("editor_publication")) : ?>
            <div id="step_5"
                 class="step_menu_feature <?php if ($level1 == 'publication_infos') : ?>f-bold active <?php endif; ?>wl_panel color-green-hover step-background sb-tour">
                <a href="<?php echo $this->getUrl('application/customization_publication_infos'); ?>">
                    <li>
                        <?php echo __('Publication'); ?>
                    </li>
                </a>
            </div>
        <?php endif; ?>

    </ul>
</div>

<?php if ($hasFeatures && ($warningCurrency || $warningLocale)): ?>
<div class="app-warnings">
    <?php if ($warningCurrency): ?>
        <div id="currency-warning"
             class="alert alert-warning">
            <?php echo p__("application", "Your application currency is not defined, please select one in <a href=\"%s\" class=\"bold-link\">Design > Localization settings</a>", null, "/application/customization_design_style/edit") ?>
        </div>
    <?php endif; ?>

    <?php if ($warningLocale): ?>
        <div id="locale-warning"
             class="alert alert-warning">
            <?php echo p__("application", "Your application locale is not defined, please select one in <a href=\"%s\" class=\"bold-link\">Design > Localization settings</a>", null, "/application/customization_design_style/edit") ?>
        </div>
    <?php endif; ?>
    <style type="text/css">
        a.bold-link {
            font-weight: bold;
            text-decoration: underline;
        }
    </style>
</div>
<?php endif; ?>
