<?php $product = $this->getProduct(); ?>
<?php $category = $product->getCategory(); ?>
<?php $parent = $category->getParentId() ? $category->getParent() : $category; ?>
<?php $children = $parent->getChildren(); ?>
<?php $application = $this->getApplication(); ?>
<div id="create_product" class="product">
    <h3 class="title-editor border-blue text-center">
        <?php echo $product->getId() ? $this->_('Edit the product') : $this->_('Create a new product'); ?>
    </h3>
    <form action="<?php echo $this->getUrl('catalog/application_product/editpost'); ?>" method="post" id="productForm" class="subcontent form-horizontal">
        <div class="container-fluid">
            <div class="form-group">
                <div class="col-md-12">
                    <button type="button" id="hide_form" class="btn color-blue pull-left" onclick="product.cancel();"><i class="fa fa-angle-left"></i></button>
                    <button type="submit" class="btn color-blue pull-right">OK</button>
                </div>
            </div>
            <div class="list">
                <div class="form-group">
                    <div class="col-sm-4">
                        <label for="product_name"><?php echo $this->_('Product name'); ?> :</label>
                    </div>
                    <div class="col-sm-8">
                        <input class="name required input-flat" type="text" id="product_name" value="<?php echo $product->getName(); ?>" name="name" placeholder="<?php echo $this->_("Product name"); ?>" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-4">
                        <label for="product_description"><?php echo $this->_('Description'); ?> :</label>
                    </div>
                    <div class="col-sm-8">
                        <textarea id="product_description" name="description" rel="description" class="contact_field input-flat description_field">
                            <?php echo $product->getDescription(); ?>
                        </textarea>
                    </div>
                </div>
                <?php if($product->getData('type') != 'format') : ?>
                <div class="form-group">
                    <div class="col-sm-4">
                        <label for="product_price"><?php echo $this->_('Price'); ?> :</label>
                    </div>
                    <div class="col-sm-8">
                        <input class="input-flat price number" type="text" id="product_price" value="<?php echo $product->getPrice(); ?>" name="price" placeholder="<?php echo __("Price"); ?>" />
                    </div>
                </div>
                <?php endif; ?>
                <?php if($children && $children->count() > 0) : ?>
                <div class="form-group">
                    <div class="col-sm-4">
                        <label for="subcategory_id"><?php echo $this->_('Category'); ?> :</label>
                    </div>
                    <div class="col-sm-8">
                        <select id="subcategory_id" name="subcategory_id" class="styled-select color-blue required">
                            <option value="<?php echo $parent->getId(); ?>"><?php echo $this->_('All'); ?></option>
                            <?php foreach($children as $child) : ?>
                            <option value="<?php echo $child->getId(); ?>"<?php if($product->getCategory()->getId() == $child->getId()) : ?> selected="selected"<?php endif; ?>><?php echo $child->getName(); ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                </div>
                <?php endif; ?>
                <div class="form-group">
                    <div class="col-sm-4">
                        <label><?php echo $this->_('Picture');?> : </label>
                    </div>
                    <div class="col-sm-8">
                    <!--[if gte IE 10]><!-->
                        <button class="upload_picture btn color-blue add" type="button">
                            <?php echo $product->getPicture() ? $this->_("Edit the") : $this->_('Add a'); ?>
                            <?php echo $this->_('picture'); ?>
                        </button>
                        <!--<![endif]-->
                        <input style="display:none" class="uploader_picture" type="file" name="files[]" data-url="<?php echo $this->getUrl('template/crop/upload'); ?>">
                    </div>
                </div>
            </div>
        </div>
        <?php if(!$product->getId() OR $product->getData('type') == 'format') : ?>
        <div class="product_formats container-fluid">
            <h3 class="title-editor title-feature-indent">
                <?php echo $this->_('Product formats'); ?>
                <?php if(!$product->getId()) : ?>
                    <input class='sb-tgl sb-tgl-flat color-blue' id='is_multiple' name='is_multiple' type='checkbox' <?php if($product->getData('type') == 'format') echo 'checked="checked"'; ?> onclick="product.toggleFormats();">
                    <label class='format-chk-tgl sb-tgl-btn color-blue' for='is_multiple' ></label>
                <?php endif; ?>
            </h3>
            <div id="list_format" class="container-fluid content-feature" <?php if($product->getData('type') != 'format') : ?> style="display:none;"<?php endif; ?>>
                <table class="table">
                    <col width="12%" />
                    <col width="38%" />
                    <col width="38%" />
                    <col width="12%" />
                    <thead>
                        <tr>
                            <th></th>
                            <th><label><?php echo $this->_('Format'); ?></label></th>
                            <th><label><?php echo $this->_('Price'); ?></label></th>
                            <th></th>
                        </tr>
                    </thead>
                    <?php $i = 0; ?>
                    <?php if($product->getId()) : ?>
                    <?php foreach($product->getType()->getOptions() as $i => $option) : ?>
                    <tr id="row_format_<?php echo $option->getId() ?>" class="format" rel="<?php echo $option->getId() ?>">
                        <td><?php echo $i + 1 ?><?php echo $i == 0 ? $this->_('st') : $this->_('nd') ?></td>
                        <td><input id="product_format_title_<?php echo $option->getId() ?>" class="format input-flat required" type="text" value="<?php echo $option->getTitle() ?>" placeholder="<?php echo __("Format"); ?>" name="option[<?php echo $option->getId() ?>][title]" rel="<?php echo $option->getId() ?>" /></td>
                        <td>
                            <input id="product_format_price_<?php echo $option->getId() ?>" class="input-flat price required number" type="text" placeholder="<?php echo __("Price"); ?>" value="<?php echo $option->getPrice() ?>" name="option[<?php echo $option->getId() ?>][price]" rel="<?php echo $option->getId() ?>"/>
                            <input id="product_format_option_id_<?php echo $option->getId() ?>" type="hidden" name="option[<?php echo $option->getId() ?>][option_id]" value="<?php echo $option->getId() ?>" rel="<?php echo $option->getId() ?>"/>
                            <input id="product_format_is_deleted_<?php echo $option->getId() ?>" type="hidden" name="option[<?php echo $option->getId() ?>][is_deleted]" rel="<?php echo $option->getId() ?>"/>
                        </td>
                        <td><?php if($i > 1) : ?><button type="button" id="delete_format_<?php echo $option->getId() ?>" rel="<?php echo $i; ?>" class="btn color-blue delete_format" title="Supprimer" onclick="product.deleteFormat('<?php echo $option->getId() ?>')"><i class="fa fa-times"></i></button><?php endif; ?></td>
                    </tr>
                    <?php endforeach; $i++; ?>
                    <?php endif; ?>
                    <?php while($i < 4) : ?>
                    <tr id="row_format_new_<?php echo $i ?>" class="format new_format"<?php if($i > 1) : ?> style="display:none;"<?php endif; ?> rel="new_<?php echo $i ?>">
                        <td><?php echo $i + 1 ?><?php echo $i == 0 ? $this->_('st') : $this->_('nd') ?></td>
                        <td><input id="product_format_title_new_<?php echo $i ?>" class="format required input-flat" type="text" value="" placeholder="<?php echo __("Format"); ?>" name="option[new_<?php echo $i ?>][title]" rel="new_<?php echo $i ?>" /></td>
                        <td>
                            <input id="product_format_price_new_<?php echo $i ?>" class="input-flat price required number" type="text" placeholder="<?php echo __("Price"); ?>" value="" name="option[new_<?php echo $i ?>][price]" rel="new_<?php echo $i ?>"/>
                            <input id="product_format_option_id_new_<?php echo $i ?>" type="hidden" name="option[new_<?php echo $i ?>][option_id]" rel="new_<?php echo $i ?>"/>
                            <input id="product_format_is_deleted_new_<?php echo $i ?>" type="hidden" value="<?php if($i > 1) : ?>1<?php endif; ?>" name="option[new_<?php echo $i ?>][is_deleted]" rel="new_<?php echo $i ?>"/>
                        </td>
                        <td><?php if($i > 1) : ?><button type="button" id="delete_format_new_<?php echo $i ?>" rel="new_<?php echo $i; ?>" class="btn color-blue delete_format" title="Supprimer" onclick="product.deleteFormat('new_<?php echo $i ?>')"><i class="fa fa-times"></i></button><?php endif; ?></td>
                    </tr>
                    <?php $i++; ?>
                    <?php endwhile; ?>
                </table>
                <button type="button" id="add_format" class="btn color-blue add" onclick="product.addFormat()"><?php echo $this->_('Add a format'); ?></button>
            </div>
        </div>
        <?php endif; ?>
        <input type="hidden" id="product_id" name="product_id" value="<?php echo $product->getId(); ?>" />
        <input type="hidden" id="category_id" name="category_id" value="<?php echo $parent->getId(); ?>" />
        <input type="hidden" id="value_id" name="value_id" value="<?php echo $this->getOptionValue()->getId(); ?>" />
        <input type="hidden" id="picture" name="picture" value="<?php echo $product->getPicture(); ?>" />
    </form>
    <form action="<?php echo $this->getUrl('catalog/application_product/validatecrop'); ?>" method="post" id="validateCrop" class="form-horizontal">
        <div class="container-fluid list subcontent">
            <div class="col-sm-3 col-xs-3" id="cont_delete_picture" >
                <?php if($product->getPicture()) : ?>
                <button type="button" onclick="product.removepicture();" id="delete_picture" class="btn color-blue"><i class="fa fa-times"></i></button>
                <?php endif; ?>
            </div>
            <div id="product_picture" class="col-sm-4 col-xs-4">
                <?php if($product->getPicture()) : ?>
                    <img src="<?php echo Application_Model_Application::getImagePath().$product->getPicture(); ?>" width="150" />
                <?php endif; ?>
            </div>
            <input type="hidden" id="file" name="file"/>
            <input type="hidden" id="x1" name="x1" />
            <input type="hidden" id="y1" name="y1" />
            <input type="hidden" id="x2" name="x2" />
            <input type="hidden" id="y2" name="y2" />
            <input type="hidden" id="w" name="w" />
            <input type="hidden" id="h" name="h" />
            <input type="hidden" id="source_width" name="source_width" value="" />
            <input type="hidden" id="source_height" name="source_height" value="" />
            <input type="hidden" id="output_width" name="output_width" value="300" />
            <input type="hidden" id="output_height" name="output_height" value="300" />
            <input type="hidden" id="crop_width" name="crop_width" value="" />
            <input type="hidden" id="crop_height" name="crop_height" value="" />
        </div>
    </form>
    <style>
        .pp_content div .product_formats .title span.right {
            width: 100px;
        }
        .pp_content div .product_formats .title span.right label {
            font-size: 20px;
        }
        .pp_content div .product_formats table tr td input {
            width: 145px;
        }
        .format-chk-tgl{
            height: 30px !important;
            width: 75px !important;
            float: right;
            position: relative !important;
            top: -5px;
            right: 5px;
        }
    </style>
</div>
