<?php

use Form2\Model\Field;
use Form2\Model\Result;
use Form2\Form\Settings as FormSettings;
use Form2\Form\Field as FormField;
use Form2\Form\Field\Delete as DeleteFormField;
use Siberian\Json;

$application = $this->getApplication();
$optionValue = $this->getOptionValue();
$valueId = $optionValue->getId();
$request = $this->getRequest();

$formField = (new FormField())
    ->setValueId($valueId);

$fields = (new Field())->findAll(
    [
        'value_id = ?' => $valueId
    ],
    [
        'position ASC'
    ]
);

$deleteFieldForm = (new DeleteFormField())
    ->setValueId($valueId);

$formSettings = (new FormSettings())
    ->setValueId($valueId);

try {
    $settings = Json::decode($optionValue->getSettings());
    $formSettings->populate($settings);
} catch (\Exception $e) {
    // Whoops!
}

$results = (new Result())->findAll(
    [
        'value_id = ?' => $valueId
    ],
    'created_at DESC'
);

?>

<div id="form-fields">

    <!-- Nav tabs -->
    <ul class="nav nav-tabs"
        role="tablist">

        <li role="presentation"
            class="<?php echo ($fields->count() > 0) ? 'active' : '' ?>">
            <a href="#tab-fields"
               aria-controls="tab-fields"
               role="tab"
               data-toggle="tab">
                <i class="fa fa-map-marker"></i>
                <?php echo p__('form2', 'Fields') ?>
            </a>
        </li>

        <li role="presentation"
            class="<?php echo ($fields->count() <= 0) ? 'active' : '' ?>">
            <a href="#tab-settings"
               aria-controls="tab-settings"
               role="tab"
               data-toggle="tab">
                <i class="fa fa-cogs"></i>
                <?php echo p__('form2', 'Settings') ?>
            </a>
        </li>

        <li role="presentation">
            <a href="#tab-results"
               aria-controls="tab-results"
               role="tab"
               data-toggle="tab">
                <i class="fa fa-search"></i>
                <?php echo p__('form2', 'Results') ?>
            </a>
        </li>

        <li role="presentation">
            <a href="#tab-design"
               aria-controls="tab-design"
               role="tab"
               data-toggle="tab">
                <i class="fa fa-image"></i>
                <?php echo p__('form2', 'Design') ?>
            </a>
        </li>

    </ul>

    <div class="tab-content">

        <!-- FIELDS -->
        <div role="tabpanel"
             class="tab-pane <?php echo ($fields->count() > 0) ? 'active' : '' ?>"
             id="tab-fields">

            <div class="feature-block-add">
                <h3 class="title-editor no-border-radius title-feature-indent">
                    <?php echo p__('form2', 'Add a section, field or spacer'); ?>
                </h3>

                <div class="container-fluid first-row-feature content-feature feature-manage-items">
                    <?php echo $formField; ?>
                </div>
            </div>

            <div class="subcontent content-color">
            <?php if ($fields->count() > 0): ?>
                <div>
                    <h3 class="title-editor no-border-radius title-feature-indent">
                        <?php echo p__('form2', 'Manage fields') ?>
                    </h3>
                    <div class="container-fluid first-row-feature content-feature feature-manage-items">
                        <table class="table content-white-bkg sb-pager table-fields">
                            <thead>
                                <tr class="border-grey">
                                    <th style="width:32px;"></th>
                                    <th style="width:30%"><?php echo p__('form2', 'Label') ?></th>
                                    <th style="width:30%"><?php echo p__('form2', 'Type') ?></th>
                                    <th style="width:30%"><?php echo p__('form2', 'Default') ?></th>
                                    <th style="width:5%"><?php echo p__('form2', 'Required') ?></th>
                                    <th style="width:5%;"><?php echo p__('form2', 'Position') ?></th>
                                    <th></th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody class="fields-sortable">
                            <?php foreach ($fields as $field) : ?>
                                <tr id="field_manage_element_<?php echo $field->getId(); ?>"
                                    rel="<?php echo $field->getId(); ?>"
                                    class="field-manage-element sb-pager field-container">
                                    <td class="field-handle"
                                        style="text-align: center;">
                                        <i class="fa fa-sort"
                                           style="margin-top: 11px;"></i>
                                    </td>
                                    <td>
                                        <h5 style="font-weight: bold;"><?php echo $field->getLabel() ?></h5>
                                    </td>
                                    <td>
                                        <?php echo p__('form2', FormField::$_types[$field->getFieldType()]) ?>
                                    </td>
                                    <td><?php echo $field->getDefaultValue() ?></td>
                                    <td>
                                        <?php if ($field->getIsRequired()): ?>
                                            <p class="label label-success"><?php echo p__('form2', 'YES') ?></p>
                                        <?php else: ?>
                                            <p class="label label-danger"><?php echo p__('form2', 'NO') ?></p>
                                        <?php endif; ?>
                                    </td>
                                    <td class="field-position"><?php echo $field->getPosition() ?></td>
                                    <td class="edit-action open-edit"
                                        data-id="field_<?php echo $field->getId(); ?>"
                                        data-form-url="<?php echo __path('/form2/field/load-form', [
                                            'field_id' => $field->getId(),
                                            'value_id' => $valueId
                                        ]); ?>">
                                        <i class="fa fa-pencil"></i>
                                    </td>
                                    <td class="delete-action">
                                        <?php
                                        $deleteFieldForm->setAttrib('data-rowid', 'field_manage_element_' . $field->getId());
                                        $deleteFieldForm->getElement('field_id')->setValue($field->getId());

                                        echo $deleteFieldForm;
                                        ?>
                                    </td>
                                </tr>
                                <tr class="edit-form"
                                    data-id="field_<?php echo $field->getId(); ?>"
                                    style="display: none;">
                                    <td colspan="8">
                                        <p class="close-edit"
                                           data-id="field_<?php echo $field->getId(); ?>">
                                            <i class="fa fa-times"></i><?php echo p__('form2', 'Close') ?>
                                        </p>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            <?php endif; ?>
            </div>

        </div>
        <!-- FIELDS -->

        <!-- SETTINGS -->
        <div role="tabpanel"
             class="tab-pane <?php echo ($fields->count() <= 0) ? 'active' : '' ?>"
             id="tab-settings">
            <div class="feature-block-add">
                <h3 class="title-editor no-border-radius title-feature-indent">
                    <?php echo p__('form2', 'Settings'); ?>
                </h3>

                <div class="container-fluid first-row-feature content-feature feature-manage-items">
                    <?php echo $formSettings; ?>
                </div>
            </div>
        </div>
        <!-- SETTINGS -->

        <!-- START RESULTS TAB -->
        <div role="tabpanel"
             class="tab-pane"
             id="tab-results">

            <div class="feature-block-add">
                <h3 class="title-editor no-border-radius title-feature-indent">
                    <?php echo p__('form2', 'Results') ?>
                </h3>
                <div class="container-fluid first-row-feature content-feature">
                    <table class="table content-white-bkg sb-pager margin-top table-results">
                        <thead>
                            <tr class="border-grey">
                                <th class="sortable numeric"
                                    style="width: 60px;"><?php echo p__('form2', 'ID'); ?></th>
                                <th class="sortable"
                                    style="width: 120px;"><?php echo p__('form2', 'Customer'); ?></th>
                                <th style="width: 70%;"><?php echo p__('form2', 'Result'); ?></th>
                                <th class="sortable date text-right"
                                    style="width: 120px;"><?php echo p__('form2', 'Date'); ?></th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($results as $result): ?>
                            <tr class="sb-pager">
                                <td>
                                    <b>#<?php echo $result->getId(); ?></b>
                                </td>
                                <td>
                                    <?php if (!empty($result->getCustomerId())): ?>
                                        <a class="btn btn-xs btn-info"
                                           href="<?php echo __path('/customer/application/edit/', [
                                               'customer_id' => $result->getCustomerId()
                                           ]); ?>">
                                            #<?php echo $result->getCustomerId(); ?>
                                        </a>
                                    <?php else: ?>
                                        <span class="btn btn-xs btn-warning">
                                            <?php echo p__('form2', 'anonymous'); ?>
                                        </span>
                                    <?php endif; ?>
                                </td>
                                <td>
                                    <button class="toggler btn btn-xs btn-info"
                                            style="float: right;"
                                            rel="toggle-table-<?php echo $result->getId(); ?>"><?php echo p__('form2', 'MORE') ?></button>
                                    <table class="sub-table toggle-table toggle-table-<?php echo $result->getId(); ?>">
                                        <?php
                                        $payload = $result->getPayload();
                                        foreach ($payload as $index => $field) {
                                            if (is_array($field['value'])) {
                                                $flatArray = array_flat($field['value']);
                                                $v = implode_polyfill('<br />', $flatArray);
                                            } else {
                                                $v = $field['value'];
                                            }
                                            $v = purify($v);
                                            if ($field['type'] === 'textarea') {
                                                $v = nl2br($v);
                                            }

                                            echo "
                                            <tr>
                                                <th>{$field['label']}</th>
                                                <td>{$v}</td>
                                            </tr>";
                                        }
                                        ?>
                                    </table>
                                </td>
                                <td class="text-right">
                                    <?php echo datetime_to_format($result->getCreatedAt(), Zend_Date::DATETIME_SHORT) ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="4">
                                    <?php echo p__('form2', 'No results.') ?>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>

            <br />

            <div class="feature-block-add">
                <h3 class="title-editor no-border-radius title-feature-indent">
                    <?php echo p__('form2', 'Export') ?>
                </h3>
                <div class="container-fluid first-row-feature content-feature">
                    <div>
                        <label for="excludeAnonymous"
                               style="margin-right: 15px;">
                            <input id="excludeAnonymous"
                                   type="checkbox"
                                   class="color-blue checkbox-inline" />
                            <?php echo p__('form2', 'Exclude anonymous results') ?>
                        </label>
                        <br />
                        <label for="lastUserRecord"
                               style="margin-right: 15px;">
                            <input id="lastUserRecord"
                                   type="checkbox"
                                   class="color-blue checkbox-inline" />
                            <?php echo p__('form2', 'Keep only last entry for identified customer') ?>
                        </label>
                        <br />
                        <button class="export-csv btn color-blue pull-right"><?php echo p__('form2', 'Export CSV') ?></button>
                        <input id="exportValueId"
                               type="hidden"
                               value="<?php echo $valueId; ?>" />
                    </div>
                </div>
            </div>
        </div>
        <!-- END RESULTS TAB -->

        <!-- DESIGN -->
        <div role="tabpanel"
             class="tab-pane"
             id="tab-design">
            <?php echo $this->importBackground($optionValue, false, false); ?>
        </div>
        <!-- DESIGN -->
</div>



<script type="text/javascript">
    ckeditor_config.form = {
        language: ckeditor_language,
        toolbar: [
            {
                name: 'basicstyles',
                groups: ['basicstyles', 'cleanup'],
                items: ['Bold', 'Italic', 'Underline', 'Strike', '-', 'RemoveFormat']
            },
            {
                name: 'paragraph',
                groups: ['indent', 'align'],
                items: ['Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']
            },
            { name: 'styles', items: ['TextColor', 'Format', 'FontSize'] },
        ],
        on: {
            change: function (event) {
                // Auto-update attached textarea;
                $('textarea#' + this.name).text(this.getData());
            }
        },
        extraAllowedContent: 'a[*];img[*];div[*];span[*];b[*];i[*];s[*];p[*]'
    };

    var optionAction = `
<div class="select_actions form-group sb-form-line">
    <div class="col-sm-10">
        <button class="add_option btn btn-sm color-blue">
            <i class="icon ion-plus"></i>
            <?php echo p__('form2', 'Add an option') ?>
        </button>
    </div>
    <div class="sb-cb"></div>
</div>`;
    var selectTemplate = `<?php echo FormField::getSelectTemplate() ?>`;

    $(document).ready(function () {
        bindForms('#form-fields');

        window.reloadOverviewFormv2 = function () {
            try {
                iframe.f.overview['form_v2']();
            } catch(e) {
                //
            }
        };

        $("table.sb-pager.table-fields").sbpager({
            with_search: true,
            items_per_page: 1000,
            search_placeholder: "<?php echo p__('form2', 'Search ...') ?>",
            callback_goto_page: function() {
                $("table.sb-pager tr.edit-form[data-id]").hide()
            }
        });

        // Sections
        $('.fields-sortable').sortable({
            handle: '.field-handle',
            axis: 'y',
            items: ' .field-container',
            opacity: 0.85,
            start: function() {
                // Clear all forms inside elements!
                $('#fields .close-edit').trigger('click');
            },
            stop: function() {
                let sections = $('.fields-sortable tr[rel]');
                let data = {
                    indexes: []
                };
                let index = 1;
                sections.each(function() {
                    let el = $(this);
                    data.indexes.push(el.attr('rel'));

                    el.find('.field-position').text(index++);
                });

                formget(
                    '/form2/field/update-positions',
                    data,
                    function(result) {
                        window.reloadOverviewFormv2();
                    },
                    function(result) {}
                );
            }
        });

        window.toggleGroups = function (formId, type) {
            $("#" + formId + " dd[id^='group_']").hide();

            switch (type) {
                case 'select':
                case 'radio':
                    $('#' + formId + ' #group_select-element').show();
                    break;
                case 'number':
                    $('#' + formId + ' #group_number-element').show();
                    break;
                case 'image':
                    $('#' + formId + ' #group_image-element').show();
                    break;
                case 'illustration':
                    $('#' + formId + ' #group_illustration-element').show();
                    break;
                case 'clickwrap':
                    $('#' + formId + ' #group_clickwrap-element').show();
                    break;
                case 'richtext':
                    $('#' + formId + ' #group_richtext-element').show();
                    break;
                case 'date':
                    $('#' + formId + ' #group_date-element').show();
                    break;
                case 'datetime':
                    $('#' + formId + ' #group_datetime-element').show();
                    break;
                default:
            }

            $("#" + formId + " [name='is_required']").parents(".sb-form-line").hide();
            $("#" + formId + " [name='default_value']").parents(".sb-form-line").show();

            switch (type) {
                case 'text':
                case 'textarea':
                case 'datetime':
                case 'date':
                case 'clickwrap':
                case 'number':
                case 'password':
                case 'select':
                    $("#" + formId + " [name='is_required']").parents(".sb-form-line").show();
                    break;
                default:
            }

            switch (type) {
                case 'clickwrap':
                case 'password':
                case 'divider':
                case 'spacer':
                case 'datetime':
                case 'date':
                case 'geolocation':
                case 'illustration':
                case 'image':
                case 'richtext':
                    $("#" + formId + " [name='default_value']").parents(".sb-form-line").hide();
                    break;
                default:
            }
        };

        window.toggleClickwrap = function (formId, type) {
            if (type === 'privacy-policy') {
                $("#" + formId + " [name='clickwrap_richtext']").parents('.sb-form-line').hide();
            } else {
                $("#" + formId + " [name='clickwrap_richtext']").parents('.sb-form-line').show();
            }
        };

        window.toggleGroups('form-edit-field', 'divider');
        window.toggleClickwrap('form-edit-field', 'privacy-policy');

        window.binderFormField = function (formId) {
            let typeFields = $("#" + formId + " [name='field_type']");

            typeFields.off('change');
            typeFields.on('change', function () {
                let type = $(this).val();

                window.toggleGroups(formId, type);
            });

            let clickwrap = $("#" + formId + " [name='clickwrap']");

            clickwrap.off('change');
            clickwrap.on('change', function () {
                let type = $(this).val();

                window.toggleClickwrap(formId, type);
            });
        };

        window.binderFormField("form-edit-field");

        window.reIndex = function (formId) {
            var options = $("#" + formId + " .select_option_index");
            options.each(function (index) {
                var _index = index + 1;
                var el = $(this);
                el.attr("rel", _index);
                var fields = el.find("[name^=select_options]");
                $(fields.get(0)).attr("name", "select_options[" + _index + "][label]");
                $(fields.get(1)).attr("name", "select_options[" + _index + "][value]");
                el.find("button.remove_option").attr("rel", _index);
                el.find("span.option_index").text(_index);
            });
        };

        window.bindSelectSortable = function (formId) {
            // Sections
            $('#' + formId + ' #fieldset-group_select').sortable({
                handle: '.select-handle',
                axis: 'y',
                items: '.select-container',
                opacity: 0.85,
                stop: function() {
                    window.reIndex(formId);
                }
            });
        };

        window.bindRemove = function () {
            var removeOptionButtons = $('.remove_option');

            removeOptionButtons.off('click');
            removeOptionButtons.on('click', function (e) {
                var elButton = $(this);
                var formId = elButton.parents('form').attr('id');
                e.preventDefault();
                var button = $(this);
                window.removeOption(formId, button.attr('rel'));
            });
        };

        window.removeOption = function (formId, index) {
            var klass = "#" + formId + " .select_option_index[rel='" + index + "']";
            var el = $(klass);
            el.remove();
            window.reIndex(formId);
        };

        window.addOption = function (formId, index, value, label) {
            var _index = index === undefined ?
                $("#" + formId + " .select_option_index").length + 1 : index;
            var _value = value === undefined ? "" : value;
            var _label = label === undefined ? "" : label;

            var newOption = selectTemplate
                .replace(/#INDEX#/g, _index)
                .replace(/#VALUE#/g, _value)
                .replace(/#LABEL#/g, _label);

            $("#" + formId + " .select_actions").before(newOption);

            window.reIndex(formId);
            window.bindRemove();
        };

        window.bindAddOption = function (formId) {
            var buttonAddOption = $("#" + formId + " .add_option");
            buttonAddOption.off("click");
            buttonAddOption.on("click", function (e) {
                e.preventDefault();
                window.addOption(formId);
            });
        };

        window.initSelect = function (formId) {
            $("#" + formId + " #fieldset-group_select").append(optionAction);
            window.bindSelectSortable(formId);
        };

        window.initSelect("form-edit-field");

        window.addOption("form-edit-field");
        window.addOption("form-edit-field");
        window.addOption("form-edit-field");
        window.reIndex("form-edit-field");
        window.bindAddOption("form-edit-field");

        window.bindRemove();


        let searchPlaceholder = '<?php echo p__js('form2', 'Search, filter ...', "'") ?>';
        $('table.sb-pager.table-results').sbpager({
            with_search: true,
            search_placeholder: searchPlaceholder
        });

        let togglerMore = '<?php echo p__js('form2', 'MORE', "'") ?>';
        let togglerLess = '<?php echo p__js('form2', 'LESS', "'") ?>';
        let inputEmail = $('input#email');
        let recipientWarning = $('.recipient-warning');

        // Toggle mail warning
        function toggleWarning () {
            if (inputEmail.val() === '') {
                recipientWarning.show();
            } else {
                recipientWarning.hide();
            }
        }

        inputEmail.off('change');
        inputEmail.on('change', function () {
            toggleWarning();
        });
        toggleWarning();

        /**
         * Easy
         * @param klass
         */
        function toggleTable (toggler, klass) {
            let el = $("." + klass);
            if (el.hasClass("toggle-table")) {
                toggler.removeClass("btn-info");
                toggler.addClass("btn-warning");
                toggler.text(togglerLess);
                el.removeClass("toggle-table");
            } else {
                toggler.removeClass("btn-warning");
                toggler.addClass("btn-info");
                toggler.text(togglerMore);
                el.addClass("toggle-table");
            }
        }

        let togglers = $('.toggler');
        togglers.off('click');
        togglers.on('click', function () {
            let toggler = $(this);
            let klass = toggler.attr('rel');
            toggleTable(toggler, klass);
        });

        let exportCsv = $('.export-csv');
        exportCsv.off('click');
        exportCsv.on('click', function () {
            let valueId = $('#exportValueId').val();
            let excludeAnonymous = $('#excludeAnonymous').is(':checked');
            let lastUserRecord = $('#lastUserRecord').is(':checked');

            let uri = "/form2/application/export-csv?value_id=" + valueId +
                "&excludeAnonymous=" + excludeAnonymous +
                "&lastUserRecord=" + lastUserRecord;

            window.open(uri, '_blank');
        });
    });
</script>

<style type="text/css">
    #design .change_layout_handler img {
        max-height: 210px;
    }

    button.remove_option {
        margin-top: 2px;
        font-size: 20px;
        padding: 0 9px;
        float: right;
    }

    button.add_option {
        margin-top: 2px;
        padding: 5px 9px;
        float: right;
        font-size: 14px;
    }

    label.select_option {
        text-indent: 6px;
        font-style: italic;
    }

    /** Results */
    .toggle-table {
        display: block;
        overflow: hidden;
        height: 20px;
    }

    table.table-results,
    table.table-results table {
        width: 100%;
        table-layout: fixed;
        word-break: break-word;
    }

    table.sub-table {
        table-layout: fixed;
    }

    table.sub-table tr {
        border-bottom: 1px solid #e1e1e1;
    }

    table.sub-table tr:nth-child(even) td,
    table.sub-table tr:nth-child(even) th {
        background-color: #f0f0f0;
    }

    #fieldset-group_datetime .sb-check-container label,
    #fieldset-group_date .sb-check-container label {
        display: block;
    }

    #fieldset-group_datetime .sb-check-container label span,
    #fieldset-group_date .sb-check-container label span {
        position: absolute;
        margin-left: 10px;
    }
</style>
