<sb-section title="'<?php echo addslashes($this->_("List of your languages")); ?>'" button="button">
    <br />
    <div class="form-group">
        <label for="filter"><?php echo $this->_("Search"); ?></label>
        <input type="text" id="filter" class="form-control" ng-model="filter" placeholder="<?php echo $this->_("Search"); ?>" />
    </div>
    <br />
    <table class="table">
        <col width="95%" />
        <col width="5%" />
        <thead>
            <tr>
                <th class="pointer" ng-click="order = 'id'; by = !by"><?php echo $this->_("Language"); ?></th>
                <th><?php echo $this->_("Actions"); ?></th>
            </tr>
        </thead>
        <tbody>
            <tr class="slide-left" ng-repeat="language in languages | filter:filter | orderBy:order:by">
                <td>{{ language.name }}</td>
                <td class="text-center">
                    <a href="<?php echo $this->getUrl("translation/backoffice_edit"); ?>/lang_id/{{ language.id }}"
                       class="btn btn-sm btn-primary">EDIT</a>
                </td>
            </tr>
        </tbody>
    </table>

    <style type="text/css">
        .btn-sm {
            padding: 1px 5px !important;
            font-size: 11px !important;
            line-height: 1.4 !important;
            font-weight: bold;
            border: 0 !important;

        }

        a.btn-sm,
        a.btn-sm:hover {
            text-decoration: none !important;
        }
    </style>
</sb-section>