<?php $option = $this->getCurrentOptionValue(); ?>
<?php $store = $this->getCurrentStore(); ?>

<li id="store_row_<?php echo $store->getId(); ?>" class="store list-group-item content-white-bkg" rel="<?php echo $store->getId(); ?>">
    <div class="row">
        <div class="col-md-10">
            <span id="store_name_<?php echo $store->getId() ?>"><?php echo $store->getName(); ?> - <?php echo $store->getFullAddress(', '); ?></span>
        </div>
        <div class="col-md-2 text-right" id="store_icons_<?php echo $store->getId(); ?>">
            <a href="javascript:void(0)" id="edit_store_<?php echo $store->getId(); ?>" class="edit_store" rel="<?php echo $store->getId() ?>">
                <i class="fa fa-pencil"></i>
            </a>
            <a href="javascript:void(0)" id="remove_store_<?php echo $store->getId(); ?>" class="remove_store" rel="<?php echo $store->getId() ?>">
                <i class="fa fa-remove"></i>
            </a>
            <input type="hidden" name="option_value_id" value="<?php echo $option->getId(); ?>" />
        </div>
    </div>
</li>