<sb-section title="'<?php echo addslashes($this->_("List of your users")); ?>'" button="button">
    <br />
    <div class="form-group">
        <label for="filter"><?php echo $this->_("Search"); ?></label>
        <input type="text" id="filter" class="form-control" ng-model="filter" placeholder="<?php echo $this->_("Search"); ?>" />
    </div>
    <br />
    <div sb-pager items="admins | filter:filter" ng-if="admins">
        <table class="table">
            <col width="5%" />
            <col width="34%" />
            <col width="29%" />
            <col width="25%" />
            <col width="9%" />
            <col width="8%" />
            <thead>
                <tr>
                    <th class="pointer" ng-click="order = 'id'; by = !by"><?php echo $this->_("Id"); ?></th>
                    <th class="pointer" ng-click="order = 'email'; by = !by"><?php echo $this->_("Email"); ?></th>
                    <th class="pointer" ng-click="order = 'name'; by = !by"><?php echo $this->_("Name"); ?></th>
                    <th class="pointer" ng-click="order = 'company'; by = !by"><?php echo $this->_("Company"); ?></th>
                    <th class="pointer" ng-click="order = 'created_at'; by = !by"><?php echo $this->_("Created At"); ?></th>
                    <th><?php echo $this->_("Actions"); ?></th>
                </tr>
            </thead>
            <tbody >
                <tr ng-repeat="admin in pageItems() | orderBy:order:by">
                    <td>{{ admin.id }}</td>
                    <td>{{ admin.email }}</td>
                    <td>{{ admin.name }}</td>
                    <td>{{ admin.company }}</td>
                    <td>{{ admin.created_at }}</td>
                    <td>
                        <a href="<?php echo $this->getUrl("admin/backoffice_edit"); ?>/admin_id/{{ admin.id }}" title="<?php echo $this->_("Edit"); ?>"><i class="fa fa-edit"></i></a>
                        <a href="<?php echo $this->getUrl("admin/backoffice_list/loginas"); ?>/key/{{ admin.key }}/admin_id/{{ admin.id }}" target="_blank" title="<?php echo $this->_("Log-in As"); ?>"><i class="fa fa-user"></i></a>
                        <a href="#" ng-click="deleteAdmin(admin)" title="<?php echo $this->_("Delete"); ?>"><i class="fa fa-remove"></i></a>
                    </td>
                </tr>
                <tr ng-show="!admins.length">
                    <td colspan="5" class="a-center"><?php echo $this->_("You don't have any users yet"); ?></td>
                </tr>
            </tbody>
        </table>
    </div>
</sb-section>