<?php $application = $this->getApplication(); ?>
<?php $option_value = $this->getOptionValue(); ?>
<?php $galleries = new Media_Model_Gallery_Music(); ?>
<?php $galleries = $galleries->findAll(array('value_id' => $option_value->getId()), 'position ASC'); ?>
<div class="edit_page media images">
    <div id="list" class="form_content">
        <div class="add-music">
            <h3 class="title-editor no-border-radius title-feature-indent">
                <?php echo $this->_('Add content') ?>
                <button type="button" onclick="showNewGallery(); return false;" class="btn color-blue pull-right bt-header-right" id="add_item">
                    <i class="fa fa-plus"></i>
                </button>
            </h3>
            <?php echo $this->createPartialHtml('no_item', 'core_view_default', 'application/customization/features/edit/no_item.phtml'); ?>
            <div id="new_musics_galery" style="display:none;" class="container-fluid first-row-feature content-feature">
                <?php
                    echo $this->getLayout()
                        ->addPartial('edit_form', 'Core_View_Default', 'media/application/gallery/music/edit/form.phtml')
                        ->setValueId($option_value->getId())
                        ->toHtml()
                    ;
                ?>
            </div>
        </div>
        <?php if($galleries->count() > 0) : ?>
        <div id="existing_items_section" class="manage">
            <h3 class="title-editor no-border-radius title-feature-indent">
                <?php echo $this->_('Manage content'); ?>
                <button type="button" class="toggle_design color-blue pull-right bt-header-right btn" id="toggle_existing_items">
                    <i class="fa fa-angle-down"></i>
                </button>
            </h3>
            <div id="existing_items" style="display:none;" class="container-fluid first-row-feature content-feature">
                <ul id="list_edit" class="table_row_galleries sortable list-group">
                    <?php foreach($galleries as $gallery) : ?>
                        <li class="list-group-item">
                            <i class="handle fa fa-sort fa fa-sort icon-move"></i>
                            <?php echo $gallery->getName() ?>
                            <span class="actions pull-right">
                                <i class="editCurrentGallery fa fa-pencil pointer"></i>
                                <i class="deleteCurrentGallery fa fa-remove pointer"></i>
                                <input type="hidden" name="gallery_id[]" value="<?php echo $gallery->getId() ?>" />
                                <input type="hidden" name="value_id" value="<?php echo $option_value->getId() ?>" />
                            </span>
                        </li>
                    <?php endforeach ?>
                </ul>
            </div>
        </div>
        <?php endif; ?>
         <div class="background">
             <?php echo $this->importBackground($option_value); ?>
        </div>
    </div>
    <div id="edit" class="subcontent" style="display:none">
    </div>
    <style type="text/css">
        #playlist_types li {
            width:125px;
            padding:0;
        }
        #playlist_types li:hover {
            cursor:pointer;
        }
        #playlist_types img,
        #playlist_types canvas,
        #playlist_types .edit_playlist_type i {
            padding: 10px;
            border-radius: 5px;
        }
        a.edit_playlist_type {
            display: block;
            padding: 20px;
        }
        #playlist_types .edit_playlist_type i {
            font-size:33px;
            height:50px;
            width:50px;
        }
        .table_row_galleries {
            width: 100%;
            list-style: none;
        }
        .table_row_galleries .actions {
            text-align: right;
            float:right;
        }
        .gallery_row {
            border-bottom: solid 1px;
        }
        .gallery_row td {
            margin: 0;
            padding: 2px;
        }
        .editCurrentGallery, .deleteCurrentGallery {
            cursor: pointer;
        }
        .list_edit-placeholder {
            height: 20px;
            border: dotted 1px;
        }
        #list_edit li {
            transition: none;
            border-radius: 3px;
            list-style: none;
        }
        #remove_playlist_image_img {
            cursor: pointer;
            vertical-align: top;
            position: absolute;
            top: 0;
            left: 15px;
        }
        #edit.subcontent {
            padding-top:0;
        }
    </style>
    <script type="text/javascript">

        $(document).ready(function () {
            bindForms('#list');
        });

        var music_playlist_image_uploader = new Uploader();
        var music_album_image_uploader = new Uploader();
        var music;

        page.setCallback('willappear', function() {

        });

        function showNewGallery() {
            $('#new_gallery').hide();
            $('#new_musics_galery').fadeIn(function(){
                //Fix IE
                if(!$('button#upload_music_picture').is(':visible')) {
                    $('input#uploader').show();
                }
                createFileupload();
            });
            $('#no_item').hide();
        }

        var Music = Class.extend({
            init: function() {
                this.processEvents();
            },
            processEvents: function() {
                //Tri galleries
                $('#list_edit').sortable({
                    handle : '.handle',
                    placeholder: "list_edit-placeholder",
                    axis: "y",
                    update : function (e, ui) {
                        var order = $(e.target).sortable('serialize');
                        $(e.target).sortable("refresh");
                        reload($("#list_edit"), "<?php echo $this->getUrl('media/application_gallery_music/sortgalleries', array('option_value_id' => $option_value->getId())); ?>?"+order, true, function() {
                            iframe.f.reload();
                        });
                    }
                });

                $('#list_edit li').hover(function(){
                   $(this).addClass('inner_content');
                }, function(){
                   $(this).removeClass('inner_content');
                });

                $('.editCurrentGallery').click(function(e) {
                    reload(this.parentNode, "<?php echo $this->getUrl('media/application_gallery_music/editpost'); ?>", true, function(datas) {
                        if(datas.content_html) {
                            $('#edit').html(datas.content_html);
                            feature.edit(function(){
                                $('#list').html('');
                                createFileupload();
//                                var id = $(e.target).parent().find('input[name="gallery_id[]"]').val();
//                                iframe.content.find('a[rel="playlist_'+id+'"]').trigger('click');
                            });
                        }
                    });
                });

                $('.deleteCurrentGallery').click(function(){
                    if(confirm('<?php echo addslashes($this->_("Are you sure you want to delete this playlist?")); ?>')) {
                        reload($(this.parentNode), '<?php echo $this->getUrl('media/application_gallery_music/deletegallery'); ?>', true, function(datas) {
                            if(datas.success) {
                                page.reload();
                            }
                        });
                    }
                    return false;
                });

            }
        });

        page.setCallback('didappear', function() {

            $('#toggle_existing_items').click(function () {
                $('#existing_items').stop().slideToggle(300, function () {
                    if ($(this).is(':visible')) {
                        $('#toggle_existing_items').children('i').removeClass('fa-angle-down').addClass('fa-angle-up');
                    $('#toggle_existing_items').removeClass('color-blue');
                        }
                    else {
                        $('#toggle_existing_items').children('i').removeClass('fa-angle-up').addClass('fa-angle-down');
                        $('#toggle_existing_items').addClass('color-blue');
                    }
                });
            });

            music = new Music();
        });

        page.setCallback('willdisappear', function() {
            $('#toggle_existing_items').unbind('click');
        });

        page.setCallback('willdisappear', function() {
            $('#close_panel').unbind('click');
        });

    </script>
</div>

