<?php
    $admin = $this->getAdmin();
?>
<!DOCTYPE html>
<html>
<head>
    <title><?php echo __('Personal data') ?></title>
    <style type="text/css">
        body {
            width: 600px;
            margin: 0 auto;
        }

        table {
            width: 100%;
        }

        table tr {
            border-bottom: 1px solid grey;
            height: 16px;
            font-size: 16px;
        }

        table tr th,
        table tr td {
            padding: 4px 0;
        }

        table tr th {
            font-weight: bold;
        }
    </style>
</head>
<body>
    <table>
        <tbody>
            <tr>
                <th><?php echo __('Company') ?></th>
                <td><?php echo $admin->getCompany() ?></td>
            </tr>
            <tr>
                <th><?php echo __('Email') ?></th>
                <td><?php echo $admin->getEmail() ?></td>
            </tr>
            <tr>
                <th><?php echo __('Firstname') ?></th>
                <td><?php echo $admin->getFirstname() ?></td>
            </tr>
            <tr>
                <th><?php echo __('Lastname') ?></th>
                <td><?php echo $admin->getLastname() ?></td>
            </tr>
            <tr>
                <th><?php echo __('Address') ?></th>
                <td><?php echo $admin->getAddress() ?></td>
            </tr>
            <tr>
                <th><?php echo __('Address (more)') ?></th>
                <td><?php echo $admin->getData('address2') ?></td>
            </tr>
            <tr>
                <th><?php echo __('Zip code') ?></th>
                <td><?php echo $admin->getZipCode() ?></td>
            </tr>
            <tr>
                <th><?php echo __('Country') ?></th>
                <td><?php echo $admin->getCountry() . '(' . $admin->getCountryCode() . ')' ?></td>
            </tr>
            <tr>
                <th><?php echo __('State / Province') ?></th>
                <td><?php echo $admin->getRegionCode() ?> // TODO</td>
            </tr>
            <tr>
                <th><?php echo __('Phone') ?></th>
                <td><?php echo $admin->getPhone() ?></td>
            </tr>
            <tr>
                <th><?php echo __('Password (hashed)') ?></th>
                <td><?php echo $admin->getPassword() ?></td>
            </tr>
        </tbody>
    </table>
</body>
</html>