<form ng-submit="save()"
      class="form-horizontal">
    <sb-section title="'<?php echo __title("Application settings"); ?>'">

        <div class="form-group">

            <div class="col-md-6">
                <label for="{{ configs.environment.code }}">{{ configs.environment.label }}</label>
                <select id="configs.environment.code"
                        class="form-control"
                        ng-model="configs.environment.value">
                    <option value="production"><?php echo __('Production'); ?></option>
                    <option value="development"><?php echo __('Development'); ?></option>
                </select>
            </div>

            <div class="col-md-6">
                <label for="{{ configs.update_channel.code }}">{{ configs.update_channel.label }}</label>
                <select id="configs.update_channel.code"
                        class="form-control"
                        ng-model="configs.update_channel.value">
                    <option value="production"><?php echo __('Production ready!'); ?></option>
                    <option value="stable"><?php echo __('Stable'); ?></option>
                    <option value="beta"><?php echo __('Testing / Beta'); ?></option>
                </select>
            </div>

            <div class="col-md-6">
                <br/>
                <p ng-if="configs.environment.value == 'production'"
                   class="alert alert-info">
                    <b><?php echo __('Production') ?></b>:
                    <?php echo __('The default setting to run your production server.') ?>
                </p>
                <p ng-if="configs.environment.value == 'development'"
                   class="alert alert-danger">
                    <b><?php echo __('Development') ?></b>:
                    <?php echo __('Errors are displayed on page, outputs are more verbose, this is an option for debug purpose, use with care as it may output some critical informations about your server.') ?>
                </p>
            </div>

            <div class="clear"></div>

            <div class="col-md-6">
                <label for="configs.redirect_https.code"><?php echo p__('backoffice', 'Enable software HTTPS redirection') ?></label>
                <select id="configs.redirect_https.code"
                        class="form-control"
                        ng-model="configs.redirect_https.value">
                    <option value="true"><?php echo __('Yes'); ?></option>
                    <option value="false"><?php echo __('No'); ?></option>
                </select>
            </div>

        </div>

        <div class="form-group">
            <div class="col-md-12">
                <button type="submit"
                        class="btn btn-primary right"><?php echo __('Save'); ?></button>
                <sb-loader is_visible="form_loader_is_visible"
                           type="'inner_content'"
                           size="'small'"
                           animation="'no'"
                           class="form_loader"></sb-loader>
                <div class="clear"></div>
            </div>
        </div>

        <div ng-show="configs.update_channel.value == 'preview'">

            <div class="clear">
                <br/>
                <br/>
            </div>

            <div class="form-group">

                <div class="col-md-12">
                    <p class="alert alert-danger">
                        <?php echo __("<b>Disclaimer:</b> You are using the <b>preview</b> update channel, this channel is intended for <b>tests & previews</b> of new features, if you are not sure stay with <b>stable channel</b>.") ?>
                        <br/>
                        <?php echo __("We recommned using <b>preview</b> on a testing or development server, we won't provide regular ticket support for these update channels, only bug reports via the form below.") ?>
                        <br/><br/>
                        <?php echo __("<b>Actual preview version is Siberian 5.0</b>.") ?>
                    </p>
                </div>

                <div class="col-md-12"
                     ng-show="configs.update_channel.value == 'preview' || configs.update_channel.value == 'beta'">
                    <p>
                        <b><?php echo __("Submit a bug report or improvement request for beta/preview") ?>:</b>
                    </p>

                    <ng-ckeditor name="beta-report"
                                 bind="report.message"
                                 skin="moono"
                                 remove-buttons="Button,HiddenField,ImageButton,Select,Textarea,TextField,Radio,Checkbox,Form"
                                 remove-plugins="print,iframe,flash,smiley,pagebreak,language,scayt,selectall,templates,specialchar"
                                 msn-count="<?php echo __("Number of typed characters:") ?>">
                    </ng-ckeditor>

                    <p>
                        <?php echo __("<b>Note for Bug report:</b> give us a maximum of description of how you reached the bug, and possibly screenshots.") ?>
                    </p>

                    <br/>
                    <a class="btn btn-primary right"
                       ng-click="submitReport();$event.stopPropagation();"><?php echo __("Send report"); ?></a>
                    <div class="clear"></div>
                </div>

            </div>

        </div>
    </sb-section>

    <sb-section title="'<?php echo __title("HTTPS & SSL Certificates"); ?>'">

        <div class="form-group">

            <div class="col-md-12">
                <p class="alert alert-info"
                   ng-bind-html="configs.testssl.message"></p>
            </div>

            <div class="col-md-6">
                <label for="{{ configs.letsencrypt_env.code }}">{{ configs.letsencrypt_env.label }}</label>
                <select id="configs.letsencrypt_env.code"
                        class="form-control"
                        ng-model="configs.letsencrypt_env.value">
                    <option value="staging"><?php echo __('Staging'); ?></option>
                    <option value="production"><?php echo __('Production'); ?></option>
                </select>

                <br/>
                <label ng-if="configs.certificates.length"
                       for="config_hostname"><?php echo __('Selected main hostname'); ?></label>
                <select ng-if="configs.certificates.length"
                        id="config_hostname"
                        class="form-control"
                        ng-model="configs.current_domain">
                    <option value=""><?php echo __('Select a hostname') ?></option>
                    <option ng-repeat="certificate in configs.certificates"
                            ng-value="certificate.hostname">{{ certificate.hostname }}
                    </option>
                </select>

                <label ng-if="!configs.certificates.length"
                       for="config_hostname"><?php echo __('Main hostname'); ?></label>
                <input type="text"
                       ng-if="!configs.certificates.length"
                       id="config_hostname"
                       class="form-control"
                       ng-model="configs.current_domain">

                <br/>
                <label ng-show="configs.cpanel_type.value != -1"><?php echo __('Request or renew the certificate via Let\'s Encrypt.') ?></label>
                <div ng-show="configs.cpanel_type.value != -1">
                    <a class="btn btn-primary left"
                       ng-click="generateSsl(false);"><?php echo __('Request & Upload to panel') ?></a>
                    <a ng-if="show_force"
                       class="btn btn-primary left"
                       ng-click="generateSsl(true);"><?php echo __('Force request & Upload to panel') ?></a>
                </div>

            </div>

            <div class="col-md-6">

                <label for="{{ configs.cpanel_type.code }}">{{ configs.cpanel_type.label }}</label>
                <select id="configs.cpanel_type.code"
                        class="form-control"
                        ng-model="configs.cpanel_type.value">
                    <option value="-1"><?php echo __('Select a panel type or self-managed') ?></option>
                    <option value="self"><?php echo __('Unknown - Self-managed'); ?><?php echo p__('backoffice', '(unsupported)'); ?></option>
                    <option value="plesk"><?php echo __('Plesk 12+ web API'); ?><?php echo p__('backoffice', '(deprecated)'); ?></option>
                    <option value="pleskcli"><?php echo __('Plesk exec API (beta)'); ?><?php echo p__('backoffice', '(partial support)'); ?></option>
                    <option value="cpanel"><?php echo __('WHM cPanel'); ?><?php echo p__('backoffice', '(unsupported)'); ?></option>
                    <option value="directadmin"><?php echo __('DirectAdmin'); ?><?php echo p__('backoffice', '(unsupported)'); ?></option>
                    <option value="vestacp"><?php echo __('VestaCP web API'); ?><?php echo p__('backoffice', '(deprecated, please upgrade to VestaCP exec API)'); ?></option>
                    <option value="vestacpcli"><?php echo __('VestaCP exec API'); ?></option>
                </select>


                <div ng-if="configs.cpanel_type.value.indexOf('plesk') >= 0">
                    <br/>
                    <div class="alert alert-warning">
                        <?php echo p__('backoffice',
                            'Plesk panel may required additional setup in order to work, please refer to this %s',
                            '<a href="https://doc.siberiancms.com/knowledge-base/how-to-setup-install-https-ssl-certificate/" target="_blank">' . p__('backoffice', 'documentation') . '</a>'); ?>
                    </div>
                </div>

                <div ng-if="['cpanel', 'directadmin', 'self'].indexOf(configs.cpanel_type.value) >= 0">
                    <br/>
                    <div class="alert alert-info">
                        <?php echo p__('backoffice', 'This panel is not officially supported and comes with no guarantee.'); ?>
                    </div>
                </div>

            </div>

            <div class="col-md-6"
                 ng-if="configs.cpanel_type.value == 'cpanel'">
                <label><?php echo __('Host') ?> *</label>
                <input class="form-control"
                       type="text"
                       ng-model="configs.cpanel.host"/>

                <label><?php echo __('Username') ?> *</label>
                <input class="form-control"
                       type="text"
                       ng-model="configs.cpanel.user"/>

                <label><?php echo __('Password') ?> *</label>
                <input class="form-control"
                       type="password"
                       ng-model="configs.cpanel.password"/>

                <label><?php echo __('Web space') ?></label>
                <input class="form-control"
                       type="text"
                       ng-model="configs.cpanel.webspace"
                       placeholder="<?php echo __('Leave blank if your web space is the current domain.') ?>"/>
            </div>

            <div class="col-md-6" ng-if="configs.cpanel_type.value == 'plesk'">

                <label><?php echo __("Host") ?> *</label>
                <input class="form-control"
                       type="text"
                       ng-model="configs.plesk.host"/>

                <label class="config-spacer"><?php echo __('Username') ?> *</label>
                <input class="form-control"
                       type="text"
                       ng-model="configs.plesk.user"/>

                <label class="config-spacer"><?php echo __('Password') ?> *</label>
                <input class="form-control"
                       type="password"
                       ng-model="configs.plesk.password"/>

                <label class="config-spacer"><?php echo __('Web space') ?> *</label>
                <input class="form-control"
                       type="text"
                       ng-model="configs.plesk.webspace"/>
            </div>

            <div class="col-md-6"
                 ng-if="configs.cpanel_type.value == 'pleskcli'">
                <label class="config-spacer"><?php echo __('IP') ?> *</label>
                <input class="form-control"
                       type="text"
                       ng-model="configs.pleskcli.ip"/>

                <label class="config-spacer"><?php echo __('Web space') ?> *</label>
                <input class="form-control"
                       type="text"
                       ng-model="configs.pleskcli.webspace"/>
            </div>

            <div class="col-md-6"
                 ng-if="configs.cpanel_type.value == 'vestacp'">
                <br/>

                <label><?php echo __("Host") ?> *</label>
                <input class="form-control"
                       type="text"
                       ng-model="configs.vestacp.host"/>

                <label class="config-spacer"><?php echo __('Username') ?> *</label>
                <input class="form-control"
                       type="text"
                       ng-model="configs.vestacp.user"/>

                <label class="config-spacer"><?php echo __('Password') ?> *</label>
                <input class="form-control"
                       type="password"
                       ng-model="configs.vestacp.password"/>

                <label class="config-spacer"><?php echo __('Web space') ?> *</label>
                <input class="form-control"
                       type="text"
                       ng-model="configs.vestacp.webspace"/>
            </div>

            <div class="col-md-6" ng-if="configs.cpanel_type.value == 'vestacpcli'">
                <br/>

                <label><?php echo __('Username') ?> *</label>
                <input class="form-control"
                       type="text"
                       ng-model="configs.vestacpcli.user"/>

                <label class="config-spacer"><?php echo __('Web space') ?> *</label>
                <input class="form-control"
                       type="text"
                       ng-model="configs.vestacpcli.webspace"/>
            </div>

            <div class="col-md-6" ng-if="configs.cpanel_type.value == 'directadmin'">

                <label><?php echo __("Host") ?> *</label>
                <input class="form-control"
                       type="text"
                       ng-model="configs.directadmin.host"/>

                <label class="config-spacer"><?php echo __('Username') ?> *</label>
                <input class="form-control"
                       type="text"
                       ng-model="configs.directadmin.user"/>

                <label class="config-spacer"><?php echo __('Password') ?> *</label>
                <input class="form-control"
                       type="password"
                       ng-model="configs.directadmin.password"/>

                <label class="config-spacer"><?php echo __('Web space') ?></label>
                <input class="form-control"
                       type="text"
                       ng-model="configs.directadmin.webspace"
                       placeholder="<?php echo __('Leave blank if your web space is the current domain.') ?>"/>

            </div>


        </div>

        <div class="form-group">
            <div class="col-md-12">

                <button type="submit"
                        class="btn btn-primary right"><?php echo __("Save"); ?></button>

                <div ng-show="configs.certificates.length">
                    <a class="btn btn-primary right"
                       style="margin-right: 15px;"
                       ng-click="testSsl();"><?php echo __("Test SSL/HTTPS") ?></a>
                </div>

                <sb-loader is_visible="form_loader_is_visible"
                           type="'inner_content'"
                           size="'small'"
                           animation="'no'"
                           class="form_loader"></sb-loader>

                <div class="clear"></div>
            </div>
        </div>
    </sb-section>


</form>

<sb-section title="'<?php echo __title("Issued certificates"); ?>'">
    <table class="table ssl-certificates">
        <thead>
        <tr>
            <th style="width:32px;"><?php echo __("ID") ?></th>
            <th style="width:140px;"><?php echo __("Platform hostname") ?></th>
            <th><?php echo __("Source") ?></th>
            <th style="width:50px;"><?php echo __("Cert") ?></th>
            <th style="width:50px;"><?php echo __("CA") ?></th>
            <th style="width:50px;"><?php echo __("Private") ?></th>
            <th style="width:130px;"><?php echo __("Updated At") ?></th>
            <th style="text-align:right;"><?php echo __("Actions") ?></th>
        </tr>
        </thead>
        <tbody ng-repeat="certificate in configs.certificates"
               ng-show="configs.certificates.length">
        <tr class="ssl-line"
            ng-class="{ 'color-success' : certificate.is_valid, 'color-failed' : !certificate.is_valid }">
            <td>{{ certificate.id }}</td>
            <td>{{ certificate.hostname }}</td>
            <td>{{ certificate.source }}</td>
            <td><a target="_blank"
                   title="<?php echo __js("Download Certificate", '"') ?>"
                   href="<?php echo $this->getUrl("/backoffice/advanced_configuration/downloadcert?type=cert&cert_id="); ?>{{ certificate.id }}">
                    <img src="/app/sae/design/desktop/backoffice/images/service/mini-cert.png"/></a>
            </td>
            <td><a target="_blank"
                   title="<?php echo __js("Download CA", '"') ?>"
                   href="<?php echo $this->getUrl("/backoffice/advanced_configuration/downloadcert?type=ca&cert_id="); ?>{{ certificate.id }}">
                    <img src="/app/sae/design/desktop/backoffice/images/service/mini-cert.png"/></a>
            </td>
            <td><a target="_blank"
                   title="<?php echo __js("Download Private", '"') ?>"
                   href="<?php echo $this->getUrl("/backoffice/advanced_configuration/downloadcert?type=private&cert_id="); ?>{{ certificate.id }}">
                    <img src="/app/sae/design/desktop/backoffice/images/service/mini-cert.png"/></a>
            </td>
            <td>{{ certificate.updated_at }}</td>
            <td style="text-align:right;">
                <a class="btn btn-xs btn-info"
                   ng-show="configs.cpanel_type.value != -1"
                   ng-click="uploadToPanel(certificate.hostname)">
                    <i class="fa fa-upload"></i>&nbsp;&nbsp;<?php echo __("Upload to panel") ?>
                </a>
                <a class="btn btn-xs btn-info"
                   style="margin-right: 10px;"
                   ng-click="certificate.show_info = !certificate.show_info">
                    <i class="fa fa-info"></i>&nbsp;&nbsp;<?php echo __("Info") ?>
                </a>
                <a class="btn btn-xs btn-danger"
                   ng-click="removeCertificate('<?php echo __js("You are about to delete this certificate, Are you sure ?", "'") ?>', certificate.id)"><span
                            class="fa fa-remove"></span></a>
            </td>
        </tr>
        <tr ng-show="certificate.show_info">
            <td colspan="8">
                <table class="info-table">
                    <tr ng-if="certificate.domains.length">
                        <td colspan="2"
                            style="white-space: normal;">
                            <b><?php echo __("Hostnames associated with this Certificate") ?>:</b> <span>{{ certificate.domains.join(', ') }}</span>
                            <br/>
                            <b><?php echo __("Issuer") ?>:</b> <span>{{ certificate.issuer }}</span>
                            <br/>
                            <b><?php echo __("Valid until") ?>:</b> <span>{{ certificate.valid_until }}</span>
                            <br/>
                            <br/>
                        </td>
                    </tr>
                    <tr ng-if="configs.cpanel_type.value == 'self'">
                        <td colspan="2"><b><?php echo __("Full path to use within your webserver.") ?></b></td>
                    </tr>
                    <tr ng-if="configs.cpanel_type.value == 'self'">
                        <td style="padding: 4px 10px 4px 0;"><b><?php echo __("Certificate path:") ?></b></td>
                        <td>{{ certificate.certificate }}</td>
                    </tr>
                    <tr ng-if="configs.cpanel_type.value == 'self'">
                        <td style="padding: 4px 10px 4px 0;"><b><?php echo __("CA path:") ?></b></td>
                        <td>{{ certificate.chain }}</td>
                    </tr>
                    <tr ng-if="configs.cpanel_type.value == 'self'">
                        <td style="padding: 4px 10px 4px 0;"><b><?php echo __("Private path:") ?></b></td>
                        <td>{{ certificate.private }}</td>
                    </tr>
                    <tr ng-if="!certificate.domains.length && configs.cpanel_type.value != 'self'">
                        <td colspan="2"><b><?php echo __("No informations.") ?></b></td>
                    </tr>
                </table>
            </td>
        </tr>
        </tbody>
        <tbody ng-show="!configs.certificates.length">
        <tr>
            <td colspan="9"><?php echo __("You have no certificate yet.") ?></td>
        </tr>
        </tbody>
    </table>

</sb-section>

<sb-section title="'<?php echo __title("Upload your own certificates"); ?>'"
            class="cert-upload">


    <div class="cert-upload ng-isolate-scope">

        <form ng-submit="createCertificate()"
              class="form-horizontal">
            <br/>

            <div class="form-group">
                <div class="col-md-12">
                    <div class="form-group col-md-6">
                        <label><?php echo __("Hostname") ?> *</label>
                        <input class="form-control"
                               type="text"
                               ng-model="form.hostname"/>
                    </div>
                </div>

                <div class="col-md-12">
                    <div class="form-group col-md-6">
                        <label><?php echo __("Upload files or use existing certificates on my server") ?></label>
                        <br/>
                        <label for="up-cert"><input type="radio"
                                                    id="up-cert"
                                                    ng-model="form.upload"
                                                    value="1"/> <?php echo __("Upload my certificates") ?></label>
                        <br/>
                        <label for="path-cert"><input type="radio"
                                                      id="path-cert"
                                                      ng-model="form.upload"
                                                      value="0"/> <?php echo __("Use existing certificates on my server") ?>
                        </label>
                    </div>
                </div>
            </div>

            <div class="form-group"
                 ng-if="form.upload == '1'">

                <!-- Certificate -->
                <div class="col-md-12">
                    <h4><?php echo __("Certificate") ?> *</h4>
                </div>

                <div class="col-md-4">
                    <div class="upload_a_file">
                        <label for="cert_path"><?php echo __("Click here to send your certificate"); ?></label>
                        <input id="cert_path"
                               type="file"
                               nv-file-select=""
                               uploader="cert_path"/>
                    </div>
                </div>

                <div class="col-md-1">
                    <div class="drop_a_file">
                        <label><?php echo __("OR"); ?></label>
                    </div>
                </div>

                <div class="col-md-5">
                    <div class="drop_a_file">
                        <label><?php echo __("Drop your certificate here"); ?></label>
                        <div ng-show="cert_path.isHTML5">
                            <div class="well drop-zone"
                                 nv-file-drop=""
                                 nv-file-over=""
                                 uploader="cert_path">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="clear"></div>

                <div class="col-md-12">
                    <table class="table"
                           ng-show="cert_path.queue.length">
                        <thead>
                        <tr>
                            <th width="75%"><?php echo __("Name") ?></th>
                            <th ng-show="cert_path.isHTML5"><?php echo __("Progress") ?></th>
                            <th class="text-center"><?php echo __("Status") ?></th>
                            <th style="width: 38px;"></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr ng-repeat="item in cert_path.queue"
                            ng-show="cert_path.queue.length">
                            <td><strong>{{ item.file.name }}</strong></td>
                            <td ng-show="cert_path.isHTML5">
                                <div class="progress">
                                    <div class="progress-bar progress-bar-striped"
                                         role="progressbar"
                                         ng-style="{ 'width': item.progress + '%' }"></div>
                                </div>
                            </td>
                            <td class="text-center">
                                <span ng-show="item.isSuccess"><i class="fa fa-check"></i></span>
                                <span ng-show="item.isCancel"><i class="fa fa-ban"></i></span>
                                <span ng-show="item.isError"><i class="fa fa-remove"></i></span>
                            </td>
                            <td nowrap class="text-right">
                                <button type="button"
                                        class="btn btn-danger btn-xs"
                                        ng-click="item.remove()"
                                        ng-disabled="item.isReady || item.isUploading">
                                    <span class="fa fa-remove"></span>
                                </button>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <!-- /Certificate -->

                <!-- Private Certificate -->
                <div class="col-md-12">
                    <h4><?php echo __("Private certificate") ?> *</h4>
                </div>

                <div class="col-md-4">
                    <div class="upload_a_file">
                        <label for="private_path"><?php echo __("Click here to send your Private certificate"); ?></label>
                        <input id="private_path"
                               type="file"
                               nv-file-select=""
                               uploader="private_path"/>
                    </div>
                </div>

                <div class="col-md-1">
                    <div class="drop_a_file">
                        <label><?php echo __("OR"); ?></label>
                    </div>
                </div>

                <div class="col-md-5">
                    <div class="drop_a_file">
                        <label><?php echo __("Drop your certificate here"); ?></label>
                        <div ng-show="private_path.isHTML5">
                            <div class="well drop-zone"
                                 nv-file-drop=""
                                 nv-file-over=""
                                 uploader="private_path">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="clear"></div>

                <div class="col-md-12">
                    <table class="table"
                           ng-show="private_path.queue.length">
                        <thead>
                        <tr>
                            <th width="75%"><?php echo __("Name") ?></th>
                            <th ng-show="private_path.isHTML5"><?php echo __("Progress") ?></th>
                            <th class="text-center"><?php echo __("Status") ?></th>
                            <th style="width: 38px;"></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr ng-repeat="item in private_path.queue"
                            ng-show="private_path.queue.length">
                            <td><strong>{{ item.file.name }}</strong></td>
                            <td ng-show="private_path.isHTML5">
                                <div class="progress">
                                    <div class="progress-bar progress-bar-striped"
                                         role="progressbar"
                                         ng-style="{ 'width': item.progress + '%' }"></div>
                                </div>
                            </td>
                            <td class="text-center">
                                <span ng-show="item.isSuccess"><i class="fa fa-check"></i></span>
                                <span ng-show="item.isCancel"><i class="fa fa-ban"></i></span>
                                <span ng-show="item.isError"><i class="fa fa-remove"></i></span>
                            </td>
                            <td nowrap class="text-right">
                                <button type="button"
                                        class="btn btn-danger btn-xs"
                                        ng-click="item.remove()"
                                        ng-disabled="item.isReady || item.isUploading">
                                    <span class="fa fa-remove"></span>
                                </button>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <!-- /Private Certificate -->

                <!-- Fullchain -->
                <div class="col-md-12">
                    <h4><?php echo __("Full chain") ?> *</h4>
                </div>

                <div class="col-md-4">
                    <div class="upload_a_file">
                        <label for="cert_path"><?php echo __("Click here to send your fullchain"); ?></label>
                        <input id="cert_path"
                               type="file"
                               nv-file-select=""
                               uploader="fullchain_path"/>
                    </div>
                </div>

                <div class="col-md-1">
                    <div class="drop_a_file">
                        <label><?php echo __("OR"); ?></label>
                    </div>
                </div>

                <div class="col-md-5">
                    <div class="drop_a_file">
                        <label><?php echo __('Drop your certificate here'); ?></label>
                        <div ng-show="fullchain_path.isHTML5">
                            <div class="well drop-zone"
                                 nv-file-drop=""
                                 nv-file-over=""
                                 uploader="fullchain_path">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="clear"></div>

                <div class="col-md-12">
                    <table class="table"
                           ng-show="fullchain_path.queue.length">
                        <thead>
                        <tr>
                            <th width="75%"><?php echo __('Name') ?></th>
                            <th ng-show="fullchain_path.isHTML5"><?php echo __('Progress') ?></th>
                            <th class="text-center"><?php echo __('Status') ?></th>
                            <th style="width: 38px;"></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr ng-repeat="item in fullchain_path.queue"
                            ng-show="fullchain_path.queue.length">
                            <td><strong>{{ item.file.name }}</strong></td>
                            <td ng-show="fullchain_path.isHTML5">
                                <div class="progress">
                                    <div class="progress-bar progress-bar-striped"
                                         role="progressbar"
                                         ng-style="{ 'width': item.progress + '%' }"></div>
                                </div>
                            </td>
                            <td class="text-center">
                                <span ng-show="item.isSuccess"><i class="fa fa-check"></i></span>
                                <span ng-show="item.isCancel"><i class="fa fa-ban"></i></span>
                                <span ng-show="item.isError"><i class="fa fa-remove"></i></span>
                            </td>
                            <td nowrap class="text-right">
                                <button type="button"
                                        class="btn btn-danger btn-xs"
                                        ng-click="item.remove()"
                                        ng-disabled="item.isReady || item.isUploading">
                                    <span class="fa fa-remove"></span>
                                </button>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <!-- /Fullchain -->

                <!-- CA Certificate -->
                <div class="col-md-12">
                    <h4><?php echo __("CA certificate") ?> *</h4>
                </div>

                <div class="col-md-4">
                    <div class="upload_a_file">
                        <label for="ca_path"><?php echo __('Click here to send your CA certificate'); ?></label>
                        <input id="ca_path"
                               type="file"
                               nv-file-select=""
                               uploader="ca_path"/>
                    </div>
                </div>

                <div class="col-md-1">
                    <div class="drop_a_file">
                        <label><?php echo __('OR'); ?></label>
                    </div>
                </div>

                <div class="col-md-5">
                    <div class="drop_a_file">
                        <label><?php echo __('Drop your certificate here'); ?></label>
                        <div ng-show="ca_path.isHTML5">
                            <div class="well drop-zone"
                                 nv-file-drop=""
                                 nv-file-over=""
                                 uploader="ca_path">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="clear"></div>

                <div class="col-md-12">
                    <table class="table"
                           ng-show="ca_path.queue.length">
                        <thead>
                        <tr>
                            <th width="75%"><?php echo __("Name") ?></th>
                            <th ng-show="ca_path.isHTML5"><?php echo __("Progress") ?></th>
                            <th class="text-center"><?php echo __("Status") ?></th>
                            <th style="width: 38px;"></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr ng-repeat="item in ca_path.queue"
                            ng-show="ca_path.queue.length">
                            <td><strong>{{ item.file.name }}</strong></td>
                            <td ng-show="ca_path.isHTML5">
                                <div class="progress">
                                    <div class="progress-bar progress-bar-striped"
                                         role="progressbar"
                                         ng-style="{ 'width': item.progress + '%' }"></div>
                                </div>
                            </td>
                            <td class="text-center">
                                <span ng-show="item.isSuccess"><i class="fa fa-check"></i></span>
                                <span ng-show="item.isCancel"><i class="fa fa-ban"></i></span>
                                <span ng-show="item.isError"><i class="fa fa-remove"></i></span>
                            </td>
                            <td nowrap class="text-right">
                                <button type="button"
                                        class="btn btn-danger btn-xs"
                                        ng-click="item.remove()"
                                        ng-disabled="item.isReady || item.isUploading">
                                    <span class="fa fa-remove"></span>
                                </button>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <!-- /CA Certificate -->


            </div>

            <div class="form-group"
                 ng-if="form.upload == '0'">

                <div class="col-md-12">
                    <div class="form-group col-md-6">
                        <label>
                            <?php echo __("Path to your Certificate") ?> *
                        </label>
                        <input class="form-control"
                               type="text"
                               ng-model="form.cert_path"/>
                    </div>
                </div>

                <div class="col-md-12">
                    <div class="form-group col-md-6">
                        <label>
                            <?php echo __("Path to your Private key") ?> *
                        </label>
                        <input class="form-control"
                               type="text"
                               ng-model="form.private_path"/>
                    </div>
                </div>

                <div class="col-md-12">
                    <div class="form-group col-md-6">
                        <label>
                            <?php echo __('Path to your Fullchain') ?> *
                        </label>
                        <input class="form-control"
                               type="text"
                               ng-model="form.fullchain_path"/>
                    </div>
                </div>

                <div class="col-md-12">
                    <div class="form-group col-md-6">
                        <label>
                            <?php echo __('Path to your CA/Chain certificate') ?> *
                        </label>
                        <input class="form-control"
                               type="text"
                               ng-model="form.ca_path"/>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12">
                    <button type="submit"
                            class="btn btn-primary right"><?php echo __('Upload'); ?></button>
                    <sb-loader is_visible="form_loader_is_visible"
                               type="'inner_content'"
                               size="'small'"
                               animation="'no'"
                               class="form_loader"></sb-loader>
                    <div class="clear"></div>
                </div>
            </div>

        </form>
    </div>
</sb-section>

<style type="text/css">
    .well.drop-zone {
        height: 80px;
        border: dotted 3px lightgray;
    }

    .loader.content_loader {
        background-position: center 100px !important;
    }

    .ssl-certificates .ssl-line td {
        padding: 5px 6px 0px 4px;
    }

    label.config-spacer {
        margin-top: 10px;
    }
</style>



