
<sb-section title="'<?php echo addcslashes(__("Installed modules"), "'"); ?>'">
    <table class="table">
        <thead>
            <tr>
                <th style="width:30%;"><?php echo __('Name') ?></th>
                <th style="width:20%;"><?php echo __('Version') ?></th>
                <th style="width:20%;"><?php echo __('License key') ?></th>
                <th style="width:15%;text-align:right;"><?php echo __('Actions') ?></th>
                <th style="width:15%;text-align:right;"><?php echo __('Enabled?') ?></th>
            </tr>
        </thead>
        <tbody>
            <tr ng-repeat="module in modules"
                ng-show="modules.length"
                ng-class="{'text-danger red-border': !module.is_enabled}">
                <td>{{ module.name }}</td>
                <td>{{ module.version }}</td>
                <td>
                    <p>{{ module.license_key }}</p>
                </td>
                <td style="text-align:right;">
                    <button class="btn btn-xs btn-info"
                            ng-repeat="(k, action) in module.actions"
                            ng-click="moduleAction(module.original_name, k);">{{ action.label }}</button>
                </td>
                <td style="text-align:right;">
                    <input type="checkbox"
                           ng-model="module.is_enabled"
                           ng-change="toggleModule(module)" />
                </td>
            </tr>
            <tr ng-show="!modules.length">
                <td colspan="<?php echo (isDev()) ? '4' : '2' ?>"><?php echo __("No modules") ?></td>
            </tr>
        </tbody>
    </table>

</sb-section>

<sb-section title="'<?php echo addcslashes(__("Installed layouts"), "'"); ?>'">
    <table class="table">
        <thead>
        <tr>
            <th style="width:35%;"><?php echo __("Name") ?></th>
            <th style="width:30%;"><?php echo __("Version") ?></th>
            <th style="width:20%;text-align:right;"><?php echo __("Actions") ?></th>
            <th style="width:15%;text-align:right;"><?php echo __('Enabled?') ?></th>
        </tr>
        </thead>
        <tbody>
        <tr ng-repeat="layout in layouts"
            ng-show="layouts.length"
            ng-class="{'text-danger red-border': !layout.is_enabled}">
            <td>{{ layout.name }}</td>
            <td>{{ layout.version }}</td>
            <td style="text-align:right;">-</td>
            <td style="text-align:right;">
                <input type="checkbox"
                       ng-model="layout.is_enabled"
                       ng-change="toggleModule(layout)" />
            </td>
        </tr>
        <tr ng-show="!layouts.length">
            <td colspan="3"><?php echo __("No layouts") ?></td>
        </tr>
        </tbody>
    </table>

</sb-section>

<sb-section title="'<?php echo addcslashes(__("Installed templates"), "'"); ?>'">
    <table class="table">
        <thead>
        <tr>
            <th style="width:45%;"><?php echo __("Name") ?></th>
            <th style="width:40%;text-align: right"><?php echo __("Version") ?></th>
            <th style="width:15%;text-align:right;"><?php echo __('Enabled?') ?></th>
        </tr>
        </thead>
        <tbody>
        <tr ng-repeat="template in templates"
            ng-show="templates.length"
            ng-class="{'text-danger red-border': !template.is_enabled}">
            <td>{{ template.name }}</td>
            <td style="text-align: right">{{ template.version }}</td>
            <td style="text-align:right;">
                <input type="checkbox"
                       ng-model="template.is_enabled"
                       ng-change="toggleModule(template)" />
            </td>
        </tr>
        <tr ng-show="!templates.length">
            <td colspan="3"><?php echo __("No templates") ?></td>
        </tr>
        </tbody>
    </table>
</sb-section>

<sb-section title="'<?php echo addcslashes(__("Installed icon packs"), "'"); ?>'">
    <table class="table">
        <thead>
        <tr>
            <th style="width:50%;"><?php echo __("Name") ?></th>
            <th style="width:30%;"><?php echo __("Version") ?></th>
            <th style="width:20%;text-align:right;"><?php echo __("Actions") ?></th>
        </tr>
        </thead>
        <tbody>
        <tr ng-repeat="icon in icons" ng-show="icons.length">
            <td>{{ icon.name }}</td>
            <td>{{ icon.version }}</td>
            <td style="text-align:right;">-</td>
        </tr>
        <tr ng-show="!icons.length">
            <td colspan="3"><?php echo __("No icon packs") ?></td>
        </tr>
        </tbody>
    </table>
</sb-section>

<sb-section title="'<?php echo addcslashes(__("Core modules"), "'"); ?>'">
    <table class="table">
        <thead>
        <tr>
            <th style="width:50%;"><?php echo __("Name") ?></th>
            <th style="width:50%;text-align:right;"><?php echo __("Version") ?></th>
        </tr>
        </thead>
        <tbody>
        <tr ng-repeat="module in core_modules"
            ng-show="core_modules.length">
            <td>{{ module.name }}</td>
            <td style="width:50%;text-align:right;">{{ module.version }}</td>
        </tr>
        <tr ng-show="!core_modules.length">
            <td colspan="2"><?php echo __("No modules") ?></td>
        </tr>
        </tbody>
    </table>

</sb-section>

<sb-section title="'<?php echo addcslashes(__("Features"), "'"); ?>'">
    <div class="alert alert-info">
        <?php echo __('You can globally disable a feature!') ?>
        <br />
        <?php echo __('Note: A disabled feature is not removed from published applications & can still be edited, but users can\'t add it anymore!') ?>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th style="width:15%;"><?php echo __("Name") ?></th>
                <th style="width:15%;"><?php echo __("Code") ?></th>
                <th style="width:50%;"><?php echo __("Description") ?></th>
                <th style="width:20%;text-align:right;"><?php echo __("Enabled?") ?></th>
            </tr>
        </thead>
        <tbody>
            <tr ng-repeat="feat in features track by feat.id"
                ng-show="features.length"
                ng-class="{'text-danger': !feat.is_enabled}">
                <td>{{ feat.name }}</td>
                <td>{{ feat.code }}</td>
                <td style="white-space: normal;">{{ feat.description }}</td>
                <td style="text-align:right;">
                    <input type="checkbox"
                           ng-model="feat.is_enabled"
                           ng-change="toggleFeature(feat)" />
                </td>
            </tr>
            <tr ng-show="!features.length">
                <td colspan="2"><?php echo __("No features") ?></td>
            </tr>
        </tbody>
    </table>
</sb-section>

<style type="text/css">
    tr.red-border {
        border-left: 2px solid #990f0c;
    }

    thead tr th {
        font-weight: bold;
    }

    tbody tr td {
        padding: 8px 8px 2px !important;
    }
</style>
