<?php


try {
    if (!$this->getApplication()) {
        throw new \Exception("gotodefault");
    }

    $application = $this->getApplication();
    $variables = Template_Model_Design::getVariables($application);
} catch (\Exception $e) {
    // Defaults!
    $variables = [
        '$email-body-custom-bg' => 'rgba(225,225,225,1)',
        '$email-header-custom-text' => 'rgba(255,255,255,1)',
        '$email-header-custom-bg' => 'rgba(147,181,205,1)',
        '$email-content-custom-text' => 'rgba(136,136,136,1)',
        '$email-content-custom-bg' => 'rgba(255,255,255,1)',
        '$email-footer-custom-text' => 'rgba(96,96,96,1)',
        '$email-button-primary-custom-text' => '#ffffff',
        '$email-button-primary-custom-bg' => '#3498db',
        '$email-button-danger-custom-text' => '#ffffff',
        '$email-button-danger-custom-bg' => '#c10600',
    ];
}

?>
<!doctype html>
<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title><?php echo $this->getEmailTitle() ?></title>
    <style>
        /* -------------------------------------
            GLOBAL RESETS
        ------------------------------------- */
        img {
            border: none;
            -ms-interpolation-mode: bicubic;
            max-width: 100%;
        }

        body {
            background-color: <?php echo $variables['$email-body-custom-bg'] ?>;
            font-family: sans-serif;
            -webkit-font-smoothing: antialiased;
            font-size: 14px;
            line-height: 1.4;
            margin: 0;
            padding: 0;
            -ms-text-size-adjust: 100%;
            -webkit-text-size-adjust: 100%;
        }

        table {
            border-collapse: separate;
            mso-table-lspace: 0;
            mso-table-rspace: 0;
            width: 100%;
        }

        table td {
            font-family: sans-serif;
            font-size: 14px;
            vertical-align: top;
        }

        /* -------------------------------------
            BODY & CONTAINER
        ------------------------------------- */

        .body {
            background-color: <?php echo $variables['$email-body-custom-bg'] ?>;
            width: 100%;
        }

        /* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */
        .container {
            display: block;
            margin: 0 auto !important;
            /* makes it centered */
            max-width: 580px;
            padding: 10px;
            width: 580px;
        }

        /* This should also be a block element, so that it will fill 100% of the .container */
        .content {
            box-sizing: border-box;
            display: block;
            margin: 0 auto;
            max-width: 580px;
            padding: 10px;
        }

        /* -------------------------------------
            HEADER, FOOTER, MAIN
        ------------------------------------- */
        .main {
            background: <?php echo $variables['$email-content-custom-bg'] ?>;
            border-radius: 0;
            width: 100%;
        }

        .wrapper {
            box-sizing: border-box;
            padding: 20px;
        }

        .content-block {
            padding-bottom: 10px;
            padding-top: 10px;
        }

        .footer {
            clear: both;
            margin-top: 10px;
            text-align: center;
            width: 100%;
            color: <?php echo $variables['$email-footer-custom-text'] ?>;
        }

        .footer td,
        .footer p,
        .footer span,
        .footer a {
            color: <?php echo $variables['$email-footer-custom-text'] ?>;
            font-size: 12px;
            text-align: center;
        }

        /* -------------------------------------
            TYPOGRAPHY
        ------------------------------------- */
        h1,
        h2,
        h3,
        h4 {
            color: <?php echo $variables['$email-content-custom-text'] ?>;
            font-family: sans-serif;
            font-weight: 400;
            line-height: 1.4;
            margin: 0;
            margin-bottom: 30px;
        }

        h1 {
            font-size: 35px;
            font-weight: 300;
            text-align: center;
            text-transform: capitalize;
        }

        p,
        ul,
        ol {
            font-family: sans-serif;
            font-size: 14px;
            font-weight: normal;
            margin: 0;
            margin-bottom: 15px;
        }

        p li,
        ul li,
        ol li {
            list-style-position: inside;
            margin-left: 5px;
        }

        a {
            color: #3498db;
            text-decoration: underline;
        }

        /* -------------------------------------
            BUTTONS
        ------------------------------------- */
        .btn {
            box-sizing: border-box;
            width: 100%;
        }

        .btn > tbody > tr > td {
            padding-bottom: 15px;
        }

        .btn table {
            width: auto;
        }

        .btn table td {
            background-color: #3498db;
            border-radius: 0;
            text-align: center;
        }

        .btn a {
            background-color: <?php echo $variables['$email-button-primary-custom-bg'] ?>;
            border: solid 1px <?php echo $variables['$email-button-primary-custom-bg'] ?>;
            border-radius: 0;
            box-sizing: border-box;
            color: <?php echo $variables['$email-button-primary-custom-bg'] ?>;
            cursor: pointer;
            display: inline-block;
            font-size: 14px;
            font-weight: bold;
            margin: 0;
            padding: 12px 25px;
            text-decoration: none;
            text-transform: capitalize;
        }

        .btn-primary table td {
            background-color: <?php echo $variables['$email-button-primary-custom-bg'] ?>;
        }

        .btn-primary a {
            background-color: <?php echo $variables['$email-button-primary-custom-bg'] ?>;
            border-color: <?php echo $variables['$email-button-primary-custom-bg'] ?>;
            color: <?php echo $variables['$email-button-primary-custom-text'] ?>;
        }

        .btn-danger table td {
            background-color: <?php echo $variables['$email-button-danger-custom-bg'] ?>;
        }

        .btn-danger a {
            background-color: <?php echo $variables['$email-button-danger-custom-bg'] ?>;
            border-color: <?php echo $variables['$email-button-danger-custom-bg'] ?>;
            color: <?php echo $variables['$email-button-danger-custom-text'] ?>;
        }

        /* -------------------------------------
            OTHER STYLES THAT MIGHT BE USEFUL
        ------------------------------------- */
        .last {
            margin-bottom: 0;
        }

        .first {
            margin-top: 0;
        }

        .align-center {
            text-align: center;
        }

        .align-right {
            text-align: right;
        }

        .align-left {
            text-align: left;
        }

        .clear {
            clear: both;
        }

        .mt0 {
            margin-top: 0;
        }

        .mb0 {
            margin-bottom: 0;
        }

        .preheader {
            color: transparent;
            display: none;
            height: 0;
            max-height: 0;
            max-width: 0;
            opacity: 0;
            overflow: hidden;
            mso-hide: all;
            visibility: hidden;
            width: 0;
        }

        .powered-by a {
            text-decoration: none;
        }

        hr {
            border: 0;
            border-bottom: 1px solid #f6f6f6;
            margin: 20px 0;
        }

        /* -------------------------------------
            RESPONSIVE AND MOBILE FRIENDLY STYLES
        ------------------------------------- */
        @media only screen and (max-width: 620px) {
            table[class=body] h1 {
                font-size: 28px !important;
                margin-bottom: 10px !important;
            }

            table[class=body] p,
            table[class=body] ul,
            table[class=body] ol,
            table[class=body] td,
            table[class=body] span,
            table[class=body] a {
                font-size: 16px !important;
            }

            table[class=body] .wrapper,
            table[class=body] .article {
                padding: 10px !important;
            }

            table[class=body] .content {
                padding: 0 !important;
            }

            table[class=body] .container {
                padding: 0 !important;
                width: 100% !important;
            }

            table[class=body] .main {
                border-left-width: 0 !important;
                border-radius: 0 !important;
                border-right-width: 0 !important;
            }

            table[class=body] .btn table {
                width: 100% !important;
            }

            table[class=body] .btn a {
                width: 100% !important;
            }

            table[class=body] .img-responsive {
                height: auto !important;
                max-width: 100% !important;
                width: auto !important;
            }
        }

        code {
            padding: 10px 15px;
            display: inline-block;
            background: lightgrey;
            font-family: lato, monospace;
            letter-spacing: .5px;
        }

        /* -------------------------------------
            PRESERVE THESE STYLES IN THE HEAD
        ------------------------------------- */
        @media all {
            .ExternalClass {
                width: 100%;
            }

            .ExternalClass,
            .ExternalClass p,
            .ExternalClass span,
            .ExternalClass font,
            .ExternalClass td,
            .ExternalClass div {
                line-height: 100%;
            }

            .apple-link a {
                color: inherit !important;
                font-family: inherit !important;
                font-size: inherit !important;
                font-weight: inherit !important;
                line-height: inherit !important;
                text-decoration: none !important;
            }

            .btn-primary table td:hover {
                filter: brightness(85%);
            }

            .btn-primary a:hover {
                filter: brightness(85%);
            }

            .btn-danger table td:hover {
                filter: brightness(85%);
            }

            .btn-danger a:hover {
                filter: brightness(85%);
            }
        }

        .header-title {
            background-color: <?php echo $variables['$email-header-custom-bg'] ?>;
        }

        .header-title h4 {
            font-size: 22px;
            color: <?php echo $variables['$email-header-custom-text'] ?>;
            text-align: center;
            margin-bottom: 0 !important;
        }


    </style>
</head>
<body class="">
<table border="0"
       cellpadding="0"
       cellspacing="0"
       class="body">
    <tr>
        <td>&nbsp;</td>
        <td class="container">
            <div class="content">
                <!-- START CENTERED WHITE CONTAINER -->
                <?php echo $this->getPartialHtml('header'); ?>

                <table  border="0"
                        cellpadding="0"
                        cellspacing="0"
                        class="main">
                    <!-- START MAIN CONTENT AREA -->
                    <tr>
                        <td class="wrapper header-title">
                            <h4><?php echo $this->getEmailTitle() ?></h4>
                        </td>
                    </tr>
                    <tr>
                        <td class="wrapper">
                            <table border="0"
                                   cellpadding="0"
                                   cellspacing="0">
                                <tr>
                                    <td>
                                        <?php echo $this->getPartialHtml('content_email') ?>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                    <!-- END MAIN CONTENT AREA -->
                </table>


                <?php echo $this->getPartialHtml('footer') ?>
                <!-- END CENTERED WHITE CONTAINER -->
            </div>
        </td>
        <td>&nbsp;</td>
    </tr>
</table>
</body>
</html>