<div class="wrapper inner_content">
    <div class="title">
        <div class="inner_content title_content">
            <h1><i class="fa fa-user"></i><?php echo __("Log-in"); ?></h1>
        </div>
    </div>
    <div class="content">

        <form ng-submit="login()"
              ng-show="!show_forgotten_password_form">

            <div class="col-md-4 col-md-offset-4">
                <div class="form-group">
                    <label for="email"><?php echo __("Email"); ?></label>
                    <input type="text"
                           id="email"
                           class="form-control email"
                           ng-model="credentials.email"
                           placeholder="<?php echo __("Email"); ?>" />
                </div>
            </div>

            <div class="clear col-md-4 col-md-offset-4">
                <div class="form-group">
                    <label for="password"><?php echo __("Password"); ?></label>
                    <input type="password"
                           id="password"
                           class="form-control"
                           ng-model="credentials.password"
                           placeholder="<?php echo __("Password"); ?>" />
                </div>
            </div>

            <div class="clear col-md-4 col-md-offset-4">
                <div class="form-group">
                    <a href="javascript:void(0)"
                       ng-click="show_forgotten_password_form = true;"><?php echo __('Forgot your password?'); ?></a>
                </div>
            </div>

            <div class="clear col-md-4 col-md-offset-4">
                <div class="form-group">
                    <button type="submit"
                            class="btn btn-primary"><?php echo __('Log in'); ?></button>
                    <sb-loader is_visible="form_loader_is_visible"
                               type="'inner_content'"
                               size="'small'"
                               animation="'no'"></sb-loader>
                </div>
            </div>

        </form>

        <div class="clear"></div>

        <form ng-submit="forgottenPassword()"
              ng-show="show_forgotten_password_form">

            <div class="col-md-4 col-md-offset-4">
                <div class="form-group">
                    <p><?php echo __('Forgot your password? Don\'t worry! Simply enter your email address and we\'ll send you a new one right now.'); ?></p>
                </div>
            </div>
            <br />
            <div class="clear col-md-4 col-md-offset-4">
                <div class="form-group">
                    <label for="email"><?php echo __("Email"); ?></label>
                    <input type="text"
                           id="email"
                           class="form-control email"
                           ng-model="credentials.email"
                           placeholder="<?php echo __("Email"); ?>" />
                </div>
            </div>

            <div class="clear col-md-4 col-md-offset-4">
                <div class="form-group">
                    <button type="button"
                            class="btn btn-danger"
                            ng-click="show_forgotten_password_form = false;">
                        <i class="fa fa-arrow-left"></i>
                    </button>
                    <button type="submit"
                            class="forgot_password_content btn btn-primary"><?php echo __('Send'); ?></button>
                    <sb-loader is_visible="form_loader_is_visible"
                               type="'inner_content'"
                               size="'small'"
                               animation="'no'"></sb-loader>
                </div>
            </div>
        </form>

        <div class="clear"></div>
    </div>
</div>
