<?php
$application = $this->getApplication();

$splashVersion = (integer) $application->getSplashVersion();

?>
<div class="page-content-wrapper">

    <?php echo $this->createPartialHtml(
            'icon_create',
            'admin_view_default',
            'application/customization/publication/app/icon.phtml'); ?>

    <div id="startup_conteneur"
         class="content sb-tour">
        <h3 class="title-editor border-purple text-center">
            <?php echo __("Unified splashscreen"); ?>
            <i class="icon ion-ios-information-outline display_tooltip"
               data-toggle="tooltip"
               title="<?php echo p__js("application", "This tool helps you choose a startup image that will be compatible with all device screen sizes. It will be seen when the app starts while it is loading.", '"') ?>"></i>
        </h3>
        <div id="startup"
             class="subcontent content-color container-fluid">
            <?php echo $this->createPartialHtml(
                    'startup_create',
                    'admin_view_default',
                    'application/customization/publication/app/startup-unified.phtml'); ?>
        </div>
    </div>

    <form id="publicationForm"
          action="<?php echo $this->getUrl('application/customization_publication_app/save'); ?>"
          method="post">
    </form>
</div>

<?php
    $pages = $application->getPages();
    $pages_id = array();
    foreach($pages as $page) {
        $pages_id[] = $page->getId();
    }
?>
<ul id="pages_id" style="display:none">
    <?php
        foreach($pages_id as $id) {
            echo '<li id="'.$id.'"></li>';
        }
    ?>
</ul>

<script type="text/javascript">

    $(document).ready(function() {

        $('#name').keyup(function() {
            setAppName($('#name').val());
        });

        $('#publicationForm').submit(function() {
            var loading = new AlertMessage();
            loading.show();
            reload(this, this.action, true, function(datas) {
                if(datas.success) {
                    clearTimeout(timer);
                }
            });
            return false;
        });

        var eq = 0;
        $('#generate_captures').click( function() {
            supprime_capture('all', '');
            $('#captures ul').html('');
            loadCaptures(eq);
        });

    });
</script>
