<?php

$application = $this->getApplication();

$ios_device = $application->getDevice(1);
$android_device = $application->getDevice(2);

$formGeneralInformation = new Application_Form_GeneralInformation();
$formGeneralInformation->populate($application->getData());

$formAdmob = new Application_Form_Admob();
$formAdmob->fill($application);

$formAppleGoogle = new Application_Form_AppleGoogle();
$formAppleGoogle->fill($application);

// App link
$appDomain = $application->getDomain();
$appKey = $application->getKey();
$currentDomain = parse_url($this->getRequest()->getBaseUrl(), PHP_URL_HOST);
if (!empty($appDomain)) {
    $appLink = "http://{$appDomain}";
} else {
    $appLink = "https://{$currentDomain}/{$appKey}";
}

?>
<div class="page-content-wrapper">

    <?php echo $this->createPartialHtml(
        'subscription',
        'admin_view_default',
        'application/customization/publication/subscription.phtml'); ?>

    <div id="general-content"
         class="content sb-tour">
        <h3 class="title-editor border-green text-center">
            <?php echo __('General information'); ?>
            <i class="icon ion-ios-information-outline display_tooltip"
               data-toggle="tooltip"
               title="<?php echo p__js("application", "You can change your application name, as well as the bundle ID and the package name. These two last items are your app unique identifiers when being published on the App Store and Google Play, you don't need to edit them except if you know what you do.", '"') ?>"></i>
        </h3>
        <div id="general"
             class="subcontent content-color">
            <div id="general-information"
                 class="container-fluid form-horizontal">

                <div class="row form-group">
                    <div class="col-md-3">
                        <?php echo p__("application", "WebApp link") ?>
                    </div>
                    <div class="col-md-7">
                        <a href="<?php echo $appLink ?>"
                           style="text-decoration: underline;"
                           onclick="window.open(this.href,'targetWindow','toolbar=no,location=yes,status=no,menubar=no,scrollbars=no,resizable=no,width=480,height=800');return false;">
                            <?php echo $appLink ?>
                        </a>
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col-md-3">
                        <?php echo p__("application", "Application ID") ?>
                    </div>
                    <div class="col-md-7">
                        <b>#<?php echo $application->getId() ?></b>
                    </div>
                </div>

                <?php echo $formGeneralInformation; ?>
            </div>
        </div>
    </div>

    <?php if ($this->_canAccess('editor_publication_admob')): ?>
    <div id="sb-tour-monetize-source"
         class="content sb-tour">
        <h3 class="title-editor border-green text-center">
            <?php echo __('Monetize your app'); ?>
            <i class="icon ion-ios-information-outline display_tooltip"
               data-toggle="tooltip"
               title="<?php echo p__js("application", "You can monetize your app by adding ad banners or interstitials that will be displayed to your app users.", '"') ?>"></i>
        </h3>
        <div class="monetize subcontent content-color">
            <div id="admob-settings"
                 class="container-fluid form-horizontal">
                <?php echo $formAdmob; ?>
            </div>
        </div>
    </div>
    <?php endif; ?>

    <div id="apple-content"
         class="content sb-tour">
        <h3 class="title-editor border-green text-center">
            <?php echo __("Stores Informations"); ?>
        </h3>
        <div class="subcontent content-color">
            <div id="apple-google"
                 class="container-fluid form-horizontal">
                <?php echo $formAppleGoogle ?>
            </div>
        </div>
    </div>

    <div class="publication-padding-bottom">&nbsp;</div>

    <script type="text/javascript">

        // Improvements
        $(document).ready(function () {
            bindForms('#general-information');
            bindForms('#admob-settings');
            bindForms('#apple-google');

            $('#android-element').addClass('col-md-6');
            $('#ios-element').addClass('col-md-6');
            $('#apple-element').addClass('col-md-6');
            $('#google-element').addClass('col-md-6');

            // Live update AppName!
            let appName = $('#name');

            appName.off('keyup');
            appName.on('keyup', function () {
                let name = $(this).val().replace(/(<([^>]+)>)/ig, '');
                // Set back stripped/value!
                $(this).val(name);
                $('#header_app_name').text(name);
            });

            let updateStore = function (store) {
                let value = $('[name="has_' + store + '_account"]:checked').val();

                let type = $('#warning_' + store);
                let email = $('#' + store + '_email');
                let password = $('#' + store + '_password');

                switch (value) {
                    case '0':
                        type.parents('.sb-form-line').show();
                        email.parents('.sb-form-line').hide();
                        password.parents('.sb-form-line').hide();
                        break;
                    case '1':
                        type.parents('.sb-form-line').hide();
                        email.parents('.sb-form-line').show();
                        password.parents('.sb-form-line').show();
                        break;
                    case '2':
                        type.parents('.sb-form-line').hide();
                        email.parents('.sb-form-line').hide();
                        password.parents('.sb-form-line').hide();
                        break;
                }
            };

            let appleAccount = $('[name="has_apple_account"]');

            updateStore('apple');
            appleAccount.off('change');
            appleAccount.on('change', function () {
                updateStore('apple');
            });

            let androidAccount = $('[name="has_android_account"]');

            updateStore('android');
            androidAccount.off('change');
            androidAccount.on('change', function () {
                updateStore('android');
            });

        });
    </script>
    <style type="text/css">
        .publication-padding-bottom {
            margin-bottom: 120px;
        }
    </style>

</div>
