<?php

$application = $this->getApplication();

$pe_use_ads = false;
if ($this->isPe()) {
    $pe_use_ads = $application->getSubscription()->getSubscription()->getUseAds();
}

$ios_device = $application->getDevice(1);
$android_device = $application->getDevice(2);

$formGeneralInformation = new Application_Form_GeneralInformation();
$formGeneralInformation->populate($application->getData());

$formAdmob = new Application_Form_Admob();
$formAdmob->fill($application);

$formAppleGoogle = new Application_Form_AppleGoogle();
$formAppleGoogle->fill($application);

?>
<div class="page-content-wrapper">

    <?php echo $this->createPartialHtml(
        'subscription',
        'admin_view_default',
        'application/customization/publication/subscription.phtml'); ?>

    <div id="general-content"
         class="content sb-tour">
        <h3 class="title-editor border-green text-center">
            <?php echo __('General information'); ?>
        </h3>
        <div id="general"
             class="subcontent content-color">
            <div id="general-information"
                 class="container-fluid form-horizontal">
                <?php echo $formGeneralInformation; ?>
            </div>
        </div>
    </div>
    <?php if (!$application->getOwnerUseAds() AND !System_Model_Config::getValueFor("application_owner_use_ads") AND !$pe_use_ads): ?>

        <div id="monetize-content"
             class="content sb-tour">
            <h3 class="title-editor border-green text-center">
                <?php echo __('Monetize your app'); ?>
            </h3>
            <div class="monetize subcontent content-color">
                <div id="admob-settings"
                     class="container-fluid form-horizontal">
                    <?php echo $formAdmob; ?>
                </div>
            </div>
        </div>
    <?php endif; ?>

    <div id="apple-content"
         class="content sb-tour">
        <h3 class="title-editor border-green text-center">
            <?php echo __("Stores Informations"); ?>
        </h3>
        <div class="subcontent content-color">
            <div id="apple-google"
                 class="container-fluid form-horizontal">
                <?php echo $formAppleGoogle ?>
            </div>
        </div>
    </div>

    <div class="publication-padding-bottom">&nbsp;</div>
</div>
<script type="text/javascript">

    // Improvements
    $(document).ready(function () {
        bindForms('#general-information');
        bindForms('#admob-settings');
        bindForms('#apple-google');

        $('#android-element').addClass('col-md-6');
        $('#ios-element').addClass('col-md-6');
        $('#apple-element').addClass('col-md-6');
        $('#google-element').addClass('col-md-6');

        // Live update AppName!
        let appName = $('#name');

        appName.off('keyup');
        appName.on('keyup', function () {
            let name = $(this).val().replace(/(<([^>]+)>)/ig, '');
            // Set back stripped/value!
            $(this).val(name);
            $('#header_app_name').text(name.substr(0, 15));
        });

        let updateStore = function (store) {
            let value = $('[name="has_' + store + '_account"]:checked').val();

            let type = $('#warning_' + store);
            let email = $('#' + store + '_email');
            let password = $('#' + store + '_password');

            switch (value) {
                case '0':
                    type.parents('.sb-form-line').show();
                    email.parents('.sb-form-line').hide();
                    password.parents('.sb-form-line').hide();
                    break;
                case '1':
                    type.parents('.sb-form-line').hide();
                    email.parents('.sb-form-line').show();
                    password.parents('.sb-form-line').show();
                    break;
                case '2':
                    type.parents('.sb-form-line').hide();
                    email.parents('.sb-form-line').hide();
                    password.parents('.sb-form-line').hide();
                    break;
            }
        };

        let appleAccount = $('[name="has_apple_account"]');

        updateStore('apple');
        appleAccount.off('change');
        appleAccount.on('change', function () {
            updateStore('apple');
        });

        let androidAccount = $('[name="has_android_account"]');

        updateStore('android');
        androidAccount.off('change');
        androidAccount.on('change', function () {
            updateStore('android');
        });

    });
</script>
<style type="text/css">
    .publication-padding-bottom {
        margin-bottom: 120px;
    }
</style>