<div class="scrollable_content">

    <div class="list l7">
        <div ng-show="show_search && collection.length > 0" class="width-100" style="padding:5px">
            <input type="text" id="search" name="search" ng-model="search" placeholder="<?php echo $this->_("Search"); ?>" style="width: 95%;"/>
        </div>
        <ul>
            <li ng-repeat="item in collection | filter:search" ng-class="{first: $index == 0, has_picture: item.picture }" ng-hide="item.is_hidden">
                <a class="block" ng-click="showItem(item)">
                    <div class="left picture" image-src="item.picture" ng-if="item.picture" sb-image></div>
                    <div class="details padding" ng-class="{has_picture: item.picture}">
                        <h3 class="title">{{ item.title }}</h3>
                        <div class="date">{{ item.send_at }}</div>
                        <div class="clear"></div>
                    </div>
                </a>
            </li>
            <li class="empty" ng-if="!collection.length">
                <p class="a-center"><?php echo $this->_("Nothing to display"); ?></p>
            </li>
        </ul>
    </div>
</div>