# DO NOT MODIFY -- auto-generated by Apache Cordova

platform :ios, '10.0'

target 'AppsMobileCompany' do
	project 'AppsMobileCompany.xcodeproj'
	pod 'FirebaseMessaging', '~> 2.0.0'
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    end
  end
end