<?php $category = $this->getCategory(); ?>
<?php $products = array(); ?>
<div id="category_<?php echo $category->getId(); ?>" class="category inner_content container-fluid subcontent category-margin-bottom content-options content-white-bkg content-feature">
    <div class="row">
        <div class="col-md-12">
            <a class="pull-left sort_category"><i class="fa fa-sort"></i></a>
            <div class="pull-right"><a href="javascript:category.remove('<?php echo $category->getId(); ?>');" class="delete_category"><i class="fa fa-remove"></i></a></div>
        </div>
    </div>
    <div class="row first-row-feature">
        <div class="col-md-4">
            <div id="category_details_<?php echo $category->getId(); ?>" class="name">
                <input type="text" id="main_category_name_<?php echo $category->getId(); ?>" class="main_category_name input-flat" name="name" rel="<?php echo $category->getId(); ?>" value="<?php echo $category->getName(); ?>" />
                <input type="hidden" name="category_id" value="<?php echo $category->getId(); ?>" />
                <input type="hidden" name="value_id" value="<?php echo $this->getOptionValue()->getId(); ?>" />
            </div>
        </div>
        <div class="col-md-4">
            <div class="add_subcategory">
                <button type="button" onclick="subcategory.add(<?php echo $category->getId(); ?>);" class="btn color-blue"><?php echo $this->_('Sub-category'); ?></button>
            </div>
        </div>
    </div>
    <div class="subcategories row" <?php if($category->getChildren()->count() == 0) : ?> style="display:none;"<?php endif; ?>>
        <div class="col-md-12 first-row-feature">
            <ul id="subcategories_all_<?php echo $category->getId(); ?>" class="list-group">
                <li id="row_all_<?php echo $category->getId() ?>" class="subcategory list-group-item">
                    <div class="subcategory_actions">
                        <a class="label_subcategory_name" href="javascript:void(0);" parent_id="<?php echo $category->getId() ?>" category_id="all"><?php echo $this->_('All'); ?></a>
                    </div>
                </li>
            </ul>
            <ul id="subcategories_<?php echo $category->getId(); ?>" class="list-group content-white-bkg subcategories_list">
                <?php if($category->getChildren()->count() > 0) : ?>
                    <?php foreach($category->getChildren() as $child) : ?>
                        <?php echo $this->getLayout()
                            ->addPartial('subcategory_'.$child->getId(), 'admin_view_default', 'catalog/application/edit/category/subcategory.phtml')
                            ->setCategory($category)
                            ->setSubcategory($child)
                            ->setOptionValue($this->getOptionValue())
                            ->toHtml()
                        ;
                        ?>
                        <?php if($child->getProducts()) : ?>
                            <?php foreach($child->getProducts() as $product) $products[$product->getPosition()] = $product->setCategory($child); ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
            </ul>
        </div>
    </div>
    <?php foreach($category->getProducts() as $product) $products[$product->getPosition()] = $product->setCategory($category)->setIsUncategorized(true); ?>
    <div id="products_label" class="row" <?php if(!count($products) > 0) echo "style='display:none'" ?>>
        <div class="col-md-12">
            <?php echo $this->_("Products"); ?>
        </div>
    </div>
    <div class="products row">
        <div class="col-md-12">
            <ul id="category_products_<?php echo $category->getId() ?>" class="products_list list-group content-white-bkg">
                <?php if(count($products) > 0) : ?>
                    <?php ksort($products); ?>
                    <?php foreach($products as $product) : ?>
                        <?php echo $this->getLayout()
                            ->addPartial('product_'.$product->getId(), 'admin_view_default', 'catalog/application/edit/category/product.phtml')
                            ->setProduct($product)
                            ->setOptionValue($this->getOptionValue())
                            ->toHtml()
                        ;
                        ?>
                    <?php endforeach; ?>
                <?php endif; ?>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <a rel="<?php echo $category->getId(); ?>" parent_id="<?php echo $category->getId(); ?>" class="add_product btn color-blue" href="#"> <?php echo $this->_('Product'); ?></a>
        </div>
    </div>
</div>
<style>
    .category-margin-bottom{margin-bottom:5px;}
    .subcategories_list{margin-left:20px}
</style>