<?php echo $this->doctype() ?>
<html>
    <head>
        <title><?php echo __($this->getTitle()) ?></title>
        <?php foreach($this->getMetas() as $meta) : ?>
        <meta <?php echo $meta->getTag() ?>="<?php echo $meta->getKey(); ?>"
              content="<?php echo $meta->getContent(); ?>" />
        <?php endforeach ?>

        <?php foreach (Core_Model_Language::getLanguages() as $language) : ?>
        <?php if(Core_Model_Language::getCurrentLanguage() == $language->getCode()) continue;?>
        <link rel="alternate"
              href="<?php echo $this->getCurrentUrl(true, $language->getCode()); ?>"
              hreflang="<?php echo $language->getCode() ?>" />
        <?php endforeach ?>

        <?php echo $this->headLink() ?>

        <?php
            $favicon = __get("favicon_backoffice");
            if (!empty($favicon)) :
        ?>
            <link rel="shortcut icon"
                  type="image/png"
                  href="<?php echo $favicon ?>" />
        <?php else: ?>
            <link rel="icon"
                  type="image/png"
                  href="/favicon.png" />
            <link rel="shortcut icon"
                  id="favicon"
                  type="image/x-icon"
                  href="/favicon.ico" />
        <?php endif; ?>

        <?php $currentRelease = __get('current_release'); ?>

        <?php $base_url = str_replace($this->getRequest()->getPathInfo(), "", $this->getRequest()->getRequestUri()); ?>
        <?php if(stripos($base_url, "/") !== 0) $base_url = "/$base_url"; ?>
        <base href="<?php echo $base_url; ?>" />

        <?php
            $backofficeTheme = __get('backoffice_theme');
            switch ($backofficeTheme) {
                default:
                case 'default':
                    echo '<link href="/app/sae/design/desktop/backoffice/css/theme-default/styles.css?t=' . Siberian_Version::VERSION . '" 
                                    media="all" 
                                    data-style="backoffice_theme"
                                    rel="stylesheet" 
                                    type="text/css" />';
                    break;
                case 'modern':
                        echo '<link href="/app/sae/design/desktop/backoffice/css/theme-modern/styles.css?t=' . Siberian_Version::VERSION . '" 
                                    media="all" 
                                    data-style="backoffice_theme"
                                    rel="stylesheet" 
                                    type="text/css" />';
                    break;
                case 'elegance':
                    echo '<link href="/app/sae/design/desktop/backoffice/css/theme-elegance/styles.css?t=' . Siberian_Version::VERSION . '" 
                                    media="all" 
                                    data-style="backoffice_theme"
                                    rel="stylesheet" 
                                    type="text/css" />';
                    break;
            }
        ?>

        <link href="/app/local/design/desktop/backoffice/css/user-style.css?t=<?php echo $currentRelease ?>"
              media="all"
              rel="stylesheet"
              type="text/css" />

        <?php echo Siberian_Debug::renderHead(); ?>
    </head>
    <body class="<?php echo $this->default_class_name ?> general">

        <div ng-app="Siberian-Backoffice">
            <?php if (APPLICATION_ENV !== 'production'): ?>
                <div class="alert alert-warning development-responsive">
                    <i class="fa fa-exclamation-triangle"></i>
                    <span>
                        <?php echo __('You current working environment is'); ?>&nbsp;
                    </span>
                    <b><?php echo __('Development') ?></b>, <?php echo __('be careful or set it back to') ?>&nbsp;
                    <a href="/backoffice/advanced_configuration">
                        <i class="fa fa-external-link"></i>
                        <b><?php echo __('Production') ?></b>
                    </a>
                </div>
            <?php endif; ?>

            <div class="top">
                <?php echo $this->getPartialHtml('header') ?>
                <div class="message slide-down"
                     ng-show="message.is_visible"
                     ng-class="{error: message.is_error}">
                    <p ng-bind-html="message.text"></p>
                </div>
            </div>
            <?php echo $this->getPartialHtml('messages') ?>
            <?php echo $this->getPartialHtml('menu'); ?>
            <div>
                <div id="wrapper"
                     class="background"
                     ng-class="direction">
                    <div ng-view class="slide-view background"
                         ng-class="code"
                         ng-if="isLoggedIn"></div>
                    <sb-login-dialog class="scale-fade background"
                                     ng-if="!isLoggedIn"></sb-login-dialog>
                </div>

                <?php echo $this->getPartialHtml("templates"); ?>
            </div>

            <div class="footer">
                <?php echo $this->getPartialHtml('footer') ?>
            </div>

            <script type="text/ng-template" id="loginForm.html">
                <?php echo $this->getPartialHtml("login"); ?>
            </script>
        </div>
        <?php echo $this->headScript() ?>

        <script type="text/javascript">
            var BASE_URL = "<?php echo $base_url == "/" ? "" : $base_url; ?>";
            var ORIG_URL = "<?php echo $this->getRequest()->getRequestUri(); ?>";
            if(ORIG_URL.indexOf('/') !== 0) ORIG_URL = '/'+ORIG_URL;
            var IMAGE_PATH = "<?php echo $this->getImagePath(); ?>";
            App.factory("Label", function(Message) {
                var factory = {};

                factory.loading = {
                    success: "",
                    error: "<?php echo __("An error occurred while loading. Please, try again later."); ?>"
                };

                factory.save = {
                    success: "<?php echo __("Info successfully saved"); ?>",
                    error: "<?php echo __("An error occurred while saving. Please try again later."); ?>"
                };

                factory.uploader = {
                    error: {
                        type: {
                            zip: "<?php echo __("You can upload a zip archive only."); ?>",
                            pem: "<?php echo __("You can upload a pem certificate only."); ?>",
                            image: "<?php echo __("You can upload an image only (.jpg, .jpeg, .gif and .png)."); ?>",
                            icon: "<?php echo __("You can upload an icon only (.ico and .png)."); ?>",
                            png: "<?php echo __("You can upload a png only (.png)."); ?>"
                        },
                        only_one_at_a_time: "<?php echo addslashes(__("You can't upload more than one file at a time.")); ?>",
                        general: "<?php echo addslashes(__("An error occurred while uploading your file. Please, try again later.")); ?>"
                    }
                };

                factory.android = {
                    generating_apk: "<?php echo __("Your APK is being generated. Please come back in a few minutes."); ?>"
                };

                factory.admin = {
                    confirm_deletion: "<?php echo __("Are you sure you want to delete this admin?"); ?>"
                };

                return factory;
            });

            App.run(function($rootScope, AUTH_EVENTS, Auth) {
                Auth.user.id = "<?php echo $this->getSession()->getBackofficeUserId(); ?>";
                $rootScope.$broadcast(AUTH_EVENTS.loginSuccess);
            })
        </script>
    </body>
</html>
