<?php $platform_name = __get("platform_name"); ?>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6 hidden-xs login-left-side">
            <?php if(System_Model_Config::getValueFor("logo")): ?>
                <div class="logo_container">
                    <img src="<?php echo $this->getLogo(); ?>" id="logo" alt="<?php echo $platform_name; ?>" title="<?php echo $platform_name; ?>" width="100%" />
                </div>
            <?php else: ?>
                <div class="logo_container">
                    <img src="<?php echo $this->getImage('login/default-logo.png'); ?>" id="logo" alt="<?php echo $platform_name; ?>" title="<?php echo $platform_name; ?>" width="100%" />
                </div>
            <?php endif; ?>
        </div>
        <div class="col-sm-6 col-xs-12 login-right-side">

            <ul class="nav navbar-nav navbar-right"
                id="ul_languages">
                <?php echo $this->getPartialHtml('languages'); ?>
            </ul>

            <div id="login_container">

                <h1 class="text-center"><?php echo $platform_name; ?></h1>
                <?php if($platform_name): ?>
                    <hr/>
                <?php endif; ?>
                <ul id="nav-login" class="nav nav-tabs" role="tablist">
                    <li style="width:50%" class="text-center active"><a href="#" rel="login"><?php echo __("Log in"); ?></a></li>
                </ul>
                <div class="subcontent">
                    <form action="<?php echo $this->getUrl('admin/account/loginpost') ?>" method="post" id="loginForm" class="form-horizontal">
                        <div class="form-group">
                            <div class="col-md-12">
                                <label for="email"><?php echo __("Email"); ?></label>
                                <input type="text" id="email" class="input-flat email" name="email" placeholder="<?php echo __("Email"); ?>" />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <label for="password"><?php echo __("Password"); ?></label>
                                <input type="password" id="password" class="input-flat" name="password" placeholder="<?php echo __("Password"); ?>" />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12 text-right">
                                <button type="submit" class="color-blue btn"><?php echo __('Log in'); ?></button>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12 text-right">
                                <a href="javascript:void(0);" id="btnForgotPassword"><?php echo __('Forgot your password ?'); ?></a>
                            </div>
                        </div>
                    </form>

                    <form action="<?php echo $this->getUrl('admin/account/forgotpasswordpost') ?>" method="post" id="forgotpasswordForm" style="display:none" class="form-horizontal">
                        <div class="form-group">
                            <div class="col-md-12">
                                <p><?php echo __('Forgot your password? Don\'t worry! Simply enter your email address and we\'ll send you a new one right now.'); ?></p>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <label for="email"><?php echo __("Email"); ?></label>
                                <input type="text" id="email" class="input-flat email" name="email" placeholder="<?php echo __("Email"); ?>" />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-6">
                                <button type="button" id="btnBackForgotPassword" class="color-blue btn"><?php echo __("Back"); ?></button>
                            </div>
                            <div class="col-xs-6 text-right">
                                <button type="submit" class="color-blue btn"><?php echo __('Send'); ?></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>

</div>
    <script type="text/javascript">
        $('#loginForm').submit(function() {
            if(!$(this).valid()) return false;
        });

        $('#forgotpasswordForm').submit(function() {
            if(!$(this).valid()) return false;

        });

        $('#btnForgotPassword').click(function() {
            $('#loginForm').hide();
            $('#forgotpasswordForm').fadeIn();
        });

        $('#btnBackForgotPassword').click(function() {
            $('#forgotpasswordForm').hide();
            $('#loginForm').fadeIn();
        });
    </script>

</div>

<script type="text/javascript">
    login_urls = {
        checklogin_post: '<?php echo $this->getUrl('admin/account/check'); ?>',
        signin_post: '<?php echo $this->getUrl('admin/account/loginpost'); ?>',
        signup_post: '<?php echo $this->getUrl('admin/account/signuppost'); ?>',
        forgotpassword_post: '<?php echo $this->getUrl('admin/account/forgotpasswordpost'); ?>'
    };

    $('#nav-login a').click(function() {
        if($(this).hasClass("active")) return false;
        if($(this).attr("rel") == "login") {
            $('#signupForm').hide();
            $('#forgotpasswordForm').hide();
            $('#loginForm').fadeIn();
        } else {
            $('#forgotpasswordForm').hide();
            $('#loginForm').hide();
            $('#signupForm').fadeIn();
        }

        $("#nav-login li").removeClass("active");
        $(this).parent("li").addClass("active");
    });
    
</script>

<style>
    .login-left-side {
        background-color: #ffffff;
        width: 50vw;
        height: 100vh;
        position: absolute;
        top: 0;
        left: 0;
    }

    .login-right-side {
        background-color: #0099c7;
        width: 50vw;
        height: 100vh;
        position: absolute;
        top: 0;
        left: 50vw;
        display: flex;
        align-items: center;
    }

    #login_container {
        width: 50%;
        min-width: 400px;
        padding: 20px;
        color: #ffffff;
    }

    label {
        color: #ffffff !important;
    }

    input#email_signup {
        position: absolute;
        left: -50000px;
        top: -50000px;
    }

    .admin_account_login .logo_container {
        text-align: right;
        margin-top: calc(50vh - 43px);
    }

    .admin_account_login .logo_container #logo {
        height: 85px;
        width: auto;
    }

    .color-blue {
        background-color: #ffffff !important;
        color: #303030 !important;
    }

    .btn {
        border-radius: 4px !important;
        border: 0 !important;
    }
    .btn:hover {
        background-color: #ffb564 !important;
        border: 0 !important;
    }

    #ul_languages {
        position: absolute;
        top: 20px;
        right: 20px;
        font-size: 16px;
        padding: 10px;
    }

    #dLabel {
        padding: 10px !important;
        background-color: #ff8d15;
    }

    .open #dLabel {
        background-color: #ffffff;
        color: #303030 !important;
    }

    .navbar-nav > li > .dropdown-menu {
        margin-top: -3px;
        border: 0;
        margin-right: 0;
        border-radius: 4px;
        box-shadow: none;
        padding: 20px 0;
    }

    .nav-tabs {
        border: 0;
    }

    .nav-tabs > li {
        float: left;
        margin: 0;
    }

    .nav-tabs > li.active {
        background-color: #ff8d15;
        border-radius: 2px 2px 0 0 !important;
    }

    .nav-tabs > li > a,
    .nav-tabs > li > a:hover,
    .nav-tabs > li > a:focus {
        margin: 0;
        border-radius: 2px 2px 0 0 !important;
        border: 0;
        font-weight: bold;
        letter-spacing: 2px;
    }

    .nav-tabs > li.active > a,
    .nav-tabs > li.active > a:hover,
    .nav-tabs > li.active > a:focus {
        background-color: transparent !important;
        color: #ffffff;
        border-radius: 2px 2px 0 0 !important;
        border: 0;
        font-weight: bold;
        letter-spacing: 2px;
    }

    .nav-tabs > li > a:hover {
        background-color: #ff8d15 !important;
        color: #303030;
    }

    .subcontent {
        background-color: #ff8d15;
        padding: 15px 15px 5px 15px;
        border-radius: 0 0 4px 4px;
        margin-top: -2px;
    }
</style>
