<div class="application">
    <div class="application_content inner_content">
        <div class="title">
            <i class="left icon-remove-sign"></i>
            <h2 class="left inner_content f-rounded"><?php echo $this->_('404, page not found') ?></h2>
            <div class="clear"></div>
            <hr />
        </div>
        <div class="area">
            <br />
            <div>
                <p><?php echo $this->_('Ouch, this page doesn\'t exist') ?></p>
            </div>
        </div>
    </div>
</div>