<p>
    <?php echo __('The APK for the application %s has been generated !', $this->getApplicationName()); ?>
</p>
<table border="0"
       cellpadding="0"
       cellspacing="0"
       class="btn btn-primary">
    <tbody>
    <tr>
        <td align="left">
            <table border="0"
                   cellpadding="0"
                   cellspacing="0">
                <tbody>
                <tr>
                    <td>
                        <a href="<?php echo $this->getLink() ?>"
                           target="_blank">
                            <?php echo __('Download the APK') ?>
                        </a>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>
    </tbody>
</table>