<?php

use Siberian\Json;

$optionValue = $this->getOptionValue();
$formSettings = new Customer_Form_Settings();
$formSettings->setValueId($optionValue->getId());

try {
    $settings = Json::decode($optionValue->getSettings());
    $formSettings->populate($settings);
} catch (\Exception $e) {
    // Defaults!
    $formSettings->populate(
        [
            'design' => 'list',
            'enable_facebook_login' => true,
            'enable_registration' => true,
            'enable_commercial_agreement' => true,
            'enable_commercial_agreement_label' => '',
            'enable_password_verification' => false,
        ]
    );
}

?>

<div id="customer_account">

    <!-- Nav tabs -->
    <ul class="nav nav-tabs"
        role="tablist">
        <li role="presentation"
            class="active">
            <a href="#settings"
               aria-controls="settings"
               role="tab"
               data-toggle="tab">
                <i class="fa fa-folder-open-o"></i>
                <?php echo __('Settings') ?>
            </a>
        </li>
        <li role="presentation">
            <a href="#tab_design"
               aria-controls="tab_design"
               role="tab"
               data-toggle="tab">
                <i class="fa fa-pencil"></i>
                <?php echo __('Design') ?>
            </a>
        </li>
    </ul>

    <div class="tab-content">
        <!-- START SETTINGS TAB -->
        <div role="tabpanel"
             class="tab-pane active"
             id="settings">
            <div class="feature-block-add">
                <h3 class="title-editor no-border-radius title-feature-indent">
                    <?php echo __('Settings'); ?>
                </h3>
                <div class="container-fluid subcontent content-feature">
                    <?php echo $formSettings; ?>
                </div>
            </div>
        </div>
        <!-- /END SETTINGS TAB -->

        <!-- START DESIGN TAB -->
        <div role="tabpanel"
             class="tab-pane"
             id="tab_design">
            <?php echo $this->importLayout($optionValue, false); ?>

            <?php echo $this->importBackground($optionValue, false); ?>
        </div>
        <!-- /END DESIGN TAB -->

    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        bindForms("#tab_design");
        bindForms("#settings");

        let commercialTick = $('#enable_commercial_agreement');
        let commercialLabel = $('#enable_commercial_agreement_label');

        let toggleCommercialLabel = function () {
            if (commercialTick.is(':checked')) {
                commercialLabel.parents('.sb-form-line').show();
            } else {
                commercialLabel.parents('.sb-form-line').hide();
            }
        };

        commercialTick.off('change');
        commercialTick.on('change', toggleCommercialLabel);

        toggleCommercialLabel();
    });
</script>

<style type="text/css">
    #customer_account #tab_design .change_layout_handler img {
        max-height: 210px;
    }
</style>
