<?php

use Siberian\Json;

$application = $this->getApplication();
$optionValue = $this->getOptionValue();
$formSettings = new Customer_Form_Settings();
$formSettings->setValueId($optionValue->getId());

try {
    $settings = Json::decode($optionValue->getSettings());
    $formSettings->populate($settings);
} catch (\Exception $e) {
    // Defaults!
    $formSettings->populate(
        [
            'design' => 'list',
            'enable_facebook_login' => true,
            'enable_registration' => true,
            'enable_commercial_agreement' => true,
            'enable_commercial_agreement_label' => '',
            'enable_password_verification' => false,
        ]
    );
}

$formSettings->setOverrides($application);

?>

<div id="customer_account">

    <!-- Nav tabs -->
    <ul class="nav nav-tabs"
        role="tablist">
        <li role="presentation"
            class="active">
            <a href="#settings"
               aria-controls="settings"
               role="tab"
               data-toggle="tab">
                <i class="fa fa-folder-open-o"></i>
                <?php echo __('Settings') ?>
            </a>
        </li>
        <li role="presentation">
            <a href="#tab_design"
               aria-controls="tab_design"
               role="tab"
               data-toggle="tab">
                <i class="fa fa-pencil"></i>
                <?php echo __('Design') ?>
            </a>
        </li>
    </ul>

    <div class="tab-content">
        <!-- START SETTINGS TAB -->
        <div role="tabpanel"
             class="tab-pane active"
             id="settings">
            <div class="feature-block-add">
                <h3 class="title-editor no-border-radius title-feature-indent">
                    <?php echo __('Settings'); ?>
                </h3>
                <div class="container-fluid subcontent content-feature">
                    <?php echo $formSettings; ?>
                </div>
            </div>
        </div>
        <!-- /END SETTINGS TAB -->

        <!-- START DESIGN TAB -->
        <div role="tabpanel"
             class="tab-pane"
             id="tab_design">
            <?php echo $this->importLayout($optionValue, false); ?>

            <?php echo $this->importBackground($optionValue, false); ?>
        </div>
        <!-- /END DESIGN TAB -->

    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        bindForms("#tab_design");
        bindForms("#settings");

        let commercialTick = $('#enable_commercial_agreement');
        let commercialLabel = $('#enable_commercial_agreement_label');

        let toggleCommercialLabel = function () {
            if (commercialTick.is(':checked')) {
                commercialLabel.parents('.sb-form-line').show();
            } else {
                commercialLabel.parents('.sb-form-line').hide();
            }
        };

        commercialTick.off('change');
        commercialTick.on('change', toggleCommercialLabel);

        toggleCommercialLabel();

        let fieldCiv = $('#extra_civility');
        let requiredCiv = $('#extra_civility_required');

        let fieldMobile = $('#extra_mobile');
        let requiredMobile = $('#extra_mobile_required');

        let fieldBirthdate = $('#extra_birthdate');
        let requiredBirthdate = $('#extra_birthdate_required');

        let fieldNickname = $('#extra_nickname');
        let requiredNickname = $('#extra_nickname_required');

        // Check civility field if required!
        let checkCivIfRequired = function () {
            if (requiredCiv.is(':checked')) {
                fieldCiv.prop('checked', true);
            }
        };
        requiredCiv.off('change');
        requiredCiv.on('change', checkCivIfRequired);

        // Uncheck civility required field if disabled!
        let toggleFieldCiv = function () {
            if (!fieldCiv.is(':checked')) {
                requiredCiv.prop('checked', false);
            }
        };
        fieldCiv.off('change');
        fieldCiv.on('change', toggleFieldCiv);

        // Check mobile field if required!
        let toggleMobile = function () {
            if (requiredMobile.is(':checked')) {
                fieldMobile.prop('checked', true);
            }
        };
        requiredMobile.off('change');
        requiredMobile.on('change', toggleMobile);

        // Uncheck mobile required field if disabled!
        let toggleFieldMobile = function () {
            if (!fieldMobile.is(':checked')) {
                requiredMobile.prop('checked', false);
            }
        };
        fieldMobile.off('change');
        fieldMobile.on('change', toggleFieldMobile);

        // Check mobile field if required!
        let toggleBirthdate = function () {
            if (requiredBirthdate.is(':checked')) {
                fieldBirthdate.prop('checked', true);
            }
        };
        requiredBirthdate.off('change');
        requiredBirthdate.on('change', toggleBirthdate);

        // Uncheck mobile required field if disabled!
        let toggleFieldBirthdate = function () {
            if (!fieldBirthdate.is(':checked')) {
                requiredBirthdate.prop('checked', false);
            }
        };
        fieldBirthdate.off('change');
        fieldBirthdate.on('change', toggleFieldBirthdate);

        // Check nickname field if required!
        let toggleNickname = function () {
            if (requiredNickname.is(':checked')) {
                fieldNickname.prop('checked', true);
            }
        };
        requiredNickname.off('change');
        requiredNickname.on('change', toggleNickname);

        // Uncheck nickname required field if disabled!
        let toggleFieldNickname = function () {
            if (!fieldNickname.is(':checked')) {
                requiredNickname.prop('checked', false);
            }
        };
        fieldNickname.off('change');
        fieldNickname.on('change', toggleFieldNickname);


    });
</script>

<style type="text/css">
    #customer_account #tab_design .change_layout_handler img {
        max-height: 210px;
    }
</style>
