<sb-section title="'<?php echo __title("People who are allowed to access the backoffice"); ?>'"
            button="button">
    <br />
    <div class="form-group">
        <label for="filter"><?php echo __("Search"); ?></label>
        <input type="text"
               id="filter"
               class="form-control"
               ng-model="filter"
               placeholder="<?php echo __("Search"); ?>" />
    </div>
    <br />
    <table class="table">
        <col width="5%" />
        <col width="55%" />
        <col width="20%" />
        <col width="20%" />
        <thead>
            <tr>
                <th class="pointer"
                    ng-click="order = 'id'; by = !by"><?php echo $this->_("Id"); ?></th>
                <th class="pointer"
                    ng-click="order = 'email'; by = !by"><?php echo $this->_("Email"); ?></th>
                <th class="pointer"
                    ng-click="order = 'created_at'; by = !by"><?php echo $this->_("Created at"); ?></th>
                <th><?php echo $this->_("Actions"); ?></th>
            </tr>
        </thead>
        <tbody>
            <tr class="slide-left"
                ng-repeat="user in users | filter:filter | orderBy:order:by">
                <td>{{ user.id }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.created_at }}</td>
                <td class="text-right">
                    <sb-loader is_visible="user.loader_is_visible"
                               type="'inner_content'"
                               size="'tiny'"></sb-loader>
                    <a href="<?php echo $this->getUrl("backoffice/account_view/index"); ?>/user_id/{{ user.id }}"
                       ng-show="!user.loader_is_visible"
                       class="btn btn-sm btn-primary">EDIT</a>
                    <a href="javascript:void(0);"
                       ng-show="!user.loader_is_visible"
                       ng-click="delete(user)"
                       class="btn btn-sm btn-danger">DELETE</a>
                </td>
            </tr>
        </tbody>
    </table>

    <style type="text/css">
        .btn-sm {
            padding: 1px 5px !important;
            font-size: 11px !important;
            line-height: 1.4 !important;
            font-weight: bold;
            border: 0 !important;
        }

        a.btn-sm,
        a.btn-sm:hover {
            text-decoration: none !important;
        }
    </style>
</sb-section>