<?php
$application = $this->getApplication();
$optionValue = $this->getOptionValue();

$page = new Cms_Model_Application_Page();
$pages = $page->findAllOrderedByRank($optionValue->getId());
$places_order = !$optionValue->getMetadataValue("places_order");

$deleteForm = new Places_Form_Place_Delete();
$deleteForm->setValueId($optionValue->getId());

$appKey = $application->getGooglemapsKey();
$appGmapsKey = $application->getGooglemapsKey();

$settingsForm = new Places_Form_Settings();

$settings = $optionValue->getSettings();
try {
    $settingsForm->populate(\Siberian_Json::decode($settings));
} catch (\Exception $e) {
    // Do not populate, json is not valid
}
$settingsForm->setValueId($optionValue->getId());


$formCategory = new Places_Form_Category();
$formCategory->setValueId($optionValue->getId());

$categories = (new Places_Model_Category())
    ->findAll(['value_id' => $optionValue->getId()], 'position ASC');

$deleteCategoryForm = new Places_Form_Category_Delete();
$deleteCategoryForm->setValueId($optionValue->getId());

?>


<div class="places-new">

    <?php if (empty($appKey)): ?>
        <div class="alert alert-danger">
            <?php echo __("You must set a Google Maps API Key in %s in order to use this feature.",
                "<b>".__("Settings")." > ".__("API")."</b>") ?>
        </div>
    <?php endif; ?>

    <?php if ($this->getMustUpdate()): ?>
        <div class="alert alert-success">
            <?php echo __("Places upgrade! New version with a better search engine, categories & display options.") ?>
            <hr />
            <?php echo __("What's new?") ?>
            <br />
            - <?php echo __("Addresses blocks can now have a website & a phone number.") ?>
            <br />
            - <?php echo __("A place can belong to multiple categories.") ?>

            <hr />
            <?php echo __("What will the full upgrade do?") ?>
            <br />
            - <?php echo __("Tags will be de-duplicated, migrated to categories & associated to existing places.") ?>
            <br />
            - <?php echo __("Existing tags will be copied in the `tag` field, which are now used to improve the full-text search.") ?>

            <br />
            <br />
            <button class="btn color-blue pull-right place-upgrade"><?php echo __("Proceed to full ugrade!") ?></button>

            <div style="clear:both;"></div>
        </div>

        <div class="alert alert-warning">
            <?php echo __("What if I choose the minimal upgrade?") ?>
            <br />
            - <?php echo __("Only tags will be copied in the `tag` field, which are now used to improve the full-text search.") ?>
            <br />
            <button class="btn color-red pull-right place-skip"><?php echo __("Ok, proceed to minimal upgrade!") ?></button>

            <div style="clear:both;"></div>
        </div>
    <?php endif; ?>

    <!-- Nav tabs -->
    <ul class="nav nav-tabs"
        role="tablist">
        <li role="presentation"
            class="active">
            <a href="#places"
               aria-controls="places"
               role="tab"
               data-toggle="tab">
                <i class="fa fa-map-marker"></i>
                <?php echo __('Places') ?>
            </a>
        </li>
        <li role="presentation">
            <a href="#new_category"
               aria-controls="new_category"
               role="tab"
               data-toggle="tab">
                <i class="fa fa-tags"></i>
                <?php echo __('Categories') ?>
            </a>
        </li>
        <li role="presentation">
            <a href="#search"
               aria-controls="search"
               role="tab"
               data-toggle="tab">
                <i class="fa fa-search"></i>
                <?php echo __('Settings & Options') ?>
            </a>
        </li>
        <li role="presentation">
            <a href="#design"
               aria-controls="design"
               role="tab"
               data-toggle="tab">
                <i class="fa fa-image"></i>
                <?php echo __('Design') ?>
            </a>
        </li>
    </ul>

    <div class="tab-content">
        <div role="tabpanel"
             class="tab-pane active"
             id="places">

            <div class="feature-block-add"
                 rel="places">
                <h3 class="title-editor no-border-radius title-feature-indent">
                    <?php echo __("Add place"); ?>
                    <button type="button"
                            rel="places"
                            class="feature-toggle-add toggle_design color-blue pull-right bt-header-right btn">
                        <i class="fa fa-plus"></i>
                    </button>
                </h3>
            </div>

            <div class="feature-block-create"
                 rel="places">
                <h3 class="title-editor no-border-radius title-feature-indent">
                    <span class="cms-title-create">
                        <?php echo __("Create a place"); ?>
                    </span>
                    <span class="cms-title-edit"
                          style="display :none;">
                        <?php echo __("Edit place"); ?>
                    </span>
                </h3>

                <span id="new_place"
                      class="cms-form-placeholder">
                    <!-- Here goes the Loaded form (Create/Edit) -->
                </span>
            </div>


            <?php if (count($pages) > 0): ?>
                <div id="places_list"
                     class="feature-block-list">
                    <div class="margin-top">
                        <h3 class="title-editor no-border-radius title-feature-indent">
                            <?php echo __("Manage"); ?>
                            <button type="button"
                                    class="toggle_design color-blue pull-right bt-header-right btn feature-toggle-items">
                                <i class="fa fa-angle-down"></i>
                            </button>
                        </h3>
                        <div class="container-fluid first-row-feature content-feature feature-manage-items">
                            <table class="table content-white-bkg sb-pager table-places">
                                <thead>
                                <tr class="border-grey">
                                    <th style="width:40px;"></th>
                                    <th class="sortable"
                                        style="width:30%;"><?php echo __("Title"); ?></th>
                                    <th class="sortable"
                                        style="width:65%;"><?php echo __("Subtitle"); ?></th>
                                    <th></th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach($pages as $place) : ?>
                                    <tr id="place_manage_element_<?php echo $place->getId(); ?>"
                                        class="place-manage-element sb-pager">
                                        <td>
                                            <?php if(!empty($place->getPicture())): ?>
                                                <img src="/images/application<?php echo $place->getPicture(); ?>"
                                                     style="width: 26px; height: 16px;" />
                                            <?php else: ?>
                                                <img src="/app/sae/design/desktop/flat/images/flat/default-place.png"
                                                     style="width: 26px; height: 16px;" />
                                            <?php endif; ?>
                                        </td>
                                        <td><?php echo $place->getTitle(); ?></td>
                                        <td><?php echo cut(html_entity_decode($place->getContent()), 60); ?></td>
                                        <td class="edit-action open-edit"
                                            rel="places"
                                            data-placeid="<?php echo $place->getId(); ?>">
                                            <i class="fa fa-pencil"></i>
                                        </td>
                                        <td class="delete-action">
                                            <?php
                                                $deleteForm->setAttrib('data-rowid', 'place_manage_element_' . $place->getId());
                                                $deleteForm->setAttrib('id', 'form-place-id-' . $place->getId());
                                                $deleteForm->getElement('id')->setValue($place->getId());
                                                $deleteForm->getElement('option_value_id')->setValue($optionValue->getId());

                                                echo $deleteForm;
                                            ?>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            <?php endif; ?>


        </div>

        <div role="tabpanel"
             class="tab-pane"
             id="new_category">

            <div class="feature-block-add">
                <h3 class="title-editor no-border-radius title-feature-indent">
                    <?php echo __('Add category'); ?>
                    <button type="button" class="feature-toggle-add toggle_design color-blue pull-right bt-header-right btn">
                        <i class="fa fa-plus"></i>
                    </button>
                </h3>
            </div>

            <div class="feature-block-create">
                <h3 class="title-editor no-border-radius title-feature-indent">
                    <?php echo __('Create a new category'); ?>
                </h3>
                <div class="container-fluid subcontent content-feature">
                    <?php echo $formCategory; ?>
                </div>
            </div>

            <?php if (count($categories) > 0): ?>
                <div class="feature-block-list">
                    <div class="margin-top">
                        <h3 class="title-editor no-border-radius title-feature-indent">
                            <?php echo __("Manage"); ?>
                            <button type="button"
                                    class="toggle_design color-blue pull-right bt-header-right btn feature-toggle-items">
                                <i class="fa fa-angle-down"></i>
                            </button>
                        </h3>
                        <div class="container-fluid first-row-feature content-feature feature-manage-items">
                            <table id="table_places_list"
                                   class="table content-white-bkg sb-pager table-categories">
                                <thead>
                                    <tr class="border-grey">
                                        <th style="width:32px;"></th>
                                        <th style="width:5%"><?php echo __("Picture") ?></th>
                                        <th style="width:45%"><?php echo __("Name") ?></th>
                                        <th style="width:45%;"><?php echo __("Position") ?></th>
                                        <th></th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody class="categories-sortable">
                                <?php foreach ($categories as $category) : ?>
                                    <tr id="category_manage_element_<?php echo $category->getId(); ?>"
                                        rel="<?php echo $category->getId(); ?>"
                                        class="category-manage-element sb-pager category-container">
                                        <td class="category-handle" style="text-align: center;">
                                            <i class="fa fa-sort"
                                               style="margin-top: 20px;"></i>
                                        </td>
                                        <td>
                                            <?php if (!empty($category->getPicture())): ?>
                                            <img src="/images/application<?php echo $category->getPicture() ?>"
                                                 style="height:64px;" />
                                            <?php else: ?>
                                            <img src="/var/apps/overview/img/placeholder/blank-512.png"
                                                 style="height:64px;" />
                                            <?php endif; ?>
                                        </td>
                                        <td>
                                            <h5 style="font-weight: bold;"><?php echo $category->getTitle() ?></h5>
                                            <p><?php echo $category->getSubtitle() ?></p>
                                        </td>
                                        <td class="category-position"><?php echo $category->getPosition() ?></td>
                                        <td class="edit-action open-edit"
                                            data-id="category_<?php echo $category->getId(); ?>"
                                            data-form-url="<?php echo __path('/places/application/load-category-form', [
                                                'category_id' => $category->getId(),
                                                'value_id' => $optionValue->getId()
                                            ]); ?>">
                                            <i class="fa fa-pencil"></i>
                                        </td>
                                        <td class="delete-action">
                                            <?php
                                            $deleteCategoryForm->setAttrib('data-rowid', 'category_manage_element_' . $category->getId());
                                            $deleteCategoryForm->setAttrib('id', 'form-category-id-' . $category->getId());
                                            $deleteCategoryForm->getElement('category_id')->setValue($category->getId());

                                            echo $deleteCategoryForm;
                                            ?>
                                        </td>
                                    </tr>
                                    <tr class="edit-form"
                                        data-id="category_<?php echo $category->getId(); ?>"
                                        style="display: none;">
                                        <td colspan="6">
                                            <p class="close-edit"
                                               data-id="category_<?php echo $category->getId(); ?>">
                                                <i class="fa fa-times"></i><?php echo __("Close") ?>
                                            </p>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            <?php endif; ?>

        </div>

        <div role="tabpanel"
             class="tab-pane"
             id="search">
            <div>
                <h3 class="title-editor title-feature-indent">
                    <?php echo __("Settings & Options"); ?>
                </h3>
            </div>
            <div class="container-fluid subcontent content-feature">
                <?php echo $settingsForm; ?>
            </div>
        </div>

        <div role="tabpanel"
             class="tab-pane"
             id="design">
            <?php echo $this->importBackground($optionValue, false, false); ?>
        </div>

    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        // Location settings
        let address = $("#address");
        let latitude = $("#lat");
        let longitude = $("#lng");

        window.initMap = function () {
            let searchBox = new google.maps.places.SearchBox(address.get(0));
            address.data('search_box', searchBox);
            google.maps.event.addListener(searchBox, 'places_changed', function () {
                let places = address.data("search_box").getPlaces();
                if (places) {
                    let place = places[0];
                    latitude.val(place.geometry.location.lat());
                    longitude.val(place.geometry.location.lng());
                }
            });
        };

        if (!$("#gmaps_libraries").length) {
            let scriptTag = document.createElement('script');
            scriptTag.setAttribute('id', 'gmaps_libraries');
            scriptTag.setAttribute('type', 'text/javascript');
            scriptTag.setAttribute('src', 'https://maps.google.com/maps/api/js?callback=window.initMap&sensor=false&libraries=places&key=<?php echo $appGmapsKey; ?>');
            (document.getElementsByTagName('head')[0] || document.documentElement).appendChild(scriptTag);
        } else {
            window.initMap();
        }

        $(".feature-toggle-add[rel='places'], .edit-action[rel='places']").on("click", function(event) {
            event.preventDefault();

            let formurl = "<?php echo $this->getUrl("/places/application/loadform") ?>";
            let datas = {value_id: <?php echo $optionValue->getId() ?>};
            let el = $(this);
            if (el.hasClass("edit-action")) {
                datas = {value_id: <?php echo $optionValue->getId() ?>, place_id: el.attr("data-placeid")}
            }

            loader.show("sb-features");

            $(".cms-form-placeholder").html("");

            $.ajax({
                url: formurl,
                method: "POST",
                dataType: "json",
                data: datas,
                success: function(data) {
                    if(data.success && data.form) {

                        $(".cms-form-placeholder").append(data.form);
                        $(".feature-block-create[rel='places']").show();
                        $(".feature-block-add[rel='places']").hide();
                        bindForms("#form-cms");

                        $("#form-cms input#tags").tagsinput({
                            confirmKeys: [13, 188],
                            tagClass: "color-blue label"
                        });

                        $(".bootstrap-tagsinput input").on('keypress', function(e){
                            if (e.keyCode == 13) {
                                e.keyCode = 188;
                                e.preventDefault();
                            }
                        });

                        $(".bootstrap-tagsinput").addClass("input-flat");

                    } else if(data.error) {
                        handleFormError(form, data);
                    }

                    loader.hide("sb-features");
                },
                error: function(data) {
                    let response = $.parseJSON(data.responseText);
                    if (response.message !== "") {
                        handleFormError(form, response);
                    } else {
                        feature_form_error("An error occured, please try again.");
                    }

                    loader.hide("sb-features");
                }
            });

            return false;
        });

        $("table.sb-pager.table-places").sbpager({
            with_search: true,
            search_placeholder: "<?php echo __("Search ...") ?>",
            callback_goto_page: function() {
                $("table.sb-pager tr.edit-form[data-id]").hide()
            }
        });

        $("table.sb-pager.table-categories").sbpager({
            with_search: true,
            items_per_page: 1000,
            search_placeholder: "<?php echo __("Search ...") ?>",
            callback_goto_page: function() {
                $("table.sb-pager tr.edit-form[data-id]").hide()
            }
        });

        // Sections
        $('.categories-sortable').sortable({
            handle: ".category-handle",
            axis: "y",
            items: " .category-container",
            opacity: 0.7,
            start: function() {
                // Clear all forms inside elements!

                $("#categories .close-edit").trigger("click");
            },
            stop: function() {
                let sections = $('.categories-sortable tr[rel]');
                let data = {
                    indexes: []
                };
                let index = 1;
                sections.each(function() {
                    let el = $(this);
                    data.indexes.push(el.attr('rel'));

                    el.find('.category-position').text(index++);
                });

                formget(
                    '/places/application/update-category-positions',
                    data,
                    function(result) {},
                    function(result) {}
                );
            }
        });

        // Continue until it's done
        let loopCount = 0;
        let loopLimit = 10;
        let updatePlaces = function (skip) {
            let url = '/places/application/update-places';
            if (skip) {
                url = '/places/application/skip-update';
            }

            formget(
                url,
                {
                    value_id: '<?php echo $optionValue->getId() ?>'
                },
                function() {
                    swal({
                        title: '<?php echo __jss('Success') ?>',
                        text: '<?php echo __jss('Your places are now up-to-date.') ?>',
                        animation: 'none'
                    }, function () {
                        swal.close();
                        page.reload();
                    });
                },
                function() {
                    updatePlaces(skip);
                    loopCount++;
                    if (loopCount > loopLimit) {
                        swal({
                            title: '<?php echo __jss('Error') ?>',
                            text: '<?php echo __jss('Please try again, something did break during the upgrade!') ?>',
                            animation: 'none'
                        }, function () {
                            swal.close();
                            page.reload();
                        });
                    }
                },
                false);
        };

        let updatePin = function () {
            let val = $("#defaultPin").val();
            let url = '/places/application/update-pins';

            formget(
                url,
                {
                    value_id: '<?php echo $optionValue->getId() ?>',
                    pinValue: val
                },
                function() {
                    swal({
                        title: '<?php echo __jss("Success") ?>',
                        text: '<?php echo __jss("Your pin settings are applied.") ?>',
                        animation: 'none'
                    }, function () {
                        swal.close();
                        page.reload();
                    });
                },
                false);
        };

        // Upgrade / Skip
        let placeUpgrade = $(".place-upgrade");
        placeUpgrade.off("click");
        placeUpgrade.on("click", function () {
            swal({
                title: '<?php echo __jss("Please wait") ?>',
                html: true,
                text: '<?php echo __jss("Upgrade can take a while depending on the places count!") ?><br /><?php echo __jss("Please wait until the page reloads!") ?>',
                showConfirmButton: false,
                animation: 'none'
            });
            updatePlaces(false);
        });

        let placeSkip = $(".place-skip");
        placeSkip.off("click");
        placeSkip.on("click", function () {
            swal({
                title: '<?php echo __jss('Please wait') ?>',
                html: true,
                text: '<?php echo __jss('Migrating tags can take a while depending on the places count!') ?><br /><?php echo __jss("Please wait until the page reloads!") ?>',
                showConfirmButton: false,
                animation: 'none'
            });
            updatePlaces(true);
        });

        // Upgrade / Skip
        let applyPin = $(".apply-default-pin");
        applyPin.off("click");
        applyPin.on("click", function () {
            swal({
                title: '<?php echo __jss("Please wait") ?>',
                html: true,
                text: '<?php echo __jss("Upgrade can take a while depending on the places count!") ?><br /><?php echo __jss("Please wait until the page reloads!") ?>',
                showConfirmButton: false,
                animation: 'none'
            });
            updatePin(false);
        });

        bindForms('#search');
        bindForms('#design');
        bindForms('#new_place');
        bindForms('#new_category');
        bindForms('#places_list');
    });
</script>
