<?php $application = $this->getApplication(); ?>
<?php $value = $this->getOptionValue(); ?>

<div class="subcontent color-content content-feature container-fluid"
     id="search_editor">
    <form method="post"
          id="search-settings-form"
          class="form-horizontal">

        <div class="form-group">
            <div class="col-md-2">
                <label id="label_search_featured_title">
                    <?php echo __("Title for featured places") ?>
                </label>
            </div>
            <div class="col-md-1">
                <input type="checkbox"
                       name="search[featured][show]"
                    <?php if ($value->getMetadata('search_featured_show')->getPayload()) echo 'checked' ?>
                       class="color-blue"/>
            </div>
            <div class="col-md-6">
                <input type="text"
                       name="search[featured][title]"
                       class="input-flat"
                       placeholder="<?php echo __js("Title for featured places") ?>"
                       value="<?php echo $value->getMetadata('search_featured_title')->getPayload() ?>" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-2">
                <label id="label_search_nonfeatured_title">
                    <?php echo __("Title for non-featured places") ?>
                </label>
            </div>
            <div class="col-md-1">
                <input type="checkbox"
                       name="search[nonfeatured][show]"
                    <?php if ($value->getMetadata('search_nonfeatured_show')->getPayload()) echo 'checked' ?>
                       class="color-blue"/>
            </div>
            <div class="col-md-6">
                <input type="text"
                       name="search[nonfeatured][title]"
                       class="input-flat"
                       placeholder="<?php echo __js("Title for non-featured places") ?>"
                       value="<?php echo $value->getMetadata('search_nonfeatured_title')->getPayload() ?>" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-2">
                <label for="search_aroundyou"
                       id="label_search_aroundyou">
                    <?php echo __("Order places by") ?>
                </label>
            </div>
            <div class="sb-radio-container col-sm-7">



                <label class="sb-custom-radio">
                    <input type="radio"
                           value="distance"
                           name="places_order"
                           class="sb-form-radio radio-inline color-blue"
                        <?php if ($value->getMetadata('places_order')->getPayload()) echo 'checked' ?> />
                    <span class="sb-radio-label"><?php echo __("Nearest") ?></span>
                </label>

                <br />

                <label class="sb-custom-radio">
                    <input type="radio"
                           value="alpha"
                           name="places_order"
                           class="sb-form-radio radio-inline color-blue"
                        <?php if ($value->getMetadata('places_order_alpha')->getPayload()) echo 'checked' ?> />
                    <span class="sb-radio-label"><?php echo __("Alphabetically") ?></span>
                </label>

                <br />

                <label class="sb-custom-radio">
                    <input type="radio"
                           value="none"
                           name="places_order"
                           class="sb-form-radio radio-inline color-blue"
                           <?php if (!($value->getMetadata('places_order_alpha')->getPayload() || $value->getMetadata('places_order')->getPayload())) echo 'checked' ?> />
                    <span class="sb-radio-label "><?php echo __("Creation date") ?></span>
                </label>

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                <div class="alert alert-info">
                    <?php echo __("<b>Geolocation</b> option for the Overview & HTML5 will be displayed & work only when using HTTPS, however it works in Android & iOS apps without HTTPS."); ?>
                </div>
            </div>
        </div>

        <div class="buttons">
            <div class="pull-right">
                <button class="btn color-blue"
                        type="button"
                        onclick="submitSearchSettingsForm();">
                    <?php echo __('Save'); ?>
                </button>
            </div>
        </div>
        <input type="hidden"
               name="option_value_id"
               value="<?php echo $value->getId(); ?>"/>
    </form>
</div>

<script>
    var submitSearchSettingsForm = function () {
        reload($("#search-settings-form"), '<?php echo $this->getUrl('places/application/searchsettings') ?>', true, function (datas) {
            if (datas.success) {
                page.reload();
            }
        });
    }
</script>

<style type="text/css">
    .sb-radio-label {
        top: 1px;
    }
</style>