<?php $application = $this->getApplication(); ?>
<?php $value = $this->getOptionValue(); ?>

<div class="subcontent color-content content-feature container-fluid" id="search_editor">
    <form method="post" id="search-settings-form" class="form-horizontal">
        <div class="form-group">
            <div class="col-md-2">
                <label for="search_text" id="label_search_text">
                    <?php echo __("Text") ?>
                </label>
            </div>
            <div class="col-md-1">
                <input type="checkbox" name="search[text][show]" <?php if ($value->getMetadata('search_text_show')->getPayload()) echo 'checked' ?> class="color-blue"/>
            </div>
            <div class="col-md-6">
                <input type="text" name="search[text][label]" class="input-flat" placeholder="<?php echo __js("Label") ?>" value="<?php echo $value->getMetadata('search_text_label')->getPayload() ?>"/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-2">
                <label for="search_type" id="label_search_text">
                    <?php echo __("Type") ?>
                </label>
            </div>
            <div class="col-md-1">
                <input type="checkbox" name="search[type][show]" <?php if ($value->getMetadata('search_type_show')->getPayload()) echo 'checked' ?> class="color-blue"/>
            </div>
            <div class="col-md-6">
                <input type="text" name="search[type][label]" class="input-flat" placeholder="<?php echo __js("Label") ?>" value="<?php echo $value->getMetadata('search_type_label')->getPayload() ?>"/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-2">
                <label for="search_address" id="label_search_address">
                    <?php echo __("Address") ?>
                </label>
            </div>
            <div class="col-md-1">
                <input type="checkbox" name="search[address][show]"
                    <?php if ($value->getMetadata('search_address_show')->getPayload()) echo 'checked' ?> class="color-blue"/>
            </div>
            <div class="col-md-6">
                <input type="text" name="search[address][label]" class="input-flat" placeholder="<?php echo __js("Label") ?>"
                       value="<?php echo $value->getMetadata('search_address_label')->getPayload() ?>"/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-2">
                <label for="search_aroundyou" id="label_search_aroundyou">
                    <?php echo __("Around you") ?>
                </label>
            </div>
            <div class="col-md-1">
                <input type="checkbox" name="search[aroundyou][show]"
                    <?php if ($value->getMetadata('search_aroundyou_show')->getPayload()) echo 'checked' ?> class="color-blue"/>
            </div>
            <div class="col-md-3">
                <input type="text" name="search[aroundyou][label]" class="input-flat" placeholder="<?php echo __js("Label") ?>"
                       value="<?php echo $value->getMetadata('search_aroundyou_label')->getPayload() ?>"/>
            </div>
            <div class="col-md-3">
                <input type="text" name="search[aroundyou][radius]" class="input-flat" placeholder="<?php echo __js("Search radius") ?>"
                       value="<?php echo $value->getMetadata('search_aroundyou_radius')->getPayload() ?>"/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12">
                <?php echo __("<b>Around you</b> option for the Overview & HTML5 will be displayed & work only when using HTTPS, however it works in Android & iOS apps without HTTPS."); ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-2">
                <label for="search_aroundyou" id="label_search_aroundyou">
                    <?php echo __("Order places") ?>
                </label>
            </div>
            <div class="sb-radio-container col-sm-7">

                <label class="sb-custom-radio">
                    <input type="radio" value="none" name="places_order" class="sb-form-radio radio-inline color-blue" <?php if (!($value->getMetadata('places_order_alpha')->getPayload() || $value->getMetadata('places_order')->getPayload())) echo 'checked' ?> />
                    <span class="sb-radio-label "><?php echo __("default, by creation date") ?></span>
                </label>

                <br />

                <label class="sb-custom-radio">
                    <input type="radio" value="distance" name="places_order" class="sb-form-radio radio-inline color-blue" <?php if ($value->getMetadata('places_order')->getPayload()) echo 'checked' ?> />
                    <span class="sb-radio-label"><?php echo __("by distance") ?></span>
                </label>

                <br />

                <label class="sb-custom-radio">
                    <input type="radio" value="alpha" name="places_order" class="sb-form-radio radio-inline color-blue" <?php if ($value->getMetadata('places_order_alpha')->getPayload()) echo 'checked' ?> />
                    <span class="sb-radio-label"><?php echo __("alphabetically") ?></span>
                </label>

            </div>
        </div>
        <div class="buttons">
            <div class="pull-right">
                <button class="btn color-blue" type="button" onclick="submitSearchSettingsForm();">
                    <?php echo __('Save'); ?>
                </button>
            </div>
        </div>
        <input type="hidden" name="option_value_id" value="<?php echo $value->getId(); ?>"/>
    </form>
</div>

<script>
    var submitSearchSettingsForm = function () {
        reload($("#search-settings-form"), '<?php echo $this->getUrl('places/application/searchsettings') ?>', true, function (datas) {
            if (datas.success) {
                page.reload();
            }
        });
    }
</script>

<style type="text/css">
    .sb-radio-label {
        top: 1px;
    }
</style>