<?php
$application = $this->getApplication();

$form = new Application_Form_Domain();
$form->populate($application->getData());

?>
<div class="row"
     id="settings_domain">
    <div class="col-md-12">
        <div class="page-content-wrapper">
            <div id="domain_content"
                 class="content solo-page sb-tour">
                <h3 class="title-editor border-blue text-center">
                    <?php echo __('Mobile website information'); ?>
                </h3>
                <div id="domain"
                     class="subcontent content-color">
                    <div class="col-md-12">
                        <?php echo $form; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    bindForms("#settings_domain");
</script>