doctrine:
    dbal:
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                driver_class: 'Doctrine\DBAL\Driver\PDO\PgSQL\Driver'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true
                #server_version: '16'
            legacy:
                url: '%env(resolve:DATABASE_LEGACY_URL)%'
                driver_class: 'Doctrine\DBAL\Driver\PDO\MySQL\Driver'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true

        default_connection: default
    orm:
        auto_generate_proxy_classes: false
        enable_lazy_ghost_objects: true
#        report_fields_where_declared: true
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                auto_mapping: true
                mappings:
                    Core:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Next/Core/Entity'
                        prefix: 'App\Next\Core\Entity'
                        alias: Core
                    Plugin:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Next/Plugin/Entity'
                        prefix: 'App\Next\Plugin\Entity'
                        alias: Plugin
            legacy:
                connection: legacy
                mappings:
                    Legacy:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Legacy/Auth/Entity'
                        prefix: 'App\Legacy\Auth\Entity'
                        alias: LegacyAuth
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
