<sb-section title="'<?php echo addcslashes(p__("firewall", "Firewall"), "'"); ?>'">
    <div class="form-group">
        <form ng-submit="saveWafEnabled()">
            <div class="col-md-6">
                <label for="waf_enabled"><?php echo p__("firewall", "Firewall") ?></label>
            </div>

            <div class="clear col-md-12">
                <br/>
                <div ng-if="waf.enabled == 1">
                    <b><?php echo p__("firewall", "WAF Enabled") ?></b>
                    <br />
                    <?php echo p__("firewall", "The Web Application Firewall is enabled and can only be disabled through the system cli commands to meet enforced security policies, <code>./cli waf:disable</code>.") ?>
                </div>
                <div ng-if="waf.enabled == 0">
                    <b><?php echo p__("firewall", "WAF Disabled") ?></b>
                    <p class="alert alert-danger">
                        <?php echo p__("firewall", "Disabling the Web Application Firewall can open your Siberian to potential XSS, Injection & various security issues, the WAF is not a guarantee your Siberian is attack proof, but highly helps filtering the most common web attacks.") ?>
                    </p>
                    <p>
                        <?php echo p__("firewall", "To enable the firewall you must use the system cli commands, <code>./cli waf:enable</code>") ?>
                    </p>
                </div>
            </div>
        </form>
        <div style="clear:both;"></div>
    </div>
</sb-section>

<sb-section title="'<?php echo addcslashes(__("ClamAV settings"), "'"); ?>'">
    <div class="form-group">

        <div class="col-md-12">
            <div class="alert alert-info">
                <b><?php echo __("ClamAV is an optional anti-virus, you can enable it up below.") ?></b>
                <br/>
                <?php echo __("Siberian uses it to scan all uploaded files that have passed the soft Firewall."); ?>
                <br/>
                <br/>
                <b><?php echo __("To be able to use ClamAV you must have it installed on your server and configured accordingly to our documentation.") ?></b>
            </div>
        </div>

        <form ng-submit="saveFwClamdSettings()">

            <div class="col-md-6"
                 style="margin-bottom: 20px;">
                <label for="fw_clamd.type"><?php echo __('Connection type') ?></label>
                <select id="fw_clamd.type"
                        class="form-control"
                        ng-model="fw_clamd.type">
                    <option value=""><?php echo __('Select a connection type:') ?></option>
                    <option value="sock"><?php echo __('Socket') ?></option>
                    <option value="ip"><?php echo __('IP:Port') ?></option>
                    <option value="disabled"><?php echo __('Disabled') ?></option>
                </select>
            </div>

            <div ng-show="fw_clamd.type == 'sock'"
                 class="clear col-md-10">
                <label for="fw_clamd.sock"><?php echo __('Socket') ?></label>
                <input type="text"
                       id="fw_clamd.sock"
                       class="form-control"
                       placeholder="<?php echo __js("Socket, example: /var/run/clamav/clamd.ctl") ?>"
                       ng-model="fw_clamd.sock"/>
            </div>

            <div ng-show="fw_clamd.type == 'ip'"
                 class="clear col-md-5">
                <label for="fw_clamd.ip"><?php echo __('IP') ?></label>
                <input type="text"
                       id="fw_clamd.ip"
                       class="form-control"
                       placeholder="<?php echo __js("IP, example: 127.0.0.1") ?>"
                       ng-model="fw_clamd.ip"/>
            </div>

            <div ng-show="fw_clamd.type == 'ip'"
                 class="col-md-5">
                <label for="fw_clamd.port"><?php echo __('Port') ?></label>
                <input type="text"
                       id="fw_clamd.port"
                       class="form-control"
                       placeholder="<?php echo __js("Port, example: 3310") ?>"
                       ng-model="fw_clamd.port"/>
            </div>

            <div class="col-md-2 pull-right">
                <button id="fw_clamd.submit"
                        style="margin-top: 24px;"
                        class="btn btn-primary"
                        type="submit"><?php echo __('Save') ?></button>
            </div>
        </form>

        <div style="clear:both;"></div>
    </div>
</sb-section>

<sb-section title="'<?php echo addcslashes(__("Add new upload extensions."), "'"); ?>'">
    <div class="form-group">
        <div class="col-md-12">
            <div class="alert alert-info">
                <b><?php echo p__("firewall", "Please note that .php, .js & .ico are strictly forbidden and can't be added") ?></b>
            </div>

            <p>
                <?php echo p__("firewall", "To meet enforced security policies, you can only add new allowed extensions through the cli commands, <code>./cli waf:extension:allow abc</code>, <code>./cli waf:extension:disallow xyz</code>") ?>
            </p>
        </div>

        <div style="clear:both;"></div>
    </div>
</sb-section>

<sb-section title="'<?php echo addcslashes(__("Allowed upload extensions."), "'"); ?>'">
    <table class="table">
        <thead>
        <tr>
            <th style="width:50%;"><?php echo __("Extension") ?></th>
            <th style="width:20%;text-align:right;"><?php echo __("Actions") ?></th>
        </tr>
        </thead>
        <tbody>
        <tr ng-repeat="fw_upload_rule in fw_upload_rules"
            ng-show="fw_upload_rules.length">
            <td>{{ fw_upload_rule.value }}</td>
            <td style="text-align:right;">
                <button class="btn btn-xs btn-danger"
                        ng-click="deleteFwUploadRule(fw_upload_rule.value)"><?php echo __('Delete') ?></button>
            </td>
        </tr>
        <tr ng-show="!fw_upload_rules.length">
            <td colspan="2"><?php echo __("No rules") ?></td>
        </tr>
        </tbody>
    </table>
</sb-section>

<sb-section title="'<?php echo addcslashes(__("Security logs (last 50 triggers)"), "'"); ?>'">
    <table class="table">
        <thead>
        <tr>
            <th style="width: 120px;"><?php echo __("Type") ?></th>
            <th><?php echo __("Message") ?></th>
            <th><?php echo __("User") ?></th>
            <th><?php echo __("Date") ?></th>
        </tr>
        </thead>
        <tbody>
        <tr ng-repeat="fw_log in fw_logs"
            ng-show="fw_logs.length">
            <td>{{ fw_log.type }}</td>
            <td>{{ fw_log.message }}</td>
            <td>{{ fw_log.user.id }} - {{ fw_log.user.email }}</td>
            <td>{{ fw_log.date }}</td>
        </tr>
        <tr ng-show="!fw_logs.length">
            <td colspan="2"><?php echo __("No logs") ?></td>
        </tr>
        </tbody>
    </table>
</sb-section>

<sb-section title="'<?php echo addcslashes(__("Slack notification settings"), "'"); ?>'">
    <div class="form-group">

        <form ng-submit="saveFwSlackSettings()">

            <div class="col-md-1">
                <label for="fw_slack.is_enabled"><?php echo __('Enabled?') ?></label>
                <input type="checkbox"
                       id="fw_slack.is_enabled"
                       class="form-control"
                       ng-model="fw_slack.is_enabled"/>
            </div>

            <div class="col-md-3">
                <label for="fw_slack.webhook"><?php echo __('Webhook') ?></label>
                <input type="text"
                       id="fw_slack.webhook"
                       class="form-control"
                       placeholder="<?php echo __js("Example: https://hooks.slack.com/services/XDEFFE/DE45GFV/RxwdF4bnhtRDsqsqzd234, ") ?>"
                       ng-model="fw_slack.webhook"/>
            </div>

            <div class="col-md-3">
                <label for="fw_slack.channel"><?php echo __('Channel') ?></label>
                <input type="text"
                       id="fw_slack.channel"
                       class="form-control"
                       placeholder="<?php echo __js("Channel: #security, #notifications, etc...") ?>"
                       ng-model="fw_slack.channel"/>
            </div>

            <div class="col-md-3">
                <label for="fw_slack.username"><?php echo __('Username') ?></label>
                <input type="text"
                       id="fw_slack.username"
                       class="form-control"
                       placeholder="<?php echo __js("Username: siberian-notifier, etc...") ?>"
                       ng-model="fw_slack.username"/>
            </div>

            <div class="col-md-2 pull-right">
                <button id="fw_slack.submit"
                        style="margin-top: 24px;"
                        class="btn btn-primary"
                        type="submit"><?php echo __('Save') ?></button>
            </div>
        </form>

        <div class="clear"></div>
    </div>
</sb-section>
