<?php $option_value = $this->getOptionValue(); ?>
<?php $application = $this->getApplication(); ?>
<?php $facebook = $option_value->getObject(); ?>
<div id="list" class="edit_page facebook">
    <form id="facebookForm" name="facebookForm" method="post" action="<?php echo $this->getUrl('social/application_facebook/editpost') ?>" class="form-horizontal">
        <h3 class="title-editor no-border-radius title-feature-indent">
            <?php echo $this->_('Facebook'); ?>
        </h3>
        <div class="container-fluid content-feature">
            <input type="hidden" name="value_id" value="<?php echo $option_value->getId(); ?>" />
            <div class="form-group first-row-feature">
                <div class="col-sm-12">
                    <label><?php echo $this->_('Enter your Facebook Fan Page Id *:') ?></label>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-6">
                    <input type="text" id="fb_url" name="fb_user" value="<?php echo $facebook->getFbUser()?>" placeholder="<?php echo $this->_("Enter your Facebook Fan Page Id") ?>" class="required input-flat" />
                </div>
                <div class="col-sm-2">
                    <button class="btn color-blue" type="submit">
                        <?php echo $this->_('OK'); ?>
                    </button>
                </div>
                <div class="col-sm-4">
                    <i id="fb_valid_username" class="fa fa-ok" style="display:none;"></i>
                    <i id="fb_invalid_username" class="fa fa-remove" style="display:none;"></i>
                    <input type="hidden" name="option_value_id" value="<?php echo $option_value->getId(); ?>" />
                    <input type="hidden" name="id" value="<?php echo $facebook->getId(); ?>" />
                </div>
            </div>
        </div>
    </form>
    <?php echo $this->importBackground($option_value); ?>
</div>
<script type="text/javascript">

    $(document).ready(function () {
        bindForms('#list');
    });

    page.setCallback('didappear', function() {

        $('#facebookForm').submit(function() {
            if(!$(this).valid()) return false;
            reload(this, this.action, true, function(datas) {
                if(datas.success) {
                    iframe.f.reload();
                }
            });
            return false;
        });

    });

    page.setCallback('willdisappear', function() {
        $('#facebookForm').unbind('submit');
    });

</script>