<?php

use PaymentStripe\Form\Settings as FormSettings;
use PaymentStripe\Model\Application as StripeApplication;

$application = $this->getApplication();

// Form
$formStripe = new FormSettings();

// Settings
try {
    $settings = StripeApplication::getSettings($application->getId());
    $formStripe->populate($settings->getData());
} catch (\Exception $e) {
    // Nope!
}


?>
<div class="row">
    <div class="col-md-12">
        <div class="page-content-wrapper">
            <div id="apis_content"
                 class="content solo-page sb-tour">

                <h3 class="title-editor border-blue text-center">
                    <?php echo p__('payment_stripe', 'Stripe payments'); ?>
                </h3>
                <div class="subcontent content-color">
                    <div class="col-md-12">
                        <div class="form-payment"
                             rel="stripe">
                            <h4 class="title-editor no-border-radius title-feature-indent">
                                <?php echo p__('payment_stripe', 'API credentials') ?>
                            </h4>
                            <div class="container-fluid content-feature">
                                <br />
                                <?php echo $formStripe ?>
                            </div>

                            <br />
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
$(document).ready(function () {
    bindForms('#apis_content');
});
</script>