<?php $option_value = $this->getOptionValue(); ?>
<?php $application = $this->getApplication(); ?>
<?php $magento = $option_value->getObject(); ?>
<div class="form_content">
    <div id="list" class="edit_page">
        <div class="magento">
            <form id="magentoForm" name="magentoForm" method="post" action="<?php echo $this->getUrl('weblink/application_magento/editpost') ?>" class="form-horizontal">
                <h3 class="title-editor no-border-radius title-feature-indent">
                    <?php echo $this->_('Magento') ?>
                </h3>
                <input type="hidden" name="value_id" value="<?php echo $option_value->getId(); ?>" />
                <div class="container-fluid first-row-feature content-feature">
                    <div class="infos">
                        <div id="magento_content">
                            <div class="form-group">
                                <div class="col-sm-12">
                                    <input type="text" id="magento" name="link" class="input-flat url" placeholder="<?php echo $this->_('Enter your Magento URL') ?>" value="<?php echo $magento->getLink()->getUrl() ?>"/>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-12">
                            <div class="save pull-right">
                                <button class="btn btn-block color-blue" type="submit">
                                    <?php echo $this->_('Save'); ?>
                                </button>
                            </div>
                        </div>
                    </div>
                    
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">

    page.setCallback('didappear', function() {

        $('#magento').change(function() {
            if(!$(this).val().isEmpty() && !$(this).val().startsWith('http://') && !$(this).val().startsWith('https://')) {
                $(this).val('http://'+$(this).val());
            }
        });
        $('#magentoForm').submit(function() {
            if(!$(this).valid()) return false;
            reload(this, this.action, true, function(datas) {
                if(datas.success) {
                    if(iframe.f.isHomepage()) {
                        iframe.f.reload();
                    }
                }
            });
            return false;
        });

    });

    page.setCallback('willdisappear', function() {
        $('#magento').unbind('change');
        $('#magentoForm').unbind('submit');
    });

</script>