<?php $application = $this->getApplication() ?>
<div id="iphone">
    <div class="iphone_content">
        <div id="mobile_homescreen">
            <img title="" alt="" src="/app/sae/design/desktop/siberian/images/customization/overview/homescreen.png"></img>
            <div id="overview_icon" class="overview mobile_view right touch_icon">
                <div class="icon">
                    <img src="<?php echo $application->getIcon(); ?>" id="preview_icon" width="62" height="62" />
                </div>
                <p id="app_name" class="no-margin"><?php echo $application->getShortName(); ?></p>
            </div>
        </div>
    </div>
</div>