<table>
    <tr style="padding: 0 15px; color:#888888; font-size: 17px; line-height: 150%; width:600px">
        <td>
            <p style="font-family: Verdana; font-weight: bold;color: #404040;font-size:18px; line-height:150%;"><?php echo $this->_('Hello,'); ?></p>
            <p align="justify">
                <span style="color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 13px;">
                    <?php echo $this->_('You have received a message from a contact:'); ?> <strong><?php echo $this->getData('name') ?></strong><br />
                </span>
            </p>
            <p align="justify" style="color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 13px;">
                <?php echo $this->_('Here is his message:'); ?> <?php echo stripslashes(nl2br($this->getInfo())) ?>
            </p>
            <p align="justify">
                <span style="color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 13px;">
                    <?php echo $this->_("Here is his email:"); ?> <a href="mailto:<?php echo $this->getData('email') ?>"><strong><?php echo $this->getData('email') ?></strong></a>
                </span>
                <?php if($phone = $this->getData('phone')) : ?>
                <br />
                <span style="color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 13px;">
                    <?php echo $this->_('And his phone number:'); ?> <?php echo $phone ?>
                </span>
                <?php endif ?>
            </p>
        </td>
    </tr>
</table>