<div class="row">
    <div class="col-md-12">
        <div class="page-content-wrapper">
            <div id="error_content" class="content solo-page">
                <h3 class="title-editor border-blue text-center">
                    <?php echo $this->_('404, page not found') ?>
                </h3>
                <div class="container-fluid first-row-feature content-feature subcontent content-color">
                    <div id="error">
                        <div class="row">
                            <div class="col-md-12 text-center">
                                <h4><?php echo $this->_('Ouch, this page doesn\'t exist') ?></h4>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12 text-center">
                                <a href="<?php echo $this->getUrl('application/customization_design_style/edit'); ?>" class="color-blue btn">
                                    <i class="fa fa-pencil"></i>
                                    <span><?php echo $this->_('Editor'); ?></span>
                                    <i class="fa fa-angle-right"></i>
                                 </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
