<div id="iphone">
    <div class="iphone_content">
	    <div id="colors_overview">
		    <iframe id="mobile_overview" src="<?php echo $this->getApplication()->getUrl("application/mobile_customization_colors", array(), Core_Model_Language::getCurrentLanguage(), true); ?>" width="323" height="580" style="overflow: hidden;"></iframe>
		    <iframe id="homepage_overview" src="<?php echo $this->getApplication()->getUrl("front/mobile_home/colors", array(), Core_Model_Language::getCurrentLanguage(), true); ?>" width="323" height="580" style="overflow: hidden; display: none;"></iframe>
	   	</div>
	</div>
</div>