<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    </head>
    <body>
        <div style="margin: auto; width: 600px;">
            <div style="margin:auto; padding: 0 15px; color:#888888; font-size: 17px; line-height: 150%; width:600px">
                <?php echo $this->getPartialHtml('header'); ?>
            </div>
            <div style="margin:auto; margin-top: 15px; padding: 0 15px; color:#888888; font-size: 17px; line-height: 150%; width:600px">
                <?php echo $this->getPartialHtml('content_email') ?>
            </div>
            <div style="margin:auto; padding: 0 15px; color:#888888; font-size: 17px; line-height: 150%; width:600px">
                <?php echo $this->getPartialHtml('footer') ?>
            </div>
        </div>
    </body>
</html>

