    <?php $option_value = $this->getOptionValue(); ?>
<?php $source_code = $option_value->getObject(); ?>
<div class="source_code">
    <div id="edit">
        <h3 class="title-editor no-border-radius">
            <?php echo $this->_('Source Code'); ?>
        </h3>
        <div class="container-fluid first-row-feature">
            <form id="sourcecodeCreateForm" action="<?php echo $this->getUrl('sourcecode/application/editpost') ?>" method="post" class="form-horizontal">
                <div class="form-group">
                    <div class="col-md-12">
                        <div class="buttons">
                            <button type="button" onclick="page.reload()" class="btn color-blue pull-left"><i class="fa fa-arrow-left"></i></button>
                            <button type="submit" class="btn color-blue pull-right">OK</button>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12">
                        <label for="html_source_code_<?php echo $option_value->getId(); ?>"><?php echo $this->_('Insert your HTML code:'); ?></label>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12">
                        <textarea id="html_source_code_<?php echo $option_value->getId(); ?>" class="html_source_code input-flat" name="html_code"><?php echo htmlentities($source_code->getHtmlCode(), ENT_QUOTES, 'UTF-8'); ?></textarea>
                    </div>
                    <input type="hidden" name="option_value_id" value="<?php echo $option_value->getId(); ?>" />
                </div>
            </form>
        </div>
    </div>

    <script type="text/javascript">

            page.setCallback('didappear', function() {
                $('#sourcecodeCreateForm').submit(function() {
                    reload(this, this.action, true, function(data) {
                        if(data.success) {
                            page.reload();
                        }
                    });
                    return false;
                });
            });

            page.setCallback('willdisappear', function() {
                $('#sourcecodeCreateForm').unbind('submit');
            });

    </script>
    <style>
        .source_code .html_source_code { width: 100%; height: 300px; }
        .source_code .buttons { padding:5px; }
    </style>

</div>
