<?php $application = $this->getApplication(); ?>
<?php $value = $this->getOptionValue(); ?>
<?php $page = new Cms_Model_Application_Page(); ?>
<?php $pages = $page->findAll(array('value_id' => $value->getId()), 'page_id DESC'); ?>
<div class="edit_page places">
    <h3 class="title-editor no-border-radius title-feature-indent">
        <?php echo $this->_('Add'); ?>
        <button type="button" id="add_item" class="toggle_design color-blue pull-right bt-header-right btn">
            <i class="fa fa-plus"></i>
        </button>
    </h3>
    <div class="margin-top">
        <div id="list">
            <?php echo $this->createPartialHtml('no_item', 'core_view_default', 'application/customization/features/edit/no_item.phtml'); ?>
            <?php if ($pages->count()) : ?>
                <h3 class="title-editor no-border-radius title-feature-indent">
                    <?php echo $this->_('Manage'); ?>
                    <button type="button" id="toggle_existing_items" class="toggle_design color-blue pull-right bt-header-right btn">
                        <i class="fa fa-chevron-down"></i>
                    </button>
                </h3>
                <div id="existing_items" style="display:none;">
                    <table class="table_row_agenda table table-hover">
                        <col width="33%" />
                        <col width="60%" />
                        <col width="7%" />
                        <?php foreach($pages as $page) : ?>
                        <tr id="place_row_<?php echo $page->getId(); ?>" class="place_row">
                            <td class="page_name">
                                <?php echo $page->getTitle(); ?>
                            </td>
                            <td class="event_type">
                                <?php echo $page->getContent(); ?>
                            </td>
                            <td class="actions">
                                <i class="edit_place fa fa-edit" rel="<?php echo $page->getId(); ?>"></i>
                                <i class="delete_place fa fa-remove"></i>
                                <input type="hidden" name="id" value="<?php echo $page->getId(); ?>" />
                                <input type="hidden" name="option_value_id" value="<?php echo $value->getId(); ?>" />
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
            <?php endif; ?>
            <div class="row">
                <div class="col-md-12">
                    <?php echo $this->getLayout()
                        ->addPartial('background_image', 'Core_View_Default', 'application/customization/features/edit/background_image.phtml')
                        ->setValueId($value->getId())
                        ->toHtml()
                    ;
                    ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <?php echo $this->getLayout()
                        ->addPartial('places_search_setup', 'Core_View_Default', 'places/application/search.phtml')
                        ->setOptionValue($value)
                        ->setPages($pages)
                        ->toHtml(); ?>
                </div>
            </div>
        </div>

        <div id="edit" class="first-row-feature" style="display: none;">
        </div>

        <script type="text/javascript">

            page.setCallback('willappear', function() {

            });

            page.setCallback('didappear', function() {

                $('#add_item').click(function() {
                    reload(this, "<?php echo $this->getUrl("places/application/form", array("option_value_id" => $value->getId())); ?>", true, function(data) {
                        $('#edit').append(data.form);
                        feature.edit();
                        cms_didappear();
                        $('#address').click().remove();
                    });
                });

                $('#toggle_existing_items').click(function() {
                    $('#existing_items').stop().slideToggle(300, function() {
                        if($(this).is(':visible')) $('#toggle_existing_items').children('i').removeClass('fa-chevron-down').addClass('fa-chevron-up');
                        else $('#toggle_existing_items').children('i').removeClass('fa-chevron-up').addClass('fa-chevron-down')
                    });
                });

                $('.edit_place').click(function() {
                    var id = $(this).attr('rel');
                    reload(this, "<?php echo $this->getUrl("places/application/form", array("option_value_id" => $value->getId())); ?>/id/"+id, true, function(data) {
                        $('#edit').append(data.form);
                        feature.edit();
                        cms_didappear();
                        $('#address').remove();
                    });
                });

                $('.delete_place').click(function() {

                    if(!confirm("<?php echo addslashes($this->_("Are you sure you want to delete this page?")); ?>")) return false;

                    var id = $(this).attr('rel');
                    reload(this.parentNode, '<?php echo $this->getUrl('cms/application_page/delete'); ?>', true, function(data) {
                        if(data.success) {
                            page.reload();
                        }
                    });
                });

            });

            page.setCallback('willdisappear', function() {
                $('#toggle_existing_items').unbind('click');
                $('#newsCreateForm').unbind('submit');
                $('#title').unbind('keyup change');
                $('.news_actions').unbind('mouseenter mouseout');
                $('.show_answers').unbind('click');
                $('.show_details').unbind('click');
                $('.edit_place').unbind('click');
                $('.delete_place').unbind('click');
            });

        </script>
        <style>
            div#list a.icon, div#list span.price {margin-top: 0;}
            .edit_place, .delete_place {cursor: pointer;}
        </style>
    </div>

</div>
