<table>
    <tr style="margin:auto; padding: 0 15px; color:#888888; font-size: 17px; line-height: 150%; width:600px">
        <td>
            <p align="justify"
               style="color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 13px;">
                <br />
                <?php echo p__('customer', 'You can follow the URL below to validate your email address!'); ?>:
                <br />
                <br />
                <a href="<?php echo $this->getData('url') ?>"
                   target="_blank"><?php echo $this->getData('url') ?></a>
                <br />
                <br />
                <?php echo p__('customer', 'Thank you!'); ?>
                <br />
            </p>
        </td>
    </tr>
</table>