<?php $option = $this->getOptionValue(); ?>
<?php $mcommerce = $option->getObject(); ?>
<?php $tax = $this->getCurrentTax(); ?>
<?php $stores = $mcommerce->getStores(); ?>
<div>
    <form id="taxEditForm" method="post" action="<?php echo $this->getUrl('mcommerce/application_settings_tax/editpost'); ?>" class="form-horizontal">
        <div class="buttons">
            <button type="button" onclick="mcommerce_settings.tax.close();" class="delete left"><i class="icon-arrow-left"></i></button>
            <button type="submit" class="default_button right">OK</button>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
        <fieldset>
            <h4 class="subtitle">
                <?php if($tax->getId()) : ?>
                <span class="left area"><?php echo $this->_("Edit the tax %s", $tax->getName()); ?></span>
                <?php else : ?>
                <span class="left area"><?php echo $this->_("Create a new tax"); ?></span>
                <?php endif; ?>
                <hr />
                <div class="clear"></div>
            </h4>
            <div class="form-group">
                <div class="col-sm-2">
                    <label for="tax_name"><?php echo $this->_("Tax name:"); ?></label>
                </div>
                <div class="col-sm-5">
                    <input type="text" id="tax_name" name="name" class="form-control required" value="<?php echo $tax->getName(); ?>" placeholder="<?php echo $this->_("Tax name"); ?>" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-2">
                    <label for="tax_rate"><?php echo $this->_("Tax rate:"); ?></label>
                </div>
                <div class="col-sm-5">
                    <input type="text" id="tax_rate" name="rate" class="form-control required number" value="<?php echo $tax->getRate(); ?>" placeholder="<?php echo $this->_("20,00 %"); ?>" />
                </div>
            </div>
        </fieldset>
        <?php if($tax->getId()) : ?>
            <input type="hidden" name="tax_id" id="tax_id" value="<?php echo $tax->getId() ?>" />
        <?php endif; ?>
        <input type="hidden" name="option_value_id" value="<?php echo $option->getId() ?>" />

    </form>
</div>