<?php
    $application = $this->getApplication();
    $ios = $application->getDevice(1);

    $form = new Application_Form_Advanced();
    $form->populate($application->getData());

    $iosData = $ios->getData();
    $iosData['request_tracking_authorization'] = $application->getRequestTrackingAuthorization();

    $formNsDescription = new Application_Form_NsDescription();
    $formNsDescription->populate($iosData);

    $orientations = Siberian_Json::decode($ios->getOrientations());
?>
<div class="row">
    <div class="col-md-12">
        <div class="page-content-wrapper">
            <div id="advanced_settings_content" class="content solo-page sb-tour">
                <h3 class="title-editor border-blue text-center">
                    <?php echo __("Advanced Application Options"); ?>
                </h3>
                <div id="advanced" class="subcontent content-color">
                    <div class="col-md-12">
                        <?php echo $form; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="page-content-wrapper">
            <div id="ios_plist" class="content solo-page sb-tour">
                <h3 class="title-editor border-blue text-center">
                    <?php echo __('iOS NS*Descriptions'); ?>
                </h3>
                <div id="advanced_ios" class="subcontent content-color">
                    <div class="col-md-12">
                        <div class="alert alert-warning">
                            <?php
$link = '<a style="text-decoration: underline !important;" href="https://developer.apple.com/app-store/review/guidelines">https://developer.apple.com/app-store/review/guidelines</a>';
echo __('Permissions Modal Alerts messages describe why your apps requires some permissions,');
echo __('like using the GPS or the camera. After the first installation of your app, those messages will be shown to the app user.');
echo '<br /><br />' . __("If your messages do not comply with App Store Review Guidelines, %s, your app might be possibly refused after Apple's review.", $link);
                            ?>
                        </div>

                        <div class="alert alert-info">
                            <?php echo __('You can use <b>%s</b> as variable for your application name.', '#APP_NAME') ?>
                        </div>

                        <?php echo $formNsDescription; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="page-content-wrapper">
            <div id="ios_plist_orientation" class="content solo-page sb-tour">
                <h3 class="title-editor border-blue text-center">
                    <?php echo __('iPhone & iPad & Android orientation'); ?>
                </h3>
                <form id="saveorientations"
                      method="post"
                      enctype="application/x-www-form-urlencoded"
                      action="<?php echo __path('/application/settings_advanced/saveorientations'); ?>"
                      class="form sb-form create feature-form">
                    <div id="advanced_ios_orientation"
                         class="subcontent content-color">

                        <input type="hidden"
                               id="android-orientation"
                               name="android"
                               value="" />

                        <!-- Android -->
                        <div class="col-md-12">
                            <h3><?php echo __("Android orientation settings") ?></h3>
                        </div>

                        <div class="col-md-12">
                            <div class="alert alert-warning"><?php echo __("Android being more restrictive with screen orientation some combination are not possible.") ?></div>
                        </div>

                        <div class="col-md-12 invalid-android hide">
                            <div class="alert alert-danger"><?php echo __("This combination is not valid, if you want both portrait & landscape please check all orientations.") ?></div>
                        </div>

                        <div class="col-md-3 center">
                            <label>
                                <img class="iphone android l90"
                                     src="/app/sae/design/desktop/flat/images/svg/android.svg" />
                                <p class="orientation-checkbox">
                                    <input class="android toggle-img"
                                           <?php echo ($orientations['android-landscape-left']) ? 'checked="checked"' : '' ?>
                                           type="checkbox"
                                           rel="landscape"
                                           name="orientations[android-landscape-left]" />
                                    <?php echo __('Landscape Left'); ?>
                                </p>
                            </label>
                        </div>
                        <div class="col-md-3 center">
                            <label>
                                <img class="iphone android"
                                     src="/app/sae/design/desktop/flat/images/svg/android.svg" />
                                <p class="orientation-checkbox">
                                    <input class="android toggle-img"
                                           <?php echo ($orientations['android-portrait']) ? 'checked="checked"' : '' ?>
                                           type="checkbox"
                                           rel="portrait"
                                           name="orientations[android-portrait]" />
                                    <?php echo __('Portrait'); ?>
                                </p>
                            </label>
                        </div>
                        <div class="col-md-3 center">
                            <label>
                                <img class="iphone android r90"
                                     src="/app/sae/design/desktop/flat/images/svg/android.svg" />
                                <p class="orientation-checkbox">
                                    <input class="android toggle-img"
                                           <?php echo ($orientations['android-landscape-right']) ? 'checked="checked"' : '' ?>
                                           type="checkbox"
                                           rel="reverseLandscape"
                                           name="orientations[android-landscape-right]" />
                                    <?php echo __('Landscape Right'); ?>
                                </p>
                            </label>
                        </div>
                        <div class="col-md-3 center">
                            <label>
                                <img class="iphone android ud180"
                                     src="/app/sae/design/desktop/flat/images/svg/android.svg" />
                                <p class="orientation-checkbox">
                                    <input class="android toggle-img"
                                           <?php echo ($orientations['android-upside-down']) ? 'checked="checked"' : '' ?>
                                           type="checkbox"
                                           rel="reversePortrait"
                                           name="orientations[android-upside-down]" />
                                    <?php echo __('Upside Down'); ?>
                                </p>
                            </label>
                        </div>

                        <!-- iPhone -->
                        <div class="col-md-12 margin-bottom-header">
                            <h3><?php echo __('iPhone orientation settings') ?></h3>
                        </div>
                        <div class="col-md-3 center">
                            <label>
                                <img class="iphone l90"
                                     src="/app/sae/design/desktop/flat/images/svg/iphone.svg" />
                                <p class="orientation-checkbox">
                                    <input class="toggle-img"
                                            <?php echo ($orientations['iphone-landscape-left']) ? 'checked="checked"' : '' ?>
                                           type="checkbox"
                                           name="orientations[iphone-landscape-left]" />
                                    <?php echo __('Landscape Left'); ?>
                                </p>
                            </label>
                        </div>
                        <div class="col-md-3 center">
                            <label>
                                <img class="iphone"
                                     src="/app/sae/design/desktop/flat/images/svg/iphone.svg" />
                                <p class="orientation-checkbox">
                                    <input class="toggle-img"
                                            <?php echo ($orientations['iphone-portrait']) ? 'checked="checked"' : '' ?>
                                           type="checkbox"
                                           name="orientations[iphone-portrait]" />
                                    <?php echo __('Portrait'); ?>
                                </p>
                            </label>
                        </div>
                        <div class="col-md-3 center">
                            <label>
                                <img class="iphone r90"
                                     src="/app/sae/design/desktop/flat/images/svg/iphone.svg" />
                                <p class="orientation-checkbox">
                                    <input class="toggle-img"
                                           <?php echo ($orientations['iphone-landscape-right']) ? 'checked="checked"' : '' ?>
                                           type="checkbox"
                                           name="orientations[iphone-landscape-right]" />
                                    <?php echo __('Landscape Right'); ?>
                                </p>
                            </label>
                        </div>
                        <div class="col-md-3 center">
                            <label>
                                <img class="iphone ud180"
                                     src="/app/sae/design/desktop/flat/images/svg/iphone.svg" />
                                <p class="orientation-checkbox">
                                    <input class="toggle-img"
                                           <?php echo ($orientations['iphone-upside-down']) ? 'checked="checked"' : '' ?>
                                           type="checkbox"
                                           name="orientations[iphone-upside-down]" />
                                    <?php echo __('Upside Down'); ?>
                                </p>
                            </label>
                        </div>

                        <!-- iPad -->
                        <div class="col-md-12 margin-bottom-header">
                            <h3 class="margin-top-header"><?php echo __('iPad orientation settings') ?></h3>
                        </div>
                        <div class="col-md-3 center">
                            <label>
                                <img class="ipad l90"
                                     src="/app/sae/design/desktop/flat/images/svg/ipad.svg" />
                                <p class="orientation-checkbox">
                                    <input class="toggle-img"
                                           <?php echo ($orientations['ipad-landscape-left']) ? 'checked="checked"' : '' ?>
                                           type="checkbox"
                                           name="orientations[ipad-landscape-left]" />
                                    <?php echo __('Landscape Left'); ?>
                                </p>
                            </label>
                        </div>
                        <div class="col-md-3 center">
                            <label>
                                <img class="ipad"
                                     src="/app/sae/design/desktop/flat/images/svg/ipad.svg" />
                                <p class="orientation-checkbox">
                                    <input class="toggle-img"
                                           <?php echo ($orientations['ipad-portrait']) ? 'checked="checked"' : '' ?>
                                           type="checkbox"
                                           name="orientations[ipad-portrait]" />
                                    <?php echo __('Portrait'); ?>
                                </p>
                            </label>
                        </div>
                        <div class="col-md-3 center">
                            <label>
                                <img class="ipad r90"
                                     src="/app/sae/design/desktop/flat/images/svg/ipad.svg" />
                                <p class="orientation-checkbox">
                                    <input class="toggle-img"
                                            <?php echo ($orientations['ipad-landscape-right']) ? 'checked="checked"' : '' ?>
                                           type="checkbox"
                                           name="orientations[ipad-landscape-right]" />
                                    <?php echo __('Landscape Right'); ?>
                                </p>
                            </label>
                        </div>
                        <div class="col-md-3 center">
                            <label>
                                <img class="ipad ud180"
                                     src="/app/sae/design/desktop/flat/images/svg/ipad.svg" />
                                <p class="orientation-checkbox">
                                    <input class="toggle-img"
                                            <?php echo ($orientations['ipad-upside-down']) ? 'checked="checked"' : '' ?>
                                           type="checkbox"
                                           name="orientations[ipad-upside-down]" />
                                    <?php echo __('Upside Down'); ?>
                                </p>
                            </label>
                        </div>

                        <div class="cold-md-12 text-right">
                            <button id="submit-orientation"
                                    class="btn color-blue"><?php echo __("Save") ?></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<style type="text/css">
    #advanced_ios_orientation .center {
        text-align: center;
    }

    #advanced_ios_orientation .margin-top-header {
        margin-top: 40px;
    }

    #advanced_ios_orientation .margin-bottom-header {
        margin-bottom: 40px;
    }

    #advanced_ios_orientation label p {
        margin-top: 20px;
    }

    #advanced_ios_orientation .orientation-checkbox {
        display: flex;
        flex-direction: row;
        text-indent: 20px;
    }

    #advanced_ios_orientation img.ipad,
    #advanced_ios_orientation img.iphone {
        width: 120px;
        filter: grayscale(100%) brightness(150%);
    }

    #advanced_ios_orientation input::before {
        filter: grayscale(100%) brightness(150%);
    }

    #advanced_ios_orientation img.ipad.active,
    #advanced_ios_orientation img.iphone.active,
    #advanced_ios_orientation input:checked::before {
        filter: grayscale(0%) brightness(100%);
    }

    #advanced_ios_orientation img.ipad.l90,
    #advanced_ios_orientation img.iphone.l90 {
        transform: rotate(-90deg);
    }

    #advanced_ios_orientation img.ipad.r90,
    #advanced_ios_orientation img.iphone.r90 {
        transform: rotate(90deg);
    }

    #advanced_ios_orientation img.ipad.ud180,
    #advanced_ios_orientation img.iphone.ud180 {
        transform: rotate(180deg);
    }
</style>

<script type="text/javascript">
    $(document).ready(function() {
        bindForms("#advanced");
        bindForms("#advanced_ios");
        bindForms("#ios_plist_orientation");

        let togglers = $('.toggle-img');
        togglers.on('click', function() {
            let el = $(this);
            if (el.prop('checked')) {
                el.parent('p').prev('img').addClass('active');
            } else {
                el.parent('p').prev('img').removeClass('active');
            }
        });

        togglers.each(function () {
            let el = $(this);
            if (el.prop('checked') || el.attr('checked') === 'checked') {
                el.parent('p').prev('img').addClass('active');
            } else {
                el.parent('p').prev('img').removeClass('active');
            }
        });

        let validateAndroid = function (values) {
            if (values.landscape && values.portrait && values.reverseLandscape && values.reversePortrait) {
                return "fullSensor";
            }
            if (!values.landscape && values.portrait && !values.reverseLandscape && values.reversePortrait) {
                return "sensorPortrait";
            }
            if (values.landscape && !values.portrait && values.reverseLandscape && !values.reversePortrait) {
                return "sensorLandscape";
            }
            if (values.landscape && !values.portrait && !values.reverseLandscape && !values.reversePortrait) {
                return "landscape";
            }
            if (!values.landscape && values.portrait && !values.reverseLandscape && !values.reversePortrait) {
                return "portrait";
            }
            if (!values.landscape && !values.portrait && values.reverseLandscape && !values.reversePortrait) {
                return "reverseLandscape";
            }
            if (!values.landscape && !values.portrait && !values.reverseLandscape && values.reversePortrait) {
                return "reversePortrait";
            }
            return false;
        };

        let androidIsValid = false;

        let validate = function (tmpValues) {
            let isValid = validateAndroid(tmpValues);
            if (!isValid) {
                androidIsValid = false;
                invalidAndroid.removeClass("hide");
                $("#submit-orientation").attr("disabled", "disabled");
            } else {
                androidIsValid = true;
                invalidAndroid.addClass("hide");
                $("#android-orientation").val(isValid);
                $("#submit-orientation").removeAttr("disabled");
            }
        };

        let checkOnchange = function () {
            /**
             // landscape
             // portrait
             // reverseLandscape
             // reversePortrait
             // sensorPortrait = 2x portrait only
             // sensorLandscape = 2x landscape only
             // fullSensor = 4
             -*/
            let tmpValues = {
                landscape: false,
                portrait: false,
                reverseLandscape: false,
                reversePortrait: false,
            };

            androids.each(function (index, item) {
                let el = $(item);
                let rel = el.attr("rel");

                switch (rel) {
                    case "landscape":
                        tmpValues.landscape = el.is(":checked");
                        break;
                    case "portrait":
                        tmpValues.portrait = el.is(":checked");
                        break;
                    case "reverseLandscape":
                        tmpValues.reverseLandscape = el.is(":checked");
                        break;
                    case "reversePortrait":
                        tmpValues.reversePortrait = el.is(":checked");
                        break;
                }
            });

            validate(tmpValues);
        };

        let invalidAndroid = $(".invalid-android");

        let androids = $('input.toggle-img.android');
        androids.off("change");
        androids.on("change", function () {
            checkOnchange();
        });

        // Onload re-check to be sure!
        checkOnchange();
    });
</script>
