<?php $option_value = $this->getOptionValue(); ?>
<?php $application = $this->getApplication(); ?>
<?php $weather = new Weather_Model_Weather(); ?>
<?php $weather->find($option_value->getId(),"value_id"); ?>
<?php $countries = Zend_Registry::get('Zend_Locale')->getTranslationList('Territory', null, 2); ?>
<?php asort($countries, SORT_LOCALE_STRING); ?>
<div id="list" class="edit_page weather">
    <form id="weatherForm" name="weatherForm" method="post" action="<?php echo $this->getUrl('weather/application/editpost') ?>">
        <h3 class="title-editor no-border-radius title-feature-indent">
            <?php echo $this->_("Weather information") ?>
        </h3>
        <input type="hidden" name="value_id" value="<?php echo $option_value->getId(); ?>" />
        <div class="container-fluid first-row-feature content-feature">
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-md-3">
                        <label for="address"><?php echo $this->_("Country:"); ?></label>
                    </div>
                    <div class="col-md-9">
                        <select id="country_code" name="country_code" class="styled-select color-blue">
                            <option value=""></option>
                            <?php foreach($countries as $key => $country): ?>
                                <option value="<?php echo $key; ?>" <?php if($key == $weather->getCountryCode()) echo "selected"; ?>><?php echo $country; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <label for="address"><?php echo $this->_("Postal code or city:"); ?></label>
                    </div>
                    <div class="col-md-9">
                        <input type="text" id="city" name="city" class="input-flat" value="<?php echo $weather->getCity(); ?>"/>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <label for="address"><?php echo $this->_("Units:"); ?></label>
                    </div>
                    <div class="col-md-9">
                        <select id="unit" name="unit" class="styled-select color-blue">
                            <option value="f" <?php if($weather->getUnit() == "f") echo "selected"; ?>>°F, mph, mi</option>
                            <option value="c" <?php if($weather->getUnit() == "c") echo "selected"; ?>>°C, km/h, km</option>
                        </select>
                    </div>
                </div>
                <div class="form-group"> 
                    <div class="col-md-12">
                        <button class="pull-right btn color-blue" type="submit">
                            <?php echo $this->_('Save'); ?>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<div class="background background-upload-image">
    <?php echo $this->importBackground($option_value); ?>
</div>

<script type="text/javascript">

    $(document).ready(function () {
        bindForms('#list');
        bindForms('.background-upload-image');
    });

    page.setCallback('didappear', function() {

        $('#weatherForm').submit(function() {
            if(!$(this).valid()) return false;
            reload($('#weatherForm'), '<?php echo $this->getUrl('weather/application/editpost') ?>', true, function(data) {
                if(data.success) {
                    page.reload();
                }
            });
            return false;
        });

    });

    page.setCallback('willdisappear', function() {
        $('#weatherForm').unbind('submit');
    });

</script>
<style>

</style>
