<?php $option_value = $this->getOptionValue(); ?>
<?php $application = $this->getApplication(); ?>
<?php $woocommerce = $option_value->getObject(); ?>
<div id="list" class="edit_page">
    <div class="woocommerce">
        <form id="woocommerceForm" name="woocommerceForm" method="post" action="<?php echo $this->getUrl('weblink/application_woocommerce/editpost') ?>" class="form-horizontal">
            <h3 class="title-editor no-border-radius title-feature-indent">
                <?php echo $this->_('WooCommerce') ?>
            </h3>
            <input type="hidden" name="value_id" value="<?php echo $option_value->getId(); ?>" />
            <div class="container-fluid first-row-feature content-feature">
                <div class="infos">
                    <div id="woocommerce_content">
                        <div class="form-group">
                            <div class="col-sm-12">
                                <input type="text" id="woocommerce" name="link" class="input-flat url" placeholder="<?php echo $this->_('Enter your WooCommerce URL') ?>" value="<?php echo $woocommerce->getLink()->getUrl() ?>"/>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-12">
                        <div class="save pull-right">
                            <button class="btn btn-block color-blue" type="submit">
                                <?php echo $this->_('Save'); ?>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<script type="text/javascript">

    page.setCallback('didappear', function() {

        $('#woocommerce').change(function() {
            if(!$(this).val().isEmpty() && !$(this).val().startsWith('http://') && !$(this).val().startsWith('https://')) {
                $(this).val('http://'+$(this).val());
            }
        });
        $('#woocommerceForm').submit(function() {
            if(!$(this).valid()) return false;
            reload(this, this.action, true, function(datas) {
                if(datas.success) {
                    if(iframe.f.isHomepage()) {
                        iframe.f.reload();
                    }
                }
            });
            return false;
        });

    });

    page.setCallback('willdisappear', function() {
        $('#woocommerce').unbind('change');
        $('#woocommerceForm').unbind('submit');
    });

</script>