<?php

$optionValue = $this->getOptionValue();
$approvals = $this->getApprovals();
$application = $this->getApplication();
$appName = $application->getName();

?>

<div role="tabpanel"
     class="tab-pane"
     id="approval">

    <div class="feature-block-list">
        <div>
            <h3 class="title-editor no-border-radius title-feature-indent">
                <?php echo p__('fanwall', 'Publications awaiting approval'); ?>
                <button type="button"
                        class="toggle_design color-blue pull-right bt-header-right btn feature-toggle-items">
                    <i class="fa fa-angle-down"></i>
                </button>
            </h3>
            <div class="container-fluid first-row-feature content-feature feature-manage-items">
                <table class="table content-white-bkg sb-pager">
                    <thead>
                        <tr class="border-grey">
                            <th class="sortable"
                                style="width:25%;"><?php echo p__('fanwall', 'Author'); ?></th>
                            <th class="sortable"
                                style="width:40%;"><?php echo p__('fanwall', 'Post'); ?></th>
                            <th class="sortable numeric"
                                style="width:20%;"><?php echo p__('fanwall', 'Pub. date'); ?></th>
                            <th style="width:15%;"></th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php if ($approvals->count() > 0): ?>
                        <?php foreach ($approvals as $approval) : ?>
                            <tr id="approval_element_<?php echo $approval->getId(); ?>">
                                <td>
                                    <?php if ($approval->getcustomerId()): ?>
                                        <a class="btn btn-xs btn-info"
                                           href="<?php echo __path("/customer/application/edit/", [
                                               "customer_id" => $approval->getCustomerId()
                                           ]); ?>">
                                            #<?php echo $approval->getcustomerId() ?> - <i><?php echo $approval->getFirstname() . " " . $approval->getLastname(); ?></i>
                                        </a>
                                    <?php else: ?>
                                        <b><?php echo $appName; ?></b> <i>(<?php echo p__("fanwall", "App") ?>)</i>
                                    <?php endif; ?>
                                </td>
                                <td><?php echo cut(base64_decode($approval->getText()), 500); ?></td>
                                <td>
                                    <span style="display: none;"><?php echo $approval->getDate(); ?></span>
                                    <span class="moment_format"><?php echo $approval->getDate(); ?></span>
                                </td>
                                <td class="text-right">
                                    <button class="btn btn-xs btn-success"><?php echo p__('fanwall', 'Approve') ?></button>
                                    <button class="btn btn-xs btn-danger"><?php echo p__('fanwall', 'Reject') ?></button>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <tr>
                            <td colspan="5"><?php echo p__('fanwall', 'No pending requests.') ?></td>
                        </tr>
                    <?php endif; ?>
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>
