<?php

$optionValue = $this->getOptionValue();
$formPost = $this->getFormPost();
$posts = $this->getPosts();
$formPostToggle = $this->getFormPostToggle();
$formPostPin = $this->getFormPostPin();
$formPostDelete = $this->getFormPostDelete();

?>

<div role="tabpanel"
     class="tab-pane active"
     id="posts">
    <div class="feature-block-add">
        <h3 class="title-editor no-border-radius title-feature-indent">
            <?php echo p__("fanwall", "Add a post"); ?>
            <button type="button"
                    class="feature-toggle-add toggle_design color-blue pull-right bt-header-right btn">
                <i class="fa fa-plus"></i>
            </button>
        </h3>
    </div>

    <div class="feature-block-create">
        <h3 class="title-editor no-border-radius title-feature-indent">
            <?php echo p__("fanwall", "Create a post"); ?>
        </h3>
        <div class="container-fluid subcontent content-feature">
            <?php echo $formPost; ?>
        </div>
    </div>

    <?php echo $this->createPartialHtml("no_item", "core_view_default", "application/customization/features/edit/no_item.phtml"); ?>

    <?php if ($posts->count() > 0): ?>
    <div class="feature-block-list">
        <div class="margin-top">
            <h3 class="title-editor no-border-radius title-feature-indent">
                <?php echo p__("fanwall", "Manage posts"); ?>
                <button type="button"
                        class="toggle_design color-blue pull-right bt-header-right btn feature-toggle-items">
                    <i class="fa fa-angle-down"></i>
                </button>
            </h3>
            <div class="container-fluid first-row-feature content-feature feature-manage-items">
                <table class="table content-white-bkg sb-pager">
                    <thead>
                        <tr class="border-grey">
                            <th class="sortable"
                                style="width:10%;"><?php echo p__("fanwall", "Title"); ?></th>
                            <th class="sortable"
                                style="width:10%;"><?php echo p__("fanwall", "Subtitle"); ?></th>
                            <th class="sortable"
                                style="width:50%;"><?php echo p__("fanwall", "Post"); ?></th>
                            <th class="sortable date"
                                style="width:20%;"><?php echo p__("fanwall", "Pub. date"); ?></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($posts as $post) : ?>
                        <tr id="post_manage_element_<?php echo $post->getId(); ?>"
                            class="post-manage-element sb-pager">
                            <td><?php echo cut($post->getTitle(), 30); ?></td>
                            <td><?php echo cut($post->getSubtitle(), 30); ?></td>
                            <td><?php echo cut($post->getText(), 500); ?></td>
                            <td><?php echo $post->getDate(); ?></td>
                            <td class="toggle-action">
                                <?php
                                $formPostPin->getElement("post_id")->setValue($post->getId());
                                $formPostPin->setToggleState($post->getSticky());
                                echo $formPostPin;
                                ?>
                            </td>
                            <td class="toggle-action">
                                <?php
                                $formPostToggle->getElement("post_id")->setValue($post->getId());
                                $formPostToggle->setToggleState($post->getIsVisible());
                                echo $formPostToggle;
                                ?>
                            </td>
                            <td class="edit-action open-edit"
                                data-id="post_<?php echo $post->getId(); ?>"
                                data-form-url="<?php echo __path("/fanwall/application/load-form", ["post_id" => $post->getId(), "value_id" => $optionValue->getId()]); ?>">
                                <i class="fa fa-pencil"></i>
                            </td>
                            <td class="delete-action">
                                <?php
                                $formPostDelete->setAttrib("data-rowid", "post_manage_element_" . $post->getId());
                                $formPostDelete->getElement("post_id")->setValue($post->getId());
                                echo $formPostDelete;
                                ?>
                            </td>
                        </tr>
                        <tr class="edit-form"
                            data-id="post_<?php echo $post->getId(); ?>"
                            style="display: none;">
                            <td colspan="8">
                                <p class="close-edit"
                                   data-id="post_<?php echo $post->getId(); ?>">
                                    <i class="fa fa-times"></i><?php echo p__("fanwall", "Close") ?>
                                </p>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>

            </div>
        </div>
    </div>
    <?php endif; ?>
</div>