<link ng-if="configs.backoffice_theme.value == 'default' || configs.backoffice_theme.value == ''"
      href="/app/sae/design/desktop/backoffice/css/theme-default/styles.css?t=<?php echo time() ?>"
      media="all"
      rel="stylesheet"
      type="text/css"/>

<link ng-if="configs.backoffice_theme.value == 'modern'"
      href="/app/sae/design/desktop/backoffice/css/theme-modern/styles.css?t=<?php echo time() ?>"
      media="all"
      rel="stylesheet"
      type="text/css"/>

<link ng-if="configs.backoffice_theme.value == 'elegance'"
      href="/app/sae/design/desktop/backoffice/css/theme-elegance/styles.css?t=<?php echo time() ?>"
      media="all"
      rel="stylesheet"
      type="text/css"/>

<form ng-submit="save()">

    <sb-section title="'<?php echo __js('Backoffice theme') ?>'">
        <div class="form-group">
            <div class="row">
                <div class="col-md-6">
                    <div class="alert alert-info">
                        <?php echo __('<b>Info</b>: Theme alert box preview.') ?>
                    </div>
                    <div class="alert alert-success">
                        <?php echo __('<b>Success</b>: Theme alert box preview.') ?>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="alert alert-warning">
                        <?php echo __('<b>Warning</b>: Theme alert box preview.') ?>
                    </div>
                    <div class="alert alert-danger">
                        <?php echo __('<b>Danger</b>: Theme alert box preview.') ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <label for="backoffice_theme"><?php echo __("Theme"); ?></label>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <select id="backoffice_theme"
                            class="form-control"
                            ng-model="configs.backoffice_theme.value">
                        <option value="default"
                                ng-selected="configs.backoffice_theme.value == 'default' || configs.backoffice_theme.value == ''"><?php echo __('Default') ?></option>
                        <option value="elegance"
                                ng-selected="configs.backoffice_theme.value == 'elegance'"><?php echo __('Elegance') ?></option>
                        <option value="modern"
                                ng-selected="configs.backoffice_theme.value == 'modern'"><?php echo __('Modern') ?></option>
                    </select>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-md-12">
                    <button type="submit"
                            class="btn btn-primary right"><?php echo __("Save"); ?></button>
                    <sb-loader is_visible="form_loader_is_visible"
                               type="'inner_content'"
                               size="'small'"
                               animation="'no'"
                               class="form_loader"></sb-loader>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </sb-section>

    <sb-section title="'<?php echo __js('Backoffice page Title') ?>'">
        <div class="form-group">
            <div class="row">
                <div class="col-md-12">
                    <div class="alert alert-info">
                        <?php echo __('You can change the browser tab title with the translations: Edit the backoffice.csv and translate Siberian - Backoffice.') ?>
                    </div>
                </div>
            </div>
        </div>
    </sb-section>

    <sb-section title="configs.logo.label"
                class="upload_area">
        <p class="help-block">
            <?php echo __("<b>File types:</b> %s<br /><b>Recommended size:</b> %s", "png, jpeg, gif", "368x85px") ?>
        </p>

        <br/>

        <div class="col-md-3">
            <div class="upload_a_file">
                <label for="logo_uploader"><?php echo __("Click here to send your logo"); ?></label>
                <input id="logo_uploader"
                       type="file"
                       nv-file-select=""
                       uploader="logo_uploader"/>
            </div>
        </div>

        <div class="col-md-1">
            <div class="drop_a_file">
                <label><?php echo __("OR"); ?></label>
            </div>
        </div>

        <div class="col-md-5">
            <div class="drop_a_file">
                <label><?php echo __("Drop your logo here"); ?></label>
                <div ng-show="logo_uploader.isHTML5">
                    <div class="well drop-zone"
                         nv-file-drop=""
                         nv-file-over=""
                         uploader="logo_uploader">
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-3"
             ng-if="configs.logo.value">
            <label><?php echo __("Current logo"); ?></label>
            <div>
                <img ng-src="{{ configs.logo.value }}"
                     width="100"/>
            </div>
        </div>


        <div class="clear"></div>

        <table class="table"
               ng-show="logo_uploader.queue.length">
            <thead>
            <tr>
                <th width="50%">Name</th>
                <th ng-show="logo_uploader.isHTML5">Size</th>
                <th ng-show="logo_uploader.isHTML5">Progress</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            <tr ng-repeat="item in logo_uploader.queue"
                ng-show="logo_uploader.queue.length">
                <td>
                    <strong>{{ item.file.name }}</strong>
                    <div ng-show="logo_uploader.isHTML5"
                         ng-thumb="{ file: item._file, height: 100 }"></div>
                </td>
                <td ng-show="logo_uploader.isHTML5"
                    nowrap>{{ item.file.size/1024/1024|number:2 }} MB</td>
                <td ng-show="logo_uploader.isHTML5">
                    <div class="progress">
                        <div class="progress-bar progress-bar-striped"
                             role="progressbar"
                             ng-style="{ 'width': item.progress + '%' }"></div>
                    </div>
                </td>
                <td class="text-center">
                    <span ng-show="item.isSuccess"><i class="fa fa-check"></i></span>
                    <span ng-show="item.isCancel"><i class="fa fa-ban"></i></span>
                    <span ng-show="item.isError"><i class="fa fa-remove"></i></span>
                </td>
                <td nowrap>
                    <button type="button"
                            class="btn btn-warning btn-xs"
                            ng-click="item.cancel()"
                            ng-disabled="!item.isUploading">
                        <span class="fa fa-ban"></span>
                    </button>
                    <button type="button"
                            class="btn btn-danger btn-xs"
                            ng-click="item.remove()"
                            ng-disabled="item.isReady || item.isUploading || item.isSuccess">
                        <span class="fa fa-remove"></span>
                    </button>
                </td>
            </tr>
            </tbody>
        </table>

    </sb-section>

    <div class="clear"></div>

    <sb-section title="configs.favicon.label"
                class="upload_area">
        <p class="help-block"><?php echo __("<b>File type:</b> %s<br /><b>Recommended size:</b> %s", "png", "32x32px"); ?></p>

        <br/>
        <div class="col-md-3">
            <div class="upload_a_file">
                <label for="favicon_uploader"><?php echo __("Click here to send your favicon"); ?></label>
                <input id="favicon_uploader"
                       type="file"
                       nv-file-select=""
                       uploader="favicon_uploader"/>
            </div>
        </div>

        <div class="col-md-1">
            <label><?php echo __("OR"); ?></label>
        </div>

        <div class="col-md-5">
            <div class="drop_a_file left">
                <label><?php echo __("Drop your favicon here"); ?></label>
                <div ng-show="favicon_uploader.isHTML5">
                    <div class="well drop-zone"
                         nv-file-drop=""
                         nv-file-over=""
                         uploader="favicon_uploader">
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-3"
             ng-if="configs.favicon.value">
            <label><?php echo __("Current favicon"); ?></label>
            <div>
                <img ng-src="{{ configs.favicon.value }}"
                     width="32"
                     height="32"/>
            </div>
        </div>

        <div class="clear"></div>

        <table class="table"
               ng-show="favicon_uploader.queue.length">
            <thead>
            <tr>
                <th width="50%">Name</th>
                <th ng-show="favicon_uploader.isHTML5">Size</th>
                <th ng-show="favicon_uploader.isHTML5">Progress</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            <tr ng-repeat="item in favicon_uploader.queue"
                ng-show="favicon_uploader.queue.length">
                <td>
                    <strong>{{ item.file.name }}</strong>
                    <div ng-show="favicon_uploader.isHTML5"
                         ng-thumb="{ file: item._file, height: 100 }"></div>
                </td>
                <td ng-show="favicon_uploader.isHTML5"
                    nowrap>{{ item.file.size/1024/1024|number:2 }} MB</td>
                <td ng-show="favicon_uploader.isHTML5">
                    <div class="progress">
                        <div class="progress-bar progress-bar-striped"
                             role="progressbar"
                             ng-style="{ 'width': item.progress + '%' }"></div>
                    </div>
                </td>
                <td class="text-center">
                    <span ng-show="item.isSuccess"><i class="fa fa-check"></i></span>
                    <span ng-show="item.isCancel"><i class="fa fa-ban"></i></span>
                    <span ng-show="item.isError"><i class="fa fa-remove"></i></span>
                </td>
                <td nowrap>
                    <button type="button"
                            class="btn btn-warning btn-xs"
                            ng-click="item.cancel()"
                            ng-disabled="!item.isUploading">
                        <span class="fa fa-ban"></span>
                    </button>
                    <button type="button"
                            class="btn btn-danger btn-xs"
                            ng-click="item.remove()"
                            ng-disabled="item.isReady || item.isUploading">
                        <span class="fa fa-remove"></span>
                    </button>
                </td>
            </tr>
            </tbody>
        </table>

    </sb-section>

    <div class="clear"></div>

    <sb-section title="configs.logo_backoffice.label"
                class="upload_area">
        <p class="help-block">
            <?php echo __("<b>File types:</b> %s<br /><b>Recommended size:</b> %s", "png, jpeg, gif", "368x85px") ?>
        </p>

        <br/>

        <div class="col-md-3">
            <div class="upload_a_file">
                <label for="logo_backoffice_uploader"><?php echo __("Click here to send your logo"); ?></label>
                <input id="logo_backoffice_uploader"
                       type="file"
                       nv-file-select=""
                       uploader="logo_backoffice_uploader"/>
            </div>
        </div>

        <div class="col-md-1">
            <div class="drop_a_file">
                <label><?php echo __("OR"); ?></label>
            </div>
        </div>

        <div class="col-md-5">
            <div class="drop_a_file">
                <label><?php echo __("Drop your logo here"); ?></label>
                <div ng-show="logo_backoffice_uploader.isHTML5">
                    <div class="well drop-zone"
                         nv-file-drop=""
                         nv-file-over=""
                         uploader="logo_backoffice_uploader">
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-3"
             ng-if="configs.logo_backoffice.value">
            <label><?php echo __("Current logo"); ?></label>
            <div>
                <img ng-src="{{ configs.logo_backoffice.value }}"
                     width="100"/>
            </div>
        </div>


        <div class="clear"></div>

        <table class="table"
               ng-show="logo_backoffice_uploader.queue.length">
            <thead>
            <tr>
                <th width="50%">Name</th>
                <th ng-show="logo_backoffice_uploader.isHTML5">Size</th>
                <th ng-show="logo_backoffice_uploader.isHTML5">Progress</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            <tr ng-repeat="item in logo_backoffice_uploader.queue"
                ng-show="logo_backoffice_uploader.queue.length">
                <td>
                    <strong>{{ item.file.name }}</strong>
                    <div ng-show="logo_backoffice_uploader.isHTML5"
                         ng-thumb="{ file: item._file, height: 100 }"></div>
                </td>
                <td ng-show="logo_backoffice_uploader.isHTML5"
                    nowrap>{{ item.file.size/1024/1024|number:2 }} MB</td>
                <td ng-show="logo_backoffice_uploader.isHTML5">
                    <div class="progress">
                        <div class="progress-bar progress-bar-striped"
                             role="progressbar"
                             ng-style="{ 'width': item.progress + '%' }"></div>
                    </div>
                </td>
                <td class="text-center">
                    <span ng-show="item.isSuccess"><i class="fa fa-check"></i></span>
                    <span ng-show="item.isCancel"><i class="fa fa-ban"></i></span>
                    <span ng-show="item.isError"><i class="fa fa-remove"></i></span>
                </td>
                <td nowrap>
                    <button type="button"
                            class="btn btn-warning btn-xs"
                            ng-click="item.cancel()"
                            ng-disabled="!item.isUploading">
                        <span class="fa fa-ban"></span>
                    </button>
                    <button type="button"
                            class="btn btn-danger btn-xs"
                            ng-click="item.remove()"
                            ng-disabled="item.isReady || item.isUploading || item.isSuccess">
                        <span class="fa fa-remove"></span>
                    </button>
                </td>
            </tr>
            </tbody>
        </table>

    </sb-section>

    <div class="clear"></div>

    <sb-section title="configs.favicon_backoffice.label"
                class="upload_area">
        <p class="help-block"><?php echo __("<b>File type:</b> %s<br /><b>Recommended size:</b> %s", "png", "32x32px"); ?></p>

        <br/>
        <div class="col-md-3">
            <div class="upload_a_file">
                <label for="favicon_backoffice"><?php echo __("Click here to send your favicon"); ?></label>
                <input id="favicon_backoffice"
                       type="file"
                       nv-file-select=""
                       uploader="favicon_backoffice_uploader"/>
            </div>
        </div>

        <div class="col-md-1">
            <label><?php echo __("OR"); ?></label>
        </div>

        <div class="col-md-5">
            <div class="drop_a_file left">
                <label><?php echo __("Drop your favicon here"); ?></label>
                <div ng-show="favicon_backoffice_uploader.isHTML5">
                    <div class="well drop-zone"
                         nv-file-drop=""
                         nv-file-over=""
                         uploader="favicon_backoffice_uploader">
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-3"
             ng-if="configs.favicon_backoffice.value">
            <label><?php echo __("Current favicon"); ?></label>
            <div>
                <img ng-src="{{ configs.favicon_backoffice.value }}"
                     width="32"
                     height="32"/>
            </div>
        </div>

        <div class="clear"></div>

        <table class="table" ng-show="favicon_backoffice_uploader.queue.length">
            <thead>
            <tr>
                <th width="50%">Name</th>
                <th ng-show="favicon_backoffice_uploader.isHTML5">Size</th>
                <th ng-show="favicon_backoffice_uploader.isHTML5">Progress</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            <tr ng-repeat="item in favicon_backoffice_uploader.queue"
                ng-show="favicon_backoffice_uploader.queue.length">
                <td>
                    <strong>{{ item.file.name }}</strong>
                    <div ng-show="favicon_backoffice_uploader.isHTML5"
                         ng-thumb="{ file: item._file, height: 100 }"></div>
                </td>
                <td ng-show="favicon_backoffice_uploader.isHTML5"
                    nowrap>{{ item.file.size/1024/1024|number:2 }} MB
                </td>
                <td ng-show="favicon_backoffice_uploader.isHTML5">
                    <div class="progress">
                        <div class="progress-bar progress-bar-striped"
                             role="progressbar"
                             ng-style="{ 'width': item.progress + '%' }"></div>
                    </div>
                </td>
                <td class="text-center">
                    <span ng-show="item.isSuccess"><i class="fa fa-check"></i></span>
                    <span ng-show="item.isCancel"><i class="fa fa-ban"></i></span>
                    <span ng-show="item.isError"><i class="fa fa-remove"></i></span>
                </td>
                <td nowrap>
                    <button type="button"
                            class="btn btn-warning btn-xs"
                            ng-click="item.cancel()"
                            ng-disabled="!item.isUploading">
                        <span class="fa fa-ban"></span>
                    </button>
                    <button type="button"
                            class="btn btn-danger btn-xs"
                            ng-click="item.remove()"
                            ng-disabled="item.isReady || item.isUploading">
                        <span class="fa fa-remove"></span>
                    </button>
                </td>
            </tr>
            </tbody>
        </table>

    </sb-section>

</form>