<table>
    <tr style="padding: 0 15px; color:#888888; font-size: 17px; line-height: 150%; width:600px">
        <td>
            <p style="font-family: Verdana; font-weight: bold;color: #404040;font-size:18px; line-height:150%;"><?php echo __("Hello,"); ?></p>
            <p align="justify">
                <span style="color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 13px;">
                    <?php echo __("You have received a message for the booking of"); ?> <strong><?php echo $this->getData("name") ?></strong><br />
                </span>
            </p>
            <p align="justify" style="color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 13px;">
                <?php echo __("Here are his personal information:"); ?>
                <ul>
                    <li><?php echo __("Name:"); ?> <?php echo $this->getData("name"); ?></li>
                    <?php if($this->getData("phone")) : ?><li><?php echo __("Phone number:"); ?> <?php echo $this->getData("phone"); ?></li><?php endif; ?>
                    <?php if($this->getData("email")) : ?><li><?php echo __("Email address:"); ?> <a href="mailto:<?php echo $this->getData("email"); ?>"><?php echo $this->getData("email"); ?></a></li><?php endif; ?>
                </ul>
            </p>
            <p align="justify" style="color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 13px;">
                <?php echo __("Booking details:"); ?>
                <ul>
                    <li><?php echo __("Date and time:"); ?> <?php echo $this->getData("date"); ?></li>
                    <li><?php echo __("Number of people"); ?>: <?php echo $this->getData("people"); ?></li>
                    <li><?php echo __("Booking subject:"); ?> <?php echo $this->getData("prestation"); ?></li>
                    <li><?php echo __("Booking location:"); ?> <?php echo $this->getData("location"); ?></li>
                    <?php if($this->getData("comment")) : ?><li><?php echo __("Comment:"); ?> <?php echo $this->getData("comment"); ?></li><?php endif; ?>
                </ul>
            </p>
        </td>
    </tr>
</table>