<?php
$store = $this->getStore();
$method = $store->getPaymentMethod('paypal')->getInstance();
?>

<?php if ($method->getId()): ?>
<div class="form-group paypal_data">
    <div class="col-sm-3">
        <label for="paypal_user"><?php echo __("Username:"); ?> <span>*</span></label>
    </div>
    <div class="col-sm-5">
        <input type="text"
               id="paypal_user"
               class="input-flat required"
               name="details_payment_methods[<?php echo $method->getMethod()->getMethodId(); ?>][user]"
               value="<?php echo $method->getUser(); ?>"
               placeholder="<?php echo __("Username"); ?>" />
    </div>
</div>
<div class="form-group paypal_data">
    <div class="col-sm-3">
        <label for="paypal_password"><?php echo __("Password:"); ?> <span>*</span></label>
    </div>
    <div class="col-sm-5">
        <input type="text"
               id="paypal_password"
               class="input-flat required"
               name="details_payment_methods[<?php echo $method->getMethod()->getMethodId(); ?>][password]"
               value="<?php echo $method->getPassword(); ?>"
               placeholder="<?php echo __('Password'); ?>" />
    </div>
</div>
<div class="form-group paypal_data">
    <div class="col-sm-3">
        <label for="paypal_signature">
            <?php echo __("Signature:"); ?> <span>*</span>
        </label>
    </div>
    <div class="col-sm-5">
        <input type="text"
               id="paypal_signature"
               class="input-flat required"
               name="details_payment_methods[<?php echo $method->getMethod()->getMethodId(); ?>][signature]"
               value="<?php echo $method->getSignature(); ?>"
               placeholder="<?php echo __('Signature'); ?>" />
    </div>
</div>
<?php endif; ?>