<?php $option_value = $this->getOptionValue(); ?>
<?php $agenda = $this->getCurrentEvent(); ?>
<div class="content-options content-white-bkg">
    <div class="row">
        <div class="col-md-12">
            <div class="buttons">
                <button type="button" onclick="custom.unbindAll(); feature.list();" class="color-blue btn pull-left"><i class="fa fa-angle-left"></i></button>
            </div>
        </div>
    </div>
    <fieldset>
        <form id="eventForm" action="<?php echo $this->getUrl('event/application/editpost'); ?>" class="form-horizontal first-row-feature">
            <div class="form-group">
                <div class="col-sm-5 col-sm-offset-3">
                    <label><?php echo $this->_('Enter your calendar\'s title') ?> <span class="required-entry"> *</span> :</label>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-3">
                    <label><?php echo $this->_('Title:')?></label>
                </div>
                <div class="col-sm-5">
                    <input type="text" name="name" value="<?php echo $agenda->getName()?>" placeholder="<?php echo $this->_('Calendar\'s title') ?>" class="input-flat required" />
                </div>
                <div class="col-sm-2">
                    <input type="hidden" name="url" value="" class="input-flat"/>
                    <input type="hidden" name="option_value_id" value="<?php echo $option_value->getId(); ?>" class="input-flat"/>
                    <input id="agenda_id" type="hidden" name="id" value="<?php echo $agenda->getId(); ?>" class="input-flat"/>
                    <input type="hidden" name="event_type" value="<?php echo $this->getEventType(); ?>" class="input-flat"/>
                    <button type="submit" class="bt-margin validate btn color-blue save_event">OK</button>
                </div>
        </form>
    </fieldset>
    <?php if($agenda->getId()):?>
        <div id="custom_content" class="agenda inner_content">
            <div class="details">
                <h4 class="no-border-radius"> <?php echo $agenda->getName()?> </h4>
            </div>
            <div class="custom_content" >
                <?php if($this->getEvents()->count() > 0) : ?>
                    <?php $date = new Zend_Date?>
                    <div class="table_row_agenda container-fluid">
                        <ul class="list-group">
                            <?php foreach($this->getEvents() as $event):?>
                                <li class="list-group-item">
                                    <div id="custom_line_<?php echo $event->getId()?>" class="event_rows row">
                                        <div class="col-sm-5 events_name">
                                            <label><?php echo Core_Model_Lib_String::truncate($event->getName(), 35)?></label>
                                        </div>
                                        <div class="col-sm-5 start_at">
                                            <?php echo $event->getFormattedStartAt($this->_("MM/dd/y \'at\' hh:mm a")); ?>
                                        </div>
                                        <div class="col-sm-2 actions">
                                            <a class="edit_event" href="<?php echo $this->getUrl('event/application_event/form', array('agenda_id' => $agenda->getId(), 'event_id'=>$event->getId(), 'option_value_id' => $option_value->getId())); ?>?ajax=true" >
                                                <i class="fa fa-pencil"></i>
                                            </a>
                                            <a href="javascript:void(0);" id="custom_<?php echo $event->getId()?>" onclick="custom.remove(<?php echo $event->getId()?>)">
                                            <i class="fa fa-times"></i>
                                                <input type="hidden" name="option_value_id" value="<?php echo $option_value->getId(); ?>" />
                                            </a>
                                        </div>
                                    </div>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                <?php else: ?>
                    <ul class="list-group">
                        <li class="list-group-item"><?php echo $this->_("Your calendar is empty")?></li>
                    </ul>
                <?php endif;?>
            </div>
            <a class="edit_event underline edit_event underline color-blue btn" id="new_event_link" href="<?php echo $this->getUrl('event/application_event/form', array('agenda_id' => $agenda->getId(), 'option_value_id' => $option_value->getId())); ?>?ajax=true"><?php echo $this->_('Event'); ?></a>
        </div>
    <?php endif; ?>

    <style type="text/css">
        .agenda div.add { padding: 0px 10px 10px; }
        .event_rows td {
            /*text-align: center;*/
            padding: 2px;
            margin: 0;
        }
        .events_name  {
            text-align: left;
            font-weight: bold;
            /*width: 45%;*/
        }

        .start_at  {
            /*text-align: center;*/
            /*width: 45%;*/
        }

        .actions  {
            text-align: right;
        }
    </style>

    <script type="text/javascript">

        custom = {
            website_template: "",
            processEvents: function() {
                $.datepicker.setDefaults( $.datepicker.regional['<?php echo Core_Model_Language::getCurrentLanguageDatepicker() ?>']);
                $('.edit_event').prettyPhoto({
                    default_width: 500,
                    show_title: false,
                    deeplinking: false,
                    social_tools: '',
                    gallery_markup: '',
                    keyboard_shortcuts: false,
                    changepicturecallback: function() {
                        custom.website_template = $("#custom_event_website_new").html();
                        $("#custom_event_website_new").remove();
                        $('#custom_event_start_at').datetimepicker({
                            dateFormat: 'yy-mm-dd'
                        });
                        $('#custom_event_end_at').datetimepicker({
                            dateFormat: 'yy-mm-dd'
                        });

                        $('#custom_event_description').ckeditor(ckeditor_config.default);
                        $("#custom_add_website").click(function() {
                            var html = custom.website_template;
                            html = html.replaceAll("new", $(".custom_event_website").length+1);
                            $("#custom_add_website").parent().parent().before(html);
                        });
                        uploadPicture();
                    },
                    theme: 'pp_none'
                });

                $('#eventForm').unbind('submit');
                $('#eventForm').submit(function(e) {
                    var form = $(e.target);
                    if(!form.valid()) return false;
                    reload(form, form.attr('action'), true, function(datas) {
                        if(datas.success) {
                            $('#agenda_id').val(datas.agenda_id);
                            this.reload();
                        }
                    }.bind(this));
                    return false;
                }.bind(this));

                return this;

            },
            unbindAll: function() {
                $('.edit_event').unbind('click');
                $('#eventForm').unbind('submit');
                return this;
            },
            removepicture: function() {
                $('#picture').val('');
                $('#btn_validate_crop').remove();
                $('#event_picture').fadeIn('slow', function() {
                    $('#event_picture').html('');
                });
                $('#delete_picture').fadeIn('slow', function() {
                    $('#delete_picture').remove();
                });
                return false;
            },

            cancel: function() {
                $('#eventForm').unbind('submit');
                $('#custom_event_start_at').datepicker("destroy");
                $('#custom_event_end_at').datepicker("destroy");
                $.prettyPhoto.close();
            },
            remove: function(id) {
                var td = $('#custom_'+id).parent();
                var tr = td.parent();
                if(confirm('<?php echo addslashes($this->_("Delete this event?")); ?>')) {
                    $('<input />').attr('type', 'hidden')
                        .attr('name', 'id')
                        .val(id)
                        .appendTo(td)
                    ;

                    reload(tr, '<?php echo $this->getUrl('event/application_event/delete'); ?>', true, function(datas) {
                        if(datas.success) {
                            tr.animate({'background-color': 'transparent', height: 0, padding: 0, opacity: 0}, 500, null, function() {tr.remove();});
                            iframe.f.reload();
                        }
                    });
                }

            },
            removeWebsite: function(id) {
                $(".group_"+id).remove();
            },
            reload: function() {

                this.unbindAll();
                reload($('#eventForm'), "<?php echo $this->getUrl('event/application/form'); ?>", true, function(datas) {
                    if(datas.form_html) {
                        $('#edit').html(datas.form_html);
                        this.processEvents();
                    }
                }.bind(this));

                iframe.f.reload();
            },
            save: function() {
                var form = $('#customEventForm');

                if(!form.valid()) return false;
                $('.uploader_picture').attr('disabled', 'disabled');

                reload(form, form.attr('action'), true, function(datas) {
                    if(datas.success) {
                        $.prettyPhoto.close();
                        this.reload();
                    }
                }.bind(this));

                return false;
            }
        }
    </script>
</div>
<style type="text/css">
    .ui-datepicker{
        z-index: 9999999 !important;
    }
</style>
