<?php $option = $this->getCurrentOptionValue(); ?>
<?php $tax = $this->getCurrentTax(); ?>

<li id="tax_row_<?php echo $tax->getId(); ?>" class="tax list-group-item content-white-bkg" rel="<?php echo $tax->getId(); ?>">
    <div class="form-group">
        <div class="col-md-10">
            <div id="tax_name_<?php echo $tax->getId() ?>"><?php echo $tax->getName(); ?></div>
        </div>
        <div class="col-md-2 text-right" id="tax_icons_<?php echo $tax->getId(); ?>">
            <a href="javascript:void(0)" id="edit_tax_<?php echo $tax->getId(); ?>" class="edit_tax" rel="<?php echo $tax->getId() ?>">
                <i class="fa fa-pencil"></i>
            </a>
            <a href="javascript:void(0)" id="remove_tax_<?php echo $tax->getId(); ?>" class="remove_tax" rel="<?php echo $tax->getId() ?>">
                <i class="fa fa-remove"></i>
            </a>
            <input type="hidden" name="option_value_id" value="<?php echo $option->getId(); ?>" />
        </div>
    </div>
</li>