<?php $application = $this->getApplication(); ?>
<div class="installer application">
    <div class="application_content inner_content">
        <div class="title">
            <i class="left icon-download-alt"></i>
            <h2 class="left inner_content f-rounded"><?php echo __('Modules'); ?></h2>
            
            <hr />
        </div>
        <div>
            <h3 class="title">
                <span><?php echo __('Upload a module'); ?></span>
                
            </h3>
            <div>
                <form id="uploadModule" method="post" name="uploadModule" action="<?php echo $this->getUrl('installer/module/upload'); ?>" enctype="multipart/form-data">
                    <br />
                    <div><p><?php echo __('Select a module to upload'); ?></p></div>
                    <br />
                    <div><input type="file" name="module" value="" /></div>
                    <br />
                    <div><button class="btn"><?php echo __('Send'); ?></button></div>
                </form>
            </div>
        </div>
    </div>
    <style>
        .installer .inner_content .btn {
            width: auto;
            padding: 0 10px;
        }
    </style>
</div>