<?php
$option = $this->getOptionValue();

$available_icons = array($option->getLibrary()->getIcons());

if($option->getCode() == 'folder') {
    $a_option = new Application_Model_Option();
    $options = $a_option->findAll();
    foreach($options as $other_option) {
        if($other_option->getCode() == 'folder') {
            continue;
        }
        $new_icons = $other_option->getLibrary()->getIcons();
        $available_icons[] = $new_icons;
    }
}

$library = new Media_Model_Library();
$all_icons = $library->getAllFeatureIcons();

# Exporter
$can_export = Siberian_Exporter::isRegistered($option->getCode()) && (APPLICATION_ENV != "production");


?>

<script type="text/javascript">
    var tmp_directory = "<?php echo Core_Model_Directory::getTmpDirectory() ?>";
</script>

<div class="content_editor">
    <h3 class="title-editor border-blue">
        <?php echo $this->_("Feature settings"); ?>
        <?php if($can_export): ?>
            <button class="color-blue pull-right bt-header-right btn">
                <a href="<?php echo $this->getUrl("{$option->getDesktopUri()}export", array("value_id" => $option->getId())); ?>">
                    <?php echo __("Export") ?>
                </a>
            </button>
        <?php endif; ?>
    </h3>
    <div id="icon_and_name" class="row icon_and_name container-fluid feature-section-bottom first-row-feature">
        <div class="col-md-3 col-xs-3 col-icon-button">
            <button type="button" id="change_icon" class="add color-blue btn<?php if(!$option->getLibrary()->getId()) : ?> no_library<?php endif; ?>" data-image="330" data-style="area" data-color="color">
                <img id="current_icon" src="<?php echo $this->getIconUrl($option); ?>" width="auto" height="40" data-image="<?php echo $option->getIconId(); ?>" data-style="color-blue" data-color="color" />
                <?php if($option->getLibrary()->getId()) : ?>
                <?php endif; ?>
            </button>
        </div>
        <div class="tabbar_name col-md-9 col-xs-9">
            <div class="form-group">
                <div class="col-md-5 col-xs-5">
                    <label for="tabbar_name"><?php echo $this->_('Page name:'); ?></label>
                </div>
                <?php if(is_numeric($option->getId())) : ?>
                <div class="col-md-3 col-xs-3 text-center">
                    <label><?php echo $this->_("Activated"); ?></label>
                </div>
                <div class="col-md-4 col-xs-4 text-center">
                    <?php if($option->getSocialSharingIsAvailable() == 1) : ?>
                    <label><?php echo $this->_("Social Sharing"); ?></label>
                    <?php endif; ?>
                </div>
                <?php endif; ?>
            </div>
            <div class="form-group">
                <div class="col-md-5 col-xs-5">
                    <input type="text" id="tabbar_name" class="input-flat" name="tabbar_name" value="<?php echo $option->getTabbarName(); ?>" />
<!--                    <img width="24" src="--><?php //echo $this->getImage('customization/ajax/spinner.gif'); ?><!--" id="loader_tabbar_name" alt="Loading" title="Loading" class="loader">-->
                    <input type="hidden" id="tabbar_name_id" name="option_value_id" value="<?php echo $option->getId() ?>" />
                </div>
                <?php if(is_numeric($option->getId())) : ?>
                <div class="col-md-3 col-xs-3">
                    <?php if($option->getLibrary()->getId()) : ?>
                        <div id="icon_library_manager" class="custom_modal icon_library_manager" style="display:none;">
                            <div id="modal_mask_icon_library_manager" class="modal_mask close_modal close_modal_icon_library_manager"></div>
                            <div>
                                <div id="icon_library" class="modal_content inner_content">
                                    <span class="pull-right" style="margin-right: 8px;">
                                        <button class="bt_close_modal_icons close_modal_icon_library_manager" type="button">
                                            <i class="fa fa-times"></i>
                                        </button>
                                    </span>
                                    <h3 class="title-editor border-blue no-border-radius">
                                        <?php echo $this->_('Manage icons'); ?>
                                    </h3>
                                    <div class="details">
                                        <div class="container-fluid content-white-bkg">
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <h3 class="subtitle">
                                                        <span>
                                                            <?php echo $this->_('Feature icons') ?>
                                                            <!--[if gte IE 10]><!-->
                                                            <div id="new_icon">
                                                                <a href="javascript:void(0)" class="upload_icon icon" rel="<?php echo $option->getId(); ?>" >
                                                                    <button class="add color-blue" type="button">
                                                                        <?php echo $this->_('Add a new icon') ?>
                                                                    </button>
                                                                </a>
                                                                <!--<![endif]-->
                                                                <span id="input_upload_custom_icon_message" style="display:none"><?php echo $this->_('Add a new icon') ?></span>
                                                                <input id="input_upload_custom_icon" class="uploader" style="display:none" type="file" name="files[]" data-url="<?php echo $this->getUrl('template/crop/upload'); ?>">
                                                            </div>
                                                        </span>
                                                    </h3>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <ul class="icons_list">
                                                        <?php $icon_ids = array(); ?>
                                                        <?php foreach($available_icons as $lib_icon) : ?>
                                                            <?php foreach($lib_icon as $icon) : ?>
                                                                <?php if($icon->getUrl() AND (!$icon->getAppId() OR $icon->getAppId() == $this->getApplication()->getId()) AND !in_array($icon->getId(), $icon_ids)) : ?>
                                                                    <li rel="<?php echo $option->getId(); ?>" class="color-blue">
                                                                        <a href="<?php echo $this->getUrl('application/customization_features/seticon'); ?>" class="left icon" rel="<?php echo $option->getId(); ?>" >
                                                                            <button class="select_icon" type="button">
                                                                                <img src="<?php echo $icon->getUrl(); ?>" width="auto" height="65" class="colorize" />
                                                                            </button>
                                                                            <input type="hidden" name="option_value_id" value="<?php echo $option->getValueId(); ?>" />
                                                                            <input type="hidden" name="icon_id" value="<?php echo $icon->getId(); ?>" />
                                                                        </a>
                                                                        <?php if($icon->getAppId()) : ?>
                                                                            <a href="<?php echo $this->getUrl('application/customization_features/deleteicon'); ?>" class="delete_icon">
                                                                                <i class="fa fa-times"></i>
                                                                                <input type="hidden" name="option_value_id" value="<?php echo $option->getValueId(); ?>" />
                                                                                <input type="hidden" name="icon_id" value="<?php echo $icon->getId(); ?>" />
                                                                            </a>
                                                                        <?php endif; ?>

                                                                    </li>
                                                                    <?php $icon_ids[] = $icon->getId() ?>
                                                                <?php endif; ?>
                                                            <?php endforeach; ?>
                                                        <?php endforeach; ?>
                                                    </ul>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <h3 class="subtitle">
                                                        <span><?php echo $this->_('Library icons') ?></span>
                                                    </h3>
                                                    <div class="form-group filter-icons">
                                                        <input type="text" class="input-flat" style="width: 200px;" placeholder="<?php echo __("Search by keywords ...") ?>" />
                                                        <button type="reset" class="btn color-blue"><?php echo __("Reset") ?></button>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <ul class="icons_list filter_list">
                                                        <?php $all_icon_ids = array(); ?>
                                                        <?php foreach($all_icons as $icon) : ?>
                                                            <?php if($icon->getUrl() AND !in_array($icon->getId(), $all_icon_ids)) : ?>
                                                                <li data-filter="<?php echo $icon->getLink() ?>" rel="<?php echo $option->getId(); ?>" class="<?php echo ($icon->getCanBeColorized()==0) ? "colorizable" : "color-blue"; ?>">
                                                                    <a href="<?php echo $this->getUrl('application/customization_features/seticon'); ?>" class="left icon" rel="<?php echo $option->getId(); ?>" >
                                                                        <button class="select_icon" type="button">
                                                                            <img src="<?php echo $icon->getUrl(); ?>" width="auto" height="65" class="colorize" />
                                                                        </button>
                                                                        <input type="hidden" name="option_value_id" value="<?php echo $option->getValueId(); ?>" />
                                                                        <input type="hidden" name="icon_id" value="<?php echo $icon->getId(); ?>" />
                                                                    </a>
                                                                    <?php if($icon->getAppId()) : ?>
                                                                        <a href="<?php echo $this->getUrl('application/customization_features/deleteicon'); ?>" class="delete_icon">
                                                                            <i class="fa fa-times"></i>
                                                                            <input type="hidden" name="option_value_id" value="<?php echo $option->getValueId(); ?>" />
                                                                            <input type="hidden" name="icon_id" value="<?php echo $icon->getId(); ?>" />
                                                                        </a>
                                                                    <?php endif; ?>

                                                                </li>
                                                                <?php $all_icon_ids[] = $icon->getId() ?>
                                                            <?php endif; ?>
                                                        <?php endforeach; ?>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                    <div id="toggle_feature_is_activated">
                        <div style="width:100%;padding-top:4px">
                            <input class='sb-tgl sb-tgl-flat feature_is_activated' id='chk_activate' type='checkbox' <?php if($option->isActive()) echo 'checked="checked"'; ?>>
                            <label class='sb-tgl-btn color-blue' for='chk_activate' ></label>
                            <input type="hidden" id="is_active" name="is_active" value="" />
                            <input type="hidden" name="value_id" value="<?php echo $option->getId(); ?>" />
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-xs-4 text-center">
                    <?php if($option->getSocialSharingIsAvailable() == 1) : ?>
                    <div id="toggle_social_sharing_is_activated">
                        <div style="width:100%;padding-top:4px">
                            <input class='sb-tgl sb-tgl-flat social_sharing_is_activated' id='chk_activate_social_sharing' type='checkbox' <?php if($option->getSocialSharingIsActive()) echo 'checked="checked"'; ?>>
                            <label class='sb-tgl-btn color-blue' for='chk_activate_social_sharing' ></label>
                            <input type="hidden" id="is_social_sharing_active" name="is_social_sharing_active" value="" />
                            <input type="hidden" name="value_id" value="<?php echo $option->getId(); ?>" />
                        </div>
                    </div>
                    <?php endif; ?>
                </div>
                <?php endif; ?>
            </div>
            
        </div>
    </div>
    
    <div class="edit_page">
        <?php echo $this->getPartialHtml('content_editor'); ?>
    </div>
    <script type="text/javascript">

        var custom_icon_uploader = new Uploader();

        page.setCallback('bind_icons_events', function() {
            $('.feature_is_activated').change(function() {
                var is_checked = $('#chk_activate').is(':checked') ? 1 : 0;
                $("#is_active").val(is_checked);
                reload(this.parentNode, '<?php echo $this->getUrl('application/customization_features/setisactive'); ?>', true, function(datas) {
                    if(datas.success) {
                        iframe.f.reloadTabbar();
                    }
                });
            });

            $('.social_sharing_is_activated').change(function() {
                var is_checked = $('#chk_activate_social_sharing').is(':checked') ? 1 : 0;
                $("#is_social_sharing_active").val(is_checked);
                reload(this.parentNode, '<?php echo $this->getUrl('application/customization_features/setisactive'); ?>', true, function(datas) {
                    if(datas.success) {
                        iframe.f.reloadTabbar();
                    }
                });
            });

            <?php if($option->getLibrary()->getId()) : ?>
            var icon_library = {
                tolerance: 180,
                mask: null,
                processEvents: function() {

                    $('#change_icon').unbind('click');
                    $('#change_icon').click(function() {
                        icon_library.open($(this).attr('rel'));
                    });

                    $('.close_modal_icon_library_manager').unbind('click');
                    $('.close_modal_icon_library_manager').click(function() {
                        icon_library.close(true);
                    });

                },
                open: function(id) {

                    $(document).keyup(function(e) {
                        if(e.which == 27) icon_library.close(true);
                    });

                    $(window).unbind('resize');
                    $(window).resize(this.resize.bind(this));

                    this.resize();

                    $('#icon_library_manager').fadeIn();
                    if(!$('#icon_library .upload_icon').is(':visible')) {
                        $('#input_upload_custom_icon_message').show();
                        $('#input_upload_custom_icon').show();
                    }

                },
                close: function(animated) {
                    if(animated) {
                        $('#icon_library_manager').fadeOut(300, function() {});
                    }
                    else {
                        $('#icon_library_manager').hide();
                        $('.library').hide();
                    }
                    $(document).unbind('keyup');
                },
                resize: function(all) {
                    var selector = ".details";
                    if(!all) selector += ":visible";
                    $('#icon_library').css('height', $(window).outerHeight() - 75);
                    $('#icon_library_manager').find(selector).css('height', $(window).outerHeight() - this.tolerance);
                }
            }

            icon_library.processEvents();

            //Ajout d'un icône
            $('#icon_library').on('click', '.icon', function() {
                reload($(this), this.href, true, function(datas) {
                    if(datas.success) {
                        updateLayout(datas);
                        icon_library.close();
                    }
                });
                return false;
            });

            //Suppression d'un icône
            $('#icon_library').on('click', '.delete_icon', function() {
                var $icon = $(this);
                reload($(this), this.href, true, function(datas) {
                    if(datas.success) {
                        $icon.parent().fadeOut(600, function(){
                            $icon.parent().remove();
                        });
                    }
                });

                return false;
            });

            $('#icon_library .upload_icon').click(function() {
                $('#input_upload_custom_icon').trigger('click');
            });

            $('#input_upload_custom_icon').fileupload({
                dataType: 'json',
                add: function(e, data) {
                    data.submit();
                    custom_icon_uploader.showProgressbar();
                },
                progressall: function(e, data) {
                    custom_icon_uploader.moveProgressbar(data);
                },
                done: function(e, data) {
                    if(data.result.error) {
                        custom_icon_uploader.showError(data.result.message);
                    }

                    if(data.result.success) {
                        custom_icon_uploader.hide();
                        var params = new Array();
                        params["url"] = '<?php echo $this->getUrl('template/crop/crop'); ?>';
                        params["file"] = data.result.files;
                        params["option_value_id"] = '<?php echo $option->getId() ?>';
                        params["output_w"] = "<?php echo $this->getIconWidth(); ?>";
                        params["output_h"] = "<?php echo $this->getIconHeight(); ?>";
                        params["output_url"] = '<?php echo str_replace('/', '$', $this->getUrl('application/customization_features/uploadicon')) ?>';
                        params["uploader"] = 'custom_icon_uploader';
                        params["image_color"] = '<?php echo $this->getApplication()->getBlock('tabbar')->getImageColor(); ?>';
                        params["is_colorizable"] = true;
                        custom_icon_uploader.crop(params);
                        custom_icon_uploader.callback = function(files) {
                            var img_src = '<?php echo Media_Model_Library_Image::getImagePathTo('/', $this->getApplication()->getId()) ?>'+files.file;
                            $('.icons_list').append('<li class="newly_added left relative">\n\
                                <a rel="<?php echo $option->getId(); ?>" class="left icon" href="<?php echo $this->getUrl('application/customization_features/seticon'); ?>">\n\
                                    <button class="select_icon" type="button">\n\
                                        <img width="65" height="65" class="colorize" src="'+img_src+'">\n\
                                    </button>\n\
                                    <input type="hidden" value="<?php echo $option->getId(); ?>" name="option_value_id">\n\
                                    <input type="hidden" value="'+files.icon_id+'" name="icon_id">\n\
                                </a>\n\
                                <a href="<?php echo $this->getUrl('application/customization_features/deleteicon'); ?>" class="delete_icon">\n\
                                    <i class="fa fa-times"></i>\n\
                                    <input type="hidden" name="option_value_id" value="<?php echo $option->getValueId(); ?>" />\n\
                                    <input type="hidden" name="icon_id" value="'+files.icon_id+'" />\n\
                                </a>\n\
                                </li>');
                            updateLayout(files);
                        }
                    }
                }
            });

            function updateLayout(datas) {
                //your pages
                $('#icon_<?php echo $option->getId(); ?>').attr('src', datas.icon_url).attr('data-image', datas.icon_id);
                //icone en cours feature
                var current_icon = datas.colored_reverse_color_icon_url ? datas.colored_reverse_color_icon_url : datas.icon_url;
                $('#current_icon').attr('src', current_icon);
                //drodown
                $('#change_icon').removeClass('open');
                $('#icons').slideUp();

                iframe.f.changeIcon(page.current.attr("rel"), datas.colored_icon_url);

            }
            <?php endif ?>

            $('#tabbar_name').keyup(function(e) {
                if(e.keyCode == 13) {
                    this.blur();
                }
                else {
                    var val = $(this).val().trim();
                    var subval = val;
                    if(subval.length > 8) subval = subval.substring(0, 3).trim()+'...'+subval.substring(subval.length-4, subval.length).trim();
                    $('#tabbar_name_<?php echo $option->getId(); ?>').html(subval);
                    iframe.content.find('.tabbar_name_<?php echo $option->getId(); ?>').html(subval);
                    iframe.content.find('#page_title_<?php echo $option->getId(); ?>').html(val);
                    if(iframe.f.page.getSubpage('<?php echo $option->getId(); ?>')) {
                        iframe.f.page.getSubpage('<?php echo $option->getId(); ?>').calcTitleWidth();
                    }
                    //folder
                    iframe.content.find('#tabbar_item_<?php echo $option->getId(); ?>').find('.text.title').html(val);
                    $('#title_editor').html(val);
                }
            }).change(function() {
                var val = $(this).val();
                var tabbar_name_loader = $('#loader_'+$(this).attr('id'));
                var subval = val;
                if(subval.length > 8) subval = subval.substring(0, 3).trim()+'...'+subval.substring(subval.length-4, subval.length).trim();
                $('#tabbar_name_<?php echo $option->getId(); ?>').html(subval);
                tabbar_name_loader.show();
                reload(this.parentNode, '<?php echo $this->getUrl('application/customization_features/settabbarname'); ?>', false, function(datas) {
                    if(datas.success) {
                        tabbar_names['<?php echo $option->getId(); ?>'] = val;
                        iframe.f.reload();
                    }
                    tabbar_name_loader.hide();
                }, function(datas) {
                    iframe.content.find('.tabbar_name_<?php echo $option->getId(); ?>').html(tabbar_names['<?php echo $option->getId(); ?>']);
                    $('#tabbar_name_<?php echo $option->getId(); ?>').html(tabbar_names['<?php echo $option->getId(); ?>']);
                    $(this).val(tabbar_names['<?php echo $option->getId(); ?>']);
                    tabbar_name_loader.hide();
                }.bind(this));
            });
        });

        page.setCallback('unbind_icons_events', function() {
            $('.feature_is_activated').unbind('change');
            <?php if($option->getLibrary()->getId()) : ?>
            $('.icon').unbind('click');
            $('#change_icon').unbind('keyup').unbind('blur');
            <?php endif; ?>
            $('#tabbar_name').unbind('keyup').unbind('blur');
        });

        /** Icon filtering */
        $(".filter-icons input[type=text]").on("keyup", function() {
            var search = $(this);
            var value = search.val();

            $(".filter_list li[data-filter]").hide();
            $(".filter_list li[data-filter]").each(function() {
                var el = $(this);
                var filter = el.data("filter");

                if(filter.indexOf(value) > -1) {
                    el.show();
                }
            });
        });

        $(".filter-icons button").on("click", function() {
            $(".filter-icons input[type=text]").val("");
            $(".filter_list li[data-filter]").show();
        });

    </script>
    <style>
        .custom_modal .modal_content li { margin: 5px; background: #0099C7; color: white; border-radius: 0px; float:left; list-style:none; }
        .custom_modal .modal_content img { padding: 8px; }
        .custom_modal .modal_content .icons_list li { /*padding: 15px;*/ }
        .custom_modal .modal_content li .select_icon { background: none; color: white;border:none; }
        .custom_modal .modal_content li .delete_icon { position:absolute; top:0; right:0; }
        .custom_modal .modal_content .container-fluid { padding-bottom: 20px; }
        .custom_modal .bt_close_modal_icons{border: none;background: transparent;font-size: 25px;}
        #icon_and_name .col-icon-button{padding-top: 8px}
        #icon_library { overflow: scroll; }
        #new_icon {  float: right;  font-size: 16px;  }
    </style>
</div>
