<p align="justify" >
    <?php echo __('You just received a publication request:'); ?><br />
    <?php echo __('App ID:'); ?> <strong><?php echo $this->getApplication()->getId() ?></strong><br />
    <?php echo __('App name:'); ?> <strong><?php echo $this->getApplication()->getName() ?></strong><br />
    <?php echo __('User ID:'); ?> <strong><?php echo $this->getAdmin()->getId() ?></strong><br />
    <?php echo __('User email:'); ?> <strong><?php echo $this->getAdmin()->getEmail() ?></strong><br />
</p>
<table border="0"
       cellpadding="0"
       cellspacing="0"
       class="btn btn-primary">
    <tbody>
    <tr>
        <td align="left">
            <table border="0"
                   cellpadding="0"
                   cellspacing="0">
                <tbody>
                <tr>
                    <td>
                        <a href="<?php echo $this->getUrl('application/backoffice_view', ['app_id' => $this->getApplication()->getId()]); ?>"
                           target="_blank">
                            <?php echo __('Click here to open the application') ?>
                        </a>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>
    </tbody>
</table>