<?php

use Cabride\Model\Payment;
use Cabride\Model\Cabride;
use Core\Model\Base;

$application = $this->getApplication();
$request = $this->getRequest();
$valueId = Cabride::getCurrentValueId();

$cabride = (new Cabride())->find($valueId, "value_id");
if (!$cabride->getId()) {
    $cabride->setValueId($valueId);
    $cabride->save();
    $cabride->reload();
}

$cu = $cabride->getCurrency();

$payments = (new Payment())->findAll(
    [
        "value_id = ?" => $valueId,
        "status = ?" => "paid"
    ],
    "created_at DESC",
    [
        "limit" => 100,
    ]
);

$stats = (new Payment())->aggregateDashboard($valueId);


?>
<div class="cabride row">
    <div class="col-md-12">
        <div class="page-content-wrapper">
            <div id="apis_content"
                 class="content solo-page sb-tour">
                <h3 class="title-editor border-blue text-center">
                    <?php echo p__("cabride", "Dashboard"); ?>
                </h3>
                <div class="subcontent content-color">
                    <div class="col-md-3">
                        <div class="alert alert-info">
                            <p class="dashboard-income"><?php echo Base::_formatPrice($stats["dayRow"]["total"], $cu) ?></p>
                            <p class="income-hint income-day">
                                <?php echo p__("cabride", "Commissions") ?>
                                <span class="pull-right">
                                    <?php echo Base::_formatPrice($stats["dayRow"]["commission"], $cu) ?>
                                </span>
                            </p>
                            <p class="income-more">
                                <?php echo p__("cabride", "TOTAL REVENUE TODAY"); ?>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="alert alert-warning">
                            <p class="dashboard-income"><?php echo Base::_formatPrice($stats["weekRow"]["total"], $cu) ?></p>
                            <p class="income-hint income-week">
                                <?php echo p__("cabride", "Commissions") ?>
                                <span class="pull-right">
                                    <?php echo Base::_formatPrice($stats["weekRow"]["commission"], $cu) ?>
                                </span>
                            </p>
                            <p class="income-more">
                                <?php echo p__("cabride", "TOTAL REVENUE OF LAST 7 DAYS"); ?>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="alert alert-success">
                            <p class="dashboard-income"><?php echo Base::_formatPrice($stats["monthRow"]["total"], $cu) ?></p>
                            <p class="income-hint income-month">
                                <?php echo p__("cabride", "Commissions") ?>
                                <span class="pull-right">
                                    <?php echo Base::_formatPrice($stats["monthRow"]["commission"], $cu) ?>
                                </span>
                            </p>
                            <p class="income-more">
                                <?php echo p__("cabride", "TOTAL REVENUE OF LAST 30 DAYS"); ?>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="alert alert-danger">
                            <p class="dashboard-income"><?php echo Base::_formatPrice($stats["yearRow"]["total"], $cu) ?></p>
                            <p class="income-hint income-year">
                                <?php echo p__("cabride", "Commissions") ?>
                                <span class="pull-right">
                                    <?php echo Base::_formatPrice($stats["yearRow"]["commission"], $cu) ?>
                                </span>
                            </p>
                            <p class="income-more">
                                <?php echo p__("cabride", "TOTAL REVENUE OF LAST 365 DAYS"); ?>
                            </p>
                        </div>
                    </div>

                    <div class="col-md-12">

                        <div class="pull-right">
                            <div class="alert alert-info">
                                <?php echo p__("cabride", "Only the 100 latest payments are shown") ?>
                            </div>
                        </div>

                        <table class="table table-striped sb-pager">
                            <thead>
                            <tr class="border-grey">
                                    <th class="sortable numeric"><?php echo p__("cabride", "ID") ?></th>
                                    <th class="sortable"><?php echo p__("cabride", "Method") ?></th>
                                    <th class="sortable numeric text-right"><?php echo p__("cabride", "Amount") ?></th>
                                    <th class="sortable numeric text-right"><?php echo p__("cabride", "Commission") ?></th>
                                    <th class="sortable numeric text-right"><?php echo p__("cabride", "Date") ?></th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($payments as $payment): ?>
                                <tr class="sb-pager">
                                    <td>
                                        <b>#<?php echo $payment->getId(); ?></b>
                                    </td>
                                    <td>
                                        <?php if ($payment->getMethod() === "credit-card"): ?>
                                            <img style="height: 20px;"
                                                 src="/app/local/modules/Cabride/features/cabride/assets/templates/images/009-credit-card.svg" />
                                            <span><?php echo p__("cabride", "Credit card") ?></span>
                                        <?php else: ?>
                                            <img style="height: 20px;"
                                                 src="/app/local/modules/Cabride/features/cabride/assets/templates/images/010-money.svg" />
                                            <span><?php echo p__("cabride", "Cash") ?></span>
                                        <?php endif; ?>
                                    </td>
                                    <td class="text-right"><?php echo Base::_formatPrice($payment->getAmount(), $cu); ?></td>
                                    <td class="text-right"><?php echo Base::_formatPrice($payment->getCommissionAmount(), $cu); ?></td>
                                    <td class="text-right">
                                        <span style="display: none;"><?php echo datetime_to_format($payment->getCreatedAt(), Zend_Date::TIMESTAMP); ?></span>
                                        <?php echo datetime_to_format($payment->getCreatedAt()); ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                            <tfoot>
                            <tr>
                                <td colspan="4">
                                    <?php echo p__("cabride", "No results for your search.") ?>
                                </td>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>


            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var searchPlaceholder = '<?php echo __js("Search ...", "'") ?>';
    $(document).ready(function () {
        $("table.sb-pager").sbpager({
            with_search: true,
            search_placeholder: searchPlaceholder
        });
    });
</script>
<style type="text/css">
    @import url("https://fonts.googleapis.com/css?family=Titillium+Web&text=0123456789%C2%A3$%E2%82%AC.,");

    p.dashboard-income {
        font-family: "Titillium Web", monospace;
        font-size: 3rem;
    }

    p.income-hint {
        font-size: 1.2rem;
        padding: 0 0 10px;
        line-height: 1.8rem;
    }

    p.income-more {
        margin: -13px;
        padding: 10px;
        font-size: 1rem;
        text-align: center;
    }

    .alert-info p.income-more {
        background-color: #48829e;
    }

    .alert-warning p.income-more {
        background-color: #966e25;
    }

    .alert-success p.income-more {
        background-color: #3c763d;
    }

    .alert-danger p.income-more {
        background-color: #823231;
    }
</style>
