<?php
$application = $this->getApplication();
$request = $this->getRequest();

use Cabride\Model\Cabride;
use Cabride\Model\Request;
use Cabride\Model\Payment;
use Cabride\Model\Payout;
use Cabride\Model\PayoutBulk;
use Cabride\Model\Cashreturn;
use Siberian\Currency;
use Cabride\Form\PeriodPicker;
use Core\Model\Base;

$application = $this->getApplication();
$request = $this->getRequest();
$valueId = Cabride::getCurrentValueId();

$cabride = (new Cabride())->find($valueId, "value_id");
if (!$cabride->getId()) {
    $cabride->setValueId($valueId);
    $cabride->save();
    $cabride->reload();
}

$cu = $cabride->getCurrency();
$cs = Currency::getCurrency($cabride->getCurrency())["symbol_native"];

$paramsCash = null;
if (!empty($_GET["dateFormat"]) && !empty($_GET["fromCash"]) && !empty($_GET["toCash"])) {
    $dateFormat = str_replace(["dd", "mm", "yy"], ["d", "m", "Y"], $_GET["dateFormat"]);
    $from = date_create_from_format($dateFormat, $_GET["fromCash"]);
    $to = date_create_from_format($dateFormat, $_GET["toCash"]);
    $paramsCash = [
        "from" => $from->format("Y-m-d 00:00:00"),
        "to" => $to->format("Y-m-d 23:59:59"),
    ];
}

$payments = (new Payment())->aggregateCashReturn($valueId, $paramsCash);

$cashArchives = (new Cashreturn())->fetchArchives($valueId);

$paramsPayout = null;
if (!empty($_GET["dateFormat"]) && !empty($_GET["fromPayout"]) && !empty($_GET["toPayout"])) {
    $dateFormat = str_replace(["dd", "mm", "yy"], ["d", "m", "Y"], $_GET["dateFormat"]);
    $from = date_create_from_format($dateFormat, $_GET["fromPayout"]);
    $to = date_create_from_format($dateFormat, $_GET["toPayout"]);
    $paramsPayout = [
        "from" => $from->format("Y-m-d 00:00:00"),
        "to" => $to->format("Y-m-d 23:59:59"),
    ];
}

$payouts = (new Payment())->aggregatePayout($valueId, $paramsPayout);

$payoutArchives = (new Payout())->fetchArchives($valueId);

$bulkArchives = (new PayoutBulk())->fetchArchives($valueId);

$periodPicker = new PeriodPicker();

function colorForStatus ($status) {
    switch ($status) {
        case "inprogress":
        case "requested":
            return "label-warning";
        case "returned":
        case "paid":
            return "label-success";
        default:
            return "label-info";
    }
}

?>
<div class="row">
    <div class="col-md-12">
        <div class="page-content-wrapper">
            <div id="cash_requests"
                 class="content solo-page sb-tour">
                <h3 class="title-editor border-blue text-center">
                    <?php echo p__("cabride", "Cash return requests"); ?>
                </h3>
                <div class="subcontent content-color">
                    <div class="col-md-12">

                        <h4 class="title-editor no-border-radius title-feature-indent">
                            <?php echo p__("cabride", "Cash return requests") ?>
                        </h4>
                        <div class="container-fluid content-feature">

                            <br />

                            <div class="alert alert-info">
                                <?php echo p__("cabride", "The cash return lines are aggregated by drivers, you can filter them by period to split the requests by week, or month for example.") ?>
                            </div>

                            <br />

                            <div class="row"
                                 id="period_picker_cash">
                                <div class="col-md-1 text-left">
                                    <label for="from_cash"
                                           style="line-height: 32px;"><?php echo p__("cabride", "FROM"); ?></label>
                                </div>
                                <div class="col-md-2">
                                    <input type="text"
                                           id="from_cash"
                                           name="from"
                                           value="<?php echo $_GET["fromCash"] ? $_GET["fromCash"] : "" ?>"
                                           class="input-flat" />
                                </div>
                                <div class="col-md-1 text-center">
                                    <label for="to_cash"
                                           style="line-height: 32px;"><?php echo p__("cabride", "TO"); ?></label>
                                </div>
                                <div class="col-md-2">
                                    <input type="text"
                                           id="to_cash"
                                           name="to"
                                           value="<?php echo $_GET["toCash"] ? $_GET["toCash"] : "" ?>"
                                           class="input-flat" />
                                </div>
                                <div class="col-md-2">
                                    <button class="btn color-blue filter-cash"><?php echo p__("cabride", "FILTER"); ?></button>
                                    <button class="btn color-blue clear-cash"><?php echo p__("cabride", "CLEAR"); ?></button>
                                </div>
                            </div>

                            <br />

                            <table class="table content-white-bkg sb-pager margin-top">
                                <thead>
                                <tr class="border-grey">
                                    <th class="sortable numeric"><?php echo p__("cabride", "ID"); ?></th>
                                    <th class="sortable"><?php echo p__("cabride", "Driver"); ?></th>
                                    <th class="sortable"><?php echo p__("cabride", "E-mail"); ?></th>
                                    <th class="sortable"><?php echo p__("cabride", "Period"); ?></th>
                                    <th class="sortable"><?php echo p__("cabride", "Payments"); ?></th>
                                    <th class="sortable numeric text-right"><?php echo p__("cabride", "Total amount"); ?></th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($payments as $payment): ?>
                                    <tr class="sb-pager">
                                        <td>
                                            <b>#<?php echo $payment->getId(); ?></b>
                                        </td>
                                        <td>
                                            <a class="btn btn-xs btn-info"
                                               href="<?php echo __path("/cabride/driver/edit", [
                                                   "driver_id" => $payment->getDriverId()
                                               ]); ?>">
                                                #<?php echo sprintf("%s %s %s", $payment->getDriverId(), $payment->getFirstname(), $payment->getLastname()) ?>
                                            </a>
                                        </td>
                                        <td><?php echo $payment->getEmail() ?></td>
                                        <td>
                                            <?php echo datetime_to_format($payment->getPeriodFrom(), Zend_Date::DATE_SHORT) ?>
                                            -
                                            <?php echo datetime_to_format($payment->getPeriodTo(), Zend_Date::DATE_SHORT) ?>
                                        </td>
                                        <td>
                                            <?php
                                                $ids = explode(",", $payment->getPaymentIds());
                                                foreach ($ids as $id) {
                                                    ?>
                                                    <a class="btn btn-xs btn-info"
                                                       href="#">
                                                        #<?php echo $id ?>
                                                    </a>
                                                    <?php
                                                }
                                            ?>
                                        </td>
                                        <td class="text-right"><?php echo Base::_formatPrice($payment->getTotal(), $cu) ?></td>
                                        <td class="text-right">
                                            <a class="btn btn-xs btn-success request-cash-return"
                                               data-driver-id="<?php echo $payment->getDriverId(); ?>">
                                                <?php echo p__("cabride", "REQUEST CASH RETURN") ?>
                                            </a>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                                <tfoot>
                                <tr>
                                    <td colspan="5">
                                        <?php echo p__("cabride", "No results for your search.") ?>
                                    </td>
                                </tr>
                                </tfoot>
                            </table>
                        </div>

                        <br />

                        <h4 class="title-editor no-border-radius title-feature-indent">
                            <?php echo p__("cabride", "Archived requests") ?>
                        </h4>
                        <div class="container-fluid content-feature">

                            <br />

                            <table class="table content-white-bkg sb-pager margin-top cabride-archives">
                                <thead>
                                <tr class="border-grey">
                                    <th class="sortable numeric"><?php echo p__("cabride", "ID"); ?></th>
                                    <th class="sortable"><?php echo p__("cabride", "Driver"); ?></th>
                                    <th class="sortable"><?php echo p__("cabride", "E-mail"); ?></th>
                                    <th class="sortable"><?php echo p__("cabride", "Period"); ?></th>
                                    <th class="sortable"><?php echo p__("cabride", "Payments"); ?></th>
                                    <th class="sortable numeric text-right"><?php echo p__("cabride", "Total amount"); ?></th>
                                    <th class="sortable"><?php echo p__("cabride", "Status"); ?></th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($cashArchives as $cashArchive): ?>
                                    <tr class="sb-pager">
                                        <td>
                                            <b>#<?php echo $cashArchive->getId(); ?></b>
                                        </td>
                                        <td>
                                            <a class="btn btn-xs btn-info"
                                               href="<?php echo __path("/cabride/driver/edit", [
                                                   "driver_id" => $cashArchive->getDriverId()
                                               ]); ?>">
                                                #<?php echo sprintf("%s %s %s", $cashArchive->getDriverId(), $cashArchive->getFirstname(), $cashArchive->getLastname()) ?>
                                            </a>
                                        </td>
                                        <td><?php echo $cashArchive->getEmail() ?></td>
                                        <td>
                                            <?php echo datetime_to_format($cashArchive->getPeriodFrom(), Zend_Date::DATE_SHORT) ?>
                                            -
                                            <?php echo datetime_to_format($cashArchive->getPeriodTo(), Zend_Date::DATE_SHORT) ?>
                                        </td>
                                        <td>
                                            <?php
                                            $ids = explode(",", $cashArchive->getPaymentIds());
                                            foreach ($ids as $id) {
                                                ?>
                                                <a class="btn btn-xs btn-info"
                                                   href="#">
                                                    #<?php echo $id ?>
                                                </a>
                                                <?php
                                            }
                                            ?>
                                        </td>
                                        <td class="text-right"><?php echo Base::_formatPrice($cashArchive->getAmount(), $cu) ?></td>
                                        <td>
                                            <span class="label <?php echo colorForStatus($cashArchive->getStatus()) ?>">
                                                <?php echo p__("cabride", $cashArchive->getStatus()); ?>
                                            </span>
                                        </td>
                                        <td class="text-right">
                                            <?php if ($cashArchive->getStatus() === "returned"): ?>
                                                <span>
                                                    <?php echo p__("cabride", "RETURNED ON %s", datetime_to_format($cashArchive->getReturnDate(), Zend_Date::DATE_SHORT)) ?>
                                                </span>
                                            <?php else: ?>
                                                <a class="btn btn-xs btn-success mark-as-returned"
                                                   data-id="<?php echo $cashArchive->getId(); ?>">
                                                    <?php echo p__("cabride", "MARK AS RETURNED") ?>
                                                </a>
                                            <?php endif; ?>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                                <tfoot>
                                <tr>
                                    <td colspan="5">
                                        <?php echo p__("cabride", "No results for your search.") ?>
                                    </td>
                                </tr>
                                </tfoot>
                            </table>

                        </div>

                    </div>
                </div>
            </div>

            <div id="commission_payout"
                 class="content solo-page sb-tour">
                <h3 class="title-editor border-blue text-center">
                    <?php echo p__("cabride", "Pay-out"); ?>
                </h3>
                <div class="subcontent content-color">
                    <div class="col-md-12">

                        <h4 class="title-editor no-border-radius title-feature-indent">
                            <?php echo p__("cabride", "Pay-out") ?>
                        </h4>
                        <div class="container-fluid content-feature">

                            <br />

                            <div class="alert alert-info">
                                <?php echo p__("cabride", "The commissions payout lines are aggregated by drivers, you can filter them by period to split payouts by week, or month for example.") ?>
                            </div>

                            <br />

                            <div class="row"
                                 id="period_picker_payout">
                                <div class="col-md-1 text-left">
                                    <label for="from_payout"
                                           style="line-height: 32px;"><?php echo p__("cabride", "FROM"); ?></label>
                                </div>
                                <div class="col-md-2">
                                    <input type="text"
                                           id="from_payout"
                                           name="from"
                                           value="<?php echo $_GET["fromPayout"] ? $_GET["fromPayout"] : "" ?>"
                                           class="input-flat" />
                                </div>
                                <div class="col-md-1 text-center">
                                    <label for="to_payout"
                                           style="line-height: 32px;"><?php echo p__("cabride", "TO"); ?></label>
                                </div>
                                <div class="col-md-2">
                                    <input type="text"
                                           id="to_payout"
                                           name="to"
                                           value="<?php echo $_GET["toPayout"] ? $_GET["toPayout"] : "" ?>"
                                           class="input-flat" />
                                </div>
                                <div class="col-md-6">
                                    <button class="btn color-blue filter-payout"><?php echo p__("cabride", "FILTER"); ?></button>
                                    <button class="btn color-blue clear-payout"><?php echo p__("cabride", "CLEAR"); ?></button>
                                    <button class="btn btn-success bulk-payout"><?php echo p__("cabride", "GENERATE BULK PAYOUT"); ?></button>
                                </div>
                            </div>

                            <br />

                            <table class="table content-white-bkg sb-pager margin-top">
                                <thead>
                                <tr class="border-grey">
                                    <th class="sortable numeric"><?php echo p__("cabride", "ID"); ?></th>
                                    <th class="sortable"><?php echo p__("cabride", "Driver"); ?></th>
                                    <th class="sortable"><?php echo p__("cabride", "E-mail"); ?></th>
                                    <th class="sortable"><?php echo p__("cabride", "Period"); ?></th>
                                    <th class="sortable"><?php echo p__("cabride", "Payments"); ?></th>
                                    <th class="sortable numeric text-right"><?php echo p__("cabride", "Total amount"); ?></th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($payouts as $payout): ?>
                                    <tr class="sb-pager">
                                        <td>
                                            <b>#<?php echo $payout->getId(); ?></b>
                                        </td>
                                        <td>
                                            <a class="btn btn-xs btn-info"
                                               href="<?php echo __path("/cabride/driver/edit", [
                                                   "driver_id" => $payout->getDriverId()
                                               ]); ?>">
                                                #<?php echo sprintf("%s %s %s", $payout->getDriverId(), $payout->getFirstname(), $payout->getLastname()) ?>
                                            </a>
                                        </td>
                                        <td><?php echo $payout->getEmail() ?></td>
                                        <td>
                                            <?php echo datetime_to_format($payout->getPeriodFrom(), Zend_Date::DATE_SHORT) ?>
                                            -
                                            <?php echo datetime_to_format($payout->getPeriodTo(), Zend_Date::DATE_SHORT) ?>
                                        </td>
                                        <td>
                                            <?php
                                            $ids = explode(",", $payout->getPaymentIds());
                                            foreach ($ids as $id) {
                                                ?>
                                                <a class="btn btn-xs btn-info"
                                                   href="#">
                                                    #<?php echo $id ?>
                                                </a>
                                                <?php
                                            }
                                            ?>
                                        </td>
                                        <td class="text-right"><?php echo Base::_formatPrice($payout->getTotal(), $cu) ?></td>
                                        <td class="text-right">
                                            <a class="btn btn-xs btn-success payout-request"
                                               data-driver-id="<?php echo $payout->getDriverId(); ?>">
                                                <?php echo p__("cabride", "PAY OUT") ?>
                                            </a>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                                <tfoot>
                                <tr>
                                    <td colspan="5">
                                        <?php echo p__("cabride", "No results for your search.") ?>
                                    </td>
                                </tr>
                                </tfoot>
                            </table>

                        </div>

                        <br />

                        <h4 class="title-editor no-border-radius title-feature-indent">
                            <?php echo p__("cabride", "Archived pay-out") ?>
                        </h4>
                        <div class="container-fluid content-feature">
                            <br />

                            <table class="table content-white-bkg sb-pager margin-top cabride-archives">
                                <thead>
                                <tr class="border-grey">
                                    <th class="sortable numeric"><?php echo p__("cabride", "ID"); ?></th>
                                    <th class="sortable"><?php echo p__("cabride", "Driver"); ?></th>
                                    <th class="sortable"><?php echo p__("cabride", "E-mail"); ?></th>
                                    <th class="sortable"><?php echo p__("cabride", "Period"); ?></th>
                                    <th class="sortable"><?php echo p__("cabride", "Payments"); ?></th>
                                    <th class="sortable numeric text-right"><?php echo p__("cabride", "Total amount"); ?></th>
                                    <th class="sortable"><?php echo p__("cabride", "Status"); ?></th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($payoutArchives as $payoutArchive): ?>
                                    <tr class="sb-pager">
                                        <td>
                                            <b>#<?php echo $payoutArchive->getId(); ?></b>
                                        </td>
                                        <td>
                                            <a class="btn btn-xs btn-info"
                                               href="<?php echo __path("/cabride/driver/edit", [
                                                   "driver_id" => $payoutArchive->getDriverId()
                                               ]); ?>">
                                                #<?php echo sprintf("%s %s %s", $payoutArchive->getDriverId(), $payoutArchive->getFirstname(), $payoutArchive->getLastname()) ?>
                                            </a>
                                        </td>
                                        <td><?php echo $payoutArchive->getEmail() ?></td>
                                        <td>
                                            <?php echo datetime_to_format($payoutArchive->getPeriodFrom(), Zend_Date::DATE_SHORT) ?>
                                            -
                                            <?php echo datetime_to_format($payoutArchive->getPeriodTo(), Zend_Date::DATE_SHORT) ?>
                                        </td>
                                        <td>
                                            <?php
                                            $ids = explode(",", $payoutArchive->getPaymentIds());
                                            foreach ($ids as $id) {
                                                ?>
                                                <a class="btn btn-xs btn-info"
                                                   href="#">
                                                    #<?php echo $id ?>
                                                </a>
                                                <?php
                                            }
                                            ?>
                                        </td>
                                        <td class="text-right"><?php echo Base::_formatPrice($payoutArchive->getAmount(), $cu) ?></td>
                                        <td>
                                            <span class="label <?php echo colorForStatus($payoutArchive->getStatus()) ?>">
                                                <?php echo p__("cabride", $payoutArchive->getStatus()); ?>
                                            </span>
                                        </td>
                                        <td class="text-right">
                                            <?php if ($payoutArchive->getStatus() === "paid"): ?>
                                                <span>
                                                    <?php echo p__("cabride", "PAID ON %s", datetime_to_format($payoutArchive->getPayoutDate(), Zend_Date::DATE_SHORT)) ?>
                                                </span>
                                            <?php else: ?>
                                                <a class="btn btn-xs btn-success mark-as-paid"
                                                   data-id="<?php echo $payoutArchive->getId(); ?>">
                                                    <?php echo p__("cabride", "MARK AS PAID") ?>
                                                </a>
                                            <?php endif; ?>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                                <tfoot>
                                <tr>
                                    <td colspan="5">
                                        <?php echo p__("cabride", "No results for your search.") ?>
                                    </td>
                                </tr>
                                </tfoot>
                            </table>

                        </div>

                        <br />

                        <h4 class="title-editor no-border-radius title-feature-indent">
                            <?php echo p__("cabride", "Bulk CSV exports") ?>
                        </h4>
                        <div class="container-fluid content-feature">
                            <br />

                            <table class="table content-white-bkg sb-pager margin-top cabride-archives">
                                <thead>
                                <tr class="border-grey">
                                    <th class="sortable numeric"><?php echo p__("cabride", "ID"); ?></th>
                                    <th class="sortable"><?php echo p__("cabride", "Period"); ?></th>
                                    <th class="sortable"><?php echo p__("cabride", "Driver IDs"); ?></th>
                                    <th class="sortable"><?php echo p__("cabride", "Payment IDs"); ?></th>
                                    <th class="sortable"><?php echo p__("cabride", "Payout IDs"); ?></th>
                                    <th class="sortable"><?php echo p__("cabride", "Total"); ?></th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($bulkArchives as $bulkArchive): ?>
                                    <tr class="sb-pager">
                                        <td>
                                            <b>#<?php echo $bulkArchive->getId(); ?></b>
                                        </td>
                                        <td>
                                            <?php if ($bulkArchive->getPeriodFrom() != "0000-00-00 00:00:00"): ?>
                                                <?php echo datetime_to_format($bulkArchive->getPeriodFrom(), Zend_Date::DATE_SHORT) ?>
                                                -
                                                <?php echo datetime_to_format($bulkArchive->getPeriodTo(), Zend_Date::DATE_SHORT) ?>
                                            <?php else: ?>
                                                -
                                            <?php endif; ?>
                                        </td>
                                        <td>
                                            <?php
                                            $ids = explode(",", $bulkArchive->getDriverIds());
                                            foreach ($ids as $id) {
                                                ?>
                                                <a class="btn btn-xs btn-info"
                                                   href="#">
                                                    #<?php echo $id ?>
                                                </a>
                                                <?php
                                            }
                                            ?>
                                        </td>
                                        <td>
                                            <?php
                                            $ids = explode(",", $bulkArchive->getPaymentIds());
                                            foreach ($ids as $id) {
                                                ?>
                                                <a class="btn btn-xs btn-info"
                                                   href="#">
                                                    #<?php echo $id ?>
                                                </a>
                                                <?php
                                            }
                                            ?>
                                        </td>
                                        <td>
                                            <?php
                                            $ids = explode(",", $bulkArchive->getPayoutIds());
                                            foreach ($ids as $id) {
                                                ?>
                                                <a class="btn btn-xs btn-info"
                                                   href="#">
                                                    #<?php echo $id ?>
                                                </a>
                                                <?php
                                            }
                                            ?>
                                        </td>
                                        <td>
                                            <?php echo Base::_formatPrice($bulkArchive->getTotal(), $cu); ?>
                                        </td>
                                        <td class="text-right">
                                            <a class="btn btn-xs btn-info"
                                               target="_blank"
                                               href="/cabride/payout/download-csv?bulkId=<?php echo $bulkArchive->getId(); ?>">
                                                <?php echo p__("cabride", "DOWNLOAD CSV") ?>
                                            </a>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                                <tfoot>
                                <tr>
                                    <td colspan="6">
                                        <?php echo p__("cabride", "No results for your search.") ?>
                                    </td>
                                </tr>
                                </tfoot>
                            </table>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    let pickerLocale = '<?php echo Core_Model_Language::getCurrentLanguageDatepickerLocale(); ?>';
    let dateFormat = null;
    let search_placeholder = '<?php echo p__js("cabride","Search, filter ...", "'") ?>';
    $(document).ready(function () {
        $("table.sb-pager").sbpager({
            with_search: true,
            search_placeholder: search_placeholder
        });

        if($.datepicker.regional[pickerLocale]) {
            $.datepicker.setDefaults($.datepicker.regional[pickerLocale]);
            dateFormat = $.datepicker.regional[pickerLocale].dateFormat;
        } else {
            $.datepicker.setDefaults($.datepicker.regional['en']);
            dateFormat = $.datepicker.regional['en'].dateFormat;
        }

        $("#from_cash").datepicker({
            changeMonth: true,
            changeYear: true,
            numberOfMonths: 2,
            onClose: function(selectedDate) {
                $("#to_cash").datepicker("option", "minDate", selectedDate);
            }
        });

        $("#to_cash").datepicker({
            changeMonth: true,
            changeYear: true,
            numberOfMonths: 2,
            onClose: function(selectedDate) {
                $("#from_cash").datepicker("option", "maxDate", selectedDate);
            }
        });

        $("#from_payout").datepicker({
            changeMonth: true,
            changeYear: true,
            numberOfMonths: 2,
            onClose: function(selectedDate) {
                $("#to_payout").datepicker("option", "minDate", selectedDate);
            }
        });

        $("#to_payout").datepicker({
            changeMonth: true,
            changeYear: true,
            numberOfMonths: 2,
            onClose: function(selectedDate) {
                $("#from_payout").datepicker("option", "maxDate", selectedDate);
            }
        });

        // functions
        let reloadPage = function () {
            let fromCash = $("#from_cash").val();
            let toCash = $("#to_cash").val();
            let fromPayout = $("#from_payout").val();
            let toPayout = $("#to_payout").val();

            location.replace(encodeURI("/cabride/dashboard/payments?dateFormat=" + dateFormat + "&fromCash=" + fromCash + "&toCash=" + toCash + "&fromPayout=" + fromPayout + "&toPayout=" + toPayout));
        };

        let filterCash = function () {
            reloadPage();
        };

        let clearCash = function () {
            $("#from_cash").val("");
            $("#to_cash").val("");

            reloadPage();
        };

        let filterPayout = function () {
            reloadPage();
        };

        let clearPayout = function () {
            $("#from_payout").val("");
            $("#to_payout").val("");

            reloadPage();
        };

        let fCash = $(".filter-cash");
        fCash.off("click");
        fCash.on("click", function () {
            filterCash();
        });

        let cCash = $(".clear-cash");
        cCash.off("click");
        cCash.on("click", function () {
            clearCash();
        });

        let fPayout = $(".filter-payout");
        fPayout.off("click");
        fPayout.on("click", function () {
            filterPayout();
        });

        let cPayout = $(".clear-payout");
        cPayout.off("click");
        cPayout.on("click", function () {
            clearPayout();
        });

        let requestCashReturn = $(".request-cash-return");

        requestCashReturn.off("click");
        requestCashReturn.on("click", function () {
            let button = $(this);
            let driverId = button.attr("data-driver-id");
            swal({
                html: true,
                title: '<?php echo p__js("cabride", "Request a cash return", "'") ?>',
                text: '<?php echo p__js("cabride","Are you sure?", "'") ?>',
                showCancelButton: true,
                closeOnConfirm: false,
                closeOnCancel: true,
                confirmButtonColor: '#449d44',
                confirmButtonText: '<?php echo p__js("cabride","Yes, send cash request", "'") ?>',
                cancelButtonText: '<?php echo p__js("cabride","No, go back!", "'") ?>',
            }, function (value) {
                if (value === false) {
                    return;
                }

                formget(
                    "/cabride/cashreturn/request-cash-return",
                    {
                        "driverId": driverId
                        <?php if (is_array($paramsCash)): ?>
                        ,"from": "<?php echo $paramsCash["from"] ?>",
                        "to": "<?php echo $paramsCash["to"] ?>"
                        <?php endif; ?>
                    },
                    function (data) {
                        // Success!
                        feature_form_success(data.message);
                        setTimeout(function () {
                            location.reload();
                        }, 3000);
                    },
                    function (data) {
                        feature_form_error(data.message);
                    });

                swal.close();
                return true;
            });
        });

        let markAsReturned = $(".mark-as-returned");

        markAsReturned.off("click");
        markAsReturned.on("click", function () {
            let button = $(this);
            let cashReturnId = button.attr("data-id");
            swal({
                html: true,
                title: '<?php echo p__js("cabride", "Mark as returned", "'") ?>',
                text: '<?php echo p__js("cabride","Are you sure?", "'") ?>',
                showCancelButton: true,
                closeOnConfirm: false,
                closeOnCancel: true,
                confirmButtonColor: '#449d44',
                confirmButtonText: '<?php echo p__js("cabride","Yes, mark as returned", "'") ?>',
                cancelButtonText: '<?php echo p__js("cabride","No, go back!", "'") ?>',
            }, function (value) {
                if (value === false) {
                    return;
                }

                formget(
                    "/cabride/cashreturn/mark-as-returned",
                    {
                        'cashReturnId': cashReturnId
                    },
                    function (data) {
                        // Success!
                        feature_form_success(data.message);
                        setTimeout(function () {
                            location.reload();
                        }, 3000);
                    },
                    function (data) {
                        feature_form_error(data.message);
                    });

                swal.close();
                return true;
            });
        });

        let payoutRequest = $(".payout-request");

        payoutRequest.off("click");
        payoutRequest.on("click", function () {
            let button = $(this);
            let driverId = button.attr("data-driver-id");
            swal({
                html: true,
                title: '<?php echo p__js("cabride", "Mark for payout", "'") ?>',
                text: '<?php echo p__js("cabride","Are you sure?", "'") ?>',
                showCancelButton: true,
                closeOnConfirm: false,
                closeOnCancel: true,
                confirmButtonColor: '#449d44',
                confirmButtonText: '<?php echo p__js("cabride","Yes, mark for payout", "'") ?>',
                cancelButtonText: '<?php echo p__js("cabride","No, go back!", "'") ?>',
            }, function (value) {
                if (value === false) {
                    return;
                }

                formget(
                    "/cabride/payout/single-driver",
                    {
                        "driverId": driverId
                        <?php if (is_array($paramsPayout)): ?>
                        ,"from": "<?php echo $paramsPayout["from"] ?>",
                        "to": "<?php echo $paramsPayout["to"] ?>"
                        <?php endif; ?>
                    },
                    function (data) {
                        // Success!
                        feature_form_success(data.message);
                        setTimeout(function () {
                            location.reload();
                        }, 3000);
                    },
                    function (data) {
                        feature_form_error(data.message);
                    });

                swal.close();
                return true;
            });
        });

        let markAsPaid = $(".mark-as-paid");

        markAsPaid.off("click");
        markAsPaid.on("click", function () {
            let button = $(this);
            let payoutId = button.attr("data-id");
            swal({
                html: true,
                title: '<?php echo p__js("cabride", "Mark as paid", "'") ?>',
                text: '<?php echo p__js("cabride","Are you sure?", "'") ?>',
                showCancelButton: true,
                closeOnConfirm: false,
                closeOnCancel: true,
                confirmButtonColor: '#449d44',
                confirmButtonText: '<?php echo p__js("cabride","Yes, mark as paid", "'") ?>',
                cancelButtonText: '<?php echo p__js("cabride","No, go back!", "'") ?>',
            }, function (value) {
                if (value === false) {
                    return;
                }

                formget(
                    "/cabride/payout/mark-as-paid",
                    {
                        'payoutId': payoutId
                    },
                    function (data) {
                        // Success!
                        feature_form_success(data.message);
                        setTimeout(function () {
                            location.reload();
                        }, 3000);
                    },
                    function (data) {
                        feature_form_error(data.message);
                    });

                swal.close();
                return true;
            });
        });

        let bulkPayout = $(".bulk-payout");

        bulkPayout.off("click");
        bulkPayout.on("click", function () {
            let button = $(this);
            swal({
                html: true,
                title: '<?php echo p__js("cabride", "Bulk payout", "'") ?>',
                <?php
                    if (is_array($paramsPayout)):
                        $from = datetime_to_format($paramsPayout['from'], \Zend_Date::DATE_SHORT);
                        $to = datetime_to_format($paramsPayout['to'], \Zend_Date::DATE_SHORT);
                ?>
                text: '<?php echo p__js("cabride","You are about to generate a bulk payout file for the following period %s", "'", "{$from} - {$to}") ?>',
                <?php else: ?>
                text: '<?php echo p__js("cabride","You are about to generate a bulk payout file for all unpaid rides.", "'") ?>',
                <?php endif; ?>
                showCancelButton: true,
                closeOnConfirm: false,
                closeOnCancel: true,
                confirmButtonColor: '#449d44',
                confirmButtonText: '<?php echo p__js("cabride","Yes, generate bulk report", "'") ?>',
                cancelButtonText: '<?php echo p__js("cabride","No, go back!", "'") ?>',
            }, function (value) {
                if (value === false) {
                    return;
                }

                formget(
                    "/cabride/payout/bulk",
                    {
                        "valueId": "<?php echo $valueId ?>"
                        <?php if (is_array($paramsPayout)): ?>
                        ,"from": "<?php echo $paramsPayout["from"] ?>",
                        "to": "<?php echo $paramsPayout["to"] ?>"
                        <?php endif; ?>
                    },
                    function (data) {
                        // Success!
                        feature_form_success(data.message);
                        setTimeout(function () {
                            location.reload();
                        }, 3000);
                    },
                    function (data) {
                        feature_form_error(data.message);
                    });

                swal.close();
                return true;
            });
        });
    });
</script>
<style type="text/css">
    .cabride-archives .label {
        font-size: 80%;
        font-weight: 200;
        letter-spacing: 2px;
        text-transform: uppercase;
        padding: .2em .4em .2em;
    }
</style>
