<?php

use Cabride\Model\Cabride;
use Cabride\Model\Client;

$application = $this->getApplication();
$request = $this->getRequest();
$valueId = Cabride::getCurrentValueId();

$passengers = (new Client())
    ->fetchForValueId($valueId);

?>
<div class="row">
    <div class="col-md-12">
        <div class="page-content-wrapper">
            <div id="passenger_content"
                 class="content solo-page sb-tour">
                <h3 class="title-editor border-blue text-center">
                    <?php echo p__("cabride", "Passengers"); ?>
                </h3>
                <div class="subcontent content-color">
                    <div class="col-md-12">
                        <table class="table content-white-bkg sb-pager margin-top">
                            <thead>
                            <tr class="border-grey">
                                <th class="sortable numeric"><?php echo p__("cabride", "ID"); ?></th>
                                <th class="sortable numeric"><?php echo p__("cabride", "Customer ID"); ?></th>
                                <th class="sortable"><?php echo p__("cabride", "Firstname"); ?></th>
                                <th class="sortable"><?php echo p__("cabride", "Lastname"); ?></th>
                                <th class="sortable"><?php echo p__("cabride", "Email"); ?></th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($passengers as $passenger): ?>
                                <tr class="sb-pager">
                                    <td>
                                        <b>#<?php echo $passenger->getId(); ?></b>
                                    </td>
                                    <td>
                                        <a class="btn btn-xs btn-info"
                                           href="<?php echo __path("/customer/application/edit/", [
                                               "customer_id" => $passenger->getCustomerId()
                                           ]); ?>">
                                            #<?php echo $passenger->getCustomerId(); ?>
                                        </a>
                                    </td>
                                    <td><?php echo $passenger->getFirstname(); ?></td>
                                    <td><?php echo $passenger->getLastname(); ?></td>
                                    <td><?php echo $passenger->getEmail(); ?></td>
                                    <td class="text-right">
                                        <a class="btn btn-xs btn-warning set-as-driver"
                                           data-id="<?php echo $passenger->getId(); ?>">
                                            <?php echo p__("cabride", "SET AS DRIVER") ?>
                                        </a>
                                        <a class="btn btn-xs btn-info"
                                           href="<?php echo __path("/customer/application/edit", [
                                               "customer_id" => $passenger->getCustomerId()
                                           ]); ?>">
                                            <?php echo p__("cabride", "EDIT") ?>
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="6">
                                        <?php echo p__("cabride", "No results for your search.") ?>
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var search_placeholder = '<?php echo p__js("cabride","Search ...", "'") ?>';
    $(document).ready(function () {
        bindForms("#passenger_content");

        $("table.sb-pager").sbpager({
            with_search: true,
            search_placeholder: search_placeholder
        });

        let deletePassenger = $(".delete-passenger");

        deletePassenger.off("click");
        deletePassenger.on("click", function () {
            let button = $(this);
            let passengerId = button.attr("data-id");
            swal({
                html: true,
                title: '<?php echo p__js("cabride", "Delete passenger", "'") ?>',
                text: '<?php echo p__js("cabride","Are you sure?", "'") ?>',
                showCancelButton: true,
                closeOnConfirm: false,
                closeOnCancel: true,
                confirmButtonColor: '#ff3a2e',
                confirmButtonText: '<?php echo p__js("cabride","Yes, Delete", "'") ?>',
                cancelButtonText: '<?php echo p__js("cabride","No, go back!", "'") ?>',
            }, function (value) {
                if (value === false) {
                    return;
                }

                formget(
                    "/cabride/client/deletepost",
                    {
                        'client_id': passengerId
                    },
                    function (data) {
                        // Success!
                        feature_form_success(data.message);
                        setTimeout(function () {
                            location.reload();
                        }, 3000);
                    },
                    function (data) {
                        feature_form_error(data.message);
                    });

                swal.close();
                return true;
            });
        });

        let setAsDriver = $(".set-as-driver");

        setAsDriver.off("click");
        setAsDriver.on("click", function () {
            let button = $(this);
            let passengerId = button.attr("data-id");
            swal({
                html: true,
                title: '<?php echo p__js("cabride", "This user will be granted as a driver.", "'") ?>',
                text: '<?php echo p__js("cabride","Are you sure?", "'") ?>',
                showCancelButton: true,
                closeOnConfirm: false,
                closeOnCancel: true,
                confirmButtonColor: '#ff3a2e',
                confirmButtonText: '<?php echo p__js("cabride","Yes, Set as driver", "'") ?>',
                cancelButtonText: '<?php echo p__js("cabride","No, go back!", "'") ?>',
            }, function (value) {
                if (value === false) {
                    return;
                }

                formget(
                    "/cabride/client/set-as-driver",
                    {
                        'clientId': passengerId
                    },
                    function (data) {
                        // Success!
                        feature_form_success(data.message);
                        setTimeout(function () {
                            location.pathname = "/cabride/dashboard/drivers";
                        }, 3000);
                    },
                    function (data) {
                        feature_form_error(data.message);
                    });

                swal.close();
                return true;
            });
        });

        <?php if ($_GET["q"] && !empty($_GET["q"])): ?>
        setTimeout(function () {
            $(".sb-search-content input[type='text']")
                .val("<?php echo __js($_GET["q"]) ?>")
                .trigger("keyup");
        }, 500);
        <?php endif; ?>
    });
</script>
