<?php
$optionValue = $this->getOptionValue();

$formDefault = new Siberian_Form_Options();

$deleteForm = new Siberian_Form_Options();

$collection = [];

/**$wordpress = (new Wordpress2_Model_Wordpress())
    ->find($optionValue->getId(), 'value_id');

// Create the WordPress if it doesn't yet exists.
if (!$wordpress->getId()) {
    $wordpress = new Wordpress2_Model_Wordpress();
    $wordpress
        ->setValueId($optionValue->getId())
        ->save();
}

$wordpressHasUrl = !empty(trim($wordpress->getData('url')));

$formWordpress = new Wordpress2_Form_Wordpress();
$formWordpress->populate($wordpress->getData());
$formWordpress
    ->getElement('password')
    ->setValue($wordpress->getPassword());

$formQuery = new Wordpress2_Form_Query();
$formQuery->populate(
    [
        'value_id' => $optionValue->getId()
    ]
);

$formSettings = new Wordpress2_Form_Settings();
$formSettings->populate($wordpress->getData());

$queries = (new Wordpress2_Model_Query())
    ->findAll(
        [
            'value_id' => $optionValue->getId()
        ],
        'position ASC'
    );

// Display sort fields only if queries are not grouped!
if ($wordpress->getData('group_queries') !== '1') {
    $formQuery->addSortFields();
}

$gotCategories = false;
try {
    $wordpressApi = new Wordpress2_Model_WordpressApi();
    $wordpressApi->init(
        $wordpress->getData('url'),
        $wordpress->getData('login'),
        $wordpress->getData('password')
    );

    $categories = $wordpressApi->getCategories();

    $formQuery
        ->loadCategories($categories);

    $gotCategories = (sizeof($categories) > 0);

} catch (Exception $e) {
    $gotCategories = false;
}

$gotPages = false;
try {
    $wordpressApi = new Wordpress2_Model_WordpressApi();
    $wordpressApi->init(
        $wordpress->getData('url'),
        $wordpress->getData('login'),
        $wordpress->getData('password')
    );

    $pages = $wordpressApi->getAllPages();

    $formQuery
        ->loadPages($pages);

    $gotPages = (sizeof($pages) > 0);

} catch (Exception $e) {
    $gotPages = false;
}

$formQuery->createSubmit();*/

?>

<div id="list"
     class="#MODULE_ACTION#">

    <!-- Nav tabs -->
    <ul class="nav nav-tabs"
        role="tablist">
        <li role="presentation"
            class="active">
            <a href="##MODULE_ACTION#"
               aria-controls="#MODULE_ACTION#"
               role="tab"
               data-toggle="tab">
                <i class="fa fa-folder-open-o"></i>
                <?php echo __('WordPress') ?>
            </a>
        </li>
        <li role="presentation">
            <a href="#design"
               aria-controls="design"
               role="tab"
               data-toggle="tab">
                <i class="fa fa-pencil"></i>
                <?php echo __('Design') ?>
            </a>
        </li>
    </ul>

    <div class="tab-content">
        <!-- START #MODULE# TAB -->
        <div role="tabpanel"
             class="tab-pane active"
             id="#MODULE_ACTION#">

            <div class="feature-block-add">
                <h3 class="title-editor no-border-radius title-feature-indent">
                    <?php echo __('Add a query'); ?>
                    <button type="button"
                            class="feature-toggle-add toggle_design color-blue pull-right bt-header-right btn">
                        <i class="fa fa-plus"></i>
                    </button>
                </h3>
                <div class="container-fluid subcontent content-feature">
                    <?php echo $formDefault; ?>
                </div>
            </div>

            <?php if ($collection->count() > 0): ?>
                <div class="feature-block-list">
                    <div class="margin-top">
                        <h3 class="title-editor no-border-radius title-feature-indent">
                            <?php echo __('Manage elements'); ?>
                            <button type="button"
                                    class="toggle_design color-blue pull-right bt-header-right btn feature-toggle-items">
                                <i class="fa fa-angle-down"></i>
                            </button>
                        </h3>
                        <div class="container-fluid first-row-feature content-feature feature-manage-items">
                            <table class="table content-white-bkg sb-pager">
                                <thead>
                                    <tr class="border-grey">
                                        #FIELDS_HEAD#
                                        <th></th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                <?php foreach($collection as $item) : ?>
                                    <tr id="#MODULE_ACTION#_manage_element_<?php echo $item->getId(); ?>"
                                        class="#MODULE_ACTION#-manage-element sb-pager">
                                        #FIELDS_BODY#
                                        <td class="edit-action open-edit"
                                            data-id="#MODULE_ACTION#_<?php echo $item->getId(); ?>"
                                            data-form-url="<?php echo __path('/#MODULE_ACTION#/application/loadform', [
                                                '#PRIMARY_KEY#' => $item->getId(),
                                                'value_id' => $optionValue->getId()
                                            ]); ?>">
                                            <i class="fa fa-pencil"></i>
                                        </td>
                                        <td class="delete-action">
                                            <?php
                                                $deleteForm->setAttrib('data-rowid', '#MODULE_ACTION#_manage_element_' . $item->getId());
                                                $deleteForm
                                                    ->getElement('#PRIMARY_KEY#')
                                                    ->setValue($item->getId());

                                                echo $deleteForm;
                                            ?>
                                        </td>
                                    </tr>
                                    <tr class="edit-form"
                                        data-id="#MODULE_ACTION#_<?php echo $item->getId(); ?>"
                                        style="display: none;">
                                        <td colspan="6">
                                            <p class="close-edit"
                                               data-id="#MODULE_ACTION#_<?php echo $item->getId(); ?>">
                                                <i class="fa fa-times"></i><?php echo __('Close') ?>
                                            </p>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        </div>
        <!-- /END #MODULE# TAB -->

        <!-- START DESIGN TAB -->
        <div role="tabpanel"
             class="tab-pane"
             id="design">
            <?php echo $this->importLayout($optionValue, false); ?>

            <?php echo $this->importBackground($optionValue, false); ?>
        </div>
        <!-- /END DESIGN TAB -->
    </div>
</div>


<link href="/app/sae/modules/#MODULE#/resources/design/desktop/flat/template/#MODULE_ACTION#/application/edit.css"
      media="screen"
      rel="stylesheet"
      type="text/css" />
<script type="text/javascript">
    var valueId = '<?php echo $optionValue->getId() ?>';
</script>
<script type="text/javascript"
        src="/app/sae/modules/#MODULE#/resources/design/desktop/flat/template/#MODULE_ACTION#/application/edit.js">
</script>