<?php $current_link = $this->getCurrentLink(); ?>
<?php $editor = $this->getAdmin()->getWhiteLabelEditor(); ?>
<?php if(APPLICATION_ENV != "production"): ?>
    <div class="alert alert-warning development-responsive">
        <i class="fa fa-exclamation-triangle"></i>
    <span>
        <?php echo __("Be careful you are working in"); ?>
    </span>
        <b><?php echo __("Development") ?></b>
    </div>
<?php endif; ?>
<nav class="navbar navbar-default content-white-bkg">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header color-blue">
        <?php $platform_name = System_Model_Config::getValueFor("platform_name"); ?>
        <a id="sb-tour-logo-platform" href="<?php echo $this->getUrl('application/customization_design_style/edit'); ?>" class="sb-tour pull-left logo-position">
            <img src="<?php echo $this->getLogo(); ?>" id="logo" alt="<?php echo $platform_name; ?>" title="<?php echo $platform_name; ?>" width="100%" />
        </a>
        <div class="logo-block"></div>
        <?php if($current_link == 'edit') : ?>
        <a id="left-menu-toggle" href="#left-menu-toggle" class="sb-tour">
            <button type="button" class="btn-close-sidebarleft color-blue btn">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </a>
        <?php endif; ?>
    </div>
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span> 
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <div class="collapse navbar-collapse" id="bs-navbar">
        <?php if(System_Model_Config::getValueFor("bootstraptour_active") == "1"): ?>
            <button id="sb-tour-enable" class="sb-tour pull-right btn color-blue" onclick="launchBootstrapTour()">
                <i class="fa fa-question-circle-o" style="font-size: 25px;"></i>
            </button>
        <?php endif; ?>
        <ul class="nav navbar-nav navbar-right">
            <li>
                <a id="sb-tour-editor" href="<?php echo $this->getUrl('application/customization_design_style/edit'); ?>" class="<?php if($current_link == 'edit'): ?> active<?php endif; ?> box foo sb-tour" title="<?php echo __('Editor') ?>">
                    <i class="fa fa-tachometer"></i>
                    <div class="section-responsive">
                        <?php echo __('Editor') ?>
                    </div>
                </a>
            </li>

            <li>
                <a id="sb-tour-my-account" href="<?php echo $this->getUrl('admin/account/edit'); ?>" class="<?php if($current_link == 'my_account') : ?> active<?php endif; ?> box foo sb-tour" title="<?php echo __('My account') ?>">
                    <i class="fa fa-user"></i>
                    <div class="section-responsive">
                        <?php echo __('My account'); ?>
                    </div>
                </a>
            </li>

            <?php if($this->_canAccess("push_admin_global")) : ?>
            <li>
                <a id="sb-tour-global-push" href="<?php echo $this->getUrl('push/admin/global'); ?>" class="<?php if($current_link == 'push_global') : ?> active<?php endif; ?> box foo sb-tour" title="<?php echo __('Push notifications') ?>">
                    <i class="fa fa-bullhorn"></i>
                    <div class="section-responsive">
                        <?php echo __('Push notifications'); ?>
                    </div>
                </a>
            </li>
            <?php endif; ?>

            <?php if(!$this->getRequest()->isWhiteLabelEditor()) : ?>

                <?php if($this->_canAccess("admin_access_management")) : ?>
                <li>
                    <a id="sb-tour-access-management" href="<?php echo $this->getUrl('admin/access_management/list'); ?>" class="<?php if($current_link == 'access_management') : ?> active<?php endif; ?> box foo sb-tour" title="<?php echo __('Access Management') ?>">
                        <i class="fa fa-road"></i>
                        <div class="section-responsive">
                            <?php echo __('Access Management'); ?>
                        </div>
                    </a>
                </li>
                <?php endif; ?>

                <?php if($this->_canAccess("support") AND $url = System_Model_Config::getValueFor("support_link")) : ?>
                    <li class="right">
                        <a id="sb-tour-support" href="<?php echo $url; ?>" target="_blank" title="<?php echo __('Support') ?>" class="box foo sb-tour">
                            <i class="fa fa-medkit"></i>
                            <div class="section-responsive">
                                <?php echo __('Support'); ?>
                            </div>
                        </a>
                    </li>
                <?php endif; ?>
            <?php endif; ?>
            <?php if($this->getSession()->getAdmin()->isAllowedToManageTour()): ?>
                <li>
                    <a href="#" title="<?php echo $this->_('Manage Tour'); ?>" onclick="sbTour.switchTourEdition()"  class="box foo">
                        <i class="fa fa-map-signs"></i>
                        <div class="section-responsive">
                            <?php echo $this->_('Manage Tour'); ?>
                        </div>
                    </a>
                </li>
            <?php endif; ?>
            <li>
                <a href="<?php echo $this->getUrl('admin/account/logout'); ?>" title="<?php echo __('Log-out') ?>" class="box foo">
                    <i class="fa fa-power-off"></i>
                    <div class="section-responsive">
                        <?php echo __('Log-out') ?>
                    </div>
                </a>
            </li>
            <?php echo $this->getPartialHtml('languages'); ?>
        </ul>
    </div>
</nav>

<style>
    #sb-tour-enable{
        height: 50px;
        margin-top: 4px;
        margin-left: 5px;
        width: 50px;
    }
</style>