<?php $order = $this->getCurrentOrder(); ?>

<table width="100%" style="max-width:600px">
    <tr style="padding: 0 15px; color:#888888; font-size: 17px; line-height: 150%; width:600px">
        <td>
            <p style="font-family: Verdana; font-weight: bold;color: #12a7ff;font-size:18px; line-height:150%;"><?php echo $this->_('Hello,'); ?></p>
            <p align="justify">
                <span style="color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 13px;">
                    <?php echo $this->_('Here is the detail of your order'); ?>
                </span>
            </p>
 
  <table width="100%">
                <col width="50%"/>
                <col width="50%"/>
 <tr>
  <td style="width:50%;vertical-align: top;">
            <h4 style="margin:10px 0; color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 15px;"><?php echo $this->_('Client'); ?></h4>
            <p style="margin:0; color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 13px;"><?php echo $order->getCustomerFirstname() . ' ' . $order->getCustomerLastname(); ?></p>
            <p style="margin:0; color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 13px;"><?php echo $order->getCustomerStreet();  ?></p>
			<p style="margin:0; color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 13px;"><?php echo $order->getCustomerStreetc(); ?></p>
            <p style="margin:0; color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 13px;"><?php echo $order->getCustomerPostcode(); ?> <?php echo $order->getCustomerCity(); ?></p>
            <p style="margin:0; color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 13px;"><?php echo $order->getCustomerPhone(); ?></p>
            <br />
 </td>
 <?php $store=$order->getStore();?>
 <td style="width:50%;vertical-align: top;">
            <h4 style="margin:10px 0; color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 15px;"><?php echo $store->getData("name"); ?></h4>
            <p style="margin:0; color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 13px;"><?php echo nl2br($store->getData("street")); ?></p>
            <p style="margin:0; color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 13px;"><?php echo $store->getData("postcode").' '.$store->getData("city");  ?></p>
			<p style="margin:0; color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 13px;"></p>
            <p style="margin:0; color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 13px;"><a href="mailto:<?php echo $store->getData("email") ?>"><?php echo $store->getData("email") ?></a></p>
            <p style="margin:0; color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 13px;"><?php echo $this->_('Phone').' '.$store->getData("phone"); ?></p>
			<p style="margin:0; color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 13px;"><?php echo $this->_('Hours of operation').' '.$store->getData("opening_hours"); ?></p>
            <br />
 </td>	 
</tr>
</table>


<?php
$strDeliveryMethod=$order->getDeliveryMethod();
if ($order->getData("delivery_datetime")!=null)	{$strDeliveryMethod .= '<br>'.$order->getData("delivery_datetime");}
if ($order->getData("delivery_comment")!=null)	{$strDeliveryMethod .= '<br>'.nl2br($order->getData("delivery_comment"));}
?>

            <h4 style="margin:10px 0; color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 15px;"><?php echo $this->_('Order details').' : '.$order->getNumber(); ?></h4>
            <table width="100%">
                <col width="50%"/>
                <col width="50%"/>
                <tr>
                    <th align="left"><?php echo $this->_('Delivery Method'); ?></th>
                    <th align="left"><?php echo $this->_('Payment Method'); ?></th>
                </tr>
                <tr>
                    <td style="vertical-align: top;"><?php echo $strDeliveryMethod; ?></td>
                    <td style="vertical-align: top;"><?php echo $order->getPaymentMethod(); ?></td>
                </tr>
            </table>
            <br />
            <table width="100%">
                <col width="70%" />
                <col width="10%" />
                <col width="10%" />
                <col width="10%" />
                <tr>
                    <th align="left"><?php echo $this->_('Product'); ?></th>
                    <th><?php echo $this->_('Unit Price'); ?></th>
                    <th><?php echo $this->_('Qty'); ?></th>
                    <th><?php echo $this->_('Total'); ?></th>
                </tr>
                <tr><td colspan="4"><div style="width:100%;margin-top:5px;margin-bottom:5px;border-bottom:2px solid black;"></div></td></tr>
            <?php foreach($order->getLines() as $line) : ?>
                <?php $format = unserialize($line->getFormat()); ?>
                <?php $text_format = isset($format['title']) ? "<br />" . $this->_("Format:") . " " . $format['title'] : ""; ?>
                <tr>
                    <td><?php echo $line->getName() . $text_format; ?></td>
                    <td align="right"><?php echo $line->getFormattedBasePriceInclTax(); ?></td>
                    <td align="center"><?php echo $line->getQty(); ?></td>
                    <td align="right"><?php echo count($line->getOptions()) ? $line->formatPrice($line->getBasePriceInclTax() * $line->getQty()): $line->formatPrice($line->getTotalInclTax()); ?></td>
                </tr>
                <?php foreach($line->getOptions() as $option) : ?>
                <tr>
                    <td style="font-size:13px;">+ <?php echo $option->getQty(); ?>x <?php echo $option->getName(); ?></td>
                    <td style="font-size:13px;" align="right"><?php echo $option->getFormattedBasePrice(); ?></td>
                    <td style="font-size:13px;" align="center"><?php echo $option->getQty() * $line->getQty(); ?></td>
                    <td style="font-size:13px;" align="right"><?php echo $line->formatPrice($option->getPriceInclTax() * $line->getQty()); ?></td>
                </tr>
                <?php endforeach; ?>
                <tr><td colspan="4"><div style="width:100%;margin-top:5px;margin-bottom:5px;border-bottom:1px solid black;"></div></td></tr>
            <?php endforeach; ?>
            </table>
            <br />
            <h4 style="margin:0; color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 15px;"><?php echo $this->_('Total'); ?></h4>
            <table width="100%">
                <col width="80%" />
                <col width="20%" />
                <tr><td colspan="2"><div style="width:100%;margin-top:0px;margin-bottom:5px;border-bottom:2px solid black;"></div></td></tr>
                <tr>
                    <th align="left"><?php echo $this->_('Subtotal'); ?></th>
                    <td align="right"><?php echo $order->getFormattedSubtotalExclTax(); ?></td>
                </tr>
                <?php if($order->getDeliveryCost() > 0) : ?>
                <tr class="cart_totals">
                    <th align="left"><?php echo $this->_('Delivery Fees'); ?></th>
                    <td align="right"><?php echo $order->getFormattedDeliveryCost(); ?></td>
                </tr>
                <tr class="cart_totals">
                    <th align="left"><?php echo $this->_('Total Excl. Tax'); ?></th>
                    <td align="right"><?php echo $order->getFormattedTotalExclTax(); ?></td>
                </tr>
                <?php endif; ?>
                <tr class="cart_totals">
                    <th align="left"><?php echo $this->_('Total Tax'); ?></th>
                    <td align="right"><?php echo $order->getFormattedTotalTax(); ?></td>
                </tr>
                <tr class="cart_totals">
                    <th align="left"><?php echo $this->_('Total'); ?></th>
                    <td align="right"><?php echo $order->getFormattedTotal(); ?></td>
                </tr>
                <?php if($order->getPaidAmount() && !$order->getHidePaidAmount()) : ?>
                <tr><td colspan="2"><div style="width:100%;margin-top:0px;margin-bottom:5px;border-bottom:2px solid black;"></div></td></tr>
                <tr>
                    <th align="left"><?php echo $this->_("I will pay"); ?></th>
                    <td align="right"><?php echo $order->getFormattedPaidAmount(); ?></td>
                </tr>
                <tr>
                    <th align="left"><?php echo $this->_("Remaining due"); ?></th>
                    <td align="right"><?php echo $order->formatPrice($order->getPaidAmount() - $order->getTotal()); ?></td>
                </tr>
                <?php endif; ?>
            </table>
        </td>
    </tr>
</table>