<?php $application = $this->getApplication(); ?>
<div class="row">
    <div class="col-md-12">
        <div class="page-content-wrapper">
            <div id="facebook_content" class="content solo-page">
                <h3 class="title-editor border-blue">
                    <?php echo $this->_('Facebook API Keys'); ?>
                </h3>
                <div id="facebook" class="subcontent content-color">
                    <div class="col-md-12">
                        <form id="facebookForm" action="<?php echo $this->getUrl('application/settings_facebook/save'); ?>" onsubmit="return false" class="form-horizontal">
                            <div class="container-fluid">
                                <div class="form-group">
                                   <div class="col-sm-2">
                                       <label for="facebook_id" class="control-label"><?php echo $this->_('App ID'); ?> : </label>
                                   </div>
                                    <div class="col-sm-4">
                                        <input type="text" id="facebook_id" name="facebook_id" class="input-flat" value="<?php echo $application->getData("facebook_id") ?>" />
                                    </div>
                                </div>
                                <div class="form-group">
                                   <div class="col-sm-2">
                                       <label for="facebook_key" class="control-label"><?php echo $this->_('Secret Key'); ?> : </label>
                                   </div>
                                    <div class="col-sm-4">
                                        <input type="text" id="facebook_key" name="facebook_key" class="input-flat" value="<?php echo $application->getData("facebook_key") ?>" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-2 pull-right">
                                        <button type="submit" class="add color-blue btn"><?php echo $this->_("Save"); ?></button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(document).ready(function(){
        $('#facebookForm').submit(function() {
            reload(this, this.action, true);
            return false;
        });
    });

</script>