<div sb-background-image value-id="'homepage'" close-on-click="close_on_click" ng-class="{background_image: style_background_image, close_on_click: close_on_click}" ng-style="style_background_image" ng-if="menu_is_visible">

    <sb-slider ng-if="homepage_slider_is_visible && homepage_slider_images" images="homepage_slider_images" autoslide-duration="homepage_slider_duration" loop-at-beginning="homepage_slider_loop_at_beginning"></sb-slider>

    <div tabbar ng-class="{'transparent-background': tabbar_is_transparent}"></div>

</div>