<?php $store = $this->getCurrentStore(); ?>
<?php $option_value = $this->getCurrentOptionValue(); ?>
<li id="row_<?php echo $store->getId(); ?>">
    <form class="form_booking form-horizontal">
        <div class="form-group">
            <div class="col-sm-4">
                <input type="text" id="store_name_<?php echo $store->getId() ?>" name="store_name" class="form-control booking_field required" value="<?php echo $store->getStoreName(); ?>"/>
            </div>
            <div class="col-sm-5">
                <input type="text" id="email_<?php echo $store->getId() ?>" name="email" class="form-control booking_field required email" value="<?php echo $store->getEmail(); ?>"/>
            </div>
            <div class="col-sm-1">
                <button type="submit" class="bt-margin default_button save_booking">OK</button>
            </div>
            <div class="col-sm-1">
                <button type="button" rel="<?php echo $store->getId(); ?>" class="bt-margin delete delete_booking"><i class="icon-remove"></i></button>
            </div>
            <input type="hidden" name="value_id" value="<?php echo $option_value->getId(); ?>"/>
            <input type="hidden" name="store_id" value="<?php echo $store->getId(); ?>"/>
        </div>
    </form>
</li>
