<?php $application = $this->getApplication(); ?>
<div class="installer application">
    <div class="application_content inner_content">
        <div class="title">
            <i class="left icon-download-alt"></i>
            <h2 class="left inner_content f-rounded"><?php echo $this->_('Modules'); ?></h2>
            <div class="clear"></div>
            <hr />
        </div>
        <div class="area">
            <h3 class="title">
                <span class="left area"><?php echo $this->_('Upload a module'); ?></span>
                <div class="clear"></div>
            </h3>
            <div>
                <form id="uploadModule" method="post" name="uploadModule" action="<?php echo $this->getUrl('installer/module/upload'); ?>" enctype="multipart/form-data">
                    <br />
                    <div><p><?php echo $this->_('Select a module to upload'); ?></p></div>
                    <br />
                    <div><input type="file" name="module" value="" /></div>
                    <br />
                    <div><button class="default_button"><?php echo $this->_('Send'); ?></button></div>
                </form>
            </div>
        </div>
    </div>
    <style>
        .installer .inner_content .default_button {
            width: auto;
            padding: 0 10px;
        }
    </style>
</div>