<div id="modal_#{id}" class="custom_modal" style="display:none;">
    <div id="modal_mask_#{id}" class="modal_mask close_modal close_modal_#{id}"></div>
    <div id="modal_content_#{id}" class="modal_content content content-color">
    
        <h3 class="title-editor border-red">
            <span class="f-bold"><?php echo $this->getTitle(); ?></span>
            <button id="close_modal_#{id}" class="close_modal close_modal_#{id} btn-add pull-right" type="button">
                <i class="fa fa-times"></i>
            </button>
        </h3>
        <div class="col-md-12 content-white-bkg container-fluid">
            <p class="f-bold"><?php echo $this->getSubtitle(); ?></p>

            <div id="modal_details_#{id}" class="modal_details content">
            <?php echo $this->getPartialHtml('modal_content'); ?>
            </div>
        </div>
    </div>
</div>