<sb-section title="'<?php echo addslashes($this->_("List of your users")); ?>'" button="button">
    <br />
    <div class="form-group">
        <label for="filter"><?php echo $this->_("Search"); ?></label>
        <input type="text" id="filter" class="form-control" ng-model="filter" placeholder="<?php echo $this->_("Search"); ?>" />
    </div>
    <br />
    <table class="table">
        <col width="5%" />
        <col width="25%" />
        <col width="25%" />
        <col width="25%" />
        <col width="15%" />
        <col width="5%" />
        <thead>
            <tr>
                <th class="pointer" ng-click="order = 'id'; by = !by"><?php echo $this->_("Id"); ?></th>
                <th class="pointer" ng-click="order = 'username'; by = !by"><?php echo $this->_("User name"); ?></th>
                <th class="pointer" ng-click="order = 'firstname'; by = !by"><?php echo $this->_("Firstname"); ?></th>
                <th class="pointer" ng-click="order = 'lastname'; by = !by"><?php echo $this->_("Lastname"); ?></th>
                <th class="pointer" ng-click="order = 'created_at'; by = !by"><?php echo $this->_("Created At"); ?></th>
                <th><?php echo $this->_("Actions"); ?></th>
            </tr>
        </thead>
        <tbody>
            <tr class="slide-left" ng-repeat="user in users | filter:filter | orderBy:order:by">
                <td>{{ user.id }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.firstname }}</td>
                <td>{{ user.lastname }}</td>
                <td>{{ user.created_at }}</td>
                <td>
                    <a href="<?php echo $this->getUrl("api/backoffice_user_edit"); ?>/user_id/{{ user.id }}" title="<?php echo $this->_("Edit"); ?>"><i class="fa fa-edit"></i></a>
                    <a href="#" ng-click="delete(user)" title="<?php echo $this->_("Delete"); ?>"><i class="fa fa-remove"></i></a>
                </td>
            </tr>
            <tr ng-show="!users.length">
                <td colspan="5" class="a-center"><?php echo $this->_("You don't have any users yet"); ?></td>
            </tr>
        </tbody>
    </table>
</sb-section>