<?php
$application = $this->getApplication();
$value = $this->getOptionValue();
$comment = new Comment_Model_Comment();
$comments = $comment->findAll(['value_id' => $value->getId()], 'comment_id DESC');
$appKey = $application->getGooglemapsKey();

?>
<div class="edit_page comment">
    <div id="list">

        <?php if (empty($appKey)): ?>
        <div class="alert alert-danger">
            <?php echo __("You must set a Google Maps API Key in %s in order to use this feature.",
                "<b>" . __("Settings") . " > " . __("API")."</b>") ?>
        </div>
        <?php endif; ?>

    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            bindForms('#list');
        });
    </script>
</div>
