<table>
    <tr style="margin:auto; padding: 0 15px; color:#888888; font-size: 17px; line-height: 150%; width:600px">
        <td>
            <p align="justify" style="color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 13px;">
                <?php echo __("A new contact form has been sent for the following offer:"); ?><br/>
                <b><?php echo $this->getPlaceTitle(); ?></b>
            </p>
            <hr style="margin:auto; padding: 0 15px; color:#e0e0e0; width:600px; height: 3px; border: 0; background-color: #e0e0e0;" />
            <p align="justify" style="color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 13px;">
                <?php echo $this->getFullname(); ?><br/>
                <?php echo $this->getEmail(); ?><br/><br/>
                <?php echo $this->getMessage(); ?>
            </p>
        </td>
    </tr>
</table>