<table width="100%" style="max-width:600px">
    <tr style="padding: 0 15px; color:#888888; font-size: 17px; line-height: 150%; width:600px">
        <td>
            <p align="justify">
                <span style="color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 13px;">
                    <?php echo $this->_("Sorry we can't proceed to deliver your order. It has been canceled."); ?>
                </span>
            </p>
        </td>
    </tr>
</table>