<?php
/**
 * @var Zend_Controller_Request_Http $request
 * @var Application_Model_Application $application
 */

    $application = $this->getApplication();
    $form = new Application_Form_Apis();

    $request = $this->getRequest();

    $form->setLoginCallbackUri(
        sprintf('%s://%s/%s?login_fb=true',
            $request->getScheme(),
            $request->getHttpHost(),
            $application->getKey())
    );
    $form->localInit();
    $form->populate($application->getData());
?>
<div class="row">
    <div class="col-md-12">
        <div class="page-content-wrapper">
            <div id="apis_content" class="content solo-page sb-tour">
                <h3 class="title-editor border-blue text-center">
                    <?php echo __('API Keys'); ?>
                </h3>
                <div class="subcontent content-color">
                    <div class="col-md-12">
                        <?php echo $form ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">

    $(document).ready(function(){
        bindForms('#apis_content');
    });

</script>
