<?php $option_value = $this->getOptionValue(); ?>
<?php $application = $this->getApplication(); ?>
<?php $weblink = $option_value->getObject(); ?>
<div class="form_content">
    <div id="list" class="edit_page weblink weblink_mono">
        <div class="mono">
            <form id="weblinkForm" name="weblinkForm" method="post" action="<?php echo $this->getUrl('weblink/application_mono/editpost') ?>" class="form-horizontal">
                <h3 class="title-editor no-border-radius title-feature-indent">
                    <?php echo __('Information') ?>
                </h3>
                <input type="hidden" name="value_id" value="<?php echo $option_value->getId(); ?>" />
                <div class="container-fluid first-row-feature content-feature">
                    <div class="infos">
                        <div id="weblink_content">
                            <div class="form-group">
                                <div class="col-sm-2">
                                    <label for="link"><?php echo __('Link') ?>:</label>
                                </div>
                                <div class="col-sm-8">
                                    <input type="text" id="weblink" name="link" class="input-flat url" value="<?php echo $weblink->getLink()->getUrl() ?>"/>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-2">
                                </div>
                                <div class="col-sm-4">
                                    <label for="link" class="checkbox-inline">
                                        <input  name="hide_navbar" class="color-blue checkbox" type="checkbox" <?php echo ($weblink->getLink()->getHideNavbar() ? 'checked' : '');?>/>
                                        <?php echo __('Without navbar') ?>
                                    </label>
                                </div>
                                <div class="col-sm-4">
                                    <label for="link" class="checkbox-inline">
                                        <input  name="use_external_app" class="color-blue checkbox" type="checkbox" <?php echo ($weblink->getLink()->getUseExternalApp() ? 'checked' : '');?>/>
                                        <?php echo __('Use external application') ?>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-12">
                            <div class="save pull-right">
                                <button class="btn btn-block color-blue" type="submit">
                                    <?php echo __('Save'); ?>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">

    page.setCallback('didappear', function() {

        $('#weblink').change(function() {
            if(!$(this).val().isEmpty() && !$(this).val().startsWith('http://') && !$(this).val().startsWith('https://')) {
                $(this).val('http://'+$(this).val());
            }
        });
        $('#weblinkForm').submit(function() {
            if(!$(this).valid()) return false;
            reload(this, this.action, true, function(datas) {
                if(datas.success) {
                    iframe.f.reloadTabbar();
                }
            });
            return false;
        });

    });

    page.setCallback('willdisappear', function() {
        $('#weblink').unbind('change');
        $('#weblinkForm').unbind('submit');
    });

</script>