<?php
// Show deprecated GCM settings for Siberian before 4.14.0!
$pre414 = false;
$installationVersion = __get('installation_version');
if (empty($installationVersion)) {
    $pre414 = true;
}
?>

<sb-section title="'<?php echo __js('Firebase Cloud Messaging', "'") ?>'">
    <form ng-submit="saveFirebaseCredentials()"
          autocomplete="off">
        <div class="form-group">
            <div class="col-md-4">
                <label for="Email"><?php echo __('E-mail') ?></label>
                <input type="text"
                       id="Email"
                       ng-model="firebase.email"
                       class="form-control"
                       autocomplete="new-password"
                       placeholder="<?php echo __js('E-mail', "'") ?>"/>
            </div>
            <div class="col-md-4">
                <label for="Passwd"><?php echo __('Password') ?></label>
                <input type="password"
                       id="Passwd"
                       ng-model="firebase.password"
                       class="form-control"
                       autocomplete="new-password"
                       placeholder="<?php echo __js('Password', "'") ?>"/>
            </div>
            <div class="col-md-4"
                 style="padding-top: 24px;">
                <button type="submit"
                        class="btn btn-primary left"><?php echo __('Save Firebase credentials'); ?></button>
                <sb-loader is_visible="credentialsLoader"
                           type="'inner_content'"
                           size="'small'"
                           animation="'no'"
                           class="form_loader"></sb-loader>
            </div>
            <div class="clear"></div>
        </div>
    </form>

    <form ng-submit="saveFirebaseProject()">
        <div class="form-group">
            <div class="col-md-4">
                <label for="DefaultProject"><?php echo __('Project Number (default)') ?></label>
                <select id="DefaultProject"
                        ng-model="firebase.projectNumber"
                        class="form-control">
                    <option value=""
                            ng-selected="!firebase.projectNumber"><?php echo __('Select a project') ?></option>
                    <option ng-repeat="project in projects"
                            ng-selected="firebase.projectNumber == project.projectNumber"
                            value="{{ project.projectNumber }}">{{ project.displayName }} ({{ project.projectId }} - {{ project.projectNumber }})</option>
                </select>
            </div>
            <div class="col-md-4">
                <label for="ServerKey"><?php echo __('Server key') ?></label>
                <input type="text"
                       id="ServerKey"
                       ng-model="firebase.serverKey"
                       class="form-control"
                       autocomplete="new-password"
                       placeholder="<?php echo __js('Server key', "'") ?>"/>
            </div>
            <div class="col-md-4"
                 style="padding-top: 24px;">
                <button type="submit"
                        class="btn btn-primary left"><?php echo __('Save project & key'); ?></button>
                <sb-loader is_visible="projectLoader"
                           type="'inner_content'"
                           size="'small'"
                           animation="'no'"
                           class="form_loader"></sb-loader>
            </div>
            <div class="clear"></div>
        </div>

        <div class="col-md-12">
            <div class="form-group">

            </div>
        </div>
    </form>
</sb-section>

<?php if ($pre414): ?>
<form ng-submit="saveKeys()">
    <sb-section title="'<?php echo __js('Google Cloud Messaging (GCM, Deprecated)', "'") ?>'">
        <div class="form-group">
            <div class="col-md-4">
                <label for="Key"><?php echo __('GCM Key') ?></label>
                <input type="text"
                       id="Key"
                       ng-model="gcm.android_key"
                       class="form-control"
                       autocomplete="new-password"
                       placeholder="<?php echo __js('GCM Key', "'") ?>"/>
            </div>
            <div class="col-md-4">
                <label for="SenderId"><?php echo __('Sender ID') ?></label>
                <input type="text"
                       id="SenderId"
                       ng-model="gcm.android_sender_id"
                       class="form-control"
                       autocomplete="new-password"
                       placeholder="<?php echo __js('Sender ID', "'") ?>"/>
            </div>
            <div class="col-md-4"
                 style="padding-top: 24px;">
                <button type="submit"
                        class="btn btn-primary left"><?php echo __('Save GCM settings'); ?></button>
                <sb-loader is_visible="form_loader_is_visible"
                           type="'inner_content'"
                           size="'small'"
                           animation="'no'"
                           class="form_loader"></sb-loader>
            </div>
            <div class="clear"></div>
    </sb-section>
</form>
<?php endif; ?>