<?php

use Push2\Model\Onesignal\Scheduler;
use Siberian\Json;

/**
 * @var $application Application_Model_Application
 */
$application = $this->getApplication();
$option = $this->getOptionValue();
$features = $application->getOptions();
$now = time();

$myAccount = (new Application_Model_Option())->find('tabbar_account', 'code');

// Special shared case with push/inApp
//$canSendMessages = ($option->getCode() === 'inapp_messages') ? true : $application->isPublished();

//$pntopic = new Topic_Model_Topic();
//$pntopic->find(
//    [
//        'app_id' => $option->getAppId()
//    ]
//);
//$customers = [];
//
//if (Push_Model_Message::hasIndividualPush()) {
//    $customer = new Customer_Model_Customer();
//    $customers = $customer->findAllWithDeviceUid($option->getAppId());
//}

$appKey = $application->getGooglemapsKey();

//$credentials = (new Push_Model_Firebase())
//    ->find(0, 'admin_id');
//
//$enable_android = !empty($credentials->getServerKey());
//$enable_ios = !empty(Push_Model_Certificate::getiOSCertificat($application->getId()));

try {
    $scheduler = new Scheduler($application);
    /**
     * @var $notificationSlice \onesignal\client\model\NotificationSlice
     */
    $notifications = $scheduler->fetchNotifications();
} catch (\Exception $e) {
    $notifications = [];
}


function getRates($notification): array {
    $notification->getFailed();
    $notification->getErrored();
    $notification->getSuccessful();
    $total = $notification->getFailed() + $notification->getErrored() + $notification->getSuccessful();
    if ($total <= 0) {
        return [0, 0];
    }

    $failed = $notification->getFailed() + $notification->getErrored();
    $success = $notification->getSuccessful();
    $success_rate = round(100 / $total * $success, 0);
    $failed_rate = round(100 / $total * $failed, 0);

    return [$success_rate, $failed_rate];
}

$feats = [];
foreach ($features as $feature) {
    $feats[] = $feature;
}

if (!function_exists('alphasortPushFeatures')) {
    function alphasortPushFeatures($a, $b)
    {
        return strcasecmp($a->getTabbarName(), $b->getTabbarName());
    }
}
usort($feats, 'alphasortPushFeatures');

$features = $feats;

$formSettings = new Push2\Form\Settings();

$settings = [
    'design' => 'list'
];
try {
    $dbSettings = Json::decode($option->getSettings());
} catch (\Exception $e) {
    $dbSettings = [];
}
$settings = array_merge($settings, $dbSettings);
$formSettings->populate($dbSettings);
$formSettings->setValueId($option->getId());

?>

<div class="edit_page push_notif">

    <!-- Nav tabs -->
    <ul class="nav nav-tabs"
        role="tablist">

        <li role="presentation"
            class="active">
            <a href="#tab-message"
               aria-controls="tab-message"
               role="tab"
               data-toggle="tab">
                <i class="fa fa-comments"></i>
                <?php echo p__('push', 'Messages') ?>
            </a>
        </li>

        <li role="presentation">
            <a href="#tab-history"
               aria-controls="tab-history"
               role="tab"
               data-toggle="tab">
                <i class="fa fa-gears"></i>
                <?php echo p__('push', 'History') ?>
            </a>
        </li>

        <li role="presentation">
            <a href="#tab-settings"
               aria-controls="tab-settings"
               role="tab"
               data-toggle="tab">
                <i class="fa fa-gears"></i>
                <?php echo p__('push', 'Settings') ?>
            </a>
        </li>

        <li role="presentation">
            <a href="#tab-design"
               aria-controls="tab-design"
               role="tab"
               data-toggle="tab">
                <i class="fa fa-image"></i>
                <?php echo p__('push', 'Design') ?>
            </a>
        </li>

    </ul>

    <div class="tab-content">

        <!-- MESSAGES -->
        <div role="tabpanel"
             class="tab-pane active"
             id="tab-message">

            <div id="list">
                <h3 class="title-editor no-border-radius title-feature-indent">
                    <?php echo p__('push2', 'Send a new push message'); ?>
                </h3>
                <div id="push2-message"
                     class="container-fluid first-row-feature content-feature">

                    <?php
                    $formPushMessage = new Push2\Form\Message(['application' => $application, 'features' => $features]);
                    $formPushMessage->setValueId($option->getId());
                    echo $formPushMessage;
                    ?>
                    <br />
                    <br />
                </div>
            </div>
        </div>
        <!-- MESSAGES -->

        <!-- MESSAGES HISTORY -->
        <div role="tabpanel"
             class="tab-pane"
             id="tab-history">
            <div class="feature-block-add">
                <?php if (sizeof($notifications) > 0): ?>
                    <div>
                        <h3 class="title-editor no-border-radius title-feature-indent">
                            <?php echo p__('push2', 'Message history') ?>
                        </h3>
                        <div class="container-fluid first-row-feature content-feature feature-manage-items">

                            <div class="alert alert-info">
                                <?php echo p__('push2', 'Only the latest 50 messages are shown below, to see more you can check your OneSignal dashboard.') ?>
                            </div>

                            <table class="table content-white-bkg sb-pager table-fields">
                                <thead>
                                <tr class="border-grey">
                                    <th><?php echo p__('push2', 'Segment') ?></th>
                                    <th><?php echo p__('push2', 'Title') ?></th>
                                    <th><?php echo p__('push2', 'Body') ?></th>
                                    <th><?php echo p__('push2', 'Scheduled?') ?></th>
                                    <th><?php echo p__('push2', 'Send after') ?></th>
                                    <th><?php echo p__('push2', 'Time') ?></th>
                                    <th><?php echo p__('push2', 'Delivery') ?></th>
                                </tr>
                                </thead>
                                <tr class="fields-sortable">
                                    <?php foreach ($notifications as $notification) : ?>
                                    <?php if ($notification->getNotification() === null): ?>
                                <tr style="background-color: #ffebeb;"
                                    id="notification_element_<?php echo $notification->getId(); ?>">
                                    <td><?php echo $notification->getSegment() ?? "Subscribed Users" ?></td>
                                    <td>
                                        <h5 style="font-weight: bold;"><?php echo $notification->getTitle() ?></h5>
                                    </td>
                                    <td><?php echo ellipsis($notification->getBody(), 50) ?></td>
                                    <td colspan="4">
                                        <?php echo p__('push2', 'This message is not in the OneSignal history anymore!') ?>
                                    </td>
                                </tr>
                                <?php else: ?>
                                    <tr id="notification_element_<?php echo $notification->getId(); ?>"
                                        rel="<?php echo $notification->getId(); ?>">
                                        <td><?php echo $notification->getSegment() ?? "Subscribed Users" ?></td>
                                        <td>
                                            <h5 style="font-weight: bold;"><?php echo $notification->getNotification()->getHeadings()->getEn() ?></h5>
                                        </td>
                                        <td><?php echo ellipsis($notification->getNotification()->getContents()->getEn(), 50) ?></td>
                                        <td>
                                            <?php if ($notification->getNotification()->getSendAfter() > $notification->getNotification()->getQueuedAt()) : ?>
                                                <span class="label label-success"><?php echo p__('push2', 'Yes') ?></span>
                                            <?php else : ?>
                                                <span class="label label-danger"><?php echo p__('push2', 'No') ?></span>
                                            <?php endif; ?>
                                        </td>
                                        <td class="moment_format" data-format="LL">
                                            <?php echo $notification->getNotification()->getSendAfter(); ?>
                                        </td>
                                        <td>
                                            <?php echo empty($notification->getNotification()->getDeliveryTimeOfDay()) ?
                                                "-" : $notification->getNotification()->getDeliveryTimeOfDay(); ?>
                                        </td>
                                        <td>
                                            <?php if ($notification->getNotification()->getSendAfter() < $now): ?>
                                                <?php list($success_rate, $failed_rate) = getRates($notification->getNotification()); ?>
                                                <div class="os-rates">
                                                    <div class="label label-success <?php if ($success_rate <= 0) { echo "hidden"; } ?>"
                                                         style="width: <?php echo $success_rate; ?>%"><?php echo $success_rate; ?>%</div>
                                                    <div class="label label-danger <?php if ($failed_rate <= 0) { echo "hidden"; } ?>"
                                                         style="width: <?php echo $failed_rate; ?>%"><?php echo $failed_rate; ?>%</div>
                                                </div>
                                            <?php else: ?>
                                                <div class="label label-info"
                                                     style="width: 100%; display: inline-block;"><?php echo p__('push2', 'To be sent!') ?></div>
                                            <?php endif; ?>
                                        </td>
                                    </tr>
                                <?php endif; ?>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
        <!-- MESSAGES HISTORY -->

        <!-- SETTINGS -->
        <div role="tabpanel"
             class="tab-pane"
             id="tab-settings">
            <div class="feature-block-add">
                <h3 class="title-editor no-border-radius title-feature-indent">
                    <?php echo p__('push', 'Settings'); ?>
                </h3>

                <div id="push-form-settings"
                     class="container-fluid first-row-feature content-feature feature-manage-items">
                    <?php echo $formSettings; ?>
                </div>
            </div>
        </div>
        <!-- SETTINGS -->

        <!-- BACKGROUND -->
        <div role="tabpanel"
             class="tab-pane"
             id="tab-design">
            <?php echo $this->importBackground($option, false, false); ?>
        </div>
        <!-- BACKGROUND -->

    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            bindForms('#push2-form-message');
            bindForms('#list');
            bindForms('#push2-form-settings');
            bindForms('#tab-design');
            bindForms('#tab-settings');

            let scheduleCheckbox = $("#is_scheduled");
            let sendAfter = $("#send_after");
            let pickerSendAfter = $("#picker_send_after");
            let deliveryTimeOfDay = $("#delivery_time_of_day");
            let pickerDeliveryTimeOfDay = $("#picker_delivery_time_of_day");
            let toggleSchedule = function () {
                if (scheduleCheckbox.is(":checked")) {
                    pickerSendAfter.parents(".sb-form-line").show();
                    pickerDeliveryTimeOfDay.parents(".sb-form-line").show();
                } else {
                    pickerSendAfter.parents(".sb-form-line").hide();
                    pickerDeliveryTimeOfDay.parents(".sb-form-line").hide();
                }
            };

            scheduleCheckbox.off("click");
            scheduleCheckbox.on("click", toggleSchedule);

            toggleSchedule();

            let processDates = function () {
                $('.moment_format').each(function () {
                    let jThis = $(this);
                    let format = jThis.data('format');
                    let tmp = moment(jThis.text() * 1000).format(format);
                    jThis.text(tmp);
                    // Removes the class to prevent multiple processing.
                    jThis.removeClass('moment_format');
                });
            };

            processDates();


            pickerSendAfter.off("change");
            pickerSendAfter.on("change", function () {
                sendAfter.val(moment(pickerSendAfter.val() * 1).locale('en-us').format('MMM D YYYY 00:00:00 Z'));
            });

            pickerDeliveryTimeOfDay.off("change");
            pickerDeliveryTimeOfDay.on("change", function () {
                deliveryTimeOfDay.val(moment(pickerDeliveryTimeOfDay.val() * 1).format("HH:mm"));
            });
        });

    </script>
    <link href="/app/sae/modules/Push2/resources/design/desktop/flat/template/push2/application/edit.css"
          media="screen"
          rel="stylesheet"
          type="text/css">
</div>
