<?php

$optionValue = $this->getOptionValue();
$valueId = $optionValue->getId();
$mCommerce = $optionValue->getObject();

// Check the root category!
$rootCategoryId = $mCommerce->getRootCategoryId();
$rootCategory = (new Catalog_Model_Category())->find($rootCategoryId);

$categories = (new Catalog_Model_Category())
    ->findByValueId($valueId, null, true, false);

if (!$rootCategory->getId()) {
    $rootCategory
        ->setName('m-commerce root category')
        ->setValueId($valueId)
        ->setPosition(0)
        ->save();

    $rootCategoryId = $rootCategory->getId();

    $mCommerce
        ->setRootCategoryId($rootCategoryId)
        ->save();

    // Fix parent_id!
    foreach ($categories as $category) {
        $parentId = $category->getParentId();
        if (empty($parentId)) {
            $category
                ->setParentId($rootCategoryId)
                ->save();
        }
    }

    $categories = (new Catalog_Model_Category())
        ->findByValueId($valueId, null, true, false);
}

// Prepare categories!
$categoriesDone = [];
$nestedCategories = [];
foreach ($categories as $category) {
    $categoryId = $category->getCategoryId();
    if (in_array($categoryId, $categoriesDone)) {
        continue;
    }
    $parentId = $category->getParentId();
    if (empty($parentId) || is_null($parentId)) {
        if (!isset($nestedCategories['root'])) {
            $nestedCategories['root'] = [
                'categories' => [],
                'products' => [],
            ];
        }
        $nestedCategories['root']['categories'][] = $category->getData();
    } else {
        if (!isset($nestedCategories[$parentId])) {
            $nestedCategories[$parentId] = [
                'categories' => [],
                'products' => [],
            ];
        }
        $nestedCategories[$parentId]['categories'][] = $category->getData();
    }
}

function generateCategoriesRecursive($content, $categoryId, $nestedCategories, $level = 0) {
    if (array_key_exists($categoryId, $nestedCategories)) {
        $categoriesProducts = $nestedCategories[$categoryId];
        $categories = $categoriesProducts['categories'];
        $products = $categoriesProducts['products'];
        uasort($categories, function($a, $b) {
            if ($a['position'] === $b['position']) {
                return 0;
            }
            return ($a['position'] < $b['position']) ? -1 : 1;
        });
        uasort($products, function($a, $b) {
            if ($a['position'] === $b['position']) {
                return 0;
            }
            return ($a['position'] < $b['position']) ? -1 : 1;
        });
        $level++;
        foreach ($categories as $category) {
            if ($level === 1) {
                $content .= '
            <li rel="' . $category['category_id'] . '">
                <span>
                    <div class="category-title" 
                         rel="' . $category['category_id'] . '">' . p__('m_commerce', 'Categories') . '</div>
                </span>';
                $subcategories = generateCategoriesRecursive('', $category['category_id'], $nestedCategories, $level);
                if (!empty($subcategories)) {
                    $content .= '
                <ul>' . $subcategories . '</ul>';
                }
                $content .= '
            </li>';
            } else {
                $content .= '
            <li class="category-sortable" 
                parentId="' . $category['parent_id'] . '"
                typeName="category"
                rel="' . $category['category_id'] . '">
                <span class="category-hover">
                    <i class="category-sortable-handle fa fa-arrows"></i>
                    <input class="category-title input-flat" 
                           rel="' . $category['category_id'] . '"
                           name="categoryName" value="' . $category['name'] . '" />
                    <i class="category-delete fa fa-remove pull-right" 
                       parentId="' . $category['parent_id'] . '"
                       typeName="category"
                       rel="' . $category['category_id'] . '"></i>
                </span>';
                $subcategories = generateCategoriesRecursive('', $category['category_id'], $nestedCategories, $level);
                if (!empty($subcategories)) {
                    $content .= '
                <ul>' . $subcategories . '</ul>';
                }
                $content .= '
            </li>';
            }
        }
    }
    return $content;
}

$outputHtml = generateCategoriesRecursive('', 'root', $nestedCategories);

?>

<div role="tabpanel"
     class="tab-pane"
     id="tab_categories">

    <div class="feature-block-add">
        <h3 class="title-editor no-border-radius title-feature-indent">
            <?php echo p__('m_commerce','Categories tree') ?>
            <button type="button" class="feature-toggle-add toggle_design color-blue pull-right bt-header-right btn">
                <i class="fa fa-plus"></i>
            </button>
        </h3>
        <div class="container-fluid subcontent content-feature">
            <div class="content content-white-bkg category-container">
                <div class="col-md-12"
                     id="catalog-tree">
                    <div class="category-title-add">
                        <button class="btn color-blue pull-right create-category">
                            <i class="fa fa-plus"
                               style="margin-right: 10px;"></i><?php echo p__('m_commerce', 'Add a category'); ?>
                        </button>
                    </div>
                    <div class="nested-categories">
                        <ul id="nested-root"
                            class="nested-sortable">
                            <!-- Nested render -->
                            <?php echo $outputHtml; ?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<link href="/app/sae/modules/Mcommerce/resources/design/desktop/flat/template/mcommerce/application/tabs/categories/edit.css"
      media="screen"
      rel="stylesheet"
      type="text/css">
<script type="text/javascript">
    var valueId = '<?php echo $optionValue->getId() ?>';
    var categoryParentId = '<?php echo $rootCategoryId ?>';
    var maxNestedLevel = 25;
    var words = {
        deleteTitle: "<?php echo p__js('m_commerce', 'Delete category!') ?>",
        deleteText: "<?php echo p__js('m_commerce', "You are about to delete the category #CATEGORY_NAME# with all it's subcategories<br />Please note that any products inside the category and it's subcategories will be deleted!") ?>",
        confirmDelete: "<?php echo p__js('m_commerce', 'Yes, delete!') ?>",
        cancelDelete: "<?php echo p__js('m_commerce', 'No, go back!') ?>"
    };
</script>
<script type="text/javascript"
        src="/app/sae/modules/Mcommerce/resources/design/desktop/flat/template/mcommerce/application/tabs/categories/edit.js">
</script>