<?php
$stores = $this->getStores();
$formStore = $this->getFormStore();
$deleteStoreForm = $this->getFormStoreDelete();
?>

<div role="tabpanel"
     class="tab-pane active"
     id="tab_stores">

    <div class="feature-block-add">
        <h3 class="title-editor no-border-radius title-feature-indent">
            <?php echo p__('m_commerce','Add a store') ?>
            <button type="button" class="feature-toggle-add toggle_design color-blue pull-right bt-header-right btn">
                <i class="fa fa-plus"></i>
            </button>
        </h3>
    </div>

    <div class="feature-block-create"
        <?php echo ($stores->count() > 0) ? 'style="display: none;"' : ''; ?>>
        <h3 class="title-editor no-border-radius title-feature-indent">
            <?php echo p__('m_commerce','New store') ?>
        </h3>
        <div class="container-fluid subcontent content-feature">
            <?php echo $formStore; ?>
        </div>
    </div>

    <?php if ($stores->count() > 0): ?>
        <div class="feature-block-list">
            <div class="margin-top">
                <h3 class="title-editor no-border-radius title-feature-indent">
                    <?php echo p__('m_commerce', 'Manage stores'); ?>
                    <button type="button" class="toggle_design color-blue pull-right bt-header-right btn feature-toggle-items">
                        <i class="fa fa-angle-down"></i>
                    </button>
                </h3>
                <div class="container-fluid first-row-feature content-feature feature-manage-items">
                    <table class="table content-white-bkg sb-pager">
                        <thead>
                        <tr class="border-grey">
                            <th class="sortable"
                                style="width:30%;"><?php echo p__('m_commerce', 'Name'); ?></th>
                            <th class='sortable'
                                style='width:30%;'><?php echo p__('m_commerce','E-mail'); ?></th>
                            <th class='sortable'
                                style='width:30%;'><?php echo p__('m_commerce','Phone'); ?></th>
                            <th></th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody class="stores-sortable">
                        <?php foreach($stores as $store) : ?>
                            <tr id="store_manage_element_<?php echo $store->getId(); ?>"
                                rel="<?php echo $store->getId(); ?>"
                                class="store-manage-element sb-pager store-container">
                                <td>
                                    <?php echo $store->getName() ?>
                                </td>
                                <td>
                                    <?php echo $store->getEmail() ?>
                                </td>
                                <td>
                                    <?php echo $store->getPhone() ?>
                                </td>
                                <td class="edit-action open-edit"
                                    data-id="store_<?php echo $store->getId(); ?>"
                                    data-form-url="<?php echo __path('/mcommerce/application_store/load-form', ['tax_id' => $store->getId()]); ?>">
                                    <i class="fa fa-pencil"></i>
                                </td>
                                <td class="delete-action">
                                    <?php
                                    $deleteStoreForm->setAttrib('data-rowid', 'store_manage_element_' . $store->getId());
                                    $deleteStoreForm->getElement('store_id')->setValue($store->getId());

                                    echo $deleteStoreForm;
                                    ?>
                                </td>
                            </tr>
                            <tr class="edit-form"
                                data-id="store_<?php echo $store->getId(); ?>"
                                style="display: none;">
                                <td colspan="7">
                                    <p class="close-edit"
                                       data-id="store_<?php echo $store->getId(); ?>">
                                        <i class="fa fa-times"></i><?php echo __('Close') ?>
                                    </p>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    <?php endif; ?>

</div>