<?php
$value_id = $this->getValue();
$unlock_type = $this->getUnlockType();
if ($this->getPromotion()->getId() != null) {
    $promotion = $this->getPromotion();
} else {
    $promotion =  new Promotion_Model_Promotion();
    $promotion->setPosIds(array());
}
$application = $this->getApplication();
?>
<h3 class="title-editor no-border-radius title-feature-indent">
    <?php echo $this->_('Create a new discount'); ?>
</h3>
<div class="container-fluid content-feature">
    <form id="promotionEditForm" method="post" action="<?php echo $this->getUrl('promotion/application/editpost', array('id' => $promotion->getId())); ?>" class="form-horizontal">
        <div class="form-group first-row-feature">
            <div class="col-md-12">
                <button type="button" onclick="page.reload();" class="btn color-blue"><i class="fa fa-angle-left"></i></button>
                <button type="submit" class="btn color-blue pull-right">OK</button>
            </div>
        </div>

        <input type="hidden" name="picture" id="picture" value="<?php echo $promotion->getPicture(); ?>" />
        <input type="hidden" name="remove_picture" id="remove_picture" value="0" />

        <div class="form-group">
            <div class="col-sm-3">
                <label><?php echo $this->_('Picture'); ?> :</label>
            </div>
            <!--[if gte IE 10]><!-->
            <div class="col-sm-9">
                <button id="picture_uploader" class="upload_picture btn color-blue" type="button" rel="<?php echo $promotion->getId() ? $promotion->getId() : 'new' ?>">
                    <?php echo $promotion->getPicture() ? $this->_("Edit the") : $this->_('Add a'); ?>
                    <?php echo $this->_('picture'); ?>
                </button>
                <!--<![endif]-->
                <input style="display:none" id="promotion_picture_uploader" class="uploader_picture" type="file" name="files[]" data-url="<?php echo $this->getUrl('template/crop/upload'); ?>">
            </div>
        </div>

        <div id="delete_picture" class="form-group"<?php if(!$promotion->getPicture()) : ?> style="display:none;"<?php endif; ?>>
            <div class="col-sm-3">
            </div>
            <div class="col-sm-4">
                <img src="<?php echo $promotion->getPictureUrl() ?>" width="238" />
                <button type="button" onclick="promotion.removePicture();" id="delete_picture" class="btn color-blue"><i class="fa fa-times"></i></button>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-3">
                <label for="title"><?php echo $this->_('Name'); ?> : <span class="input-required">*</span></label>
            </div>
            <div class="col-sm-9">
                <input type="text" id="title" name="title" class="input-flat" value="<?php echo $promotion->getTitle(); ?>" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-3">
                <label for="description"><?php echo $this->_('Description'); ?> : <span class="input-required">*</span></label>
            </div>
            <div class="col-sm-9">
                <textarea type="textarea" rows="4" id="description" name="description" class="input-flat"><?php echo $promotion->getDescription(); ?></textarea>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-3">
                <label for="conditions"><?php echo $this->_('Conditions'); ?> : <span class="input-required">*</span></label>
            </div>
            <div class="col-sm-9">
                <input type="text" id="conditions" name="conditions" class="input-flat" value="<?php echo $promotion->getConditions(); ?>" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-9 col-sm-offset-3">
                <label for="is_unique">
                    <input id="is_unique" type="checkbox" class="color-blue checkbox-inline" value="1" name="is_unique" <?php if ($promotion->getIsUnique() == 1) echo 'checked="checked"' ?> color="color-blue"/>
                    <span><?php echo $this->_('use only once'); ?> ?</span>
                </label>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-3">
                <label for="end_at"><?php echo $this->_('End at'); ?> :</label>
            </div>
            <div class="col-sm-9">
                <input type="text" id="end_at" name="end_at" class="calendar input-flat" <?php if ($promotion->getId() AND !$promotion->getEndAt()) echo 'disabled="disabled"' ?> value="<?php if ($promotion->getEndAt()) echo $promotion->getEndAt(); ?>" autocomplete="off" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-3">
                <label for="is_illimited"><?php echo $this->_('or unlimited'); ?> :</label>
            </div>
            <div class="col-sm-8">
                <label for="is_illimited">
                    <input type="checkbox" id="is_illimited" <?php if ($promotion->getId() AND !$promotion->getEndAt()) echo 'checked="checked"' ?> name="is_illimited" value="1" color="color-blue" class="color-blue checkbox-inline"/>
                    <span>(<?php echo $this->_("you'll be able to remove this promotion later"); ?>)</span>
                </label>
            </div>
        </div>

        <?php if($unlock_type == "qrcode" && $this->getPromotion()->getId() == null): ?>
            <div class="form-group">
                <div class="col-md-5 col-md-offset-3 text-center">
                    <div id="qrcode_info">
                        <button onclick="generateQrcode()" class="btn btn-grey"><?php echo $this->_("Generate QRCode"); ?></button>
                        <input type="text" name="unlock_code" class="required" />
                    </div>
                </div>
            </div>
        <?php endif; ?>

        <input type="hidden" name="value_id" value="<?php echo $value_id ?>" />
        <input type="hidden" name="unlock_by" value="<?php echo $unlock_type ?>" />
        <?php if($promotion->getId()) : ?>
            <input type="hidden" name="id" id="promotion_id" value="<?php echo $promotion->getId() ?>" />
        <?php endif; ?>

    </form>
</div>
<style>
    #qrcode_info input[type='text'] { position:absolute; left:-9999px; }
    button#delete_picture {
        position: absolute;
        top: 0;
        left:15px;
    }
</style>

<script>
    function generateQrcode() {
        var unlock_type = $("input[name='unlock_by']").val();

        if(unlock_type == "qrcode") {
            $("#qrcode_info").append('<img width="24" src="/app/design/desktop/siberian/images/customization/ajax/spinner.gif" id="loader_tabbar_name" alt="Loading" title="Loading" class="loader">');
            var length = 9,
                charset = "abcdefghijklnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
                retVal = "";
            for (var i = 0, n = charset.length; i < length; ++i) {
                retVal += charset.charAt(Math.floor(Math.random() * n));
            }
            $("#qrcode_info").empty().append('<input type="hidden" name="unlock_code" value="'+retVal+'"><img src="http://api.qrserver.com/v1/create-qr-code/?color=000000&bgcolor=FFFFFF&data=sendback%3A' + retVal + '&qzone=1&margin=0&size=200x200&ecc=L" alt="qr code" />');
        }
    }
</script>