<div id="tabbar_items" class="overview-tabbar tabbar_items tabbar {{ features.layoutId }} ng-hide" ng-class="{'slide-top': animate_tabbar}" ng-show="tabbar_is_visible">
    <ul id="tabbar" class="tabbar_l1">
        <li ng-repeat="option in features.overview.options">
            <a tabbar-items option="option" go-to-url="goToUrl(option)" class="item relative" ng-class="{ is_link: option.is_link }" target="_parent" title="{{ option.name }}">
                <div class="fullscreen"></div>
                <img ng-src="{{ option.icon_url }}" ng-class="{ colorable: option.icon_is_colorable }" width="30" height="30" title="{{ option.name }}" alt="{{ option.name }}" />
                <span class="block">{{ option.name }}</span>
                <div ng-if="option.code == 'push_notification' && pushs" class="badge">{{ pushs }}</div>
            </a>
        </li>
    </ul>
</div>

<div id="scrollview_tabbar_items" class="full-tabbar background scrollable_content slide-top ng-hide" ng-show="pages_list_is_visible">
    <ul>
        <li ng-repeat="option in features.options">
            <a tabbar-items option="option" go-to-url="goToUrl(option)" class="item relative" target="_parent" title="{{ option.name }}">
                <div class="fullscreen"></div>
                <img ng-src="{{ option.icon_url }}" alt="" title="" width="30" height="30" class="left" ng-class="{ colorable: option.icon_is_colorable }" title="{{ option.name }}" alt="{{ option.name }}" />
                <span class="block left">{{ option.name }}</span>
                <div ng-if="option.code == 'push_notification' && pushs" class="badge">{{ pushs }}</div>
                <div class="clear"></div>
            </a>
        </li>
        <li>
            <a href="javascript:void(0)" class="item" ng-click="closeList();">
                <span id="tabbar_name_close" class="block"><?php echo $this->_("Close") ?></span>
            </a>
        </li>
    </ul>
</div>