<?php $application = $this->getApplication(); ?>
<div class="row">
    <div class="col-md-12">
        <div class="page-content-wrapper">
            <div id="domain_content" class="content solo-page sb-tour">
                <h3 class="title-editor border-blue text-center">
                    <?php echo $this->_('Mobile website information'); ?>
                </h3>
                <div id="domain" class="subcontent content-color">
                    <div class="col-md-12">
                        <form id="urlForm" action="<?php echo $this->getUrl('application/settings_domain/save'); ?>" onsubmit="return false" class="form-horizontal">
                            <div class="container-fluid">
                                <div class="form-group">
                                   <div class="col-sm-2">
                                       <label for="domain" class="control-label"><?php echo $this->_('Domain name'); ?> : </label>
                                   </div>
                                    <div class="col-sm-5">
                                        <input type="text" id="domain" name="domain" class="save_url input-flat domain_500_width" value="<?php echo $application->getDomain() ? $application->getDomain() : $application->getUrl() ?>" />
                                    </div>
                                </div>
                                <div id="config_cname" class="form-group row_config_cname"<?php if(!$application->getDomain()) : ?> style="display:none;"<?php endif; ?>>
                                    <div class="col-sm-3">
                                        <label><?php echo $this->_('Checking CNAME configuration:'); ?></label>
                                    </div>
                                    <div id="loader_config_cname" class="col-sm-1" style="display:none;">
                                        <img src="<?php echo $this->getImage('customization/ajax/spinner.gif'); ?>" alt="Loading" title="Loading" width="24" />
                                    </div>
                                    <div class="col-sm-9">
                                        <span id="error_config_cname" class="result_config_cname text-danger" style="display:none"><i class="fa fa-times"></i><?php echo $this->_('Your CNAME is not properly set'); ?></span>
                                        <span id="success_config_cname" class="result_config_cname" style="display:none"><i class="icon-ok"></i><?php echo $this->_('Your CNAME is properly set'); ?></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-2 pull-right text-right">
                                        <button type="submit" class="color-blue btn"><?php echo $this->_("Save"); ?></button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $('#urlForm').submit(function() {
        // add a warning when changing app URL KEY and Domain
        var confirmation = confirm("<?php echo __("If your app is already published, changing the domain will break it. You will have to republish it. Change it anyway?")?>");
        if (confirmation) {
            reload($('#urlForm'), $('#urlForm').attr('action'), true, function(data) {
                if(data.success) {
                    $('#domain').val(data.application_url);
                    if(data.show_cname_state) {
                        $("#config_cname").show();
                        $("#success_config_cname").fadeIn();
                    } else {
                        $("#config_cname").hide();
                        $("#result_config_cname").hide();
                    }
                }
            }, function() {
                $("#config_cname").hide();
                $("#result_config_cname").hide();
            });
        }
        return false;
    });

    <?php if($application->getDomain()) : ?>
    checkCname();
    <?php endif; ?>

    function checkCname() {

        var cname_loader = $('#loader_config_cname');
        $('.result_config_cname').hide();
        cname_loader.show();
        reload($('#error_config_cname'), '<?php echo $this->getUrl('application/settings_domain/checkcname'); ?>', false, function(datas) {
            cname_loader.hide();
            if(datas.code != 'undefined') {
                if(datas.code == 0) $('#success_config_cname').fadeIn();
                else if(datas.code == 1) $('#error_config_cname').fadeIn();
            }

        }, function() {
            cname_loader.hide();
        });

    }

</script>