<?php $field = $this->getField(); ?>
<li class="field" id="field_<?php echo $field->getId(); ?>" rel="<?php echo $field->getSection_id(); ?>">
    <a class="handle_field left"><i class="icon-move"></i></a>
    <p class="name left"><?php echo $field->getName(); ?></p>
    <p class="field_type left"><?php echo $field->getTypeLabel(); ?></p>
    <div class="actions right">
        <a rel="prettyPhoto[ajax]" href="<?php echo $this->getUrl('form/application_field/edit', array('option_value_id' => $this->getOptionValue()->getId(), 'field_id' => $field->getId(), 'section_id' => $field->getSection_id())); ?>?ajax=true" class="icon edit_field"><i class="icon-edit"></i></a>
        <a href="javascript:void(0);" onclick="field.remove(<?php echo $field->getId(); ?>); return false;" class="icon"><i class="icon-remove"></i></a>
        <input type="hidden" name="field_id" value="<?php echo $field->getId(); ?>" />
    </div>
    <div class="clear"></div>
</li>