<?php
$option = $this->getCurrentOptionValue();
$mcommerce = $option->getObject();
$promos = $mcommerce->getPromos();
?>
<div id="settings_list" pos="1">
    <div id="promo_manager">
        <h3 class="title-editor no-border-radius title-feature-indent">
            <?php echo $this->_('Discount settings'); ?>
            <button type="button" id="add_item" class="edit_promo color-blue pull-right bt-header-right btn">
                <i class="fa fa-plus"></i>
            </button>
        </h3>
        <?php echo $this->createPartialHtml('no_item', 'core_view_default', 'application/customization/features/edit/no_item.phtml'); ?>
        <div id="section_existing_promos" <?php if (!$promos->count()) : ?> style="display:none"<?php endif; ?>
             class="margin-top">
            <h3 class="title-editor no-border-radius title-feature-indent">
                <?php echo $this->_("Manage discounts"); ?>
                <button type="button" id="toggle_existing_promos" class="color-blue pull-right bt-header-right btn">
                    <i class="fa fa-angle-down"></i>
                    <input type="hidden" name="option_value_id" value="<?php echo $option->getId(); ?>"/>
                </button>
            </h3>
            <div id="existing_promos" style="display:none;" class="container-fluid first-row-feature content-feature">
                <ul class="list-group promos_list">
                    <?php foreach ($promos as $promo) : ?>
                        <?php echo $this->getLayout()->addPartial('row_promo_'.$promo->getId(), 'admin_view_default', 'mcommerce/application/edit/settings/discount/li.phtml')
                            ->setCurrentOptionValue($option)
                            ->setCurrentPromo($promo)
                            ->toHtml();
                        ?>
                    <?php endforeach ?>
                </ul>
            </div>
        </div>
    </div>
</div>
<br>
<script type="text/javascript">
    var discount = {
        processEvents: function() {
            $('#toggle_existing_promos').click(function() {
                $('#existing_promos').stop().slideToggle(300, function() {
                    if($(this).is(':visible')) $('#toggle_existing_promos').children('i').removeClass('fa-angle-down').addClass('fa-angle-up');
                    else $('#toggle_existing_promos').children('i').removeClass('fa-angle-up').addClass('fa-angle-down')
                });
            });

            $('.edit_promo').each(function(i, element) {
                this.bindEditPromo($(element));
            }.bind(this));
            $('.remove_promo').each(function(i, element) {
                this.bindRemovePromo($(element));
            }.bind(this));
        },
        bindPromoElements: function(id) {
            if($('#edit_promo_'+id).length) this.bindEditPromo($('#edit_promo_'+id));
            if($('#remove_promo_'+id).length) this.bindRemovePromo($('#remove_promo_'+id));
            return this;
        },
        bindEditPromo: function(element) {
            element.click(function(e) {
                if(!element.children('input').length) {
                    $('<input />').attr('type', 'hidden').attr('name', 'option_value_id').addClass('option_value_id').val('<?php echo $option->getId(); ?>').appendTo(element);
                    if(element.attr('rel')) $('<input />').attr('type', 'hidden').attr('name', 'promo_id').val(element.attr('rel')).appendTo(element);
                }

                this.load(element);
            }.bind(this));
        },
        bindRemovePromo: function(element) {
            element.click(function(e) {

                if(!confirm('<?php echo addslashes($this->_('Are you sure you want to delete this discount?'))?>')) return false;

                if(!element.children('input').length) {
                    $('<input />').attr('type', 'hidden').attr('name', 'option_value_id').addClass('option_value_id').val('<?php echo $option->getId(); ?>').appendTo(element);
                    if(element.attr('rel')) $('<input />').attr('type', 'hidden').attr('name', 'promo_id').val(element.attr('rel')).appendTo(element);
                }

                this.remove(element);
            }.bind(this));
        },
        load: function(a) {
            reload(a, '<?php echo $this->getUrl('mcommerce/application_settings_discount/edit'); ?>', true, function(datas) {
                if(datas.form_html) {
                    $('#promo_edit').html(datas.form_html);
                    $('#promoEditForm').submit(function() {

                        $(this).find('input.required.number').each(function() {
                            var val = parseFloat($(this).val().replace(',', '.'));
                            if(!isNaN(val)) {
                                $(this).val(val);
                            }
                        });

                        if(!$(this).valid()) return false;

                        reload(this, this.action, true, function(datas) {
                            if(datas.success) {
                                if(datas.row_html) {
                                    $('#existing_promos').children('ul.promos_list').append(datas.row_html);
                                    this.bindPromoElements(datas.promo_id);
                                    if(!$('#section_existing_promos').is(':visible')) $('#section_existing_promos').show();
                                }
                                else if(datas.promo_name) {
                                    $('#promo_name_'+datas.promo_id).html(datas.promo_name);
                                }
                                this.close();
                            }
                        }.bind(discount));
                        return false;
                    });
                    $('label.delivery_method').click(function() {
                        setupLabel($(this));
                    });
                    $('label.payment_method').click(function() {
                        setupLabel($(this));
                    });
                    feature.slide($('#settings'), $('#promo_edit'), 'right');
                    var d = (navigator.userAgent && navigator.userAgent.indexOf('WebKit')) != -1 ? document.body : document.documentElement;
                    $(d).animate({scrollTop: $('body').offset().top});
                }
            });
        },
        remove: function(a) {
            reload(a, '<?php echo $this->getUrl('mcommerce/application_settings_discount/remove'); ?>', true, function(datas) {
                if(datas.success) {
                    $('#edit_promo_'+datas.promo_id).unbind('click');
                    $('#remove_promo_'+datas.promo_id).unbind('click');
                    $('#promo_row_'+datas.promo_id).remove();
                    console.log('#promo_row_'+datas.promo_id)
                    if(!$('#existing_promos').find('li').length) $('#section_existing_promos').fadeOut();
                }
            });
        },
        close: function() {
            $('#promoditForm').unbind('submit');
            feature.slide($('#promo_edit'), $('#settings'), 'left', function() {$('#promo_edit').html('')});
        },
        destroy: function() {
            $('#promoditForm').unbind('submit');
            $('.edit_promo').unbind('click');
            $('.remove_promo').unbind('click');
        }
    }
    $(document).ready(function(){
        discount.processEvents();
    })
</script>