<sb-section title="'<?php echo __title("Manage Access"); ?>'">
    <form ng-submit="saveAppOwner()" class="ng-scope ng-pristine ng-valid">
        <div class="form-group col-md-6">

            <label class="control-label">Account owner of this app</label>
            <select class="form-control " ng-selected="owner.admin_id === application.admin.id" ng-model="tmp_application.owner" name="owner" id="owner">
                <option ng-repeat="owner in application.list_of_admins"
                        ng-selected="owner.admin_id === application.owner.id"
                        value="{{ owner.admin_id }}">
                    {{ owner.admin_id }} - {{ owner.admin_email }} - {{ owner.admin_host }}
                </option>
            </select>
            <tt>{{ tmp_application.owner }}</tt>
        </div>
        <div class="form-group col-md-4" style="margin-top:32px;">
                <span style="display: inline-flex;"
                      ng-if="application.owner.whitelabel.exist === true"> <?php echo __("White Label"); ?>:&nbsp;  {{ application.admin.whitelabel.host }}&nbsp; <span/>
                    <span class="btn btn-sm btn-warning"
                          ng-if="application.owner.whitelabel.is_active === '0'"><?php echo __("not active"); ?> </span>
                    <span class="btn btn-sm btn-success"
                          ng-if="application.owner.whitelabel.is_active === '1'"><?php echo __("active"); ?> </span>
                <br/>
                    <span style="display: inline-flex;margin-left:20px;"><?php echo __("Custom SMTP"); ?>:&nbsp;</span>
                        <span class="btn btn-sm btn-warning"
                              ng-if="application.owner.whitelabel.smtp === '0'"><?php echo __("not active"); ?> </span>
                        <span class="btn btn-sm btn-success"
                              ng-if="application.owner.whitelabel.smtp === '1'"><?php echo __("active"); ?> </span>
        </div>
        <div class="form-group col-md-2 text-right" style="margin-top:24px;">
            <button type="submit" class="btn btn-primary right">Save</button>
            <div class="form_loader no loader inner_content small no loader inner_content small ng-hide"
                 ng-show="is_visible" is_visible="form_loader_is_visible" type="'inner_content'" size="'small'"
                 animation="'no'">

            </div>

        </div>
    </form>
    <br/>

    <div class="col-md-12">
        <p class="help-block"><?php echo __("Manage Admins access feature by feature."); ?></p>

        <br/>

        <table class="table">
            <colgroup>
                <col width="3%">
                <col width="40%">
                <col width="30%">
                <col width="17%">
            </colgroup>
            <thead>
            <tr>
                <th><?php echo __('Id') ?></th>
                <th><?php echo __('Name') ?></th>
                <th><?php echo __('Email') ?></th>
                <th class="text-right"><?php echo __('Actions') ?></th>
            </tr>
            </thead>
            <tbody>
            <tr ng-repeat="admin in application.admin_list">
                <td>
                    <b>#{{ admin.admin_id }}</b>
                </td>
                <td>{{ admin.firstname }} {{ admin.lastname }}</td>
                <td>{{ admin.email }}</td>
                <td class="text-right">
                    <a href="<?php echo $this->getUrl("admin/backoffice_list/loginas"); ?>/key/{{ admin.key }}/admin_id/{{ admin.admin_id }}"
                       target="_blank"
                       class="btn btn-sm btn-info"><?php echo __('IMPERSONATE') ?></a>
                    <a href="<?php echo $this->getUrl("application/backoffice_view_acl"); ?>/app_id/{{ application.app_id }}/admin_id/{{ admin.admin_id }}"
                       class="btn btn-sm btn-primary"><?php echo __('EDIT') ?></a>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</sb-section>