<sb-section title="'<?php echo __title("Manage Access"); ?>'">

    <div class="row">
        <div class="col-md-12">
            <h4 class="section-title "><?php echo p__('backoffice_application', 'Application owner'); ?></h4>
        </div>
        <div class="col-md-12">
            <div class="section-content">
                <div class="row">
                    <div class="form-group col-md-6">
                        <p>
                            <?php echo p__('backoffice_application', 'Actual owner of this app') ?>:
                            <b>#{{ application.owner.id }} - {{ application.owner.email }}</b>
                        </p>
                        <br />
                        <input type="text"
                               class="form-control"
                               ng-model="filter.owner"
                               placeholder="<?php echo p__js('backoffice_application', 'Search, filter...', '"') ?>" />
                        <br />
                        <select class="form-control"
                                name="owner"
                                id="owner"
                                ng-model="tmp_application.selectedOwner">
                            <option value=""><?php echo p__('backoffice_application', 'Change app owner') ?></option>
                            <option ng-repeat="owner in application.list_of_admins | filter:filter.owner track by owner.admin_id"
                                    ng-selected="owner.admin_id == tmp_application.selectedOwner"
                                    value="{{ owner.admin_id }}">
                                #{{ owner.admin_id }} - {{ owner.admin_email }}{{ owner.admin_host ? ' - [WL] ' + owner.admin_host : '' }}
                            </option>
                        </select>
                    </div>

                    <div class="form-group clear col-md-12 pull-right text-right">
                        <button type="submit"
                                ng-click="saveAppOwner()"
                                class="btn btn-primary right"><?php echo p__('backoffice_application', 'Save') ?></button>
                    </div>
                </div>

                <div class="clear"></div>
            </div>
        </div>
    </div>

    <br />

    <div class="row">
        <div class="col-md-12">
            <h4 class="section-title "><?php echo p__('backoffice_application', 'Application admins'); ?></h4>
        </div>
        <div class="col-md-12">
            <div class="section-content">
                <p class="help-block"><?php echo p__('backoffice_application', 'Manage admins access feature by feature.'); ?></p>

                <table class="table table-striped">
                    <colgroup>
                        <col width="8%">
                        <col width="32%">
                        <col width="35%">
                        <col width="25%">
                    </colgroup>
                    <thead class="admin-head">
                        <tr>
                            <th><?php echo __('Id') ?></th>
                            <th><?php echo __('Name') ?></th>
                            <th><?php echo __('Email') ?></th>
                            <th class="text-right"><?php echo __('Actions') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr ng-repeat="admin in application.admin_list">
                            <td>
                                <b>#{{ admin.admin_id }}</b>
                            </td>
                            <td>{{ admin.firstname }} {{ admin.lastname }}</td>
                            <td>{{ admin.email }}</td>
                            <td class="text-right">
                                <a href="<?php echo $this->getUrl("admin/backoffice_list/loginas"); ?>/key/{{ admin.key }}/admin_id/{{ admin.admin_id }}"
                                   target="_blank"
                                   class="btn btn-sm btn-info"><?php echo __('IMPERSONATE') ?></a>
                                <a href="<?php echo $this->getUrl("application/backoffice_view_acl"); ?>/app_id/{{ application.app_id }}/admin_id/{{ admin.admin_id }}"
                                   class="btn btn-sm btn-primary"><?php echo __('EDIT') ?></a>
                                <a ng-if="admin.admin_id != application.owner.id"
                                   ng-click="removeAppAdmin(application.app_id, admin.admin_id )"
                                   class="btn btn-sm btn-danger"><?php echo __('DELETE') ?></a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <style type="text/css">
        .admin-head tr th {
            font-weight: bold;
        }
    </style>
</sb-section>
