<?php
use Siberian\AdNetwork;
?>

<sb-section title="'<?php echo __title("Advertising"); ?>'">
    <form ng-submit="saveAdvertisingInfo()">

        <div class="col-md-12">

            <div class="form-group">
                <div class="checkbox">
                    <label for="admob_enable_ads">
                        <input type="checkbox"
                               id="admob_enable_ads"
                               ng-model="application_admob.use_ads"
                               ng-checked="application_admob.use_ads"
                               class="form-control" />
                            <?php echo p__('backoffice_application', 'Enable Ads'); ?>
                    </label>
                </div>
            </div>

            <div class="form-group">
                <div class="checkbox">
                    <label for="admob_test_ads"
                           class="control-label">
                        <input type="checkbox"
                               id="admob_test_ads"
                               class="form-control"
                               ng-model="application_admob.test_ads"
                               ng-checked="application_admob.test_ads" />
                            <?php echo p__('backoffice_application', 'Display test Ads') ?>
                    </label>
                </div>
            </div>

            <?php if (AdNetwork::$mediationEnabled): ?>
                <div class="form-group">
                    <div class="checkbox">
                        <label for="mediation_facebook"
                               class="control-label">
                            <input type="checkbox"
                                   id="mediation_facebook"
                                   class="form-control"
                                   ng-model="application_admob.mediation_facebook"
                                   ng-checked="application_admob.mediation_facebook" />
                            <?php echo p__('backoffice_application', 'Enable Facebook audience network mediation') ?>
                        </label>
                    </div>
                </div>

                <div class="form-group">
                    <div class="checkbox">
                        <label for="mediation_startapp"
                               class="control-label">
                            <input type="checkbox"
                                   id="mediation_startapp"
                                   class="form-control"
                                   ng-model="application_admob.mediation_startapp"
                                   ng-checked="application_admob.mediation_startapp" />
                            <?php echo p__('backoffice_application', 'Enable StartApp network mediation') ?>
                        </label>
                    </div>
                </div>
            <?php endif; ?>

        </div>

        <div ng-repeat="device in application_admob.devices">

            <div class="col-md-{{ 12 / application_admob.devices.length }}">

                <div class="subtitle">
                    <h4>{{ device.name }}</h4>
                    <div class="clear"></div>
                </div>

                <div class="form-group">
                    <label for="admob-appid-{{ device.name }}"><?php echo __('AdMob application ID'); ?> *</label>
                    <input type="text"
                           id="admob-appid-{{ device.name }}"
                           placeholder="ca-app-pub-0000000000000000~0000000000"
                           ng-model="device.admob_app_id"
                           class="form-control" />
                </div>

                <div class="form-group">
                    <label for="admob-id-{{ device.name }}"
                           class="control-label"><?php echo __("AdMob Banner ID"); ?></label>
                    <input type="text"
                           id="admob-id-{{ device.name }}"
                           class="form-control"
                           ng-model="device.admob_id"/>
                </div>

                <div class="form-group">
                    <label for="admob-interstitial-id-{{ device.name }}"
                           class="control-label"><?php echo __("AdMob Interstitial ID"); ?></label>
                    <input type="text"
                           id="admob-interstitial-id-{{ device.name }}"
                           class="form-control"
                           ng-model="device.admob_interstitial_id"/>
                </div>

                <div class="form-group">
                    <label for="admob-type-{{ device.name }}"
                           class="control-label"><?php echo __("AdMob Type"); ?></label>
                    <select id="admob-type-{{ device.name }}"
                            class="form-control"
                            ng-model="device.admob_type">
                        <option value="banner"><?php echo __("Banner") ?></option>
                        <option value="interstitial"><?php echo __("Interstitial") ?></option>
                        <option value="banner-interstitial"><?php echo __("Banner & Interstitial") ?></option>
                    </select>
                </div>

            </div>

        </div>


        <div class="form-group">
            <div class="col-md-12">
                <button type="submit"
                        class="btn btn-primary right"><?php echo __("Save"); ?></button>
                <sb-loader is_visible="device_form_loader_is_visible"
                           type="'inner_content'"
                           size="'small'"
                           animation="'no'"
                           class="form_loader"></sb-loader>
                <div class="clear"></div>
            </div>
        </div>
    </form>

    <div class="clear"></div>
</sb-section>
