<sb-section title="'<?php echo __title("Generate and publish iOS Application"); ?>'">

    <div class="row">
        <div class="col-md-12">
            <h4 class="section-title "><?php echo p__("backoffice_application","Licensing"); ?></h4>
        </div>
        <div class="col-md-12">
            <div class="section-content">
                <div ng-if="iosBuildLicenceError !== ''"
                     class="alert alert-danger">
                    {{ iosBuildLicenceError }}
                </div>

                <div ng-if="iosBuildActivationRemain === false">
                    <div class="cssloader-small"></div>
                </div>
                <div ng-if="iosBuildActivationRemain !== false">
                    <strong><?php echo p__("backoffice_application","Remaining builds") ?></strong> - {{ iosBuildActivationRemain }}
                </div>

                <br />

                <div class="alert alert-info">
                    <?php
                    echo p__("backoffice_application","You can change your license in <b>%s > %s</b>",
                        __("Settings"),
                        __("General"))
                    ?>
                </div>
            </div>
        </div>
    </div>

    <br />

    <div class="row">
        <div class="col-md-12">
            <h4 class="section-title "><?php echo p__("backoffice_application","Publication settings"); ?></h4>
        </div>
        <div class="col-md-12">
            <div class="section-content">

                <form autocomplete="off"
                      ng-submit="noop()">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label"
                                       for="iTunesConnectLogin"><?php echo p__("backoffice_application", "App Store Connect login"); ?></label>
                                <input type="text"
                                       value=""
                                       ng-model="ios_publish_informations.itunes_login"
                                       class="form-control"
                                       id="iTunesConnectLogin"
                                       autocomplete="new-password">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label"
                                       for="iTunesConnectPassword"><?php echo p__("backoffice_application", "Password"); ?></label>
                                <input type="password"
                                       value=""
                                       ng-model="ios_publish_informations.itunes_password"
                                       class="form-control"
                                       id="iTunesConnectPassword"
                                       autocomplete="new-password">
                            </div>
                        </div>
                    </div>

                    <div class="row">

                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="control-label"
                                       for="iTunesTeams">
                                    <?php echo p__("backoffice_application", "Apple Development team id"); ?>
                                </label>
                                <input class="form-control"
                                       id="iTunesTeams"
                                       required
                                       ng-model="ios_publish_informations.selected_team" />

                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="control-label"
                                       for="iTunesTeamsName">
                                    <?php echo p__("backoffice_application", "Team name"); ?>
                                </label>
                                <input class="form-control"
                                       id="iTunesTeamsName"
                                       required
                                       ng-model="ios_publish_informations.selected_team_name" />

                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="control-label"
                                       for="iTunesTeams">
                                    <?php echo p__("backoffice_application", "App Store Connect provider") ?>
                                </label>
                                <input class="form-control"
                                       id="iTunesProvider"
                                       required
                                       ng-model="ios_publish_informations.selected_provider" />
                            </div>
                        </div>

                        <div class="col-md-12">
                            <div class="alert alert-info highlight-a">
                                <?php echo p__(
                                    "backoffice_application",
                                    "How to find Team ID, Team name & Provider? Follow this <a href=\"%s\" target=\"blank\">documentation</a>",
                                    "https://doc.siberiancms.com/knowledge-base/find-apple-team-id-name-provider/") ?>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-4">
                            <label for="{{ device.id }}_status"><?php echo p__("backoffice_application","Language"); ?></label>
                            <div class="form-group">
                                <select name="languages"
                                        class="form-control"
                                        ng-model="ios_publish_informations.languages">
                                    <?php foreach (Application_Model_Languages::getSupportedLanguages() as $code => $language) : ?>
                                        <option value="<?php echo $code; ?>"><?php echo __($language); ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12 form-group">
                            <label for="ios-code-version-noads"> <?php echo p__("backoffice_application","Options"); ?> </label>
                            <div class="row checkbox">
                                <div class="col-md-3">
                                    <label for="ios-autobuild-has-ads">
                                        <input type="checkbox"
                                               id="ios-autobuild-has-ads"
                                               name="ios-autobuild-has-ads"
                                               ng-checked="ios_publish_informations.has_ads"
                                               ng-model="ios_publish_informations.has_ads">
                                        <?php echo p__("backoffice_application","With ads functionality"); ?>
                                    </label>
                                </div>
                                <div class="col-md-9">
                                    <?php echo p__("backoffice_application",
                                        "* If Apple doesn't detect any configured ads, your application will be refused."); ?>
                                </div>
                            </div>
                            <div class="row checkbox">
                                <div class="col-md-3">
                                    <label for="ios-autobuild-has-audio">
                                        <input type="checkbox"
                                               id="ios-autobuild-has-audio"
                                               name="ios-autobuild-has-audio"
                                               ng-checked="ios_publish_informations.has_audio"
                                               ng-model="ios_publish_informations.has_audio">
                                        <?php echo p__("backoffice_application","With background audio playing"); ?>
                                    </label>
                                </div>
                                <div class="col-md-9">
                                    <?php echo p__("backoffice_application",
                                        "* You must tell Apple why you need the background audio playing."); ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label"
                                       for="iTunesConnectIdentifier">
                                    <?php echo p__("backoffice_application","Build information"); ?>
                                </label>
                                <div>
                                    <div class="alert"
                                         ng-class="{
                                            'alert-danger': ios_publish_informations.last_build_status === 'failed',
                                            'alert-info': ios_publish_informations.last_build_status !== 'failed'}">
                                        <b><?php echo __('Status'); ?></b>:
                                        <span ng-if="ios_publish_informations.last_build_status">{{ios_publish_informations.last_build_status}}</span>
                                        <span ng-if="!ios_publish_informations.last_build_status"><?php echo p__("backoffice_application","idle") ?></span>
                                        <p ng-if="ios_publish_informations.last_build_status === 'failed'">
                                            <b><?php echo __('Last error'); ?></b>:
                                            <span ng-bind-html="ios_publish_informations.error_message"></span>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6 form-group">

                            <label class="control-label"
                                   for="iTunesConnectIdentifier"><?php echo __('Service status / load'); ?></label>

                            <div ng-if="ios_publish_informations.stats.isOnline"
                                 ng-class="ios_publish_informations.stats.loadColor">
                                <?php echo __('Current load is') ?> <b>{{ ios_publish_informations.stats.load }}</b>
                                <br/>
                                <?php echo __('Your build should be ready') ?> <b>{{ ios_publish_informations.stats.fromNow }}</b>
                            </div>

                            <div ng-if="!ios_publish_informations.stats.isOnline"
                                 class="alert alert-danger">
                                <?php echo __('Current status is') ?> <b>{{ ios_publish_informations.stats.offlineStatus }}</b>
                                <br/>
                                <?php echo __('Message') ?>:
                                <br/>
                                <b>{{ ios_publish_informations.stats.offlineMessage }}</b>
                            </div>

                        </div>

                        <div class="col-md-12">
                            <button ng-click="saveCredentialsAutopublish()"
                                    class="btn btn-primary left">
                                <i class="icofont icofont-save"></i> <?php echo __("Save credentials & settings"); ?>
                            </button>

                            <button ng-disabled="disableRequest()"
                                    ng-click="requestPublication()"
                                    style="margin-left: 15px;"
                                    class="btn btn-primary left">
                                <i class="fa fa-send"></i> <?php echo __("Request a publication"); ?>
                            </button>

                            <sb-loader is_visible="refreshPublish"
                                       type="'inner_content'"
                                       size="'small'"
                                       animation="'no'"
                                       class="form_loader"></sb-loader>
                        </div>

                    </div>

                    <div class="clear"></div>
                </form>
            </div>
        </div>
    </div>

    <br />

    <div class="row">
        <div class="col-md-12">
            <h4 class="section-title "><?php echo p__("backoffice_application","Service notes"); ?></h4>
        </div>
        <div class="col-md-12">
            <div class="section-content">
                <div ng-repeat="message in ios_publish_informations.stats.messages"
                     ng-class="message.colors">
                    <b>{{ message.title }} - {{ toCalendar(message.date) }}</b>
                    <br/>
                    {{ message.message }}
                </div>
            </div>
        </div>
    </div>

    <div class="clear"></div>

    <style type="text/css">
        .highlight-a a {
            text-decoration: underline;
            font-weight: bold;
        }
    </style>
</sb-section>