<?php
use Siberian\Version;
?>
<sb-section title="'<?php echo __title("Mobile Source Codes"); ?>'">

    <div class="row">
        <div class="col-md-12">
            <h4 class="section-title "><?php echo p__("backoffice_application","Sources"); ?></h4>
        </div>
        <div class="col-md-12">
            <div class="section-content">

                <table class="table queue">

                    <colgroup>
                        <col width="30%" />
                        <col width="50%" />
                        <col width="20%" />
                    </colgroup>

                    <tbody>
                        <tr>
                            <td>
                                <label class="control-label"><?php echo __("iOS"); ?></label>
                                <br/>
                                <span class="source-hint"><?php echo __('Xcode 15.0.1 - macOS Sonoma') ?>
                                    , <?php echo __("iOS 12+") ?></span>
                            </td>
                            <td ng-if="['', 'ca-app-pub-0000000000000000~0000000000'].indexOf(application.devices[0].admob_app_id.trim()) === -1">
                                <a ng-if="application.zip.ios"
                                   href="<?php echo $this->getUrl("") ?>{{ application.zip.ios.path }}"
                                   class="help-block"
                                   target="_self">
                                    <i class="fa fa-cloud-download"></i> <?php echo __("Download latest sources"); ?> {{
                                    application.zip.ios.date }}
                                </a>

                                <span ng-if="!application.zip.ios"><?php echo __("Not yet generated.") ?></span>
                            </td>
                            <td ng-if="['', 'ca-app-pub-0000000000000000~0000000000'].indexOf(application.devices[0].admob_app_id.trim()) === -1"
                                class="text-right">
                                <a ng-if="application.queued.positions.ios == 0"
                                   ng-click="generateSource(1, 0)"
                                   href="javascript:void(0)"
                                   class="block"
                                   target="_self"><i
                                            class="fa fa-gears"></i> <?php echo __("Generate sources"); ?></a>
                                <span ng-show="application.queued.positions.ios == 1">
                                        <img class="gear-loader"
                                             src="/app/sae/design/desktop/backoffice/images/loader/gears.gif"/><?php echo __("Generating") ?>
                                    </span>
                                <span ng-show="application.queued.positions.ios > 1">
                                        <i class="fa fa-random"></i> <?php echo __("Queued") ?>: {{ application.queued.positions.ios }}/{{ application.queued.total }}
                                    </span>
                                <a ng-show="application.queued.positions.ios > 1"
                                   ng-click="cancelQueue(1, 0)"
                                   href="javascript:void(0)">
                                    <i class="fa fa-times"></i> <?php echo __("Cancel") ?>
                                </a>
                            </td>
                            <td colspan="2"
                                ng-if="['', 'ca-app-pub-0000000000000000~0000000000'].indexOf(application.devices[0].admob_app_id.trim()) !== -1">
                                <div class="alert alert-warning">
                                    <?php echo p__('backoffice_application', 'AdMob app id is required to generate iOS sources.') ?>
                                </div>
                            </td>
                        </tr>

                        <tr>
                            <td>
                                <label class="control-label"><?php echo __("iOS (without AdMob)"); ?>
                                <br/>
                                <span  class="source-hint"><?php echo __("Xcode 15.0.1 - macOS Sonoma") ?>
                                    , <?php echo __("iOS 12+") ?></span>
                            </td>
                            <td>
                                <a ng-if="application.zip.iosnoads"
                                   href="<?php echo $this->getUrl("") ?>{{ application.zip.iosnoads.path }}"
                                   class="help-block"
                                   target="_self">
                                    <i class="fa fa-cloud-download"></i> <?php echo __("Download latest sources"); ?> {{
                                    application.zip.iosnoads.date }}
                                </a>

                                <span ng-if="!application.zip.iosnoads"><?php echo __("Not yet generated.") ?></span>

                                <div>
                                    <p class="help-block"><?php echo __("Apple rejects apps that includes Ad support but doesn't use it.<br />Generate your iOS app without AdMob if you don't include Ads."); ?></p>
                                    <p class="help-block">
                                        <i><?php echo __("Note that if you want to add Ads later, you will have to publish the app with AdMob support."); ?></i>
                                    </p>
                                </div>
                            </td>
                            <td class="text-right">
                                <a ng-if="application.queued.positions.iosnoads == 0"
                                   ng-click="generateSource(1, 1)"
                                   href="javascript:void(0)"
                                   class="block"
                                   target="_self">
                                    <i class="fa fa-gears"></i> <?php echo __("Generate sources"); ?>
                                </a>
                                <span ng-show="application.queued.positions.iosnoads == 1">
                                        <img class="gear-loader"
                                             src="/app/sae/design/desktop/backoffice/images/loader/gears.gif"/><?php echo __("Generating") ?>
                                    </span>
                                <span ng-show="application.queued.positions.iosnoads > 1">
                                        <i class="fa fa-random"></i> <?php echo __("Queued") ?>: {{ application.queued.positions.iosnoads }}/{{ application.queued.total }}
                                    </span>
                                <a ng-show="application.queued.positions.iosnoads > 1"
                                   ng-click="cancelQueue(1, 1)"
                                   href="javascript:void(0)">
                                    <i class="fa fa-times"></i> <?php echo __("Cancel") ?>
                                </a>
                            </td>
                        </tr>

                        <tr>
                            <td>
                                <label class="control-label"><?php echo __("Android"); ?></label>
                                <br/>
                                <span class="source-hint"><?php echo __('Android Studio 4+') ?>
                                    , <?php echo __('Android 5.0+') ?></span>
                            </td>
                            <td>
                                <a ng-if="application.zip.android"
                                   href="<?php echo $this->getUrl("") ?>{{ application.zip.android.path }}"
                                   class="help-block"
                                   target="_self">
                                    <i class="fa fa-cloud-download"></i> <?php echo __("Download latest sources"); ?> {{
                                    application.zip.android.date }}
                                </a>
                                <span ng-if="!application.zip.android"><?php echo __("Not yet generated.") ?></span>
                            </td>
                            <td class="text-right">
                                <a ng-if="application.queued.positions.android == 0"
                                   ng-click="generateSource(2, 0)"
                                   href="javascript:void(0)"
                                   class="block"
                                   target="_self">
                                    <i class="fa fa-gears"></i> <?php echo __("Generate sources"); ?>
                                </a>
                                <span ng-show="application.queued.positions.android == 1">
                                        <img class="gear-loader"
                                             src="/app/sae/design/desktop/backoffice/images/loader/gears.gif"/><?php echo __("Generating") ?>
                                    </span>
                                <span ng-show="application.queued.positions.android > 1">
                                            <i class="fa fa-random"></i> <?php echo __("Queued") ?>: {{ application.queued.positions.android }}/{{ application.queued.total }}
                                        </span>
                                <a ng-show="application.queued.positions.android > 1"
                                   ng-click="cancelQueue(2, 0)"
                                   href="javascript:void(0)">
                                    <i class="fa fa-times"></i> <?php echo __("Cancel") ?>
                                </a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <br />

    <div class="row">
        <div class="col-md-12">
            <h4 class="section-title "><?php echo p__("backoffice_application","Advanced application settings"); ?></h4>
        </div>
        <div class="col-md-12">
            <div class="section-content">

                <form ng-submit="saveInfo()"
                      class="row">

                    <div class="col-md-12">
                        <div class="alert alert-warning">
                            <?php echo __("After saving any advanced settings, you must rebuild / republish the application for changes to take effect.") ?>
                        </div>
                    </div>

                    <div class="col-md-12">
                        <div class="form-group">
                            <div class="checkbox">
                                <label for="disable_battery_optimization">
                                    <input type="checkbox"
                                           id="disable_battery_optimization"
                                           ng-model="tmp_application.disable_battery_optimization"
                                           ng-checked="tmp_application.disable_battery_optimization"/>
                                    <?php echo __("Allows MediaPlayer (Audio & Radio) to ask permission for disabling <b>Android</b> battery optimizations."); ?>
                                </label>
                            </div>
                            <br />
                            <div>
                                <?php echo __("Please note that Google Play can reject your app if the use case is not strictly required.") ?><br />
                                <?php echo __("You can find acceptable use cases for permission <b>REQUEST_IGNORE_BATTERY_OPTIMIZATIONS</b> on Android %s, according to Android developers.", "<a class=\"link\" href=\"https://developer.android.com/training/monitoring-device-state/doze-standby#whitelisting-cases\">" . __("here") . "</a>") ?>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-12">
                        <div class="form-group">
                            <div class="checkbox">
                                <label for="disable_location">
                                    <input type="checkbox"
                                           id="disable_location"
                                           ng-model="tmp_application.disable_location"
                                           ng-checked="tmp_application.disable_location"/>
                                    <?php echo p__("application", "Disable location service & permissions."); ?>
                                </label>
                            </div>
                            <br />
                            <div>
                                <?php echo p__("application", "Please note that if you are using a feature that requires location services & disable it here, these features will not work correctly."); ?><br />
                            </div>
                        </div>
                    </div>

                    <div class="col-md-12">
                        <div class="form-group">
                            <button type="submit"
                                    class="btn btn-primary right"><?php echo __("Save"); ?></button>
                            <sb-loader is_visible="application_form_loader_is_visible"
                                       type="'inner_content'"
                                       size="'small'"
                                       animation="'no'"
                                       class="form_loader"></sb-loader>
                            <div class="clear"></div>
                        </div>
                    </div>
                </form>

                <div class="clear"></div>

            </div>
        </div>
    </div>


    <div class="clear"></div>

    <style type="text/css">
        .source-hint {
            font-style: italic;
            font-size: 13px;
            letter-spacing: 1px;
        }

        .help-block {
            white-space: normal;
        }
    </style>

</sb-section>
