<sb-section title="'<?php echo __title("User Information"); ?>'">

    <div class="col-md-12">
        <div class="form-group">
            <label class="control-label"><?php echo __("Name"); ?></label>
            <p>{{ application.admin.name }}</p>
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <label class="control-label"><?php echo __("Email"); ?></label>
            <p>{{ application.admin.email }}</p>
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <label class="control-label"><?php echo __("Company"); ?></label>
            <p>{{ application.admin.company }}</p>
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <label class="control-label"><?php echo __("Phone"); ?></label>
            <p>{{ application.admin.phone }}</p>
        </div>
    </div>

    <div class="clear"></div>

</sb-section>