        <!-- START #MODULE# TAB -->
        <div role="tabpanel"
             class="tab-pane active"
             id="##MODEL_SHORT#">

            <div class="feature-block-add">
                <h3 class="title-editor no-border-radius title-feature-indent">
                    <?php echo __('Add %s', '#HUMAN#'); ?>
                    <button type="button"
                            class="feature-toggle-add toggle_design color-blue pull-right bt-header-right btn">
                        <i class="fa fa-plus"></i>
                    </button>
                </h3>
                <div class="container-fluid subcontent content-feature">
                    <?php echo $formDefault; ?>
                </div>
            </div>

            <?php if ($collection->count() > 0): ?>
                <div class="feature-block-list">
                    <div class="margin-top">
                        <h3 class="title-editor no-border-radius title-feature-indent">
                            <?php echo __('Manage elements'); ?>
                            <button type="button"
                                    class="toggle_design color-blue pull-right bt-header-right btn feature-toggle-items">
                                <i class="fa fa-angle-down"></i>
                            </button>
                        </h3>
                        <div class="container-fluid first-row-feature content-feature feature-manage-items">
                            <table class="table content-white-bkg sb-pager">
                                <thead>
                                <tr class="border-grey">
                                    #FIELDS_HEAD#
                                    <th></th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach($collection as $item) : ?>
                                    <tr id="#MODULE_LOWER#_manage_element_<?php echo $item->getId(); ?>"
                                        class="#MODULE_LOWER#-manage-element sb-pager">
                                        #FIELDS_BODY#
                                        <td class="edit-action open-edit"
                                            data-id="#MODULE_LOWER#_<?php echo $item->getId(); ?>"
                                            data-form-url="<?php echo __path('#FORM_LOAD_ACTION#', [
                                                '#PRIMARY_KEY#' => $item->getId(),
                                                'value_id' => $optionValue->getId()
                                            ]); ?>">
                                            <i class="fa fa-pencil"></i>
                                        </td>
                                        <td class="delete-action">
                                            <?php
                                            $deleteForm->setAttrib('data-rowid', '#MODULE_LOWER#_manage_element_' . $item->getId());
                                            $deleteForm
                                                ->getElement('#PRIMARY_KEY#')
                                                ->setValue($item->getId());

                                            echo $deleteForm;
                                            ?>
                                        </td>
                                    </tr>
                                    <tr class="edit-form"
                                        data-id="#MODULE_LOWER#_<?php echo $item->getId(); ?>"
                                        style="display: none;">
                                        <td colspan="6">
                                            <p class="close-edit"
                                               data-id="#MODULE_LOWER#_<?php echo $item->getId(); ?>">
                                                <i class="fa fa-times"></i><?php echo __('Close') ?>
                                            </p>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        </div>
        <!-- /END #MODULE# TAB -->