<?php $application = $this->getApplication(); ?>
<?php $option_value = $this->getOptionValue(); ?>
<?php $image = new Media_Model_Gallery_Image(); ?>
<?php $images = $image->findAll(array('value_id' => $option_value->getId()), 'gallery_id DESC'); ?>
<?php $instagram_is_available = $application->getInstagramClientId() && $application->getInstagramToken(); ?>
<?php
//If we're unable to get acces token then facebook is not available
$facebook = new Social_Model_Facebook();
$facebook_is_available = $facebook->getAccessToken() != null;
?>
<div class="media images">
    <div class="form_content">
        <div class="add-image">
            <h3 class="title-editor no-border-radius title-feature-indent">
                <?php echo $this->_('Add') ?>
                <button type="button" onclick="$('#no_item').hide(); $('#new_images_galery').show();" class="btn toggle_design color-blue pull-right bt-header-right" id="add_item">
                    <i class="fa fa-plus"></i>
                </button>
            </h3>
            <div id="albums_found" style="display: none;">
                <h3 class="title-editor no-border-radius">
                    <?php echo $this->_('Choose an album'); ?> :
                </h3>
                <ul id="albums_found_list">
                </ul>
            </div>

            <?php echo $this->createPartialHtml('no_item', 'core_view_default', 'application/customization/features/edit/no_item.phtml'); ?>

            <div id="new_images_galery" style="display:none;" class="container-fluid first-row-feature feature-section-bottom">
                <div id="choose_type">
                    <ul class="list-group">
                        <li class="color-blue list-group-item btn capitalize" rel="picasa">
                            <a href="javascript:void(0);" rel="picasa" class="block select_type image_type_select capitalize">
                                <i title="Picasa" class="fa fa-google block img_icon" alt="Picasa" /></i>
                                <p><?php echo $this->_('Picasa') ?></p>
                            </a>
                        </li>
                        <li class="color-blue list-group-item btn capitalize" rel="instagram" <?php if(!$instagram_is_available) : ?> onclick="featureNotAvailable()" <?php endif; ?>>
                            <a href="javascript:void(0);" rel="instagram" class="block select_type<?php if($instagram_is_available) : ?> image_type_select<?php endif; ?>">
                                <i title="Instagram" class="fa fa-instagram block img_icon" alt="Instagram"></i>
                                <p><?php echo $this->_('Instagram') ?></p>
                            </a>
                        </li>
                        <li class="color-blue list-group-item btn capitalize" rel="custom">
                            <a href="javascript:void(0);" rel="custom" class="block select_type image_type_select capitalize">
                                <i title="<?php echo $this->_("My images"); ?>" class="fa fa-camera block img_icon" alt="<?php echo $this->_("My images"); ?>"></i>
                                <p><?php echo $this->_('My images') ?></p>
                            </a>
                        </li>
                        <li class="color-blue list-group-item btn capitalize" rel="facebook" <?php if(!$facebook_is_available) : ?> onclick="featureNotAvailable()" <?php endif; ?>>
                            <a href="javascript:void(0);" rel="facebook" class="block select_type image_type_select capitalize">
                                <i title="<?php echo $this->_("Facebook"); ?>" class="fa fa-facebook block img_icon" alt="<?php echo $this->_("Facebook"); ?>"></i>
                                <p><?php echo $this->_('Facebook') ?></p>
                            </a>
                        </li>
                    </ul>
                </div>

                <div id="table_list_images_new" style="display:none" class="container-fluid">
                    <div class="row">
                        <div class="col-sm-1"></div>
                        <div class="col-sm-5">
                            <label><span id="name-label"><?php echo $this->_('Gallery Name') ?></span> <span class="required-entry required"> *</span> :</label>
                        </div>
                        <div class="col-sm-4">
                            <label id="label_search"><?php echo $this->_('Search') ?> <span class="required-entry required"> *</span> :</label>
                        </div>
                    </div>
                    <div class="row" rel="list_new">
                        <div class="col-sm-1 img-col color-blue">
                            <i id="type_picasa" rel="picasa" class="fa fa-google bt-margin type_selected" title="Picasa" alt="Picasa" style="display:none;" ></i>
                            <i id="type_instagram" rel="instagram" class="bt-margin type_selected fa fa-instagram" title="Instagram" alt="Instagram" style="display:none;" ></i>
                            <i id="type_custom" rel="user" class="margin-top-5 type_selected fa fa-camera" title="<?php echo $this->_("My images"); ?>" alt="<?php echo $this->_("My images"); ?>" style="display:none;"></i>
                            <i id="type_facebook" rel="facebook" class="margin-top-5 type_selected fa fa-facebook" title="<?php echo $this->_("Facebook"); ?>" alt="<?php echo $this->_("Facebook"); ?>" style="display:none;"></i>
                        </div>
                        <div class="col-sm-5">
                            <input id="name-input" type="text" name="name" value="" placeholder="<?php echo $this->_('Gallery Name') ?>" class="input-flat required" />
                        </div>
                        <div class="col-sm-4">
                            <button type="button" id="input_custom" class="new_search_input search_input upload_picture btn btn-block required" rel="list_new"><?php echo $this->_('Send your pictures') ?></button>
                            <input type="text" id="input_picasa" name="param" value="" placeholder="<?php echo $this->_('Parameter') ?>" class="new_search_input search_input input-flat required" />
                            <select name="param_facebook" id="input_facebook" class="sb-select styled-select color-blue form-control no-dk required new_search_input"></select>
                            <input type="hidden" id="input_instagram" name="param_instagram" value="" class="new_search_input search_input" />
                        </div>
                        <div class="col-sm-1">
                            <input type="hidden" name="value_id" value="<?php echo $option_value->getId(); ?>" />
                            <button type="button" class="bt-margin validate btn save_image btn color-blue">OK</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div id="edit_images" style="display:none;">
            <i class="icon-caret-up"></i>

            <h3 class="title-editor no-border-radius title-feature-indent">
                <?php echo $this->_('Send your pictures') ?>
                <a id="close_panel" class="btn color-blue pull-right bt-header-right" href="javascript:void(0);">
                    <i class="fa fa-times"></i>
                </a>
            </h3>
            <!--[if gte IE 10]><!-->
            <div class="container-fluid first-row-feature">
                <button type="button" id="trigger_upload_image" class="btn color-blue btn-block"><?php echo $this->_('Browse') ?></button>
                <!--<![endif]-->
                <input id="upload_image" style="display:none;" multiple type="file" name="files[]" data-url="<?php echo $this->getUrl('template/crop/upload'); ?>" />
                <h4 class="conditions"><?php echo $this->_('Maximum size : 2000*2000 px - Allowed filetypes : jpg and png') ?></h4>
                <div id="list_images">
                    <?php foreach ($images as $image) : ?>
                        <ul style="display:none" id="list_<?php echo $image->getId(); ?>" class="list-group">
                            <?php if ($image->getTypeId() == 'custom') : ?>
                                <?php $gallery = new Media_Model_Gallery_Image_Custom(); ?>
                                <?php $gs = $gallery->findAll(array('gallery_id' => $image->getId())); ?>
                                <?php foreach ($gs as $p) : ?>
                                    <li class="list-group-item content-white-bkg">
                                        <div class="row">
                                            <div class="col-sm-2">
                                                <img class="img_list_<?php echo $image->getId(); ?>" height="60px" width="60px" src="<?php echo Application_Model_Application::getImagePath().$p->getData('url') ?>" />
                                            </div>
                                            <div class="col-sm-5">
                                                <label><?php echo $this->_('Title:') ?></label>
                                                <input type="text" id="image_<?php echo $image->getId(); ?>_<?php echo $p->getId(); ?>_title" name="images[list_<?php echo $image->getId(); ?>][<?php echo $p->getId(); ?>][title]" class="input-flat" value="<?php echo $p->getTitle(); ?>" maxlength="30" onkeyup="$('#' + $(this).attr('id') + '_receiver').val($(this).val());" />
                                            </div>
                                            <div class="col-sm-4">
                                                <label><?php echo $this->_('Description:') ?></label>
                                                <input type="text" id="image_<?php echo $image->getId(); ?>_<?php echo $p->getId(); ?>_description" name="images[list_<?php echo $image->getId(); ?>][<?php echo $p->getId(); ?>][description]" class="input-flat" value="<?php echo $p->getDescription(); ?>" maxlength="255" onkeyup="$('#' + $(this).attr('id') + '_receiver').val($(this).val());" />
                                            </div>
                                            <div class="col-sm-1">
                                                <a onclick="deleteImage($(this), '<?php echo $image->getId(); ?>', '<?php echo $p->getId(); ?>');" href="javascript:void(0);" class="btn color-blue pull-right "><i class="fa fa-times"></i></a>
                                            </div>
                                        </div>
                                    </li>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </ul>
                    <?php endforeach; ?>
                    <ul style="display:none" id="list_new">
                    </ul>
                </div>
            </div>
        </div>

        <?php if ($images->count() > 0) : ?>
        <div class="manage">
            <div id="existing_items_section">
                <h3 class="title-editor no-border-radius title-feature-indent">
                    <?php echo $this->_('Manage'); ?>
                    <button type="button" class="toggle_design color-blue pull-right bt-header-right btn" id="toggle_existing_items">
                        <i class="fa fa-chevron-down"></i>
                    </button>
                </h3>
                <div id="existing_items" style="display:none;" class="container-fluid first-row-feature">
                    <div id="table_list_images">
                        <div class="row container-fluid">
                            <div class="col-sm-1"></div>
                            <div class="col-sm-4">
                                <label>
                                    <?php echo $this->_('Gallery Name') ?>
                                    <span class="required-entry required"> *</span> :</label>
                            </div>
                            <div class="col-sm-5">
                                <label><?php echo $this->_('Search') ?> <span class="required-entry required"> *</span> :</label>
                            </div>
                        </div>
                        <?php foreach ($images as $image) : ?>
                            <?php echo $this->getLayout()->addPartial('row_' . $image->getId(), 'admin_view_default', 'media/application/gallery/image/edit/row.phtml')
                                ->setCurrentImage($image)
                                ->setCurrentOptionValue($option_value)
                                ->toHtml()
                            ;?>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
        </div>
        <?php endif; ?>
        <div class="background">
            <?php echo $this->getLayout()
                ->addPartial('background_image', 'Core_View_Default', 'application/customization/features/edit/background_image.phtml')
                ->setValueId($option_value->getId())
                ->toHtml()
            ; ?>
        </div>

    </div>

    <script type="text/javascript">
        var label = {
            'picasa': '<?php echo $this->_('Gallery Name') ?>',
            'custom': '<?php echo $this->_('Gallery Name') ?>',
            'instagram': '<?php echo $this->_('Gallery Name') ?>',
            'facebook': '<?php echo $this->_('Facebook page ID') ?>',
        }, selected;

        page.setCallback('willappear', function() {

            $('.image_type_select').parent().click(function() {

                var id = $(this).attr('rel');

                selected = id;
                // depending on the clicked option display the appropriate label
                $('#name-label').html(label[id]);
                $('#name-input').attr('placeholder', label[id]);
                // Load
                $('#input_facebook').focus(function () {
                    reload(this, '<?php echo $this->getUrl('media/application_gallery_image/albums/'); ?>?pageid=' + $('#name-input').val(), true, function (data) {
                        $('#input_facebook').html("");
                        $.each(data, function (i, album) {
                            $('#input_facebook').append($('<option>', {
                                value: album.id,
                                text: album.name
                            }));
                        });
                    });
                });

                if(id == "instagram") {
                    $("#input_instagram").val(1);
                    $("#label_search").hide();
                } else {
                    $("#input_instagram").val("");
                    $("#label_search").show();
                }

                $('.type_selected').hide();
                $('#type_' + id).show();
                $('#choose_type').hide();

                $('.new_search_input').removeClass('required').hide(),
                        $('#input_' + id).addClass('required').show();

                $('#table_list_images_new').show();

            });
        });

        $('.save_image').click(function() {
            var _that = $(this);
            var tr = $(this.parentNode.parentNode);
            var error = false;
            tr.find('input.required').each(function() {
                if($(this).val().isEmpty()) {
                    $(this).addClass('error');
                    if($(this).next('p.error').length == 0) $(this).after('<p class="error"><?php echo addslashes($this->_('Required field')) ?></p>');
                    error = true;
                }
                else {
                    $(this).removeClass('error');
                    $(this).next('p.error').remove();
                }
            });

            if(error) return false;

            reload(tr, '<?php echo $this->getUrl('media/application_gallery_image/editpost'); ?>', true, function(datas) {
                if(datas.success) {
                    if(datas.albums) {
                        for(var id in datas.albums) {
                            var album = datas.albums[id];
                            var li = $('<li />');
                            var a = $('<a />').addClass('album_found block').attr('href', album).attr('rel', album.id).html(album.title).appendTo(li);
                            $('<img />').attr('src', album.image).attr('width', 140).attr('height', 'auto').prependTo(a);
                            li.appendTo($('#albums_found_list'));
                        }
                        $('#albums_found').prettyPhoto({
                            default_width: 500,
                            default_height: 400,
                            show_title: false,
                            deeplinking: false,
                            social_tools: '',
                            gallery_markup: '',
                            keyboard_shortcuts: false,
                            changepicturecallback: function() {
                                $('#albums_found_list .album_found').click(function() {
                                    var input = _that.next('input.album_id');
                                    if(!input.length) {
                                        input = $('<input />').attr('type', 'hidden').attr('name', 'album_id');
                                        _that.after(input);
                                    }

                                    input.val($(this).attr('rel'));

                                    _that.click();
                                    $.prettyPhoto.close();
                                    return false;
                                });
                            },
                            callback: function() {
                                $('#albums_found_list .album_found').unbind('click');
                                $('#albums_found_list').empty();
                            },
                            theme: 'pp_none'
                        });
                        $.prettyPhoto.open('#albums_found');

                    }
                    else {
                        page.reload();
                    }
                }
            });
        });

        $('.delete_image').click(function() {
            if(confirm('<?php echo addslashes($this->_('Delete this gallery?')); ?>')) {
                var td = $(this.parentNode);
                var tr = $(this.parentNode.parentNode);
                reload(tr, '<?php echo $this->getUrl('media/application_gallery_image/delete'); ?>', true, function(datas) {
                    if(datas.success) {
                        iframe.f.reload();
                        tr.animate({opacity: 0.3, height: 0}, 500, function() {
                                tr.remove();
                                if($('.row_image').length == 0) {
                                    $('#existing_items_section').hide();
                                    $('#table_list_images').hide();
                                    $('#no_item').show();
                                }
                        });
                    }
                });
            }
        });

        page.setCallback('didappear', function() {
            $('#toggle_existing_items').click(function() {
                $('#existing_items').stop().slideToggle(300, function() {
                    if ($(this).is(':visible'))
                        $('#toggle_existing_items').children('i').removeClass('fa-chevron-down').addClass('fa-chevron-up');
                    else
                        $('#toggle_existing_items').children('i').removeClass('fa-chevron-up').addClass('fa-chevron-down')
                });
            });
            upload();
        });

        page.setCallback('willdisappear', function() {
            $('#toggle_existing_items').unbind('click');
            $('.image_type_select').parent().unbind('click');
        })

        function deleteImage(element, list_id, image_id) {

            var img_id = "list_" + list_id;
            if(list_id == 'custom') {
                img_id = "list_new";
                $("input[type='hidden'][name*='images[" + img_id + "][" + image_id + "]']").remove();
            } else {
                $('#input_' + list_id).after("<input type='hidden' name='images[list_" + list_id + "][" + image_id + "][delete]' value='1' />");
            }

            element.parent().parent().remove();

            var html = $('.img_' + img_id).length;
            if (html == 0)
                html = '<?php echo addslashes($this->_("Send your pictures")); ?>';
            else if (html <= 1)
                html += ' <?php echo addslashes($this->_("Image")); ?>';
            else
                html += ' <?php echo addslashes($this->_("Images")); ?>';

            $('#input_' + list_id).html(html);

        }

        function slideDown(el) {
            $('#edit_images ul').hide();
            $('#edit_images ul#' + $(el).attr('rel')).show();
            $('#edit_images').css('top', $(el).parent().position().top + 57 + 'px');
            $('#edit_images').slideDown('fast');
        }

        function slideUp() {
            $('#edit_images').slideUp('fast');
        }

        function upload() {

            $('#close_panel').click(function() {
                $('#edit_images').slideUp('fast');
            });

            $('.upload_picture').click(function() {
                if ($('#edit_images').is(':visible')) {
                    slideUp();
                } else {
                    slideDown(this);
                    if (!$('button#trigger_upload_image').is(':visible')) {
                        $('input#upload_image').show();
                    }
                }
            });

            $('#trigger_upload_image').click(function() {
                $('#upload_image').click();
            });

            var uploader = new Uploader();
            $('#upload_image').fileupload({
                dataType: 'json',
                add: function(e, data) {
                    $('#edit_images p.error').remove();
                    var option_v = '<?php echo $option_value->getId(); ?>';
                    data.formData = {value_id: option_v},
                    data.submit();
                    uploader.showProgressbar();
                },
                progressall: function(e, data) {
                    uploader.moveProgressbar(data);
                },
                done: function(e, data) {
                    if (data.result.error) {
                        uploader.showError(data.result.message);
                    } else {
                        uploader.hide();
                        var id = $('#edit_images #list_images ul:visible').attr('id');
                        var short_id = id.split('_');
                        short_id = short_id[1];
                        if (isNaN(short_id))
                            short_id = 'custom';
                        var tmp_image_id = data.result.files.replace('.', '_');

                        $('#input_' + short_id).after('\n\
                            <input type="hidden" class="input_images" name="images[' + id + '][' + tmp_image_id + '][path]" value="' + data.result.files + '"/>\n\
                            <input type="hidden" id="image_' + id + '_' + tmp_image_id + '_title_receiver" name="images[' + id + '][' + tmp_image_id + '][title]" value="" />\n\
                            <input type="hidden" id="image_' + id + '_' + tmp_image_id + '_description_receiver" name="images[' + id + '][' + tmp_image_id + '][description]" value="" />\n\
                        ');

                        $('#edit_images ul#' + id).append('<div class="row">\n\
                            <div class="col-sm-2">\n\
                                <img class="img_' + id + '" height="60px" width="60px" src="<?php echo Core_Model_Directory::getTmpDirectory() ?>/' + data.result.files + '" />\n\
                            </div>\n\
                            <div class="col-sm-5">\n\
                                <label><?php echo addslashes($this->_('Title:')) ?></label>\n\
                                <input type="text" id="image_' + id + '_' + tmp_image_id + '_title" value="" maxlength="30" class="input-flat" onkeyup="$(\'#\'+$(this).attr(\'id\')+\'_receiver\').val($(this).val());" />\n\
                            </div>\n\
                            <div class="col-sm-4">\n\
                                <label><?php echo addslashes($this->_('Description:')) ?></label>\n\
                                <input type="text" id="image_' + id + '_' + tmp_image_id + '_description" value="" maxlength="255" class="input-flat" onkeyup="$(\'#\'+$(this).attr(\'id\')+\'_receiver\').val($(this).val());" />\n\
                            </div>\n\
                            <div class="col-sm-1">\n\
                                <br/><a onclick="deleteImage($(this), \'' + short_id + '\',\'' + tmp_image_id + '\');" href="javascript:void(0);" class="btn color-blue"><i class="fa fa-times"></i></a>\n\
                            </div>\n\
                            \n\
                        </li>');

                        var html = $('.img_' + id).length;
                        if (html == 0)
                            html = + '<?php echo addslashes($this->_("Send your pictures")); ?>';
                        else if (html <= 1)
                            html += ' <?php echo addslashes($this->_("Image")); ?>';
                        else
                            html += ' <?php echo addslashes($this->_("Images")); ?>';

                        $('#input_' + short_id).html(html);

                    }
                }
            });
        }

        page.setCallback('willdisappear', function() {
            $('.upload_picture').unbind('click');
            $('#close_panel').unbind('click');
            $('.save_image').unbind('click');
            $('.delete_image').unbind('click');
        });
    </script>
    <style>
        .media.images #choose_type ul {
            padding-left: 26%;
            margin:0;
        }
        #albums_found_list li {
            float: left;
            width: 150px;
            height: 150px;
            font-size: 13px;
            text-align: center;
            line-height: 14px;
            overflow: hidden;
        }
        #albums_found_list li img {
            margin-bottom: 7px;
        }
        #choose_type li {
            padding-top: 20px;
            float: left;
            width: 120px;
        }
        .img-col {
            padding: 5px 0;
            text-align: center;
        }
        #list_new {
            padding: 0;
        }
        #list_new li {
            list-style: none;
        }
        #list_images ul {
            list-style: outside none none;
            padding: 0;
        }
        #list_images ul li a {
            margin-top: 2em;
        }
        .row_image {
            margin-bottom: 10px;
        }
        #list_new .row .control .btn.color-blue {
            margin-top: 1.9em;
        }
        #close_panel .fa.fa-times {
            text-indent: -55px;
        }
    </style>
</div>