
<form ng-submit="save()" class="form-horizontal">
    <sb-section title="'<?php echo addcslashes(__("Application settings"), "'"); ?>'">

        <div class="form-group">

            <div class="col-md-6">
                <label for="{{ configs.environment.code }}">{{ configs.environment.label }}</label>
                <select id="configs.environment.code" class="form-control" ng-model="configs.environment.value">
                    <option value="production"><?php echo __("Production"); ?></option>
                    <option value="development"><?php echo __("Development"); ?></option>
                </select>
            </div>

            <div class="col-md-6">
                <label for="{{ configs.update_channel.code }}">{{ configs.update_channel.label }}</label>
                <select id="configs.update_channel.code" class="form-control" ng-model="configs.update_channel.value">
                    <option value="stable"><?php echo __("Stable"); ?></option>
                    <option value="beta"><?php echo __("Beta"); ?></option>
                </select>
            </div>
        </div>

        <?php if(APPLICATION_ENV != "production"): ?>
        <div class="form-group">

            <div class="col-md-12">
                <br /><br />
                <?php echo __("HTTPS support is in test, you should only try it on your development server prior to prepare for further migration.") ?>
                <br /><br />
            </div>

            <div class="col-md-6">
                <label for="{{ configs.use_https.code }}">{{ configs.use_https.label }}</label>
                <select id="configs.use_https.code" class="form-control" ng-model="configs.use_https.value">
                    <option value="0"><?php echo __("No"); ?></option>
                    <option value="1"><?php echo __("Yes"); ?></option>
                </select>
            </div>

            <div class="col-md-6">
            </div>
        </div>
        <?php endif; ?>

        <div class="form-group">
            <div class="col-md-12">
                <button type="submit" class="btn btn-primary left"><?php echo __("Save"); ?></button>
                <sb-loader is_visible="form_loader_is_visible" type="'inner_content'" size="'small'" animation="'no'" class="form_loader"></sb-loader>
                <div class="clear"></div>
            </div>
        </div>

    </sb-section>
</form>


